### ISSUE TITLE
Denote current time point within an equation in the model

### ISSUE THREAD

**Issue by motyocska** [nlmixrdevelopment/nlmixr#108]
Matt,

how would one denote current time point in an equation using nlmixr? For example: what would be the equivalent of T in this fortran code using nlmixr in and ODE system? I tried 'time' but not taking it, perhaps because it needs to be declared separately? 

in fortran looks like: DEXP(-K*T)

thanks,

Andras

**Comment by mattfidler** [comment]
I this is related to issue #46, 

You can use `t` as:

```
exp(-k*t)
```
