### ISSUE TITLE
Estimate relative BE using an indicator variable

### ISSUE THREAD

**Issue by derekganes** [nlmixrdevelopment/nlmixr#109]
Hi nlmixr,
I'm a new user of nlmixr.
I like it. 
What is the best way to estimate relative BE using TRT (0, 1) as an indicator variable in the dataset?
Thanks for your help.
Regards,
Derek

Derek Ganes, PhD
Toronto, ON, Canada

*************************************

```R
library(nlmixr)

data <- read.csv("xx.csv")

basemod <- function() {
  
  ini({
    
    tktr <- 0.92 #log(2.5) #transit lag-time
    tn <- 3.6 #log(35) #transit lag-time
    tka <- -1.0 #log(0.36)
    tke <- -0.87 #log(0.42)
    tv <- 0.69 #log(2.0)
    
    eta.ktr ~ 1 #transit lag-time
    eta.n ~ 1 #transit lag-time
    eta.ka ~ 1
    eta.ke ~ 1
    eta.v ~ 1
    
    add.err <- 0.1
    
  })
  
  model({
    
    Dose=500 #all subjects received 500 mg
    
    ktr <- exp(tktr + eta.ktr) #transit lag-time
    n <- exp(tn + eta.n) #transit lag-time
    ka <- exp(tka + eta.ka)
    ke <- exp(tke + eta.ke)
    v <- exp(tv + eta.v)
    
    lnfac = log(2.5066) + (n + 0.5) * log(n) - n #nfac=sqrt(2*3.1415)*n**(n+0.5)*exp(-n) Stirling ~ n!

    d / dt(depot) = exp(log(Dose) + log(ktr) + n * log(ktr * t) - ktr *
                          t - lnfac) - ka * depot
    d / dt(center) = ka * depot - ke * center
    
    cp = center / v
    cp ~ add(add.err)
    
  })
}

fit <- nlmixr(basemod, data, est = "saem")

nlmixr(basemod)
fit
str(fit)
plot(fit)
traceplot(fit)
summary(fit)

```

**Comment by mattfidler** [comment]
Hi Derek,

There is some discussion of this on #59. 

You would include a `TRT` in the dataset, and then refer to it in the model:

```R
basemod <- function() {
  
  ini({
    
    tktr <- 0.92 #log(2.5) #transit lag-time
    tn <- 3.6 #log(35) #transit lag-time
    tka <- -1.0 #log(0.36)
    tke <- -0.87 #log(0.42)
    tv <- 0.69 #log(2.0)
    f1= 0.1 # log F
    eta.ktr ~ 1 #transit lag-time
    eta.n ~ 1 #transit lag-time
    eta.ka ~ 1
    eta.ke ~ 1
    eta.v ~ 1
        
    add.err <- 0.1
    
  })
  
  model({
    
    Dose=500 #all subjects received 500 mg
    
    ktr <- exp(tktr + eta.ktr) #transit lag-time
    n <- exp(tn + eta.n) #transit lag-time
    ka <- exp(tka + eta.ka)
    ke <- exp(tke + eta.ke)
    v <- exp(tv + eta.v)
   fcp <- exp(f1)
    
    lnfac = log(2.5066) + (n + 0.5) * log(n) - n #nfac=sqrt(2*3.1415)*n**(n+0.5)*exp(-n) Stirling ~ n!

    d / dt(depot) = exp(log(Dose) + log(ktr) + n * log(ktr * t) - ktr *
                          t - lnfac) - ka * depot
    d / dt(center) = ka * depot - ke * center
    cp = center / v *fcp*TRT + center/v*(1-TRT)
    
    cp ~ add(add.err)
    
  })
}
```

I cannot test this model without data, so I hope I did not make any errors.

**Comment by mattfidler** [comment]
We also have explicit support for transit compartment models, I will have to dig out the code.

**Comment by derekganes** [comment]
Hi Matthew,

Thanks for your help.

I ran it and received the following:

Regards,

Derek

 

************************************

> fit <- nlmixr(basemod, data, est = "saem")

Compiling RxODE differential equations...done.

PKG_CXXFLAGS=-IC:/Users/Derek/DOCUME~1/R/WIN-LI~1/3.5/nlmixr/include -IC:/Users/Derek/DOCUME~1/R/WIN-LI~1/3.5/STANHE~1/include -IC:/Users/Derek/DOCUME~1/R/WIN-LI~1/3.5/Rcpp/include -IC:/Users/Derek/DOCUME~1/R/WIN-LI~1/3.5/RCPPAR~1/include -IC:/Users/Derek/DOCUME~1/R/WIN-LI~1/3.5/RCPPEI~1/include -IC:/Users/Derek/DOCUME~1/R/WIN-LI~1/3.5/BH/include

PKG_LIBS= $(BLAS_LIBS) $(LAPACK_LIBS)

C:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG       -IC:/Users/Derek/DOCUME~1/R/WIN-LI~1/3.5/nlmixr/include -IC:/Users/Derek/DOCUME~1/R/WIN-LI~1/3.5/STANHE~1/include -IC:/Users/Derek/DOCUME~1/R/WIN-LI~1/3.5/Rcpp/include -IC:/Users/Derek/DOCUME~1/R/WIN-LI~1/3.5/RCPPAR~1/include -IC:/Users/Derek/DOCUME~1/R/WIN-LI~1/3.5/RCPPEI~1/include -IC:/Users/Derek/DOCUME~1/R/WIN-LI~1/3.5/BH/include   -O2 -Wall  -mtune=generic -c saem59685e2229ddx64.cpp -o saem59685e2229ddx64.o

C:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o saem59685e2229ddx64.dll tmp.def saem59685e2229ddx64.o -LC:/PROGRA~1/R/R-35~1.1/bin/x64 -lRblas -LC:/PROGRA~1/R/R-35~1.1/bin/x64 -lRlapack -LC:/PROGRA~1/R/R-35~1.1/bin/x64 -lR

done.

Error in dim(mPars) <- c(N, ninputpars) : 

  dims [product 14] do not match the length of object [27]

In addition: Warning message:

In nlmixrData.default(data) :

  Sorting by ID, TIME; Output fit may not be in the same order as input dataset.

**Comment by mattfidler** [comment]
Thank you @derekganes 

I have asked someone more familiar with the saem routines to look into this.  They are in the middle of a NDA, so they are a bit busy.  Hopefully we can figure this out soon.

**Comment by mattfidler** [comment]
If you can provide some reproducible example (aka data) I will look into this some more.  Otherwise, I will close this for now.

**Comment by derekganes** [comment]
Hi Matthew,

I ended up using Saemix directly as shown below.

I’ll revisit nlmixr. 

Thank you for your help.

Regards,

Derek

 

*****************

setwd(

  "XX"

)

XXdata <- read.csv("XX.csv")

 

library(saemix)

saemix.data <- saemixData(

  name.data = XXdata,

  header = TRUE,

  sep = ",",

  na = NA,

  name.group = c("Id"),

  name.predictors = c("Dose", "Time", "Trt"),

  name.response = c("Concentration"),

  name.covariates = c("-"),

  units = list(

    x = "hr",

    y = "ng/mL",

    covariates = c("-")

  ),

  name.X = "Time"

)

model1cpt <- function(psi, id, xidep) {

  dose <- xidep[, 1]

  t <- xidep[, 2]

  trt <- xidep[, 3]

  ka <- psi[id, 1]

  k <- psi[id, 2]

  V <- psi[id, 3]

  rf <- psi[id, 4]

  tlag <- psi[id, 5]

  ypred <-

    dose * ka / (V * (ka - k)) * (exp(-k * (t - tlag)) -

                                    exp(-ka * (t - tlag))) * (trt + rf * (1 - trt))

  ypred <- (ypred + abs(ypred)) / 2

  return(ypred)

}

saemix.model <- saemixModel(

  model = model1cpt,

  description = "One-compartment model with first-order absorption,

  relative BA, lag-time",

  psi0 = matrix(

    c(0.35, 0.37, 1.18, 0.85, 0.5,

      0, 0, 0, 0, 0),

    ncol = 5,

    byrow = TRUE,

    dimnames = list(NULL,

                    c("ka", "k", "V", "rf", "tlag"))

  ),

  transform.par = c(1, 1, 1, 1, 1),

  covariate.model = matrix(c(0, 0, 0, 0, 0,

                             0, 0, 0, 0, 0),

                           ncol = 5,

                           byrow = TRUE),

  fixed.estim = c(1, 1, 1, 1, 1),

  

  covariance.model = matrix(

    c(1,    0,            0,            0,            0,

      0,      1,            0,            0,            0,

      0,      0,            1,            0,            0,

      0,      0,            0,            1,            0,

      0,      0,            0,            0,            1),

    ncol = 5,

    byrow = TRUE

  ),

  omega.init = matrix(

    c(1,    0,            0,            0,            0,

      0,      1,            0,            0,            0,

      0,      0,            1,            0,            0,

      0,      0,            0,            1,            0,

      0,      0,            0,            0,            1),

    ncol = 5,

    byrow = TRUE

  ),

  error.model = "constant"

)

saemix.options <- list(

  seed = 632545,

  save = TRUE,

  save.graphs = TRUE,

  nb.chains = 5,

  nbiter.saemix = c(300, 150)

)

saemix.fit <- saemix(saemix.model, saemix.data, saemix.options)

 

print(saemix.fit)

plot(saemix.fit)

plot(

  saemix.fit,

  plot.type = "individual.fit",

  ilist = c(1:14),

  ask = FALSE

)

plot(saemix.fit, plot.type = "residuals.scatter")

**Comment by mattfidler** [comment]
Thanks for the update @derekganes 

Note that nlmixr does not use saemmix for estimation, so results can vary.
