### ISSUE TITLE
Unclear how to specify covariates

### ISSUE THREAD

**Issue by rfaelens** [nlmixrdevelopment/nlmixr#11]
It is unclear how to specify covariates in the ODE form.

The following code works perfectly fine:
```
# NLMixr model-based analysis; no covariates
library(nlmixr, quietly=TRUE)
dat <- read.table(system.file("examples/theo_md.txt", package = "nlmixr"), head=TRUE)
ode <- "
KE = CL/V;
d/dt(depot) =-KA*depot;
d/dt(centr) = KA*depot - KE*centr;
CONC = centr/V;
"
mypar <- function(lKA, lV, lCL)
{
  KA <- exp(lKA)
  V <- exp(lV)
  CL <- exp(lCL)
}
specs <- list(fixed=lKA+lV+lCL~1, 
              random = pdDiag(lKA+lCL~1), 
              start=c(lKA=0.5, lV=-2.5, lCL=-3.2))
fit <- nlme_ode(
  dat, 
  model=ode, 
  par_model=specs, 
  par_trans=mypar, 
  response="CONC"
)
nlme_gof(fit)
```

Adding in a covariate:
```
# NLMixr model-based analysis; covariates
library(nlmixr, quietly=TRUE)
dat <- read.table(system.file("examples/theo_md.txt", package = "nlmixr"), head=TRUE)
ode <- "
KE = (WT/70)^0.75 * CL/V;
d/dt(depot) =-KA*depot;
d/dt(centr) = KA*depot - KE*centr;
CONC = centr/V;
"
mypar <- function(lKA, lV, lCL)
{
  KA <- exp(lKA)
  V <- exp(lV)
  CL <- exp(lCL)
}
specs <- list(fixed=lKA+lV+lCL~1, 
              random = pdDiag(lKA+lCL~1), 
              start=c(lKA=0.5, lV=-2.5, lCL=-3.2))
fit <- nlme_ode(
  dat, 
  model=ode, 
  par_model=specs, 
  par_trans=mypar, 
  response="CONC"
)
nlme_gof(fit)
```

We then receive an error message:
```
Error in ..ModList$m1$run(theta, ev, inits, transit_abs = FALSE, atol = 1e-08,  : 
  var(s) not found in input pars.
 WT 
```

**Comment by wwang-at-github** [comment]
page 8 of the vignette provides a simple example of including covariates
with nlme_xxx functions:
specs <- list(
fixed=list(lKA~1, lCL+lV~WT),
random = pdDiag(lKA+lCL~1),
start=c(0.5, -3.2, 0, -1, 0))
fit <- nlme_lin_cmpt(dat, par_model=specs, ncmt=1)
#plot(augPred(fit,level=0:1))
#fit

**Comment by wwang-at-github** [comment]
nlme_ode can include covariates similarly

**Comment by RikSchoemaker** [comment]
If I understand correctly, what this means is that al least for nlme, one is restricted to additive covariates of the form:
lCL+THETA(x)*WT
As parameters are estimated in the log-space, an additive covariate for a binary 0,1 indicator variable means you estimate the additive shift on log scale which you can translate to a fold-change (and then to a percentage change if you so please). So far, so good. But in the example above, you want to estimate a specific functional form, i.e. allometric scaling on weight. For NONMEM, this would look like:

```
TVCL  = LOG(THETA(1)) ;Clearance (L/hr)
CL    = EXP(TVCL+THETA(4)*(LOG(WT/70))+ETA(1))
```

If you want to estimate THETA(4) using nlme/nlmixr (the allometric exponent), you would need to calculate LOGWT as covariate using:
`datr$LOGWT<-log(datr$WT/70)`

and then specify 
`specsC <- list(fixed=list(lKA~1,lCL+lV~LOGWT), etc...)`

This all still seems sunny, although I don't know yet how you would fix a particular parameter (say you want to fix your exponents to 0.75 and 1 for CL and V).

So I thought I'd try it out with a simulated dataset ([ORAL2COMPCOV.txt](https://github.com/nlmixrdevelopment/nlmixr/files/1085042/ORAL2COMPCOV.txt)) that runs smoothly using NONMEM with the following code:


```
datr <- read.csv("ORAL2COMPCOV.txt", header=TRUE,stringsAsFactors=F)
datr$EVID<-ifelse(datr$EVID==1,101,datr$EVID)

mypar <- function(lCL, lV, lKA,lK23,lK32 )
{   CL = exp(lCL) 
    V  = exp(lV)
    KE = CL/V
    KA = exp(lKA)
    K12 = exp(lK23)
    K21 = exp(lK32)
}

specs <- list(fixed=lCL+lV+lKA+lK23+lK32~1, 
random = pdDiag(lCL+lV+lKA+lK23+lK32~1),
start=c(lCL=1.5,lV=4.5,lKA=0.1,lK23=-2.5,lK32=-2.3))

fit <- nlme_lin_cmpt(datr, par_model=specs, par_trans=mypar, ncmt=2, 
verbose=TRUE,oral=TRUE,parameterization=2,weight=varPower(fixed=c(1)))
```
This works perfectly but does not contain covariates yet, so I expanded to:

```
datr$LOGWT <- log(datr$WT/70)
specsC <- list(fixed=list(lKA+lK23+lK32~1,lCL+lV~LOGWT), 
random = pdDiag(lCL+lV+lKA+lK23+lK32~1), 
start=c(lKA=0.1,lK23=-2.5,lK32=-2.3,lCL=1.5,lV=4.5,0.75,1))
fitC <- nlme_lin_cmpt(datr, par_model=specsC, par_trans=mypar, ncmt=2,
verbose=TRUE,oral=TRUE,parameterization=2,weight=varPower(fixed=c(1)))
```
and unfortunately this crashes after the first iteration with the message:
```
**Iteration 1
LME step: Loglik: -91177.35, nlminb iterations: 18
reStruct  parameters:
       ID1        ID2        ID3        ID4        ID5 
9.68527202 9.71791195 9.32275729 0.24329075 0.01674503 
Error in nlme.formula(model = DV ~ ..ModList$user_fn(lCL, lV, lKA, lK23,  : 
  Singularity in backsolve at level 0, block 1
```
Clues anyone? Have I specified correct starting values for the covariate parameters? In the correct locations? Is the order of the parameter names essential in the nlme syntax?

Cheers,

Rik

**Comment by mattfidler** [comment]
I can reproduce your issue Rik.  However, I think this is a problem with nlme in general.  There are other places where this is cited:

https://stat.ethz.ch/pipermail/r-help/2005-November/082071.html

The advice there was that it was over-paramterized.  I don't know how strong the relationship you simulated is, though.

**Comment by mattfidler** [comment]
Using the following paramterization, I can achieve minimization.  As I understand it, though, it only has a weight corporate on volume, not on clearance.

```R
datr$LOGWT <- log(datr$WT/70)
specsC <- list(fixed=list(lKA + lK23 + lK32 + lCL~ 1, lV ~ LOGWT), 
               random = pdDiag(lCL+lV+lKA+lK23+lK32~1), 
               start=c(lKA=0.1,lK23=-2.5,lK32=-2.3,lCL=1.5,lV=4.5,0.75))
fitC <- nlme_lin_cmpt(datr, par_model=specsC, par_trans=mypar, ncmt=2,
                      verbose=TRUE,oral=TRUE,parameterization=2,weight=varPower(fixed=c(1)))
```

If I change it to

```
datr$LOGWT <- log(datr$WT/70)
specsC <- list(fixed=list(lKA+lK23+lK32 + lV ~ 1, lCl~LOGWT), 
               random = pdDiag(lCL+lV+lKA+lK23+lK32~1), 
               start=c(lKA=0.1,lK23=-2.5,lK32=-2.3,lCL=1.5,lV=4.5,0.01))
fitC <- nlme_lin_cmpt(datr, par_model=specsC, par_trans=mypar, ncmt=2,
                      verbose=TRUE,oral=TRUE,parameterization=2,weight=varPower(fixed=c(1)))
```
The singularity returns.

**Comment by rfaelens** [comment]
OK, I think I'm following so far.
What is still missing is a way to fix parameter estimates, instead of estimating them?

**Comment by RikSchoemaker** [comment]
I've seen newer versions of nlmixr where the mypar function can be used to specify covariate relationships. I'm hoping that will sort this issue! Not sure if any of this is available from GitHub though...

```
mypar <- function (lKA, lCL, lV, beta, WT)
{
KA = exp (lKA)
CL = exp (lCL)
V = exp (lV+beta*WT )
}
specs<- list (
fixed=list (lKA+lCL+lV+beta~1 ) ,
random = pdDiag (lKA+lCL~1 ) ,
start=c (0.5 , -3. 2 , -1 , 0)
)
fit<- nlme _ lin_ cmpt (
dat, par_model =specs ,
ncmt = 1 , parameterization= 1 , par_ trans=mypar)
```

**Comment by mattfidler** [comment]
I belive this should work with the github version as well.
