### ISSUE TITLE
Should this perhaps be new.cov rather than all.covs?

### ISSUE THREAD

**Issue by gen0mic** [nlmixrdevelopment/nlmixr#110]
https://github.com/nlmixrdevelopment/nlmixr/blob/3ee8779bce795caab05db5858b7db9f6cdbb8a81/R/simulate.R#L391

**Comment by mattfidler** [comment]
Thanks.  I haven't thought about it yet.  I am keeping it on my radar.

**Comment by mattfidler** [comment]
Indeed you were correct.  Thank you for pointing it out.  It has been fixed.
