### ISSUE TITLE
Simple and real way to install nlmixr.

### ISSUE THREAD

**Issue by Potamophylax** [nlmixrdevelopment/nlmixr#111]
Dear Colleagues,

I would to start using this package, but I ran into huge problems when installing it.
Is there a simple and reliable way to install this package?
I ask this because execution of the chain:
RTools -> Python -> SymPy -> RxODE -> devTools -> nlmixr -> xpose.nlmixr
— this is not an easy installation method, errors constantly appear on this way.

The installer for Windows, as I understand it, is already outdated, and versions of R , when it is installed, begin to conflict with each other, and incomprehensible errors constantly start to surface. Or is there a relatively new version of the installer with instruction for it? because after installation this "installator" nothing happened...

Previously, I had problems with working in some packages, in this case I can’t even start working because it cannot be simply installed. More truly, its separate parts cannot be installed. 

Thank you for help!
--
Windows 7; R 3.4.4/R 3.5.0/ R 3.5.1

**Comment by mattfidler** [comment]
If you have a specific issue, please put more information on this issue so we can try to fix it together.

**Comment by Potamophylax** [comment]
@mattfidler thanks a lot for your advice!

Of cource, I understand problems of such complex structurex and packages with many links.
I will try to install nlmixr until all will work!

**Comment by Potamophylax** [comment]
@mattfidler **mea culpa**!
Last windows installer works perfectly!

**Comment by mattfidler** [comment]
Great.
