### ISSUE TITLE
Some questions related to work in shinyMixR.

### ISSUE THREAD

**Issue by Potamophylax** [nlmixrdevelopment/nlmixr#112]
Many thanks to the developers for one of the few packages with SAEM in R.

I like working with this package through a GUI made in _Shiny_. But I had a few questions about this interface.

**1)** Explain me, please, how to open my own dataset (and not the default dataset on theophylline) in the _ShinyMixR_ interface?

**2)** A more general question: is there a combined error model in the package, or should it be taken by itself as a sum additive and proportional errors?

**3)** Are there additional scripts for analyzing the simulation results? For example, I really need an evaluation ​​of the implemented covariates p-values for the report. Where can I find such a function?

With great gratitude for the help!

**Comment by mattfidler** [comment]
I think this should be filed on the shinyMixR page

https://github.com/RichardHooijmaijers/shinyMixR

**Comment by mattfidler** [comment]
As far as the additive + proportional error models they are a simple sum:

```R
cp ~ add(add.err) + prop(prop.err)
```

**Comment by Potamophylax** [comment]
Thank you, Matt!

It works well.
