### ISSUE TITLE
Not getting “BSV(CV%) and Shrink(SD)%” when using nlmixr

### ISSUE THREAD

**Issue by Bo-NONMEM** [nlmixrdevelopment/nlmixr#113]
I have some problem in getting “BSV(CV%) and Shrink(SD)%” when I used nlmixr.

First of all, I recently installed “Windows installer” of nlmixr onto my computer, following the link on the webpage: https://nlmixrdevelopment.github.io/nlmixr_bookdown/install.html

Secondly, I did a test-run below, 

```R
str(theo_sd)
one.cmt <- function() {
    ini({
        tka <- .5   # log Ka
        tcl <- -3.2 # log Cl
        tv <- -1    # log V
        eta.ka ~ 1
        eta.cl ~ 2
        eta.v ~ 1
        add.err <- 0.1
    })
    model({
        ka <- exp(tka + eta.ka)
        cl <- exp(tcl + eta.cl)
        v <- exp(tv + eta.v)
        linCmt() ~ add(add.err)
    })
}

fit <- nlmixr(one.cmt, theo_sd, est="nlme")
#---------------------------------------------------------------------
```
however, I get a warning message below:

```R
Calculating Table Variables...
done
Warning message:
In nlmixrUI.nlme.var(obj) : Initial condition for additive error ignored with nlme"
#---------------------------------------------------------------------
```
And also, although I could get most estimated parameters from the output, I still could not get “BSV(CV%)” and “Shrink(SD)%” after calling “ print(fit)”, “fit$par.fixed”, or “fit$shrink”.

**Comment by Bo-NONMEM** [comment]
I ran the code "fit <- nlmixr(one.cmt, theo_sd, est="saem",control=saemControl(n.burn=50,n.em=100,print=50))", then below is what I got:

Compiling SAEM user function...C:/Rtools/mingw_64/bin/g++  -I"C:/Users/u0047789/AppData/Local/nlmixr/R/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"  -IC:/Users/u0047789/AppData/Local/nlmixr/R/library/nlmixr/include -IC:/Users/u0047789/AppData/Local/nlmixr/R/library/STANHE~1/include -IC:/Users/u0047789/AppData/Local/nlmixr/R/library/Rcpp/include -IC:/Users/u0047789/AppData/Local/nlmixr/R/library/RCPPAR~1/include -IC:/Users/u0047789/AppData/Local/nlmixr/R/library/RCPPEI~1/include -IC:/Users/u0047789/AppData/Local/nlmixr/R/library/BH/include   -O2 -Wall  -mtune=core2 -c saem2e0c545d73f7x64.cpp -o saem2e0c545d73f7x64.o
In file included from C:/Users/u0047789/AppData/Local/nlmixr/R/library/RCPPAR~1/include/armadillo:53:0,
                 from C:/Users/u0047789/AppData/Local/nlmixr/R/library/RCPPAR~1/include/RcppArmadilloForward.h:46,
                 from C:/Users/u0047789/AppData/Local/nlmixr/R/library/RCPPAR~1/include/RcppArmadillo.h:31,
                 from saem2e0c545d73f7x64.cpp:1:
C:/Users/u0047789/AppData/Local/nlmixr/R/library/RCPPAR~1/include/armadillo_bits/compiler_setup.hpp:474:96: note: #pragma message: WARNING: use of OpenMP disabled; this compiler doesn't support OpenMP 3.0+
   #pragma message ("WARNING: use of OpenMP disabled; this compiler doesn't support OpenMP 3.0+")
                                                                                                ^
C:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o saem2e0c545d73f7x64.dll tmp.def saem2e0c545d73f7x64.o -LC:/Users/u0047789/AppData/Local/nlmixr/R/bin/x64 -lRblas -LC:/Users/u0047789/AppData/Local/nlmixr/R/bin/x64 -lRlapack -lgfortran -lm -lquadmath -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/Users/u0047789/AppData/Local/nlmixr/R/bin/x64 -lR
done.
1:    -3.5526   -0.6595    0.4192    1.9000    0.9500    0.9500   10.1848
50:   -3.1839  -0.7810   0.5284   0.0603   0.0252   0.4778   0.4956
100:   -3.2156  -0.7850   0.4624   0.0738   0.0177   0.4553   0.4831
150:   -3.2131  -0.7843   0.4582   0.0729   0.0184   0.4382   0.4770
C:/Rtools/mingw_64/bin/gcc  -I"C:/Users/u0047789/AppData/Local/nlmixr/R/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c rx_773021bed88694dfc6a195e38a8e8d32_x64.c -o rx_773021bed88694dfc6a195e38a8e8d32_x64.o
C:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o rx_773021bed88694dfc6a195e38a8e8d32_x64.dll tmp.def rx_773021bed88694dfc6a195e38a8e8d32_x64.o -LC:/Users/u0047789/AppData/Local/nlmixr/R/bin/x64 -lRblas -LC:/Users/u0047789/AppData/Local/nlmixr/R/bin/x64 -lRlapack -lgfortran -lm -lquadmath -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/Users/u0047789/AppData/Local/nlmixr/R/bin/x64 -lR
Calculating Table Variables...
done
Warning message:
In collectWarnings(do.call(focei.fit.data.frame0, call, envir = parent.frame(1))) :
  DESCRIPTION file of package 'rlang' is missing or broken

**Comment by mattfidler** [comment]
I would recommend uninstalling the version you have (by removing the directory), and then reinstalling the latest;  The list of releases are here:

https://github.com/nlmixrdevelopment/nlmixr/releases

This will be updated with all the installers and releases.

**Comment by Bo-NONMEM** [comment]
Thanks a lot. It works now!!!

**Comment by mattfidler** [comment]
Great
