### ISSUE TITLE
Cannot install windows version

### ISSUE THREAD

**Issue by EvanTarbell** [nlmixrdevelopment/nlmixr#126]

**Comment by EvanTarbell** [comment]
Hi 
I followed the instructions for installing the windows version. I uninstalled my system anaconda and R and re-installed them. Then i got the following problem:

> RxODE::rxWinPythonSetup()
RxODE requires SymPy for this function.
We recommend you install SymPy for Python and then interact with Python using reticulate.
In Windows you can have help setting this up by typing: `rxWinPythonSetup()`.
Another option is to use SnakeCharmR
Error in rxSymPyStart() : Could not start SymPy
Requirement already up-to-date: pip in c:\r\r-35~1.2\rxpython\lib\site-p~1 (19.0)
Requirement already up-to-date: sympy in c:\r\r-35~1.2\rxpython\lib\site-p~1 (1.3)
Requirement already satisfied, skipping upgrade: mpmath>=0.19 in c:\r\r-35~1.2\rxpython\lib\site-p~1 (from sympy) (1.1.0)
Requirement already up-to-date: numpy in c:\r\r-35~1.2\rxpython\lib\site-p~1 (1.16.0)

i was able to install RxODE, but the error came when trying to link it to python. I have python installed as well as SymPy (if i type 'python' on the cmd it opens the prompt and am able to 'import sympy'. Am i missing something? Any help is appreciated

**Comment by mattfidler** [comment]
Are you using R 3.5.2?  Do you have `SnakeCharmR` or `reticulate`?

**Comment by EvanTarbell** [comment]
Let me start by thanking you for the quick reply.
Yes i am using R 3.5.2. I was able to install reticulate but not SnakeCharmR.
I have Anaconda 5.2 (python 3.6 as per the recommendations) with SymPy installed.

**Comment by mattfidler** [comment]
My recommendation is to remove anaconda and use the R/nlmixr windows installer located at

https://github.com/nlmixrdevelopment/nlmixr/releases

Often various python installations can fight with one another.  I have also found that in windows SnakeCharmR is more stable.

Let me know if this works for you.

**Comment by EvanTarbell** [comment]
Thanks for the reply. It does seem like it was installed. SnakeCharmR is now installed. However, running through the example specified here : 
https://cran.r-project.org/web/packages/nlmixr/vignettes/running_nlmixr.html
with the command: 
 fit <- nlmixr(one.cmt, theo_sd, est="nlme")
threw the following errors: 

0.000000e+00 1.298998e-11 # this is the last line of iteration 7 before sympy was supposed to be called
Error in strsplit(ret, "\n") : non-character argument
In addition: Warning message:
In nlmixrUI.nlme.var(obj) :
  Initial condition for additive error ignored with nlme
Error in strsplit(ret, "\n") : non-character argument
Warning message:
In as.focei.nlmixrNlme(fit, uif, pt, data = dat, calcResid = calc.resid) :
  Error calculating nlmixr object, return classic nlme object
Am i just missing some command or parameter? Or should i start a new issue for this?
And again, thank you for your help.

**Comment by EvanTarbell** [comment]
I also used the test_install script and got the following results:
> source("https://raw.githubusercontent.com/nlmixrdevelopment/nlmixr/master/build/test_install.R")
Correct R version: Yes, R version 3.5.1 (2018-07-02)
RxODE installed: Yes
Python installed: Yes, Python 3.7.1
sympy installed: Yes
devtools package installed: Yes
Rtools installed: Yes
RxODE package installed: Yes
SnakeCharmR package installed: Yes
nlmixr package installed: Yes
xpose.nlmixr package installed: Yes
shinyMixR package installed: Yes
Error in strsplit(ret, "\n") : non-character argument
In addition: Warning message:
package ‘RxODE’ was built under R version 3.5.2 
Error in strsplit(ret, "\n") : non-character argument
C:/R/NLMIXR~1.0-7/rtools/mingw_64/bin/g++  -I"C:/R/NLMIXR~1.0-7/R/include" -DNDEBUG       -IC:/R/NLMIXR~1.0-7/R/library/nlmixr/include -IC:/R/NLMIXR~1.0-7/R/library/STANHE~1/include -IC:/Users/SCOTTV~1/DOCUME~1/R/WIN-LI~1/3.5/Rcpp/include -IC:/Users/SCOTTV~1/DOCUME~1/R/WIN-LI~1/3.5/RCPPAR~1/include -IC:/Users/SCOTTV~1/DOCUME~1/R/WIN-LI~1/3.5/RCPPEI~1/include -IC:/Users/SCOTTV~1/DOCUME~1/R/WIN-LI~1/3.5/BH/include   -O2 -Wall  -mtune=generic -c saem1dbc3efcce1x64.cpp -o saem1dbc3efcce1x64.o
C:/R/NLMIXR~1.0-7/rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o saem1dbc3efcce1x64.dll tmp.def saem1dbc3efcce1x64.o -LC:/R/NLMIXR~1.0-7/R/bin/x64 -lRblas -LC:/R/NLMIXR~1.0-7/R/bin/x64 -lRlapack -LC:/R/NLMIXR~1.0-7/R/bin/x64 -lR
Error in strsplit(ret, "\n") : non-character argument
Error in strsplit(ret, "\n") : non-character argument
Error in strsplit(ret, "\n") : non-character argument

**Comment by mattfidler** [comment]
Could you see whether reticulate is in the packages.  Try:

```R
library(reticulate)
```

and see if it succeeds or fails.

**Comment by mattfidler** [comment]
Can you remove reticulate.  Often I have found that reticulate doesn't seem to work on windows for nlmixr.  It is great for every other system.  I already opened an issue.

https://github.com/rstudio/reticulate/issues/366

**Comment by EvanTarbell** [comment]
> .libPaths()
[1] "C:/Users/Scott Van Wart/Documents/R/win-library/3.5"
[2] "C:/R/nlmixr_1.0.0-7/R/library"

thanks

**Comment by mattfidler** [comment]
Hi @EvanTarbell 

I would go to the `C:/Users/Scott Van Wart/Documents/R/win-library/3.5` directory and remove the `reticulate` package by deleting the `reticulate` directory.  If you want to make sure there are no conflicts you can delete all the packages in the `C:/Users/Scott Van Wart/Documents/R/win-library/3.5` directory.  By the way, do you want me to mask your user name?

**Comment by EvanTarbell** [comment]
I removed reticulate from my library and still got the following error when running the test scripts:
 source("https://raw.githubusercontent.com/nlmixrdevelopment/nlmixr/master/build/test_install.R")

Correct R version: Yes, R version 3.5.1 (2018-07-02)
RxODE installed: Yes
Python installed: Yes, Python 3.7.1
sympy installed: Yes
devtools package installed: Yes
Rtools installed: Yes
RxODE package installed: Yes
SnakeCharmR package installed: Yes
nlmixr package installed: Yes
xpose.nlmixr package installed: Yes
shinyMixR package installed: Yes
Error in strsplit(ret, "\n") : non-character argument
Error in strsplit(ret, "\n") : non-character argument
C:/R/NLMIXR~1.0-7/rtools/mingw_64/bin/g++  -I"C:/R/NLMIXR~1.0-7/R/include" -DNDEBUG       -IC:/R/NLMIXR~1.0-7/R/library/nlmixr/include -IC:/R/NLMIXR~1.0-7/R/library/STANHE~1/include -IC:/Users/EVANTA~1/DOCUME~1/R/WIN-LI~1/3.5/Rcpp/include -IC:/Users/EVANTA~1/DOCUME~1/R/WIN-LI~1/3.5/RCPPAR~1/include -IC:/R/NLMIXR~1.0-7/R/library/RCPPEI~1/include -IC:/Users/EVANTA~1/DOCUME~1/R/WIN-LI~1/3.5/BH/include   -O2 -Wall  -mtune=generic -c saem2b84917516x64.cpp -o saem2b84917516x64.o
C:/R/NLMIXR~1.0-7/rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o saem2b84917516x64.dll tmp.def saem2b84917516x64.o -LC:/R/NLMIXR~1.0-7/R/bin/x64 -lRblas -LC:/R/NLMIXR~1.0-7/R/bin/x64 -lRlapack -LC:/R/NLMIXR~1.0-7/R/bin/x64 -lR
Error in strsplit(ret, "\n") : non-character argument
Error in strsplit(ret, "\n") : non-character argument
Error in strsplit(ret, "\n") : non-character argument

And thank you for all your help getting me to this stage

**Comment by mattfidler** [comment]
Hi @EvanTarbell,

Can you try the install script again.

I updated the install script.

**Comment by EvanTarbell** [comment]
Hi @mattfidler 

The error is the same as before. It seems like everything is good up until the point where the script attempts to run the test run, at which point it crashes with the strsplit(ret,"/n") non-character argument error.

**Comment by EvanTarbell** [comment]
Hi @mattfidler 

Ive tried to run the SAEM example as such:
 one.compartment.saem <- function() {
+     ini({
+         tka <- .5   # Log Ka
+         tcl <- -3.2 # Log Cl
+         tv <- -1    # Log V
+         eta.ka ~ 1
+         eta.cl ~ 2
+         eta.v ~ 1
+         add.err <- 0.1
+     })
+     model({
+         ka <- exp(tka + eta.ka)
+         cl <- exp(tcl + eta.cl)
+         v <- exp(tv + eta.v)
+         d/dt(depot) = -ka * depot
+         d/dt(center) = ka * depot - cl / v * center
+         cp = center / v 
+         cp ~ add(add.err)
+     })
+ }
> fit <- nlmixr(one.compartment.saem, theo_sd, est="saem")

which then results in the following messages:
Compiling RxODE differential equations...done.
PKG_CXXFLAGS=-IC:/R/NLMIXR~1.0-7/R/library/nlmixr/include -IC:/R/NLMIXR~1.0-7/R/library/STANHE~1/include -IC:/Users/EVANTA~1/DOCUME~1/R/WIN-LI~1/3.5/Rcpp/include -IC:/Users/EVANTA~1/DOCUME~1/R/WIN-LI~1/3.5/RCPPAR~1/include -IC:/R/NLMIXR~1.0-7/R/library/RCPPEI~1/include -IC:/Users/EVANTA~1/DOCUME~1/R/WIN-LI~1/3.5/BH/include
PKG_LIBS= $(BLAS_LIBS) $(LAPACK_LIBS)
C:/R/NLMIXR~1.0-7/rtools/mingw_64/bin/g++  -I"C:/R/NLMIXR~1.0-7/R/include" -DNDEBUG       -IC:/R/NLMIXR~1.0-7/R/library/nlmixr/include -IC:/R/NLMIXR~1.0-7/R/library/STANHE~1/include -IC:/Users/EVANTA~1/DOCUME~1/R/WIN-LI~1/3.5/Rcpp/include -IC:/Users/EVANTA~1/DOCUME~1/R/WIN-LI~1/3.5/RCPPAR~1/include -IC:/R/NLMIXR~1.0-7/R/library/RCPPEI~1/include -IC:/Users/EVANTA~1/DOCUME~1/R/WIN-LI~1/3.5/BH/include   -O2 -Wall  -mtune=generic -c saem1dfc49962c55x64.cpp -o saem1dfc49962c55x64.o
C:/R/NLMIXR~1.0-7/rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o saem1dfc49962c55x64.dll tmp.def saem1dfc49962c55x64.o -LC:/R/NLMIXR~1.0-7/R/bin/x64 -lRblas -LC:/R/NLMIXR~1.0-7/R/bin/x64 -lRlapack -LC:/R/NLMIXR~1.0-7/R/bin/x64 -lR
done.
1:    0.1503  -3.3314  -0.6447   0.9500   1.9000   0.9500   9.6167
2:    0.5210  -3.5986  -0.5154   0.9025   1.8050   0.9025   4.2880
3:    0.7840  -3.5040  -0.6070   0.8574   1.7147   0.8574   2.1258
... etc 
499:    0.4547  -3.2153  -0.7848   0.4411   0.0713   0.0180   0.4775
500:    0.4546  -3.2153  -0.7848   0.4413   0.0713   0.0180   0.4774
Load into sympy...Using sympy via SnakeCharmR
done
Freeing Python/SymPy memory...done
################################################################################
Optimizing expressions in Predictions/EBE model...done
Compiling Predictions/EBE model...done
Standardized prediction/ebe models produced.
Error : 'foceiFitCpp_' is not an exported object from 'namespace:RxODE'
Error : 'foceiFitCpp_' is not an exported object from 'namespace:RxODE'
Warning message:
In as.focei.saemFit(.fit, uif, pt, data = dat, calcResid = calc.resid,  :
  Error calculating nlmixr object, return classic object

Im not sure if this helps identify where my issues are coming from, as it does appear that python, sympy, SnakeCharmR etc are there.
And once again, thank you for your patience and help thus far!!

**Comment by mattfidler** [comment]
I believe it is because you have a mismatch between supported versions of RxODE.  It seems you have the development version of RxODE in your local library and the release version of nlmixr.

I think you need to go to the `C:/Users/User/Documents/R/win-library/3.5` directory and remove any `RxODE` and `nlmixr` folders in there.  This should correct the issue.

**Comment by EvanTarbell** [comment]
Hi @mattfidler 

That did it!! The test script ran to completion and reported that the various modules ran successfully!
Thank you for all your help!

**Comment by mattfidler** [comment]
Awesome!  That is great.
