### ISSUE TITLE
shinyMixR failed in Win 10.

### ISSUE THREAD

**Issue by sliao99** [nlmixrdevelopment/nlmixr#129]
When I tried to run 'run1', I got this error msg.  Is there ways to fix this?

 ***************C:/Users/User/Documents/shinyMixR/temp/run1.prog.txt***************
Loading required package: nlme
Loading required package: RxODE
Error: unexpected '}' in:
"  data_nlm <- 
}"
Execution halted

**Comment by mattfidler** [comment]
Hi @sliao99 I opened an issue in the ShinyMixR repository.
