### ISSUE TITLE
nlmix R not working

### ISSUE THREAD

**Issue by DimitrisVoul** [nlmixrdevelopment/nlmixr#130]
Hello I am trying to install and use nlmix R but I have a lot of problem along the way.

I have installed RxODE normally from github and when I run RxODE::rxWinPythonSetup() i get an error for SnakeCharm R

> Error: package or namespace load failed for 'SnakeCharmR':
>  .onAttach failed in attachNamespace() for 'SnakeCharmR', details:
>   call: rcpp_Py_get_var("_SnakeCharmR_return")
>   error: variable is not a string
> Error: loading failed
> Execution halted
> ERROR: loading failed
> * removing 'C:/Users/jimmas/Documents/R/win-library/3.5/SnakeCharmR'
> In R CMD INSTALL

Trying installing SnakeCharmR using install_github("asieira/SnakeCharmR") still the same.

I then installed reticulate and rSympy and run the model and get the following error:

> Error in dynLoad(.cDllFile) : 
>   Evaluation error: unable to load shared object 'C:/Users/jimmas/AppData/Local/Temp/Rtmp6r3NKp/rx_50de63abff1be36f3d1aa2fafff14238_x64.dll':
>   LoadLibrary failure:  The specified module could not be found.
> .
> In addition: Warning messages:
> 1: In nmDataConvert(dat) :
>   Assumed all DV values are observations. (EVID=0)
> 2: In nmDataConvert(dat) : Assuming AMT=0.
> 3: In nlmixrData.default(data) :
>   Sorting by ID, TIME; Output fit may not be in the same order as input dataset.
> Error in rxCompile.character(model, extraC = extraC, debug = debug, calcJac = calcJac,  : 
>   Error loading model.

I am not sure what can be the problem and what I need to do.

**Comment by mattfidler** [comment]
I suggest uninstalling R and using the nlmixr installer; 

https://github.com/nlmixrdevelopment/nlmixr/releases

In this release everything is setup for you.  

Let me know if this works for you.

**Comment by DimitrisVoul** [comment]
Thank you very much. I will give it a try and let you know.

Can I use that through Rstudio?

**Comment by DimitrisVoul** [comment]
I uninstalled R and installed I run the nlmixr installer. 

SnakeCharm is finally installed but unfortunately I still have some issues. Namely I get this error when I try to run the model

> Error: 'rxSymInvCreate' is not an exported object from 'namespace:RxODE'

and when i tried to run the install checker I get the following:

> Correct R version: Yes, R version 3.5.1 (2018-07-02)
> RxODE installed: Yes
> Python installed: Yes, Python 3.7.1
> sympy installed: Yes
> devtools package installed: Yes
> Rtools installed: Yes
> RxODE package installed: Yes
> SnakeCharmR package installed: Yes
> nlmixr package installed: Yes
> xpose.nlmixr package installed: Yes
> shinyMixR package installed: Yes
> Error in strsplit(ret, "\n") : non-character argument


after which it stops

**Comment by mattfidler** [comment]
Can you check your `.libPaths()`;  Please let me know what is output there:

For me it gives:

```R
> .libPaths()
[1] "c:/R/nlmixr_1.0.0-7/R/library"
```

**Comment by mattfidler** [comment]
Note, that this does work with rstudio.

**Comment by DimitrisVoul** [comment]
I get the following:

 "C:/Users/Username/Documents/R/win-library/3.5"   "c:/R/nlmixr_1.0.0-7/R/library"

**Comment by mattfidler** [comment]
There may be conflicting packages in `C:/Users/Username/Documents/R/win-library/3.5`

You can remove the packages there, or just try:

```R
.libPaths(.libPaths()[2])
```
And then run it nlmixr to see if it works for you.  You can check to make sure the `.libPaths()` only contains the nlmixr library before you test it out.

If so, you may wish to remove the packages in 3.5, unless you use them in a different version of R.  Otherwise, you may wish to have the `.libPaths()` at the beginning of your nlmixr scripts.

**Comment by mattfidler** [comment]
Also, for some reason nlmixr and R sometimes has problems with international characters and spaces in `UserName`, though I'm not quite sure that is true in this case

**Comment by DimitrisVoul** [comment]
I tried that and it seems to be working just fine now. Thank you very much for all the help!

**Comment by mattfidler** [comment]
I'm glad it worked for you :) 

If you need any other help let me know.
