### ISSUE TITLE
nlmixr fails with a `function not provided` error message

### ISSUE THREAD

**Issue by tamas-ferenci** [nlmixrdevelopment/nlmixr#132]
After running the default example in the vignette (`fit <- nlmixr(one.compartment.saem, theo_sd, est="saem")`), I got the following error message:

`Compiling RxODE equations...done. Error in cur.fn(a) :    function 'rx_1b381593d1e6bba011dfaf16614bff77_x64_ode_solver' not provided by package 'rx_1b381593d1e6bba011dfaf16614bff77_x64'`

This doesn't happen with the CRAN version of nlmixr/RxODE, but when I update both from the Github, this is the result...

**Comment by mattfidler** [comment]
I'm not sure exactly why this happens, but it can usually be fixed  by:

```R
library(nlmixr)
rxClean()
```

**Comment by tamas-ferenci** [comment]
Thanks! It didn't work (returned `FALSE`, even when I ran RStudio as Administrator), but by a very little debugging it became obvious that `.rxTempDir()` is not cleared, so I simply manually deleted everything from that folder from the operating system, and after that everything was fine!
