### ISSUE TITLE
Conditional statements in FOCEi

### ISSUE THREAD

**Issue by DimitrisVoul** [nlmixrdevelopment/nlmixr#133]
Hello,

I am trying to use nlmixr and focei for a differential model where the differential equation depends on a parameter value, i.e. if value < threshold then we have differential equation 1 otherwise differential equation 2.

I implemented it but I get an error that I don't provide the value despite the fact that it is defined in the model section just above.

As an example
```R
> model({
>     V0 <- exp(tv0+eta.v0) 
>     KGROW <- exp(tkgrow+eta.kgrow) 
>  
>     V(0) = V0 
>     r = ((3/(4*pi))*V)^(1/3)
>     
>     if (r < 0.5) {
>       d/dt(V) = KGROW*V^1
>     } else {
>       d/dt(V)= KGROW*V^2
>     }
>     
>     V~prop(prop.err)
````
I get

> Error in RxODE::foceiFitCpp_(.ret) : 
>   The following parameter(s) are required for solving: r

**Comment by mattfidler** [comment]
Can you provide the full model, not just the `model` block?

**Comment by DimitrisVoul** [comment]
Yes sure, there you go:

> fullmodel <- function() {
>   ini({
>     tv0 <- -1.4
>     tkgrow <- -3
>     trdiff <- -3
>     prop.err <- 0.3
>     
>     eta.v0 ~ 0.07
>     eta.kgrow ~ 1
>     eta.rdiff ~ 1
> })
> model({
>     V0 <- exp(tv0+eta.v0) 
>     KGROW <- exp(tkgrow+eta.kgrow) 
>  
>     V(0) = V0 
>     r = ((3/(4*pi))*V)^(1/3)
>     
>     if (r < 0.5) {
>       d/dt(V) = KGROW*V^1
>     } else {
>       d/dt(V)= KGROW*V^2
>     }
>     
>     V~prop(prop.err)
>   })
> }

**Comment by mattfidler** [comment]
Thanks.  It seems like it should work.  Do you have any data you can share.  If you don't want to share it on a public forum, you can email me.

**Comment by mattfidler** [comment]
I guess I mis-spoke there is some errors in your model:
``` r
library(nlmixr)
fullmodel <- function() {
 ini({
 tv0 <- -1.4
 tkgrow <- -3
 trdiff <- -3
 prop.err <- 0.3
 
 eta.v0 ~ 0.07
 eta.kgrow ~ 1
eta.rdiff ~ 1
 })
model({
 V0 <- exp(tv0+eta.v0) 
 KGROW <- exp(tkgrow+eta.kgrow) 

 V(0) = V0 
 r = ((3/(4*pi))*V)^(1/3)
 
if (r < 0.5) {
  d/dt(V) = KGROW*V^1
 } else {
   d/dt(V)= KGROW*V^2
 }
 
 V~prop(prop.err)
})
}

nlmixr(fullmodel)
#> Error in nlmixrUI(object): Model error: initial estimates provided without variables being used: trdiff, eta.rdiff
```

<sup>Created on 2019-02-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mattfidler** [comment]
You can fix the model, as shown below;  Maybe you can try with the updated model?

``` r
library(nlmixr)
fullmodel <- function() {
 ini({
 tv0 <- -1.4
 tkgrow <- -3
 prop.err <- 0.3
 
 eta.v0 ~ 0.07
 eta.kgrow ~ 1
 })
model({
 V0 <- exp(tv0+eta.v0) 
 KGROW <- exp(tkgrow+eta.kgrow) 

 V(0) = V0 
 r = ((3/(4*pi))*V)^(1/3)
 
if (r < 0.5) {
  d/dt(V) = KGROW*V^1
 } else {
   d/dt(V)= KGROW*V^2
 }
 
 V~prop(prop.err)
})
}

nlmixr(fullmodel)
#> ▂▂ RxODE-based ODE model ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
#> ── Initialization: ────────────────────────────────────────────────────────
#> Fixed Effects ($theta):
#>    tv0 tkgrow 
#>   -1.4   -3.0
#> 
#> Omega ($omega):
#>           eta.v0 eta.kgrow
#> eta.v0      0.07         0
#> eta.kgrow   0.00         1
#> ── Model: ─────────────────────────────────────────────────────────────────
#> 
#> ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
```

<sup>Created on 2019-02-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DimitrisVoul** [comment]
Sorry about the error in the example. they were due to the fact that I copied the wrong model partly.

I have tried the suggested model with the theo_sd data set and focei and I still get the same error. That r is needed for the computation

**Comment by mattfidler** [comment]
Can you provide your complete code so I can reproduce exactly?

**Comment by DimitrisVoul** [comment]
The code is exactly the code in your comment just above using the theo_sd data.

> library(nlmixr)
> fullmodel <- function() {
>  ini({
>  tv0 <- -1.4
>  tkgrow <- -3
>  prop.err <- 0.3
>  
>  eta.v0 ~ 0.07
>  eta.kgrow ~ 1
>  })
> model({
>  V0 <- exp(tv0+eta.v0) 
>  KGROW <- exp(tkgrow+eta.kgrow) 
> 
>  V(0) = V0 
>  r = ((3/(4*pi))*V)^(1/3)
>  
> if (r < 0.5) {
>   d/dt(V) = KGROW*V^1
>  } else {
>    d/dt(V)= KGROW*V^2
>  }
>  
>  V~prop(prop.err)
> })
> }
> 
> fit<-nlmixr(fullmodel,theo_sd,est='focei')

**Comment by mattfidler** [comment]
I cannot reproduce with the github version of nlmixr/RxODE.  Instead I get:

``` r
library(nlmixr)

fullmodel <- function() {
 ini({
 tv0 <- -1.4
 tkgrow <- -3
 prop.err <- 0.3

 eta.v0 ~ 0.04
 eta.kgrow ~ 0.05
 })
model({
 V0 <- exp(tv0+eta.v0)
 KGROW <- exp(tkgrow+eta.kgrow)

 V(0) = V0
 r = ((3/(4*pi))*V)^(1/3)

if (r < 0.5) {
  d/dt(V) = KGROW*V^1
 } else {
   d/dt(V)= KGROW*V^2
 }

 V~prop(prop.err)
})
}

fit<-nlmixr(fullmodel,theo_sd,est='focei', control=list(method="lsoda"))
#> Calculate ETA-based prediction and error derivatives:
#> ################################################################################
#> ## Condition: (!(r<0.5))
#> ################################################################################
#> Using sympy via reticulate
#> Calculate Jacobian
```

    #> Calculate Sensitivities

    #> Load into sympy...
    #> done
    #> Calculate ∂(f)/∂(η)

    #> Calculate ∂(R²)/∂(η)

    #> Freeing Python/SymPy memory...
    #> done
    #> ################################################################################
    #> ## Condition: (r<0.5)
    #> ################################################################################
    #> Calculate Jacobian

    #> Calculate Sensitivities

    #> Load into sympy...
    #> done
    #> Calculate ∂(f)/∂(η)

    #> Calculate ∂(R²)/∂(η)

    #> Freeing Python/SymPy memory...
    #> done
    #> ################################################################################
    #> Optimizing expressions in Predictions/EBE model...done
    #> Compiling Predictions/EBE model...done
    #> Optimizing expressions in Inner model...done
    #> Compiling Inner model...done
    #> The model-based sensitivities have been calculated.
    #> Key: U: Unscaled Parameters; X: Back-transformed parameters; G: Gradient
    #> |-----+---------------+-----------+-----------+-----------+-----------|
    #> |    #| Objective Fun |       tv0 |    tkgrow |  prop.err |           |
    #> |.....................|           |...........|...........|...........|
    #> |-----+---------------+-----------+-----------+-----------+-----------|
    #> DLSODA-  Warning..Internal T (=R1) and H (=R2) are         
    #>       such that in the machine, T + H = T on the next step 
    #>      (H = step size). Solver will continue anyway
    #> DLSODA-  Warning..Internal T (=R1) and H (=R2) are         
    #>       such that in the machine, T + H = T on the next step 
    #>      (H = step size). Solver will continue anyway
    #> DLSODA-  Warning..Internal T (=R1) and H (=R2) are         
    #>       such that in the machine, T + H = T on the next step 
    #>      (H = step size). Solver will continue anyway
    #> DLSODA-  Warning..Internal T (=R1) and H (=R2) are         
    #>       such that in the machine, T + H = T on the next step 
    #>      (H = step size). Solver will continue anyway
    #> DLSODA-  Warning..Internal T (=R1) and H (=R2) are         
    #>       such that in the machine, T + H = T on the next step 
    #>      (H = step size). Solver will continue anyway
    #> DLSODA-  Warning..Internal T (=R1) and H (=R2) are         
    #>       such that in the machine, T + H = T on the next step 
    #>      (H = step size). Solver will continue anyway
    #> DLSODA-  Warning..Internal T (=R1) and H (=R2) are         
    #>       such that in the machine, T + H = T on the next step 
    #>      (H = step size). Solver will continue anyway
    #> DLSODA-  Warning..Internal T (=R1) and H (=R2) are         
    #>       such that in the machine, T + H = T on the next step 
    #>      (H = step size). Solver will continue anyway
    #> DLSODA-  Warning..Internal T (=R1) and H (=R2) are         
    #>       such that in the machine, T + H = T on the next step 
    #>      (H = step size). Solver will continue anyway
    #> DLSODA-  Warning..Internal T (=R1) and H (=R2) are         
    #>       such that in the machine, T + H = T on the next step 
    #>      (H = step size). Solver will continue anyway
    #> DLSODA-  Above warning has been issued I1 times. 
    #>      It will not be issued again for this problem
    #> DINTDY-  T (=R1) illegal     
    #>       T not in interval TCUR - HU (= R1) to TCUR (=R2)     
    #> DINTDY-  T (=R1) illegal     
    #>       T not in interval TCUR - HU (= R1) to TCUR (=R2)     
    #> DLSODA-  Trouble in DINTDY.  ITASK = I1, TOUT = R
    #> Error in foceiFitCpp_(.ret): Evaluation error: bad solve.

<sup>Created on 2019-02-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

This implies it cannot fit the `theo_sd` to the model you have, which is not really a surprise...

**Comment by DimitrisVoul** [comment]
The problem for me is that I don't even get to the fitting part. It doesn't perform the fitting because I get the error saying that parameter "r" is missing.

So the issue is not fitting the theo_sd data but rather fixing this missing parameter error I get when using the IF statement.

If I don't use IF then the fitting is performed normally.

**Comment by DimitrisVoul** [comment]
The error I get;

`rx_expr_001 ~ 2*V
rx_expr_002 ~ ETA[1]+THETA[1]
rx_expr_003 ~ ETA[2]+THETA[2]
rx_expr_004 ~ Rx_pow_di(V, 2)
rx_expr_005 ~ exp(rx_expr_002)
rx_expr_006 ~ exp(rx_expr_003)
rx_expr_007 ~ V*exp(rx_expr_003)
rx_expr_008 ~ Rx_pow_di(THETA[3], 2)
rx_expr_009 ~ 2*rx_expr_008
rx_expr_010 ~ 2*rx_expr_008*V
rx_expr_011 ~ rx_expr_004*exp(rx_expr_003)
V(0) = exp(rx_expr_002)
if(r<0.5){
d/dt(V) = V*exp(rx_expr_003)
}
else{
d/dt(V) = rx_expr_004*exp(rx_expr_003)
}
rx__sens_V_BY_ETA_1___(0) = exp(rx_expr_002)
if(r<0.5){
d/dt(rx__sens_V_BY_ETA_1___) ~ rx__sens_V_BY_ETA_1___*exp(rx_expr_003)
d/dt(rx__sens_V_BY_ETA_2___) ~ V*exp(rx_expr_003)+rx__sens_V_BY_ETA_2___*exp(rx_expr_003)
}
else{
d/dt(rx__sens_V_BY_ETA_1___) = rx_expr_001*rx__sens_V_BY_ETA_1___*exp(rx_expr_003)
d/dt(rx__sens_V_BY_ETA_2___) = rx_expr_004*exp(rx_expr_003)+rx_expr_001*rx__sens_V_BY_ETA_2___*exp(rx_expr_003)
}
rx_yj_ ~ 2
rx_lambda_ ~ 1
rx_pred_ = V
rx__sens_rx_pred__BY_ETA_1___ = rx__sens_V_BY_ETA_1___
rx__sens_rx_pred__BY_ETA_2___ = rx__sens_V_BY_ETA_2___
rx_r_ = rx_expr_008*rx_expr_004
rx__sens_rx_r__BY_ETA_1___ = 2*rx_expr_008*V*rx__sens_V_BY_ETA_1___
rx__sens_rx_r__BY_ETA_2___ = 2*rx_expr_008*V*rx__sens_V_BY_ETA_2___

Error in RxODE::foceiFitCpp_(.ret) : 
  The following parameter(s) are required for solving: r`

**Comment by mattfidler** [comment]
I suggest trying the github version

```R
devtools::install_github("nlmixrdevelopment/RxODE")
devtools::install_github("nlmixrdevelopment/nlmixr")
```

If you run into any issues, let me know.

**Comment by DimitrisVoul** [comment]
I am afraid I cannot do that because I will run into exactly the same issues I had before of RxODE not connecting to python. I only fixed that when I downloaded the nlmixr installer per your suggestion

**Comment by mattfidler** [comment]
I don't think that is true.  The python connection will still use the nlmixr installed version.

However before you begin, please check the following variable:

```R
.libPaths()
```
