### ISSUE TITLE
Errors when installing RxODE

### ISSUE THREAD

**Issue by kilterwind** [nlmixrdevelopment/nlmixr#136]
Below is the messages I got when I was running `install_github("nlmixrdevelopment/RxODE")`:

```
> install_github("nlmixrdevelopment/RxODE")
Downloading GitHub repo nlmixrdevelopment/RxODE@master
Installing 38 packages: BH, brew, colorspace, dparser, dplyr, fansi, farver, ggforce, ggplot2, gtable, inline, labeling, lazyeval, munsell, mvnfast, n1qn1, pillar, pkgconfig, plogr, plyr, PreciseSums, purrr, R.methodsS3, R.oo, R.utils, RColorBrewer, RcppArmadillo, reshape2, rex, scales, stringi, stringr, tibble, tidyselect, tweenr, units, utf8, viridisLite

# [All packages installed with MD5 sums checked]  
  
  
   checking for file 'C:\Users\Matthew\AppData\Local\Temp\RtmpGeWjEp\remotes16d02a89684c\nlmixrdevelopment-RxODE-0517061/DESCRIPTION' ...
   checking for file 'C:\Users\Matthew\AppData\Local\Temp\RtmpGeWjEp\remotes16d02a89684c\nlmixrdevelopment-RxODE-0517061/DESCRIPTION' ... 
√  checking for file 'C:\Users\Matthew\AppData\Local\Temp\RtmpGeWjEp\remotes16d02a89684c\nlmixrdevelopment-RxODE-0517061/DESCRIPTION' (412ms)

  
-  preparing 'RxODE': (2.8s)
   checking DESCRIPTION meta-information ...
   checking DESCRIPTION meta-information ... 
√  checking DESCRIPTION meta-information
-  cleaning src
-  running 'cleanup.win'
-  checking for LF line-endings in source and make files and shell scripts (808ms)
-  checking for empty or unneeded directories

  
Removed empty directory 
   Removed empty directory 'RxODE/man-roxygen'

-  building 'RxODE_0.8.1-0.tar.gz'

Warning:
   Warning: file 'RxODE/cleanup' did not have execute permissions: corrected
Warning:
   Warning: file 'RxODE/configure' did not have execute permissions: corrected

Installing package into ‘C:/Users/Matthew/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'RxODE' ...
--------[[begin src/Makevars.win]]--------
# -*- mode: makefile-gmake -*-
CXX_STD     = CXX11

################################################################################
## Package library flags.
PKG_LIBS    = $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS) $(SHLIB_OPENMP_CFLAGS)

# Release options
PKG_CFLAGS  =  $(SHLIB_OPENMP_CFLAGS)
PKG_CPPFLAGS = $(SHLIB_OPENMP_CFLAGS)

SOURCES_C = call_dvode.c dop853.c tran.c omegaChol.c init.c par_solve.c cfode.c common.c corfailure.c correction.c daxpy.c ddot.c dgefa.c dgesl.c dscal.c fnorm.c idamax.c intdy.c lsoda.c methodswitch.c orderswitch.c prja.c scaleh.c solsy.c stoda.c vmnorm.c strdup_printf.c rprintf.c lincmt.c box.c
SOURCES_CPP = RcppExports.cpp WinDrive.cpp rxInv.cpp rxData.cpp etTran.cpp et.cpp rxStack.cpp
SOURCES_FORTAN = dlsoda.f opkda1_abbr.f opkda2.f

OBJECTS = $(SOURCES_C:.c=.o) $(SOURCES_FORTAN:.f=.o) $(SOURCES_CPP:.cpp=.o)

.PHONY: all mylibs
all: $(SHLIB)
$(SHLIB): mylibs
mylibs:  
        $(CC) -I"$(R_INCLUDE_DIR)" $(CFLAGS) $(CPPFLAGS) $(SHLIB_CFLAGS) $(CPICFLAGS) -I../inst/include/ ../inst/include/RxODE_model.h || $(CC) --version

# mylibs:
#       clang -I"$(R_INCLUDE_DIR)" $(CFLAGS) $(CPPFLAGS) $(SHLIB_CFLAGS) $(CPICFLAGS) -I../inst/include/ ../inst/include/RxODE_model.h -emit-pch -o ../inst/include/RxODE_model.h.pch


--------[[end src/Makevars.win]]--------
** libs
Error: (converted from warning) this package has a non-empty 'configure.win' file,
so building only the main architecture
* removing 'C:/Users/Matthew/Documents/R/win-library/3.5/RxODE'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/Matthew/AppData/Local/Temp/RtmpGeWjEp/file16d0529f19be/RxODE_0.8.1-0.tar.gz’ had non-zero exit status
```

Here is my `sessioninfo()`:
```
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_Hong Kong SAR.1252  LC_CTYPE=English_Hong Kong SAR.1252    LC_MONETARY=English_Hong Kong SAR.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_Hong Kong SAR.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] usethis_1.4.0  devtools_2.0.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0        ps_1.3.0          prettyunits_1.0.2 rprojroot_1.3-2   digest_0.6.18     crayon_1.3.4      withr_2.1.2       assertthat_0.2.0  R6_2.4.0          backports_1.1.3  
[11] magrittr_1.5      rlang_0.3.1       cli_1.0.1         curl_3.3          fs_1.2.6          remotes_2.0.2     callr_3.1.1       desc_1.2.0        tools_3.5.2       glue_1.3.0       
[21] pkgload_1.0.2     compiler_3.5.2    processx_3.2.1    pkgbuild_1.0.2    sessioninfo_1.1.1 memoise_1.1.0
```

Besides, I have installed the latest version of Rtools (3.5) and Python (3.7, through Anaconda).

I was not successful and had attempted to uninstall all of R, Python, Rtools and removed all relevant environmental `PATH`, hoping a fresh start might help. It did not. Any suggestion?

Thanks!
Matthew

**Comment by mattfidler** [comment]
I haven't tried with R 3.5.2 yet.  

Do you use anaconda?

**Comment by mattfidler** [comment]
Or are you going to use sensitivity equations with RxODE? (like with nlmixr)

**Comment by kilterwind** [comment]
> I haven't tried with R 3.5.2 yet.
> 
> Do you use anaconda?

Okay. Should I try 3.5.0 or 3.5.1?
And yes I am using anaconda already.

And, what to do with the sensitivity equations? Am I right that if I need to use nlmixr I need to get RxODE installed anyway?

**Comment by mattfidler** [comment]
Yes you need the python RxODE.

You can try to install nlmixr from CRAN.

```
install.packages(c("nlmixr","RxODE"))
```

**Comment by kilterwind** [comment]
I installed both `nlmixr` and `RxODE` using the above command. Then I go on to last section [here](https://github.com/nlmixrdevelopment/nlmixr) to test the install. What I get is this:
```
Correct R version: Yes, R version 3.5.2 (2018-12-20)
RxODE installed: Yes
Python installed: Yes, Python 3.7.1
sympy installed: Yes
devtools package installed: Yes
RxODE package installed: Yes
Rtools installed or not needed: Yes
SnakeCharmR package installed: No
        To install, use install_github('nlmixrdevelopment/SnakeCharmR') to do so
        Note SnakeCharmR seems to work better on windows than reticulate...
retuclate package installed: No
# And then output of sessionInfo()
```
So, looks like `SnakeCharmR` is missing. I followed the instructions in the same page to try to install `SnakeCharmR` but without success:
```
Downloading GitHub repo nlmixrdevelopment/SnakeCharmR@master
√  checking for file 'C:\Users\Matthew\AppData\Local\Temp\RtmpO4aFOg\remotes2e0079102c3a\nlmixrdevelopment-SnakeCharmR-fc4ef64/DESCRIPTION' (335ms)
-  preparing 'SnakeCharmR':
√  checking DESCRIPTION meta-information
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'SnakeCharmR_1.0.7.tar.gz'
  Warning: file 'SnakeCharmR/cleanup' did not have execute permissions: corrected
  Warning: file 'SnakeCharmR/configure' did not have execute permissions: corrected

Installing package into ‘C:/Users/Matthew/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'SnakeCharmR' ...
./configure.win: line 18: pythonC:\ProgramData\Anaconda3: No such file or directory
Error running pythonC:\ProgramData\Anaconda3, exiting.
ERROR: configuration failed for package 'SnakeCharmR'
* removing 'C:/Users/Matthew/Documents/R/win-library/3.5/SnakeCharmR'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/Matthew/AppData/Local/Temp/RtmpO4aFOg/file2e003d6bd93/SnakeCharmR_1.0.7.tar.gz’ had non-zero exit status
```

Any idea? The path `C:\ProgramData\Anaconda3` should be correct - `python.exe` is directly under this directory and `sympy` can be imported from within.

**Comment by kilterwind** [comment]
I tried to shift to R 3.5.0 and tried again to install `SnakeCharmR` using `devtools::install_github("nlmixrdevelopment/SnakeCharmR")`. The installation went through this time. The installation test could also run to the end after installing `xpose`, `xpose.nlmixr` and `shinyMixR`. I tested my own model and `nlmixr` gave similar results to NONMEM. So, I think it can be considered running properly now!

The only strange phenomenon for now is that `library(SnakeCharmR)` still crashes R, despite being able to run properly.

**Comment by mattfidler** [comment]
Perhaps Rtools isn't compatible with R 3.5.1;  It seems like the compiling failed.

If you wished to include SnakeCharmR without crashing R, you can do the following:

```R
library(RxODE)
library(SnakeCharmR)
```

`RxODE` adjusts the environment variables to allow python to run well in R.  If python environmental variables are not setup correctly, python will exit.  It uses a "abort" call, which also crashes R.

**Comment by mattfidler** [comment]
You can see the python environmental variables adjusted here:

https://github.com/nlmixrdevelopment/nlmixr#notes-on-python-configuration

**Comment by mattfidler** [comment]
I'm glad it works for you.  Feel free to post if you have any other issues.

**Comment by melmelie** [comment]
@mattfidler 
I'd appreciate your help with the install, it appears that I am stuck and I have spent a full day already on this. Here's my session info: I am running 64-bit Windows, R Version [64-bit] C:\Program Files\R\R-3.5.0. My question is whether it's possible to not have SnakeCharmR installed and still have successful installation?
Running [source("test_install.R")], I get: 
Correct R version: Yes, R version 3.5.0 (2018-04-23)
RxODE installed: Yes
Python installed: Yes, Python 3.7.1
sympy installed: Yes
devtools package installed: Yes
RxODE package installed: Yes
Rtools installed or not needed: Yes
SnakeCharmR package installed: No
	To install, use install_github('nlmixrdevelopment/SnakeCharmR') to do so
	Note SnakeCharmR seems to work better on windows than reticulate...
reticulate package installed: Yes
units package installed: Yes
nlmixr package installed: Yes
xpose.nlmixr package installed: Yes
shinyMixR package installed: Yes
nlmixr run under nlme: Yes
nlmixr run under saem: Yes
nlmixr run under focei: Yes
---- Installation test finished! ----

As you can see, SnakeCharmR is not installed and library(SnakeCharmR) returns Error in library(SnakeCharmR) : there is no package called ‘SnakeCharmR’. 
devtools::install_github("nlmixrdevelopment/SnakeCharmR") gives an error:
Error: Failed to install 'SnakeCharmR' from GitHub:
  (converted from warning) installation of package ‘C:/Users/elmelm01/AppData/Local/Temp/1/RtmpayAiD2/file2708392b4476/SnakeCharmR_1.0.7.tar.gz’ had non-zero exit status.
Note that I am using Anaconda and nlmixr appears to be seeing this:
* installing *source* package 'SnakeCharmR' ...
Found Python version 3.7
Detected EXEC_PREFIX=c:\R\NLMIXR~1.0-7\python
Detected library dir c:\R\NLMIXR~1.0-7\python/libs
Detected library name python37
Detected include dir c:\R\NLMIXR~1.0-7\python/include
--------[[begin src/Makevars.win]]--------
PKG_LIBS=-L'c:\R\NLMIXR~1.0-7\python/libs' -lpython37
PKG_CPPFLAGS=-I'c:\R\NLMIXR~1.0-7\python/include'
CXX_STD=CXX11
--------[[end src/Makevars.win]]--------
** libs.

I am concerned that the package isn't installed correctly especially that I get error message when running focei:
unhandled error message: EE:lsoda -- at t = 0 and step size _C(h) = 1.60517e-010, the
         corrector convergence failed repeatedly or
         with fabs(_C(h)) = hmin
 @(lsoda.c:897)¢ƒÉ¼Îñ?šD§*

yet, I get the following successful installation note even after these error messages:
nlmixr run under nlme: Yes
nlmixr run under saem: Yes
nlmixr run under focei: Yes
---- Installation test finished! ----
Begin Session Info:
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] nlmixr_1.1.1-1  RxODE_0.9.1-3   reticulate_1.13

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2                lattice_0.20-35           prettyunits_1.0.2        
 [4] ps_1.3.0                  vpc_1.1.0                 assertthat_0.2.1         
 [7] rprojroot_1.3-2           digest_0.6.20             ggforce_0.3.1            
[10] R6_2.4.0                  backports_1.1.4           sys_3.3                  
[13] ggplot2_3.2.1             pillar_1.4.2              rlang_0.4.0              
[16] curl_4.0                  lazyeval_0.2.2            rstudioapi_0.10          
[19] callr_3.3.1               Matrix_1.2-14             mvnfast_0.2.5            
[22] desc_1.2.0                devtools_2.1.0            dparser_0.1.8            
[25] PreciseSums_0.3           polyclip_1.10-0           munsell_0.5.0            
[28] compiler_3.5.0            xfun_0.9                  pkgconfig_2.0.2          
[31] pkgbuild_1.0.5            tidyselect_0.2.5          tibble_2.1.3             
[34] crayon_1.3.4              dplyr_0.8.3               withr_2.1.2              
[37] MASS_7.3-49               lbfgs_1.2.1               grid_3.5.0               
[40] nlme_3.1-137              jsonlite_1.6              gtable_0.3.0             
[43] huxtable_4.6.1            magrittr_1.5              units_0.6-4              
[46] scales_1.0.0              cli_1.1.0                 n1qn1_6.0.1-3            
[49] farver_1.1.0              fs_1.3.1                  RcppArmadillo_0.9.600.4.0
[52] remotes_2.1.0             rex_1.1.2                 testthat_2.2.1           
[55] brew_1.0-6                generics_0.0.2            lotri_0.1.1              
[58] tools_3.5.0               glue_1.3.1                tweenr_1.0.1             
[61] purrr_0.3.2               processx_3.4.1            pkgload_1.0.2            
[64] parallel_3.5.0            yaml_2.2.0                colorspace_1.4-1         
[67] sessioninfo_1.1.1         memoise_1.1.0             knitr_1.24               
[70] usethis_1.5.1

**Comment by billchenxi** [comment]
```
install.packages(c("nlmixr","RxODE"))
Retrieving 'https://mran.microsoft.com/snapshot/2020-10-08/bin/windows/contrib/4.0/nlmixr_1.1.1-9.zip/nlmixr_1.1.1-9.zip' ...
Retrieving 'https://mran.microsoft.com/snapshot/2020-11-19/bin/windows/contrib/4.0/RxODE_0.9.2-1.zip/RxODE_0.9.2-1.zip' ...
* There are no packages to install.
Warning messages:
1: curl: (22) The requested URL returned error: 404 Not Found 
2: curl: (22) The requested URL returned error: 404 Not Found 
```

**Comment by mattfidler** [comment]
This is because RxODE and nlmixr are currently not on CRAN.  We are going back and forth with CRAN right now to try to get them there.
