### ISSUE TITLE
unhandled error message: 5000 steps taken before reaching tout :    Could not solve the system.

### ISSUE THREAD

**Issue by EvanTarbell** [nlmixrdevelopment/nlmixr#139]
When i try to run the model fitting with nlme, i get the following error:

> fit = nlmixr(pbpk,d2,est="nlme")
unhandled error message: EE:[lsoda] 5000 steps taken before reaching tout
 @(lsoda.c:750)
Error in rxSolve.default(object = get("rxDll", envir = <environment>),  : 
  Could not solve the system.

Is there a way to increase the maxStep from nlmixr? Or does this imply that the model isnt good/formatted correctly etc?

Thanks

**Comment by mattfidler** [comment]
Hi @EvanTarbell 

There isn't a way currently to increase the maxsteps from nlmixr for nlme, I will put that in the next version.  It should be easy enough to include.

**Comment by EvanTarbell** [comment]
Thanks @mattfidler

**Comment by tamas-ferenci** [comment]
Dear @mattfidler ,

I receive a very similar error message:
```
unhandled error message: EE:[lsoda] 50000 steps taken before reaching tout
 @(lsoda.c:750
```

Note that there is `50000` there, not `5000`.

That's quite mysterious, as the default value - which I haven't changed - of `maxstepsOde` which (I think!) you were referring to above is `5000`... Also, setting that parameter doesn't change the error message.

**Comment by Danielsite** [comment]
Hi mattfidler:

I also found issue when using SAEM estimator. Is there any solving methods?

Also I found the speed of nlmixr() is quite slow. My dataset is about 8000+ records. 
Are there any methods to increase the model building speed?

**Comment by mattfidler** [comment]
If you are use `saem` you can increase the number of cores for parallel solving, though in general with that size of a dataset the process will be slow.  This isn't just true of `nlmixr`/`nlmixr2` but for commercial solutions in general.

**Comment by Danielsite** [comment]
Thank you for your reply! So the way to increase cores is to add this "setRxThreads(threads = 0)" at the beginning of the code right?

**Comment by mattfidler** [comment]
Yes.  This is one way.  I prefer to use:

```r
rxode2::setRxThreads(percent=100)
```

Because it is a bit easier to figure out what is going on, but either works.
