### ISSUE TITLE
issue with installation in window

### ISSUE THREAD

**Issue by rrrooonnn** [nlmixrdevelopment/nlmixr#14]
When running install_github("nlmixrdevelopment/nlmixr"), ar command is not found, wondering what's wrong with that. Below is the error message.

ar crv libdparse.a arg.o parse.o scan.o symtab.o util.o dparse_tree.o
make[1]: ar: Command not found
make[1]: *** [libdparse.a] Error 127
make[1]: Leaving directory `/cygdrive/c/Users/Dark/AppData/Local/Temp/RtmpC8oA2x/devtoolsf4c33634b58/nlmixrdevelopment-nlmixr-45fd1f4/src/d'
make: *** [libdparse] Error 2
Warning: running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-34~1.1/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-34~1.1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="nlmixr.dll" WIN=64 TCLBIN=64 ' had status 2
ERROR: compilation failed for package 'nlmixr'
* removing 'C:/Users/Dark/Documents/R/win-library/3.4/nlmixr'
Installation failed: Command failed (1)

**Comment by kestrel99** [comment]
Hi,

**make** seems unsable to find **ar**, a utility which forms part of the compiler package required by nlmixr - on my system, it's installed automatically with Rtools (version 3.4, available from https://cran.r-project.org/bin/windows/Rtools/) and lives in C:\Rtools\mingw_64\x86_64-w64-mingw32\bin. 

Do you have Rtools34 installed? If not, can you install it (64-bit only, ideally) and try again? If it is installed, please make sure there aren't any other versions of the compilation tools interfering with the process, e.g. Cygwin. The Rtools compiler tools need to appear _first_ in your Windows system path (this can be edited from Windows Control Panel - search for Environment Variables). 

If this doesn't solve your problem, please let us know.
