### ISSUE TITLE
Numbering conventions for CMT in data

### ISSUE THREAD

**Issue by EvanTarbell** [nlmixrdevelopment/nlmixr#142]
I'm not sure if this should be an issue, as it is really just a question but:

I have a whole body PBPK model consisting of 204 ODEs.  The 76th ODE listed in the model block represents the compartment in which the dose is administered.  For the CMT field in the data, does the dose (ie when EVID == 1) have to be listed as 76 or can it be any number? 

Thanks in advance

**Comment by mattfidler** [comment]
Hi @EvanTarbell ,

**In the stable release**

Indeed if you use `nmDataConvert` the dose has to be to the 76th compartment.    

If you use `RxODE` EVIDs directly the `EVID` for the dose is `7601`; 

**Goal for next release**

In this release you would simply have `CMT=stateName` say you named your compartment `cmt76` the dose could be `CMT=cmt76`

**Comment by EvanTarbell** [comment]
Thanks @mattfidler !!
