### ISSUE TITLE
nlmixr 1.1.0-0 pre release notes: is this a typo or a serious problem?

### ISSUE THREAD

**Issue by nholford** [nlmixrdevelopment/nlmixr#149]
The notes for this pre-release include:

"Support of NONMEM-style datasets directly (except MDV and some other less used data items)"

MDV is an important data item in a NONMEM data set. Why can't nlmixr fully support the NONMEM data format that has proved its flexibility over decades of use?

**Comment by mattfidler** [comment]
Yes;  I plan to add `MDV` but do not plan to add the following, unless you can make a good case for them:
- `pcmt`
- `call`

What is stopping me is what happens when `MDV` and `EVID` conflict.  Peraps you know offhand?

**Comment by nholford** [comment]
I have never found a real need for PCMT so if you don't support it that is fine.
I have never noticed the CALL option before so ditto for support.

My understanding is that MDV is 1 for all records except when EVID=0. In that case MDV=0 to use the DV value as an observation otherwise the observation is treated as missing.
I am not aware of a conflict between MDV and EVID. Can you give an example?

**Comment by mattfidler** [comment]
What happens when:
-  `MDV=1` and `EVID=0`;  Is it equivalent to `EVID=2`?
- What happens when `MDV=0` and `AMT>0` does NONMEM error?

**Comment by mattfidler** [comment]
- What happens when `MDV=1` and `EVID>0`

**Comment by nholford** [comment]
From a user perspective MDV=1 and EVID=0 is equivalent to EVID=2. There may be some additional calcs done with MDV=1 and EVID=0 compared with MDV=1 and EVID=2 but that is a NONMEM internal issue.

When MDV=0 and AMT>0 this triggers an NM-TRAN error.

MDV should always be 1 when EVID is >0. MDV is only used to change the interpretation of EVID=0.

**Comment by mattfidler** [comment]
Thats fine, I always thought that MDV was an abbreviated EVID, so I can definately add the support.

**Comment by mattfidler** [comment]
Should be fixed.  Need to add some unit tests for it.
