### ISSUE TITLE
Nonlinear non-population ODE model

### ISSUE THREAD

**Issue by krinaj** [nlmixrdevelopment/nlmixr#15]
Hello nlmixr development team,

I am trying out nlmixr for the first time and have an issue. I have a multi dose data set (simulated) for a single subject. I am fixing most of the parameters and trying to estimate one parameter only. I do not need to BSV random effect. I am using nlme_ode() function and am getting the following error message.  I believe it is looking for random effect parameters formula. Any suggestions?

Also, how do I mention residual error structure in this type of model?

I am not sure how to attach a dataset here. I can send it in email if needed.

Thanks,
Krina

Model Code:

```
ode <- "
CL=0.111;
Vmax=11.9;
Km=33.9;
V1=2.91;
Q=0.445;
V2=3.06;
C1 = centr/V1;
C2 = peri/V2;
d/dt(depot) = -KA*depot;
d/dt(centr) = KA*depot - CL*C1 - Vmax*C1/(Km+C1) - Q*C1 + Q*C2;
d/dt(peri)  = Q*C1 - Q*C2;
"
specs <- list(fixed=lKA~1, start=c(KA=-0.916))

mypar <- function(lKA) {KA=exp(lKA)}

fit <- nlme_ode(fitdata, ode, par_model=specs, par_trans=mypar, response="C1")
```

**_Error in reStruct(random, REML = REML, data = NULL) : 
  'object' must be a list or a formula_**

If I update the specs with the following, it works
`specs <- list(fixed=lKA~1, random=lKA~1, start=c(KA=-0.916))`

**Comment by RikSchoemaker** [comment]
Dear Krina,

You describe the issue very well: the non-linear mixed effect routine fails when you have no mixed effects in your model (as it should). I suggest you study the vignette and take a look at the dynmodel routine instead: this estimates parameters for systems without random effects :-)

Good luck!

Rik

**Comment by krinaj** [comment]
Thanks so much, Rik. I tried dynmodel().

When I use the following for event record, it gives me the following error
message . I think it is because of 0 in sampling time which is producing
NAs in estimation.

ev <- eventTable(amount.units = "mg", time.units = "days")
ev$add.sampling(seq(0, 147, 0.25), time.units="days")
ev$add.dosing(dose=600, nbr.doses=7, dosing.interval= 21, start.time=0)

"Error in system$solve(theta, evTable, atol = 1e-06, rtol = 1e-06) :
 NA/NaN/Inf in foreign function call (arg 2)"

I took out 0 day sampling in the following:
ev <- eventTable(amount.units = "mg", time.units = "days")
ev$add.sampling(seq(0.25, 147, 0.25), time.units="days")
ev$add.dosing(dose=600, nbr.doses=7, dosing.interval= 21, start.time=0)

It runs the model and estimates are good as well. However, it gives
following warning message which leads to error message in residuals vs.
pred plot.
In (yo - yp)^2/sgy^2 :
  longer object length is not a multiple of shorter object length

Any suggestions on how to keep 0 in sampling? I attached the rmd file.

Thanks,
Krina

**Comment by RikSchoemaker** [comment]
Hi Krina,

Unfortunately, I've never worked with dynmodel myself but perhaps someone else on the list knows about this.

Kind regards,

Rik

**Comment by wwang-at-github** [comment]
Dear Krina:

Are you willing to share your code & data?  I'd be happy to look into it.
It seems to be a coding error to me from what you've shared.

Best,
Wenping

**Comment by krinaj** [comment]
Hi Wenping,

Sure, Code (includes simulated data) file attached. I think it may be some
coding error on my side as well, but can't seem to figure out.

Thanks,
Krina

**Comment by wwang-at-github** [comment]
Hi Krina:

I didn't get your attachments.  Could you re-send?

Wenping

**Comment by krinaj** [comment]
Hmm, I see it attached in my sent email. Attached again and copied the code
below as well.

Many thanks,
Krina

---
title: "Test"
output: html_document
---
```{r setup, include=FALSE}
rm(list = ls())

setwd("~/My_Projects/Test")

library(nlmixr)
library(dplyr)
```

```{r}
#Set up and compile RxODE model
ode <- "
C1 = centr/V1;
C2 = peri/V2;
d/dt(depot) = -KA*depot;
d/dt(centr) = F*KA*depot - CL*C1 - Vmax*C1/(Km+C1) - Q*C1 + Q*C2;
d/dt(peri)  = Q*C1 - Q*C2;
"

#Compile model
m1 <- RxODE(model = ode)

#Dosing scenario with sampling times defined
ev <- eventTable(amount.units = "mg", time.units = "days")
ev$add.sampling(seq(0.25, 147, 0.25), time.units="days")
ev$add.dosing(dose=600, nbr.doses=7, dosing.interval= 21, start.time=0)
```

```{r}
#Run Simulations

SimPars <- c(KA=0.404, F=0.771, CL=0.111, Vmax=11.9, Km=33.9, V1=2.91,
Q=0.445, V2=3.06)

Init <- c(0, 0, 0)

Sims <- m1$solve(SimPars, events=ev, Init) %>% as.data.frame()

SimPlot <- plot(Sims$C1~Sims$time, type="l")
```

```{r}
########################################Estimation
#Prepare dataset
fitdata <- Sims %>% select(time, Cp=C1)
str(fitdata)

#Define error model
mod <- Cp ~ C1 + prop(0.1)

########################################Estimation Exercise 1: Estimate Ka
and fix all other parameters
#Initial estimates
InitialKA <- c(KA=0.5)

#Fixed parameters
fixPars <- c(F=0.771, CL=0.111, Vmax=11.9, Km=33.9, V1=2.91, Q=0.445,
V2=3.06)

#Fit the model to data
fit <- dynmodel(m1, mod, ev, data=fitdata, fixPars=fixPars, InitialKA,
method = "PORT", control=list(maxeval=999), squared=T)

#Summary of results and plot
summary(fit)
par(mfrow=c(1,3))
plot(fit)
```

**Comment by wwang-at-github** [comment]
Hi Krina:

I made minor changes to your code.  Now it works for me.

I used the time=0 trick documented in the vignette.  I don't remember why
this trick was built in.

Best,
Wenping



library(nlmixr)
library(dplyr)

#Set up and compile RxODE model
ode <- "
C1 = centr/V1;
C2 = peri/V2;
d/dt(depot) = -KA*depot;
d/dt(centr) = F*KA*depot - CL*C1 - Vmax*C1/(Km+C1) - Q*C1 + Q*C2;
d/dt(peri) = Q*C1 - Q*C2;
"

#Compile model
m1 <- RxODE(model = ode)

#Dosing scenario with sampling times defined
ev <- eventTable(amount.units = "mg", time.units = "days")
ev$add.sampling(seq(0.25, 147, 0.25), time.units="days")
ev$add.dosing(dose=600, nbr.doses=7, dosing.interval= 21, start.time=0)

#Run Simulations

SimPars <- c(KA=0.404, F=0.771, CL=0.111, Vmax=11.9, Km=33.9, V1=2.91,
             Q=0.445, V2=3.06)

Init <- c(0, 0, 0)

Sims <- m1$solve(SimPars, events=ev, Init) %>% as.data.frame()

SimPlot <- plot(Sims$C1~Sims$time, type="l")

########################################Estimation
#Prepare dataset
fitdata <- Sims %>% select(time, Cp=C1)
str(fitdata)
fitdata$Cp = fitdata$Cp + rnorm(fitdata$Cp,0,.1*fitdata$Cp)

#Define error model
mod <- Cp ~ C1 + prop(0.1)

########################################Estimation Exercise 1: Estimate Ka
and fix all other parameters
#Initial estimates
InitialKA <- c(KA=0.5)

#Fixed parameters
fixPars <- c(F=0.771, CL=0.111, Vmax=11.9, Km=33.9, V1=2.91, Q=0.445,
             V2=3.06)

ev$add.sampling(0, time.units="days")
#Fit the model to data
fit <- dynmodel(m1, mod, ev, data=fitdata, fixPars=fixPars, InitialKA,
                method = "PORT", control=list(maxeval=999), squared=T)

#Summary of results and plot
summary(fit)
par(mfrow=c(1,3))
plot(fit)

**Comment by krinaj** [comment]
Many thanks, Wenping. This trick works well.
