### ISSUE TITLE
1.1.0-3 installer version: Windows 10 GUI crash compiling model

### ISSUE THREAD

**Issue by nholford** [nlmixrdevelopment/nlmixr#150]
Windows 10 GUI crash compiling model:

> pk.fit.ka1t <- nlmixr(one.compartment.saem, data.pk,  est="saem", control=saemControl(print=100000))
Compiling RxODE equations...Error building model
-- stdout output ---------------------------------------------------------------
c:/R/NLMIXR~2.0-3/R/rtools/mingw_64/bin/gcc  -I"c:/R/NLMIXR~2.0-3/R/include" -DNDEBUG       -I"C:\R\NLMIXR~2.0-3\R\library\RxODE\include"   -O2 -Wall  -std=gnu99 -mtune=generic -c rx_db0ad78e7805f888dfcfd284cdf7e8f8_x64.c -o rx_db0ad78e7805f888dfcfd284cdf7e8f8_x64.o

-- stderr output ---------------------------------------------------------------
internal error in mingw32_gt_pch_use_address, at config/i386/host-mingw32.c:190: MapViewOfFileEx: Attempt to access invalid address. 

make: *** [c:/R/NLMIXR~2.0-3/R/etc/x64/Makeconf:208: rx_db0ad78e7805f888dfcfd284cdf7e8f8_x64.o] Error 1

Error: Error building model
>

**Comment by mattfidler** [comment]
In the following post:

http://community.axoloti.com/t/error-when-going-live-with-the-patching/583

It seems to say that the mingw installation was corrupt.  Can you try the following:

```R
> Sys.which("gcc")
                                                     gcc 
"c:\\R\\NLMIXR~1.0-1\\R\\rtools\\mingw_64\\bin\\gcc.exe" 
````

This will tell me if it is your Rtools that is corrupt or if it is the internally installed nlmixr rtools that is corrupt.

**Comment by nholford** [comment]
Windows found gcc is in the Rtools installed in the root of drive C:
> Sys.which("gcc")
                                 gcc 
"C:\\Rtools\\mingw_64\\bin\\gcc.exe" 
> 

Both C:\Rtools\bin and C:\Rtools\mingw_64\bin are in the Windows path. This follows the recommendation when installing Rtools. So I changed these paths to Rtools to use the nlmixr installation.

However, although gcc is now found in the right place the error persists:

> pk.fit.ka1t <- nlmixr(one.compartment.saem, data.pk,  est="saem", control=saemControl(print=100000))
Compiling RxODE equations...Error building model
-- stdout output ---------------------------------------------------------------
c:/R/NLMIXR~2.0-3/R/rtools/mingw_64/bin/gcc  -I"c:/R/NLMIXR~2.0-3/R/include" -DNDEBUG       -I"C:\R\NLMIXR~2.0-3\R\library\RxODE\include"   -O2 -Wall  -std=gnu99 -mtune=generic -c rx_db0ad78e7805f888dfcfd284cdf7e8f8_x64.c -o rx_db0ad78e7805f888dfcfd284cdf7e8f8_x64.o

-- stderr output ---------------------------------------------------------------
internal error in mingw32_gt_pch_use_address, at config/i386/host-mingw32.c:190: MapViewOfFileEx: Attempt to access invalid address. 

make: *** [c:/R/NLMIXR~2.0-3/R/etc/x64/Makeconf:208: rx_db0ad78e7805f888dfcfd284cdf7e8f8_x64.o] Error 1

Error: Error building model
> Sys.which("gcc")
                                                     gcc 
"c:\\R\\NLMIXR~2.0-3\\R\\rtools\\mingw_64\\bin\\gcc.exe" 
>

**Comment by mattfidler** [comment]
I'm not clear how you changed these paths.  My recommendation is to try the following:
- Temporarily rename `c:\Rtools\` to `c:\Rtools2` or something similar
- Restart R
- Attempt to build the model again.

If this doesn't work, perhaps it is a permissions issue.  You can also check:

```R
rxTempDir()
```

This *should* be a file that you can write to and have execute permissions for.  I'm not sure if this is the case here

**Comment by nholford** [comment]
I changed the Windows path by changing the system environment path variable using the Windows Settings app. Easy.  I changed the Rtools path to the root of C: then I tried renaming Rtools to Rtools2. 

I then opened R. Before I loaded any of the libraries I use for nlmixr I tried Sys.which("gcc") and it returned a null string. This makes sense because the Windows path pointed to "Rtools" and not to "Rtools2".

I then ran the nlmixr R script which failed with the mingw error.

> pk.fit.ka1t <- nlmixr(one.compartment.saem, data.pk,  est="saem", control=saemControl(print=100000))
Compiling RxODE equations...Error building model
-- stdout output ---------------------------------------------------------------
c:/R/NLMIXR~2.0-3/R/rtools/mingw_64/bin/gcc  -I"c:/R/NLMIXR~2.0-3/R/include" -DNDEBUG       -I"C:\R\NLMIXR~2.0-3\R\library\RxODE\include"   -O2 -Wall  -std=gnu99 -mtune=generic -c rx_db0ad78e7805f888dfcfd284cdf7e8f8_x64.c -o rx_db0ad78e7805f888dfcfd284cdf7e8f8_x64.o

-- stderr output ---------------------------------------------------------------
internal error in mingw32_gt_pch_use_address, at config/i386/host-mingw32.c:190: MapViewOfFileEx: Attempt to access invalid address. 

make: *** [c:/R/NLMIXR~2.0-3/R/etc/x64/Makeconf:208: rx_db0ad78e7805f888dfcfd284cdf7e8f8_x64.o] Error 1

Error: Error building model

After that Sys.which("gcc") pointed to the nlmixr R installation.

> Sys.which("gcc")
                                                     gcc 
"c:\\R\\NLMIXR~2.0-3\\R\\rtools\\mingw_64\\bin\\gcc.exe" 
>

**Comment by mattfidler** [comment]
Hm.  This is perplexing.  I have had issues in Windows before.  I never figured out why.  One day it stopped working and then after a system upgrade it worked again....

https://github.com/rwinlib/rtools35/issues/8

I have searched and cannot find anything helpful here.

**Comment by mattfidler** [comment]
I'm just fishing for things to try, at this point.

Could it be a permissions issue?  Do you have execute permissions, read/write permissions?

**Comment by nholford** [comment]
My scripts work fine with 1.0.0-7. I have tested that again today. So my system is working fine with that version.  I am sysadmin so have permissions for everything. The problems start with 1.0.0-8 and continue up to and including 1.1.0-3.

**Comment by mattfidler** [comment]
Hm.  It could be the R/Rtools version differences.  I will have to check what version of R 1.0.0-7 used. I could try to use the same version of R to setup nlmixr.  Unfortunately it does take time to setup the system, so this isn't a quick fix.  As a side note it will test if the R version is causing the issue with `R CMD BACH` or not.

**Comment by nholford** [comment]
Matt, Sorry that this is such a frustration. It is not the first time that Rtools has caused us grief. I understand it is a necessary part of nlmixr but it is too bad that it is not easier to keep versions in sync. That is a fundamental defect of the complexity of R.

**Comment by mattfidler** [comment]
The new installer uses R 3.5.1;  perhaps this will work with your setup.

**Comment by nholford** [comment]
I get these warning messages as expected from using R 3.5.1 with the 1.1.04 installer. 

Warning messages:
1: package ‘xpose’ was built under R version 3.5.3 
2: package ‘ggplot2’ was built under R version 3.5.3 

But unfortunately it has not fixed the mingw problem. Could it be something to do with mingw32 and using 64 bit Windows 10?

> fit.TOS <- nlmixr(pk.turnover.emax, data.pkpd, est="saem", table=list(cwres=TRUE), control=saemControl(print=100000))
Compiling RxODE equations...Error building model
-- stdout output ---------------------------------------------------------------
c:/R/NLMIXR~1.0-4/R/rtools/mingw_64/bin/gcc  -I"c:/R/NLMIXR~1.0-4/R/include" -DNDEBUG       -I"C:\R\NLMIXR~1.0-4\R\library\RxODE\include"   -O2 -Wall  -std=gnu99 -mtune=generic -c rx_82c6091a062af69b11309240408fe237_x64.c -o rx_82c6091a062af69b11309240408fe237_x64.o

-- stderr output ---------------------------------------------------------------
internal error in mingw32_gt_pch_use_address, at config/i386/host-mingw32.c:190: MapViewOfFileEx: Attempt to access invalid address. 

make: *** [c:/R/NLMIXR~1.0-4/R/etc/x64/Makeconf:208: rx_82c6091a062af69b11309240408fe237_x64.o] Error 1

Error: Error building model

> Sys.which("gcc")
                                                     gcc 
"c:\\R\\NLMIXR~1.0-4\\R\\rtools\\mingw_64\\bin\\gcc.exe"

**Comment by mattfidler** [comment]
I'm using mingw 64 bit windows 10, and it works OK for me.  I'm actually not sure why this is occuring.

**Comment by nholford** [comment]
I have done some more exploration to find out why the nlmixr model cannot be compiled with version 1.1.0-4. First of all I show what happens with nlmixr 1.0.0.7.

**Installer nlmixr 1.0.0.7**

Sys.which("aspell") is used to find out where R thinks Rtools is located. With nlmixr 1.0.0-7 Sys.which("aspell") reports it is always located in C:\Rtools. The RxODE compilation succeeds. See further below for what happens with 1.1.0-4.
> Sys.which("aspell")
                       aspell 
"C:\\Rtools\\bin\\aspell.exe" 
> 
> srclib="C:\\R\\nlmixr_1.0.0-7\\R\\library"
> #srclib="C:\\R\\nlmixr_1.1.0-4\\R\\library"
> library(nlmixr,lib=srclib)
> Sys.which("aspell")
                       aspell 
"C:\\Rtools\\bin\\aspell.exe" 
>
> library(xpose.nlmixr,lib=srclib) # Needed for GOF
Loading required package: xpose
Loading required package: ggplot2
Do you like the new xpose? Give us some feedback on github:
https://github.com/UUPharmacometrics/xpose

Attaching package: ‘xpose’

The following object is masked from ‘package:nlmixr’:

    vpc

The following object is masked from ‘package:stats’:

    filter


Attaching package: ‘xpose.nlmixr’

The following object is masked from ‘package:nlmixr’:

    vpc

> nlmixrver=packageVersion("nlmixr")
> nlmixrver
[1] ‘1.0.0.7’
> Sys.which("aspell")
                       aspell 
"C:\\Rtools\\bin\\aspell.exe" 
> 

[ details omitted]

> fit.TOS <- nlmixr(pk.turnover.emax, data.pkpd, est="saem", table=list(cwres=TRUE), control=saemControl(print=100000))
Compiling RxODE differential equations...C:/Rtools/mingw_64/bin/gcc  -I"C:/R/NLMIXR~2.0-7/R/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c rx_0c6f70d9d820b79ccffc6ba8ce20c0c1_x64.c -o rx_0c6f70d9d820b79ccffc6ba8ce20c0c1_x64.o
C:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o rx_0c6f70d9d820b79ccffc6ba8ce20c0c1_x64.dll tmp.def rx_0c6f70d9d820b79ccffc6ba8ce20c0c1_x64.o -LC:/R/NLMIXR~2.0-7/R/bin/x64 -lRblas -LC:/R/NLMIXR~2.0-7/R/bin/x64 -lRlapack -lgfortran -lm -lquadmath -LC:/R/NLMIXR~2.0-7/R/bin/x64 -lR
done.
PKG_CXXFLAGS=-IC:/R/NLMIXR~2.0-7/R/library/nlmixr/include -IC:/R/NLMIXR~2.0-7/R/library/STANHE~1/include -IC:/R/NLMIXR~2.0-7/R/library/Rcpp/include -IC:/R/NLMIXR~2.0-7/R/library/RCPPAR~1/include -IC:/R/NLMIXR~2.0-7/R/library/RCPPEI~1/include -IC:/R/NLMIXR~2.0-7/R/library/BH/include
PKG_LIBS= $(BLAS_LIBS) $(LAPACK_LIBS)
C:/Rtools/mingw_64/bin/g++  -I"C:/R/NLMIXR~2.0-7/R/include" -DNDEBUG       -IC:/R/NLMIXR~2.0-7/R/library/nlmixr/include -IC:/R/NLMIXR~2.0-7/R/library/STANHE~1/include -IC:/R/NLMIXR~2.0-7/R/library/Rcpp/include -IC:/R/NLMIXR~2.0-7/R/library/RCPPAR~1/include -IC:/R/NLMIXR~2.0-7/R/library/RCPPEI~1/include -IC:/R/NLMIXR~2.0-7/R/library/BH/include   -O2 -Wall  -mtune=generic -c saem413c66f7569bx64.cpp -o saem413c66f7569bx64.o
C:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o saem413c66f7569bx64.dll tmp.def saem413c66f7569bx64.o -LC:/R/NLMIXR~2.0-7/R/bin/x64 -lRblas -LC:/R/NLMIXR~2.0-7/R/bin/x64 -lRlapack -LC:/R/NLMIXR~2.0-7/R/bin/x64 -lR
done.

> Sys.which("aspell")
                       aspell 
"C:\\Rtools\\bin\\aspell.exe" 
> 

**Installer nlmixr 1.1.0.4**

Rtools folder name in the nlmixr 1.1.0-4 installation deliberately changed so that it should not be found.  
Note that before loading the libraries required to run nlmixr that Rtools is found where it actually exists (C:\Rools). But after loading the nlmixr library Sys.which() has been fooled to say it is in a folder which does not exist. The compilation error message is the same as that seen when the Rtools folder actually exists as a sub-folder of the nlmixr R installation (see earlier in this thread). So this suggests that the difference between version 1.0.0.7 and version 1.1.0-4 is due to an error related to the path to Rtools in order to do the compilation. Even when the path actually exists the compilation fails. This is a well known bug in Rtools and nlmixr which typically fails unless Rtools is actually located in C:\Rtools (see Issue #70) . A work around to the problem would be to find a way for the nlmixr library NOT to try to point to the Rtools in the nlmixr installation and instead use C:\Rtools.

![image](https://user-images.githubusercontent.com/26332480/56077739-1fdac800-5de0-11e9-88b6-80f65d0311c4.png)



> Sys.which("aspell")
                       aspell 
"C:\\Rtools\\bin\\aspell.exe" 
> 
> #srclib="C:\\R\\nlmixr_1.0.0-7\\R\\library"
> srclib="C:\\R\\nlmixr_1.1.0-4\\R\\library"
> library(nlmixr,lib=srclib)
> Sys.which("aspell")
                                           aspell 
"C:\\R\\NLMIXR~1.0-4\\R\\rtools\\bin\\aspell.exe" 
>
> library(xpose.nlmixr,lib=srclib) # Needed for GOF
Loading required package: xpose
Loading required package: ggplot2
Note: the next xpose release (v0.5) will bring some major changes.
If you rely on xpose for your work, please keep an eye on our github:
https://github.com/UUPharmacometrics/xpose

Attaching package: ‘xpose’

The following object is masked from ‘package:nlmixr’:

    vpc

The following object is masked from ‘package:stats’:

    filter


Attaching package: ‘xpose.nlmixr’

The following object is masked from ‘package:nlmixr’:

    vpc

Warning messages:
1: package ‘xpose’ was built under R version 3.5.3 
2: package ‘ggplot2’ was built under R version 3.5.3 
> nlmixrver=packageVersion("nlmixr")
> nlmixrver
[1] ‘1.1.0.4’
> Sys.which("aspell")
                                           aspell 
"C:\\R\\NLMIXR~1.0-4\\R\\rtools\\bin\\aspell.exe" 
>

[ details omitted]

> fit.TOS <- nlmixr(pk.turnover.emax, data.pkpd, est="saem", table=list(cwres=TRUE), control=saemControl(print=100000))
Compiling RxODE equations...Error building model
-- stdout output ---------------------------------------------------------------
C:/R/NLMIXR~1.0-4/R/rtools/mingw_64/bin/gcc  -I"C:/R/NLMIXR~1.0-4/R/include" -DNDEBUG       -I"C:\R\NLMIXR~1.0-4\R\library\RxODE\include"   -O2 -Wall  -std=gnu99 -mtune=generic -c rx_82c6091a062af69b11309240408fe237_x64.c -o rx_82c6091a062af69b11309240408fe237_x64.o

-- stderr output ---------------------------------------------------------------
internal error in mingw32_gt_pch_use_address, at config/i386/host-mingw32.c:190: MapViewOfFileEx: Attempt to access invalid address. 

make: *** [C:/R/NLMIXR~1.0-4/R/etc/x64/Makeconf:208: rx_82c6091a062af69b11309240408fe237_x64.o] Error 1

Error: Error building model
> Sys.which("aspell")
                                           aspell 
"C:\\R\\NLMIXR~1.0-4\\R\\rtools\\bin\\aspell.exe"

**Comment by mattfidler** [comment]
Rtools can be a problem.  Let me see if I can fix this.  This was an inadvertent regression.  nlmixr should choose Rtools in `c:\Rtools\` if it is there.

**Comment by mattfidler** [comment]
Thank you for tracking this down some more.

**Comment by mattfidler** [comment]
Hi @nholford  the 1.1.0-6 intaller uses a version that prefers `c:\rtools`.  At the same time, a colleague of mine had the same issue, and using `c:\rtools` didn't resolve the issue.  My second computer is in the shop and should be returned tomorrow (hopefully).  If I can reproduce it on the second computer, perhaps I can fix this (or at least figure out when it was introduced).

**Comment by mattfidler** [comment]
I think this should fix it

https://github.com/nlmixrdevelopment/nlmixr/releases/download/v1.1.0-7/nlmixr_1.1.0-7_x86_64_install.exe

**Comment by nholford** [comment]
Thanks Matt. version 1.1.0-7 has fixed the Rtools related problem which seems to have been at the root of the crash on my Windows 10 installation.

**Comment by mattfidler** [comment]
Thanks for informing me.

**Comment by mattfidler** [comment]
To be clear this was not a Rtools issue; rather it was because RxODE pre-compiled part of the models.  When installing, this piece was not compatible with the different versions of windows.  Probably some sort of security feature between different versions of windows.

I still want to allow this pre-compilation to increase speed, but I haven't added it yet.  It would have to be pre-compiled on the first RxODE model.
