### ISSUE TITLE
1.1.0-3 Installer version: Windows Server 2012 command line crash in Python

### ISSUE THREAD

**Issue by nholford** [nlmixrdevelopment/nlmixr#151]
Thanks for the 1.1.0-3 installer.
I tried using it from the Windows command line (Windows Server 2012). Rterm.exe crashed because Python could not find UTF-8 encoding mode.

![image](https://user-images.githubusercontent.com/26332480/55946669-664bed80-5c4d-11e9-804d-6b0210a64584.png)

**Comment by mattfidler** [comment]
Hm.  Perhaps this is related:

https://stackoverflow.com/questions/28127513/attributeerror-module-object-has-no-attribute-setdefaultencoding

**Comment by mattfidler** [comment]
Could you try the following in R:

```R
library(SnakeCharmR)
```
This is what I get;  Perhaps nlmixr is detecting a different python version on your computer?

```R
> library(SnakeCharmR)
SnakeCharmR 1.0.7 - R and Python Integration
Contribute and submit issues at https://github.com/asieira/SnakeCharmR

Python version 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]
```

**Comment by mattfidler** [comment]
Also try:
```R
library(RxODE)
library(SnakeCharmR)
```
And see what it gives.  `RxODE` tries to correct some python issues, so the result may be different.

**Comment by nholford** [comment]
The default SnakeCharmR library shows this:

> library(SnakeCharmR)
SnakeCharmR 1.0.7 - R and Python Integration
Contribute and submit issues at https://github.com/asieira/SnakeCharmR

Python version 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]

When I load the library I expect to be installed by the nlmixr installer there is a load error for python37.dll:

Restarting R session...
![image](https://user-images.githubusercontent.com/26332480/55967194-264f2f80-5c7a-11e9-8ecf-f605e5d2303a.png)

followed by this misleading additional error message because the Windows File Explorer shows that the SnakeCharmR.dll exists:


Error: package or namespace load failed for ‘SnakeCharmR’ in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/R/nlmixr_1.1.0-3/R/library/SnakeCharmR/libs/x64/SnakeCharmR.dll':
  LoadLibrary failure:  The specified module could not be found.
> 

![image](https://user-images.githubusercontent.com/26332480/55966725-3c102500-5c79-11e9-8dfb-56a8f390738d.png)

In fact python37.dll exists in C:\R\nlmixr_1.1.0-3\python.

When I try loading the RxODE library then that helps SnakeCharmR and I get the same version as you did.

> srclib="C:\\R\\nlmixr_1.1.0-3\\R\\library"
> library(RxODE,lib=srclib)
> library(SnakeCharmR,lib=srclib)
SnakeCharmR 1.0.7 - R and Python Integration
Contribute and submit issues at https://github.com/asieira/SnakeCharmR

Python version 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]
>
So it seems to be important to specify the lib argument to point to the nlmixr R library when loading libraries and to include an explicit load of SnakeCharmR after RxODE before attempting to run nlmixr.

**Comment by mattfidler** [comment]
I have found that when anaconda is installed, `reticulate` may work better.

Can you try:

```R
install.packages("reticulate")
```

And see if this works better for you

**Comment by nholford** [comment]
Now I am loading SnakeCharmR after RxODE I am not having a Python problem anymore. So no need for me to try reticulate.

**Comment by mattfidler** [comment]
Ah.  I'm glad it is working for you.  

Python setup can be strangling some time (ha ha)
