### ISSUE TITLE
1.1.0-3 installer version of nlmixr: fit object throws error when used with plot() 

### ISSUE THREAD

**Issue by nholford** [nlmixrdevelopment/nlmixr#154]
This fit object was produced by nlmixr after correcting the MDV error in the data (see issue #152) . The fit results look fine but the object is missing something when it is passed to plot():

> plot(pd.fit.TOS)
Error in cbind(new.pts, new.covs) : object 'new.covs' not found

**Comment by mattfidler** [comment]
I saw this too.  I thought I fixed it here

072636878625599e20c37a92968279ccfa3e3df5

But I think I must have grabbed the wrong nlmixr version when I built the installer.

You can probably update by:

```R
devtools::install_github("nlmixrdevelopment/nlmixr")
```

**Comment by nholford** [comment]
Thanks for noting the plot() problem exists in the 1.1.0-3 installer. I tried with and without attempting to install glue beforehand and trying to update all new versions of associated packages.  Attempts to update nlmixr ended in the usual way (for me) with lots of errors.  I will wait for the next installer release to see if this fixed.


> install.packages("glue", lib = destlib)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/glue_1.3.1.zip'
Content type 'application/zip' length 172477 bytes (168 KB)
downloaded 168 KB

package ‘glue’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot remove prior installation of package ‘glue’

The downloaded binary packages are in
	C:\Users\nhol004\AppData\Local\Temp\2\Rtmp0ydYKo\downloaded_packages
> devtools::install_github("nlmixrdevelopment/nlmixr",lib=destlib)
Downloading GitHub repo nlmixrdevelopment/nlmixr@master
These packages have more recent versions available.
Which would you like to update?

 1:   classInt    (0.2-3        -> 0.3-1       ) [CRAN]     2:   clipr       (0.4.1        -> 0.5.0       ) [CRAN]  
 3:   dplyr       (0.7.7        -> 0.8.0.1     ) [CRAN]     4:   e1071       (1.7-0        -> 1.7-1       ) [CRAN]  
 5:   ggplot2     (3.1.0        -> 3.1.1       ) [CRAN]     6:   purrr       (0.2.5        -> 0.3.2       ) [CRAN]  
 7:   rlang       (0.3.3        -> 0.3.4       ) [CRAN]     8:   RxODE       (0.8.0-8      -> 0.8.0-9     ) [CRAN]  
 9:   StanHeaders (2.18.0       -> 2.18.1      ) [CRAN]    10:   tidyr       (0.8.2        -> 0.8.3       ) [CRAN]  
11:   vpc         (f198806e5... -> 2b2aead35...) [GitHub]  12:   CRAN packages only                                 
13:   All                                                  14:   None                                               

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 14
√  checking for file 'C:\Users\nhol004\AppData\Local\Temp\2\Rtmp0ydYKo\remotes1ac050b299a\nlmixrdevelopment-nlmixr-4387da9/DESCRIPTION' ...
-  preparing 'nlmixr': (1.7s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (978ms)
-  checking for empty or unneeded directories
   Removed empty directory 'nlmixr/inst/examples/ACoP7poster'
   Removed empty directory 'nlmixr/inst/examples/LiveDemo'
   Removed empty directory 'nlmixr/man-roxygen'
-  looking to see if a 'data/datalist' file should be added
-  building 'nlmixr_1.1.0-4.tar.gz'
   
* installing *source* package 'nlmixr' ...
Error in file.copy(f, instdir, TRUE) : 
  (converted from warning) problem copying .\NAMESPACE to C:\R\nlmixr_1.1.0-3\R\library\nlmixr\NAMESPACE: Permission denied
* removing 'C:/R/nlmixr_1.1.0-3/R/library/nlmixr'
* restoring previous 'C:/R/nlmixr_1.1.0-3/R/library/nlmixr'
Error in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) : 
  (converted from warning) problem copying C:\R\nlmixr_1.1.0-3\R\library\00LOCK-nlmixr\nlmixr\bak\DESCRIPTION to C:\R\nlmixr_1.1.0-3\R\library\nlmixr\bak\DESCRIPTION: Permission denied
Execution halted
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/nhol004/AppData/Local/Temp/2/Rtmp0ydYKo/file1ac01d3657de/nlmixr_1.1.0-4.tar.gz’ had non-zero exit status

**Comment by mattfidler** [comment]
I changed the installer to pull the correct version of nlmixr.  I tested and there wasn't an error when running the models.  Since nothing changed in github, the installer name is the same this time. (1.1.0-4)

**Comment by nholford** [comment]
Thanks for the 1.1.0-4 installer. The plot() problem has now been fixed.

**Comment by mattfidler** [comment]
Great!
