### ISSUE TITLE
PD modelling with control and treatment groups

### ISSUE THREAD

**Issue by DimitrisVoul** [nlmixrdevelopment/nlmixr#156]
Hello,

I am trying to run a tumour growth model with a drug effect parameter and I am not sure what the syntax needs to be so that nlmixr knows which groups is which so that it dismisses the parameter in the control group.

Similarly if I want to extend this to multiple treatment groups.

Do I need to create a column in the data identifying the respective group and if yes what do I need to do for the ODE syntax before running nlmixr?

**Comment by DedeLLL** [comment]
I think you can use a index variable "drug" : drug=0 indicates the control group and drug =1 indicates the test group. Then you define the parameters like:  pram=pram_test*drug+pram_control*(1-drug). If you have more than two groups you can specify them with multiple index variables.

**Comment by mattfidler** [comment]
Thanks @DedeLLL ,  I must have missed this issue.  I agree.

**Comment by nholford** [comment]
IMHO a more elegant way to deal with this kind of conditional event is to use a conditional construct:

if (drug==0) { # control group
   pram=pram_control 
} else { # treated group
   pram=pram_test 
}

This has the communication advantage of allowing specific comments and also more than one variable can be include in the each conditional block e.g.

if (drug==0) { # control group
   pram=pram_control
   offset=0 
} else { # treated group
   pram=pram_test 
   offset=slope*dose
}

**Comment by mattfidler** [comment]
Hi @nholford ,

I agree it is easier to read and is superior in this way.

At the same time, the logic is treated differently in nlmixr currently.  The `if/then` clauses, sometimes called branching clauses, are parsed as follows:

- All `if` clauses are parsed out
- The code under each condition has `eta`-based sensitivities calculated
- The code is compared line by line to make see where the differences are in the code and the construct another `if`/`else` clause

This means the code without the `if`/`else` performs better than the code without the `if`/`else` in it. 

This does not take into account the possible speed gain by non-branching code in long runs;  Depending on the expense of the expression can be faster than branching code in long runs.

This makes me wonder about the ability of changing `if`/`else` blocks into non-branching expressions to save time.  I will think about this and possibly work on it later.

**Comment by DimitrisVoul** [comment]
Thank you everyone very much for you answers. I will try both ways and see what works better for me.
