### ISSUE TITLE
covariate(s) not found

### ISSUE THREAD

**Issue by jfstanding** [nlmixrdevelopment/nlmixr#159]
I have just installed the latest Github RxODE and nlmixr and encountered a new error message.  In models that have previously run, even though the covariate is in the dataset, I am getting the following error message:
```r
covariate(s) not found
```

This is happening on multiple models, so somehow the dataset is not read in properly.  Here is an example:

```{r, eval = FALSE}
#
####### read in phenobarbitone data from NONMEM and format for nlmixr ########
#
pheno.dta <- read.table("PHENO", header = FALSE, stringsAsFactors = FALSE)
colnames(pheno.dta) <- c("ID", "TIME", "AMT", "WT", "APGR", "DV", "MDV", "EVID")
#head(pheno.dta)
#str(pheno.dta)
# make the DV and AMT a numeric
pheno.dta$DV[pheno.dta$DV=="."] <- 0
pheno.dta$AMT[pheno.dta$AMT=="."] <- 0
pheno.dta$DV <- as.numeric(pheno.dta$DV)
pheno.dta$AMT <- as.numeric(pheno.dta$AMT)
# EVID should be 101
pheno.dta$EVID[pheno.dta$AMT>0] <- 101
pheno.dta$log_allo_wt <- log(pheno.dta$WT / 1.3) # 1.3 is median weight
####### Allometric clearance wihout OMEGA block to remove correlation V,CL ########
run7.mod <- function() {
  ini({
    tcl <- log(0.008) # typical value of clearance
    tv <-  log(0.6)   # typical value of volume
    all.cl <- 1 # allometric exponent on CL
    eta.cl ~ 0.1      # interindividual variability on clearance 
    eta.v ~ 0.1       # interindividual variability on volume
    #eta.cl + eta.v ~ c(1,
    #                   0.00001, 1) 
                      # interindividual variability on clearance and volume
    add.err <- 0.1    # residual variability
  })
  model({
    cl <- exp(tcl + all.cl * log_allo_wt + eta.cl) # individual value of clearance
    v <- exp(tv + eta.v)    # individual value of volume
    ke <- cl / v            # elimination rate constant
    d/dt(A1) = - ke * A1    # model differential equation
    cp = A1 / v             # concentration in plasma
    cp ~ add(add.err)       # define error model
  })
}
###### 1 CMT add err est=FO ######
run7.fo <- nlmixr(run7.mod, pheno.dta, est="fo")
#
```

I get the following output:

```r
Model:
cmt(A1);
rx_expr_001~-ETA[2];
rx_expr_002~ETA[1]+THETA[1];
rx_expr_003~rx_expr_001-THETA[2];
rx_expr_004~THETA[3]*log_allo_wt;
rx_expr_005~exp(rx_expr_003);
rx_expr_006~A1*rx_expr_005;
rx_expr_007~rx_expr_002+rx_expr_004;
rx_expr_008~exp(rx_expr_007);
d/dt(A1)=-A1*rx_expr_005*rx_expr_008;
rx_yj_~2;
rx_lambda_~1;
rx_pred_=rx_expr_006;
rx_r_=Rx_pow_di(THETA[4],2);
tcl=THETA[1];
tv=THETA[2];
cl=rx_expr_008;
v=exp(ETA[2]+THETA[2]);
ke=rx_expr_005*rx_expr_008;
cp=rx_expr_006;
nlmixr_pred~rx_expr_006;
cmt(cp);
Needed Covariates:
[1] "log_allo_wt"
```
Error in (function (data, inits, PKpars, model = NULL, pred = NULL, err = NULL,  : 
  Not all the covariates are in the dataset.

```{r}
# It is there:
head(pheno.dta)
```
  ID TIME  AMT  WT APGR   DV MDV EVID log_allo_wt
1  1  0.0 25.0 1.4    7  0.0   1  101  0.07410797
2  1  2.0  0.0 1.4    7 17.3   0    0  0.07410797
3  1 12.5  3.5 1.4    7  0.0   1  101  0.07410797
4  1 24.5  3.5 1.4    7  0.0   1  101  0.07410797
5  1 37.0  3.5 1.4    7  0.0   1  101  0.07410797
6  1 48.0  3.5 1.4    7  0.0   1  101  0.07410797
```

**Comment by mattfidler** [comment]
Thank you @jfstanding,

I can reproduce the issue.

<details>
``` r
library(nlmixr)
pheno.dta <- pheno_sd
pheno.dta$log_allo_wt <- log(pheno.dta$WT / 1.3)

run7.mod <- function() {
  ini({
    tcl <- log(0.008) # typical value of clearance
    tv <-  log(0.6)   # typical value of volume
    all.cl <- 1 # allometric exponent on CL
    eta.cl ~ 0.1      # interindividual variability on clearance 
    eta.v ~ 0.1       # interindividual variability on volume
    #eta.cl + eta.v ~ c(1,
    #                   0.00001, 1) 
                      # interindividual variability on clearance and volume
    add.err <- 0.1    # residual variability
  })
  model({
    cl <- exp(tcl + all.cl * log_allo_wt + eta.cl) # individual value of clearance
    v <- exp(tv + eta.v)    # individual value of volume
    ke <- cl / v            # elimination rate constant
    d/dt(A1) = - ke * A1    # model differential equation
    cp = A1 / v             # concentration in plasma
    cp ~ add(add.err)       # define error model
  })
}

run7.fo <- nlmixr(run7.mod, pheno.dta, est="fo")
#> Model:
#> cmt(A1);
#> rx_expr_001~-ETA[2];
#> rx_expr_002~ETA[1]+THETA[1];
#> rx_expr_003~rx_expr_001-THETA[2];
#> rx_expr_004~THETA[3]*log_allo_wt;
#> rx_expr_005~exp(rx_expr_003);
#> rx_expr_006~A1*rx_expr_005;
#> rx_expr_007~rx_expr_002+rx_expr_004;
#> rx_expr_008~exp(rx_expr_007);
#> d/dt(A1)=-A1*rx_expr_005*rx_expr_008;
#> rx_yj_~2;
#> rx_lambda_~1;
#> rx_pred_=rx_expr_006;
#> rx_r_=Rx_pow_di(THETA[4],2);
#> tcl=THETA[1];
#> tv=THETA[2];
#> cl=rx_expr_008;
#> v=exp(ETA[2]+THETA[2]);
#> ke=rx_expr_005*rx_expr_008;
#> cp=rx_expr_006;
#> nlmixr_pred~rx_expr_006;
#> cmt(cp);
#> Needed Covariates:
#> [1] "log_allo_wt"
#> Error in (function (data, inits, PKpars, model = NULL, pred = NULL, err = NULL, : Not all the covariates are in the dataset.
```

<sup>Created on 2019-05-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
</details>

**Comment by mattfidler** [comment]
Thank you again @jfstanding for reporting this!

I have fixed the issue and provided a updated model with the covariate effect and a covariance between cl/v with `"fo"` "`foi"` "`foce`" and "`focei`"

<details>

``` r
library(nlmixr)

pheno.dta <- pheno_sd
pheno.dta$log_allo_wt <- log(pheno.dta$WT / 1.3)

run7.mod <- function() {
  ini({
    tcl <- log(0.008) # typical value of clearance
    tv <-  log(0.6)   # typical value of volume
    all.cl <- 1 # allometric exponent on CL
    eta.cl + eta.v ~ c(1,
                       0.01, 1)
                      # interindividual variability on clearance and volume
    add.err <- 0.1    # residual variability
  })
  model({
    cl <- exp(tcl + all.cl * log_allo_wt + eta.cl) # individual value of clearance
    v <- exp(tv + eta.v)    # individual value of volume
    ke <- cl / v            # elimination rate constant
    d/dt(A1) = - ke * A1    # model differential equation
    cp = A1 / v             # concentration in plasma
    cp ~ add(add.err)       # define error model
  })
}

run7.fo <- nlmixr(run7.mod, pheno.dta, est="fo", control=list(print=0))
#> Needed Covariates:
#> [1] "log_allo_wt"
#> Calculating covariance matrix
#>                            done
#> Warning in .collectWarnings(do.call(foceiFit.data.frame0, call, envir =
#> parent.frame(1))): Gradient problems with initial estimate and covariance;
#> see $scaleInfo
#> Needed Covariates:
#> [1] "log_allo_wt"
#> Calculating residuals/tables
#> done.
print(run7.fo)
#> ── nlmixr FO (outer: nlminb) estimation with FOCE posthoc estimation ──────
#>          OBJF      AIC       BIC Log-likelihood Condition Number
#> FOCE 677.3327 976.2036  997.5076      -481.1018          14.2565
#> FO   680.3366 979.2075 1000.5115      -482.6038          14.2565
#> 
#> ── Time (sec; $time): ─────────────────────────────────────────────────────
#>            setup optimize covariance table
#> elapsed 0.145357 0.074168    0.07417 0.027
#> 
#> ── Population Parameters ($parFixed or $parFixedDf): ──────────────────────
#>                          Parameter  Est.     SE %RSE
#> tcl     typical value of clearance -5.09 0.0531 1.04
#> tv         typical value of volume 0.318 0.0491 15.4
#> all.cl   allometric exponent on CL  1.21   0.15 12.4
#> add.err       residual variability  3.01            
#>            Back-transformed(95%CI) BSV(CV%) Shrink(SD)%
#> tcl     0.00614 (0.00553, 0.00681)     23.2      48.6% 
#> tv               1.37 (1.25, 1.51)     35.8     -7.88% 
#> all.cl           3.37 (2.51, 4.52)                     
#> add.err                       3.01                      
#> 
#>   Covariance Type ($covMethod): r,s
#>   Correlations in between subject variability (BSV) matrix:
#>     cor__eta.v.eta.cl 
#>             0.0463
#>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs)
#>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink
#>   Minimization message ($message):
#>     relative convergence (4)
#> 
#> ── Fit Data (object is a modified tibble): ────────────────────────────────
#> # A tibble: 155 x 21
#>   ID     TIME    DV  EVID log_allo_wt  PRED    RES   WRES IPRED  IRES
#>   <fct> <dbl> <dbl> <int>       <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl>
#> 1 1        2   17.3     0      0.0741  18.0 -0.707 -0.259  18.5 -1.25
#> 2 1      112.  31       0      0.0741  28.5  2.52   0.924  29.8  1.25
#> 3 2        2    9.7     0      0.143   10.8 -1.09  -0.402  12.9 -3.22
#> # … with 152 more rows, and 11 more variables: IWRES <dbl>, CPRED <dbl>,
#> #   CRES <dbl>, CWRES <dbl>, eta.cl <dbl>, eta.v <dbl>, cl <dbl>, v <dbl>,
#> #   ke <dbl>, cp <dbl>, A1 <dbl>
plot(run7.fo)
```

![](https://i.imgur.com/djAG6b7.png)![](https://i.imgur.com/fB1TGtx.png)![](https://i.imgur.com/5ZohTh2.png)![](https://i.imgur.com/F6DBSYN.png)![](https://i.imgur.com/iM38BgT.png)

    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?

![](https://i.imgur.com/tWNxsoh.png)

    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?

![](https://i.imgur.com/YuMoRbw.png)

    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?

![](https://i.imgur.com/RStiKpf.png)

    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?

![](https://i.imgur.com/3FS5CfS.png)

``` r
run7.foi <- nlmixr(run7.mod, pheno.dta, est="foi", control=list(print=0))
#> Calculate ETA-based prediction and error derivatives:
#> Using sympy via reticulate
#> Calculate Jacobian
```

    #> Calculate Sensitivities

    #> Load into sympy...
    #> done
    #> Calculate ∂(f)/∂(η)

    #> Calculate ∂(R²)/∂(η)

    #> Freeing Python/SymPy memory...
    #> done
    #> ################################################################################
    #> Optimizing expressions in Predictions/EBE model...done
    #> Compiling Predictions/EBE model...done
    #> Optimizing expressions in Inner model...done
    #> Compiling Inner model...done
    #> The model-based sensitivities have been calculated.
    #> Needed Covariates:
    #> [1] "log_allo_wt"
    #> Calculating covariance matrix
    #>                            done
    #> Warning in .collectWarnings(do.call(foceiFit.data.frame0, call, envir =
    #> parent.frame(1))): Gradient problems with initial estimate and covariance;
    #> see $scaleInfo
    #> Needed Covariates:
    #> [1] "log_allo_wt"
    #> Calculating residuals/tables
    #> done.
    print(run7.foi)
    #> ── nlmixr FOi (outer: nlminb) estimation with FOCEi posthoc estimation ────
    #>           OBJF      AIC       BIC Log-likelihood Condition Number
    #> FOCEi 677.3327 976.2036  997.5076      -481.1018          14.2565
    #> FO    680.3366 979.2075 1000.5115      -482.6038          14.2565
    #> 
    #> ── Time (sec; $time): ─────────────────────────────────────────────────────
    #>            setup optimize covariance table
    #> elapsed 0.213497 0.074787   0.074788 0.028
    #> 
    #> ── Population Parameters ($parFixed or $parFixedDf): ──────────────────────
    #>                          Parameter  Est.     SE %RSE
    #> tcl     typical value of clearance -5.09 0.0531 1.04
    #> tv         typical value of volume 0.318 0.0491 15.4
    #> all.cl   allometric exponent on CL  1.21   0.15 12.4
    #> add.err       residual variability  3.01            
    #>            Back-transformed(95%CI) BSV(CV%) Shrink(SD)%
    #> tcl     0.00614 (0.00553, 0.00681)     23.2      48.6% 
    #> tv               1.37 (1.25, 1.51)     35.8     -7.88% 
    #> all.cl           3.37 (2.51, 4.52)                     
    #> add.err                       3.01                      
    #> 
    #>   Covariance Type ($covMethod): r,s
    #>   Correlations in between subject variability (BSV) matrix:
    #>     cor__eta.v.eta.cl 
    #>             0.0463
    #>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs)
    #>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink
    #>   Minimization message ($message): 
    #>     relative convergence (4)
    #> 
    #> ── Fit Data (object is a modified tibble): ────────────────────────────────
    #> # A tibble: 155 x 21
    #>   ID     TIME    DV  EVID log_allo_wt  PRED    RES   WRES IPRED  IRES
    #>   <fct> <dbl> <dbl> <int>       <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl>
    #> 1 1        2   17.3     0      0.0741  18.0 -0.707 -0.259  18.5 -1.25
    #> 2 1      112.  31       0      0.0741  28.5  2.52   0.924  29.8  1.25
    #> 3 2        2    9.7     0      0.143   10.8 -1.09  -0.402  12.9 -3.22
    #> # … with 152 more rows, and 11 more variables: IWRES <dbl>, CPRED <dbl>,
    #> #   CRES <dbl>, CWRES <dbl>, eta.cl <dbl>, eta.v <dbl>, cl <dbl>, v <dbl>,
    #> #   ke <dbl>, cp <dbl>, A1 <dbl>
    plot(run7.foi)

![](https://i.imgur.com/64VKOlM.png)![](https://i.imgur.com/DJFniQX.png)![](https://i.imgur.com/AfP3yxw.png)![](https://i.imgur.com/v2JNkod.png)![](https://i.imgur.com/68MEOd8.png)

    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?

![](https://i.imgur.com/w5pQQsv.png)

    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?

![](https://i.imgur.com/u3qB3vR.png)

    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?

![](https://i.imgur.com/P1yhs6R.png)

    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?

![](https://i.imgur.com/JpUtUCX.png)

``` r

run7.foce <- nlmixr(run7.mod, pheno.dta, est="foce", control=list(print=0))
#> Needed Covariates:
#> [1] "log_allo_wt"
#> Calculating covariance matrix
#>                            done
#> Calculating residuals/tables
#> done.
#> Warning in .collectWarnings(do.call(foceiFit.data.frame0, call, envir =
#> parent.frame(1))): Gradient problems with initial estimate and covariance;
#> see $scaleInfo
print(run7.foce)
#> ── nlmixr FOCE (outer: nlminb) fit ────────────────────────────────────────
#>          OBJF     AIC     BIC Log-likelihood Condition Number
#> FOCE 672.5521 971.423 992.727      -478.7115         12.57212
#> 
#> ── Time (sec; $time): ─────────────────────────────────────────────────────
#>            setup optimize covariance table
#> elapsed 0.660323 0.466417   0.466419 0.034
#> 
#> ── Population Parameters ($parFixed or $parFixedDf): ──────────────────────
#>                          Parameter  Est.     SE %RSE
#> tcl     typical value of clearance -5.13 0.0529 1.03
#> tv         typical value of volume 0.344 0.0556 16.2
#> all.cl   allometric exponent on CL  1.24  0.141 11.4
#> add.err       residual variability  2.77            
#>            Back-transformed(95%CI) BSV(CV%) Shrink(SD)%
#> tcl     0.00594 (0.00536, 0.00659)     19.5      45.4% 
#> tv               1.41 (1.26, 1.57)     42.3      2.86% 
#> all.cl           3.46 (2.63, 4.57)                     
#> add.err                       2.77                      
#> 
#>   Covariance Type ($covMethod): r,s
#>   Correlations in between subject variability (BSV) matrix:
#>     cor__eta.v.eta.cl 
#>            0.00276
#>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs)
#>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink
#>   Minimization message ($message): 
#>     relative convergence (4)
#> 
#> ── Fit Data (object is a modified tibble): ────────────────────────────────
#> # A tibble: 155 x 21
#>   ID     TIME    DV  EVID log_allo_wt  PRED    RES   WRES IPRED  IRES
#>   <fct> <dbl> <dbl> <int>       <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl>
#> 1 1        2   17.3     0      0.0741  17.6 -0.264 -0.101  18.5 -1.17
#> 2 1      112.  31       0      0.0741  28.3  2.71   1.04   29.8  1.19
#> 3 2        2    9.7     0      0.143   10.5 -0.830 -0.317  13.0 -3.29
#> # … with 152 more rows, and 11 more variables: IWRES <dbl>, CPRED <dbl>,
#> #   CRES <dbl>, CWRES <dbl>, eta.cl <dbl>, eta.v <dbl>, cl <dbl>, v <dbl>,
#> #   ke <dbl>, cp <dbl>, A1 <dbl>
plot(run7.foce)
```

![](https://i.imgur.com/IRF3UXz.png)![](https://i.imgur.com/SRw3mg5.png)![](https://i.imgur.com/iASDSnC.png)![](https://i.imgur.com/Sm6QTlv.png)![](https://i.imgur.com/1iZp02e.png)

    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?

![](https://i.imgur.com/P6bP7nv.png)

    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?

![](https://i.imgur.com/hLCJ4zd.png)

    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?

![](https://i.imgur.com/BJAvPLy.png)

    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?

![](https://i.imgur.com/8AORjgz.png)

``` r

run7.focei <- nlmixr(run7.mod, pheno.dta, est="focei", control=list(print=0))
#> Needed Covariates:
#> [1] "log_allo_wt"
#> Calculating covariance matrix
#>                            done
#> Calculating residuals/tables
#> done.
#> Warning in .collectWarnings(do.call(foceiFit.data.frame0, call, envir =
#> parent.frame(1))): Gradient problems with initial estimate and covariance;
#> see $scaleInfo
print(run7.focei)
#> ── nlmixr FOCEi (outer: nlminb) fit ───────────────────────────────────────
#>           OBJF      AIC      BIC Log-likelihood Condition Number
#> FOCEi 672.5693 971.4402 992.7442      -478.7201         12.55725
#> 
#> ── Time (sec; $time): ─────────────────────────────────────────────────────
#>           setup optimize covariance table
#> elapsed 0.29733 0.490822   0.490823 0.016
#> 
#> ── Population Parameters ($parFixed or $parFixedDf): ──────────────────────
#>                          Parameter  Est.     SE %RSE
#> tcl     typical value of clearance -5.13 0.0527 1.03
#> tv         typical value of volume 0.345 0.0556 16.1
#> all.cl   allometric exponent on CL  1.24  0.141 11.4
#> add.err       residual variability  2.78            
#>            Back-transformed(95%CI) BSV(CV%) Shrink(SD)%
#> tcl     0.00594 (0.00536, 0.00659)     19.7      45.6% 
#> tv               1.41 (1.27, 1.57)     42.3      2.93% 
#> all.cl           3.45 (2.62, 4.55)                     
#> add.err                       2.78                      
#> 
#>   Covariance Type ($covMethod): r,s
#>   Correlations in between subject variability (BSV) matrix:
#>     cor__eta.v.eta.cl 
#>           0.000607
#>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs)
#>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink
#>   Minimization message ($message): 
#>     relative convergence (4)
#> 
#> ── Fit Data (object is a modified tibble): ────────────────────────────────
#> # A tibble: 155 x 21
#>   ID     TIME    DV  EVID log_allo_wt  PRED    RES    WRES IPRED  IRES
#>   <fct> <dbl> <dbl> <int>       <dbl> <dbl>  <dbl>   <dbl> <dbl> <dbl>
#> 1 1        2   17.3     0      0.0741  17.5 -0.244 -0.0926  18.5 -1.17
#> 2 1      112.  31       0      0.0741  28.3  2.73   1.04    29.8  1.19
#> 3 2        2    9.7     0      0.143   10.5 -0.818 -0.311   13.0 -3.28
#> # … with 152 more rows, and 11 more variables: IWRES <dbl>, CPRED <dbl>,
#> #   CRES <dbl>, CWRES <dbl>, eta.cl <dbl>, eta.v <dbl>, cl <dbl>, v <dbl>,
#> #   ke <dbl>, cp <dbl>, A1 <dbl>
plot(run7.focei)
```

![](https://i.imgur.com/XD7jU3d.png)![](https://i.imgur.com/Uu9ZI8w.png)![](https://i.imgur.com/0NbCUeV.png)![](https://i.imgur.com/nwk3nk4.png)![](https://i.imgur.com/DEnIIW0.png)

    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?

![](https://i.imgur.com/aSUoAR2.png)

    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?

![](https://i.imgur.com/E3HUMQp.png)

    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?

![](https://i.imgur.com/qpFbpBK.png)

    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?
    #> geom_path: Each group consists of only one observation. Do you need to
    #> adjust the group aesthetic?

![](https://i.imgur.com/MbYsihF.png)

<sup>Created on 2019-05-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

</details>

**Comment by mattfidler** [comment]
A couple of notes:
- Github nlmixr supports NONMEM-style datasets.  Full details are in the RxODE page  https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-events.html
- The Phenobarbatol dataset is now in nlmixr, since it was included in other open-source packages.

**Comment by jfstanding** [comment]
Thanks, very efficient!  Works fine on my machine now after installing latest nlmixr/RxODE.  Small point, the 5th one of you standard plots should have IWRES vs TIME as title.  Out of interest, why does it default to IWRES vs IPRED and TIME rather than CWRES/NPDE etc.?  Wouldn't IWRES e affected by shrinkage?

**Comment by mattfidler** [comment]
Hi @jfstanding 

I'm glad it works for you. 

You are right `IWRES` can definitely be affected by shrinkage (both `ETA` and `EPS` in NONMEM-speak);  The `CWRES`/`NPDE` are not necessarily calculated in every fit object, so currently it doesn't add these plots, though it could (if they exist).
