### ISSUE TITLE
Error in SnakeCharmR installation

### ISSUE THREAD

**Issue by dryoutao** [nlmixrdevelopment/nlmixr#173]
Hi gurus,

I'm attempting to install SnakeCharmR so as to install nlmixr subsequently. I'm on a Mac OS 10.3.16 with Xcode version 10.1.

I've successfully run these

system('pip install --upgrade pip')
py_install("nose")
py_install("tornado")
py_install("pandas")
py_install("sympy")
use_python("python")

However, when I attempt to run this
 > devtools::install_github("nlmixrdevelopment/SnakeCharmR",force = TRUE) 

It complains

python.cpp:4:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^~~~~~~~~~
1 error generated.
make: *** [python.o] Error 1
ERROR: compilation failed for package ‘SnakeCharmR’

What shall I do?

Many thanks,
Tao

**Comment by mattfidler** [comment]
Try using reticulate instead

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dryoutao** [comment]
Hi Matt, much appreciated for the quick reply. I edited my initial post for a bit more information.

I wonder if you could please give me a bit more detailed instructions. Should I look at an article on reticulate?

Best,
Tao

**Comment by mattfidler** [comment]
Hi @dryoutao 

In theory all you would need to do is:

```R
install.packages("reticulate")
```

**Comment by mattfidler** [comment]
Once that is done, and you have installed `RxODE`, you should be able to try:
``` r
library(RxODE)
rxSymPyVersion()
#> Using sympy via reticulate
#> [1] 1.3
```

<sup>Created on 2019-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mattfidler** [comment]
Let me know if this works for you.

**Comment by dryoutao** [comment]
Hi Matt,

Much appreciated for the tips. I'd like to confirm it works. 

I have python 2 and python 3 on the Mac and I needed to specify which version to use so that RxODE works.

Assuming one has installed sympy, numpy, nose, tornado etc already, that's what one needs to run in R on a Mac

library(reticulate)
use_python("/usr/local/bin/python3")
install.packages("devtools")
library(devtools)
install.packages("RxODE")
library(RxODE)
demo("demo1","RxODE")
rxSymPyVersion()
browseVignettes("RxODE")
rxTest(FALSE) # shorter test
rxTest() # run all of the unit tests
install_github("nlmixrdevelopment/nlmixr",force = TRUE)
library(nlmixr)

Best,
Tao

**Comment by mattfidler** [comment]
Great Tao!

I believe that `reticulate` is faster than `SnakeCharmR`.  At the same time, it doesn't work on some windows machines, though I'm not entirely sure why.
