### ISSUE TITLE
External validation of nlmixr model fit

### ISSUE THREAD

**Issue by karthikl6** [nlmixrdevelopment/nlmixr#175]
Hi @mattfidler ,

I have an nlmixr model and I want to validate this using test data set that is not used in model development. So, if I want to simulate for this new dataset and generate a VPC plot, is there any way that I can do using VPC function of nlmixr with parameters obtained from model developed using training dataset?  

Also for VPC function of nlmixr, I tried to change the size of text in plot using 'theme_light(base_size=18)', but this did not worked. Could you please hel me on this as well.

```{r}
vpc(myEmaxgammafoceifit, n=10, show=list(obs_dv=T, obs_ci=T, obs_median=T, pi=T, pi_ci=T, sim_median=T), xlab="Time",  ylab="Concentrations",vpc_theme = theme1) +  theme_light(base_size=18)
```

Thanks!!

**Comment by mattfidler** [comment]
Hi @karthikl6 

The current github version of `nlmixr`/`RxODE` changed the `vpc` object to allow the `theme_light` to be used.  

``` r
library(nlmixr)
library(ggplot2)
one.cmt <- function() {
    ini({
        tka <- 0.45 # Log Ka
        tcl <- 1 # Log Cl
        tv <- 3.45    # Log V
        eta.ka ~ 0.6
        eta.cl ~ 0.3
        eta.v ~ 0.1
        add.err <- 0.7
    })
    model({
        ka <- exp(tka + eta.ka)
        cl <- exp(tcl + eta.cl)
        v <- exp(tv + eta.v)
        linCmt() ~ add(add.err)
    })
}
f <- nlmixr(one.cmt, theo_sd, "focei", foceiControl(print=0))
#> Calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====done
#> Calculating residuals/tables
#> done.
#> Warning in (function (uif, data, est = NULL, control = list(), ...,
#> sum.prod = FALSE, : Initial ETAs were nudged; (Can control by
#> foceiControl(etaNudge=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ...,
#> sum.prod = FALSE, : ETAs were reset to zero during optimization; (Can
#> control by foceiControl(resetEtaP=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ...,
#> sum.prod = FALSE, : Gradient problems with initial estimate and covariance;
#> see $scaleInfo

vpc(f) + theme_light(base_size=18)
#> Compiling VPC model...
#> done
#> done (0.35 sec)
#>   $rxsim = original simulated data
#>   $sim = merge simulated data
#>   $obs = observed data
#>   $gg = vpc ggplot
#> use vpc(...) to change plot options
#> plotting the object now
```

![](https://i.imgur.com/4S3qLcG.png)

<sup>Created on 2019-05-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mattfidler** [comment]
Also, it should be possible to simulate with an updated parameter set.  

The `RxODE` model is located in `fit$simInfo$rx`, you can always compile it and provide whatever simulation information you need and use this data in Ron Keizer's excellent vpc package. 

The information about what you need is at http://vpc.ronkeizer.com/, which is the `vpc` function that nlmixr currently uses.

**Comment by mattfidler** [comment]
Let me know if you get stuck.  

To compile the RxODE model, you simply need to use:

```r
rx <- RxODE(fit$simInfo$rx)
```

**Comment by karthikl6** [comment]
Hi @mattfidler ,

Thank you very much for your response. Regarding external validation, I made the initial estimates of parameters to final estimates in model code and nlmixr() function with external validation dataset using maxOuterIterations=0. I beleive this does not do any estimations and so used this fit object in vpc function. Does this make sense??

**Comment by mattfidler** [comment]
Hi @karthikl6 

`maxOuterIterations=0` performs the `inner` problem estimation, that is it estimates the subject's best parameters based on the pouplation model.

Since the VPC only uses the variability, `maxOuterIterations=0` is OK. It is also equivalent to the `"posthoc"` estimation method.

You could peform this valdation by [model piping](https://nlmixrdevelopment.github.io/nlmixr/articles/modelPiping.html) to make it easier if you wish.  You would simply need to pipe your old model into a new model with an updated dataset using the following code

```r
fit %>%
  nlmixr(new_data,"posthoc") %>% # The posthoc fit would have the estimates of the prior fit with the new data
  nlmixr::vpc()
```

**Comment by karthikl6** [comment]
Perfect, this is what I was looking for, since I couldn't figure this I tried maxOuterIterations=0 to get the VPC. Thank you very much!!

**Comment by mattfidler** [comment]
Great
