### ISSUE TITLE
Error installing on Windows 10

### ISSUE THREAD

**Issue by tmssou** [nlmixrdevelopment/nlmixr#18]
Hello,

I tried to following the installing instruction here:
https://github.com/nlmixrdevelopment/nlmixr/blob/master/inst/Installing_nlmixr.pdf

But as soon as I get to the step:
install_github('nlmixrdevelopment/nlmixr')
Or:
install_github('nlmixrdevelopment/RxODE')

I keep seeing this error message:
* installing *source* package 'nlmixr' ...
Warning in file(file, if (append) "a" else "w") :
  cannot open file 'C:/Users/Name/Documents/R/win-library/3.4/nlmixr/DESCRIPTION': No such file or directory
Error in file(file, if (append) "a" else "w") : 
  cannot open the connection
ERROR: installing package DESCRIPTION failed for package 'nlmixr'
* removing 'C:/Users/Name/Documents/R/win-library/3.4/nlmixr'
Installation failed: Command failed (1)

I tried running R in administrator mode but that didn't help. Does anyone know how I can solve this?

Thank you.

**Comment by wwang-at-github** [comment]
does this help?

https://stackoverflow.com/questions/16680618/installing-packages-onto-r

**Comment by tmssou** [comment]
I'm not sure if that's the same problem I'm having. I tried the suggestions as I could but they didn't seem to work either.

**Comment by wwang-at-github** [comment]
I think it would save you a lot of headache if you install R to
c:\R\R-3.x.x.

BTW, we'll have a CRAN release soon for nlmixr.  The new UI is much better
& friendly.  You may want to the try the new version.  If you cannot wait,
try the dpaser-saem branch:
https://github.com/nlmixrdevelopment/nlmixr/tree/dparser-saem

best,
wenping

**Comment by tmssou** [comment]
I'll wait for the CRAN release then. Thanks again.

**Comment by mattfidler** [comment]
I would suggest the Windows installer:

https://github.com/nlmixrdevelopment/nlmixr/releases/tag/v0.9.0-2

If it doesn't work, let me know.
