### ISSUE TITLE
Installation error: Compilation failed for nlmixr

### ISSUE THREAD

**Issue by karthikl6** [nlmixrdevelopment/nlmixr#180]
Hi @mattfidler ,

I tried to update nlmixr to latest version on GitHub, but it throws an error: 
`compilation failed for package 'nlmixr'`. 
When I looked closely I found that it is looking for g++.exe in a different path than mentioned in environment variables 
`C:/Rtools/mingw_64/g++.exe: not found`. It is actually located in `C:/Rtools/mingw_64/bin/g++.exe`. I'm not sure what went wrong, I've also updated R version to 3.5. Could you please let me help in resolving this?

**Comment by mattfidler** [comment]
Hi @karthikl6 ,

Now the StanHeaders require C++14, so therefore `nlmixr` which links to these require `C++14` there is an additional step to get this working. I'm currently trying to work through this.  

For me the following will work:
```r
devtools::install("nlmixrdevelopment/RxODE")
library(RxODE)
rxC14();
devtools::install("nlmixrdevelopment/nlmixr");
```
Perhaps that will work for you?

**Comment by karthikl6** [comment]
No, still the same issue.
![image](https://user-images.githubusercontent.com/20660426/58360341-56334a80-7e56-11e9-992a-c5514e4bf738.png)

**Comment by mattfidler** [comment]
You can fix it by editing you ~/.R/Makevars.win and changing the g++ line
to bin\g++.exe

**Comment by mattfidler** [comment]
Did you ever get this working?

**Comment by karthikl6** [comment]
Apologies for the late reply, yes editing Makevars.win worked. Thank you very much!!
