### ISSUE TITLE
Error after running nlmixr to fit data

### ISSUE THREAD

**Issue by DimitrisVoul** [nlmixrdevelopment/nlmixr#183]
Hello. I run nlmixr with proportional error and focei. After the fitting the minimisation of the likelihood is complete and the covariance matrix is calculated I get the following error:

```
Calculating covariance matrix
[====|====|====|====|====|====|====|===           ]  80%; ncores=8;  237.090 sec Cannot calculate covariance.
[====|====|====|====|====|====|====|====|====|====] 100%; ncores=8;  238.805 sec 
Error in RxODE::foceiFitCpp_(.ret) : 
  Not compatible with requested type: [type=NULL; target=double].
```

**Comment by mattfidler** [comment]
Hi @DimitrisVoul ,

I'm sorry for the delay;  I have not be able to reproduce this error.  Could you provide a reproducable example.

I will be away from my computer for a few weeks, expect a delay in responses.

**Comment by DimitrisVoul** [comment]
I am afraid the code and data I use are quite specific and I cannot share them. But I have a lot of parameters that need to be fitted. Around 62. When i decrease them to around 52 it works fine so it might be an issue with the too many parameters.

**Comment by DimitrisVoul** [comment]
After installing the latest version that problem was solved.

**Comment by mattfidler** [comment]
Great!
