### ISSUE TITLE
False convergence with FOCEi

### ISSUE THREAD

**Issue by karthikl6** [nlmixrdevelopment/nlmixr#186]
Hi @mattfidler ,

What exactly does false convergence mean? If my model output of parameter estimates and GOF plots are reasonable can I still consider this model taking forward? Could you please let me know your thoughts?

**Comment by mattfidler** [comment]
Hi @karthikl6,

The URL in the model printout answers the question "what does false convergence mean?"
- https://stackoverflow.com/questions/40039114/r-nlminb-what-does-false-convergence-actually-mean

Here is the snippet:

```
In an ODE system, false convergence may mean "useless" evaluations were performed.
  See https://stackoverflow.com/questions/40039114/r-nlminb-what-does-false-convergence-actually-mean
  It could also mean the convergence is poor, check results before accepting fit
  You may also try a good derivative free optimization:
    nlmixr(...,control=list(outerOpt="bobyqa"))
```

So, if the model parameter estimates and GOF plots are reasonable, I think you can move forward.

For the test models, some of the more complex models minmized to answers similar to NONMEM, but had nlmixr port's algorithm had "false convergence", so to me it doesn't make a huge difference.  This is a peculiariaty of the port algoritm. Other algorithms may converge and say nothing at the false convergence test.  

In fact, you really should always check the goodness fit plots before accepting a fit.  When running some NONMEM FOCEi models in the past (and to be fair some nlmixr FOCEi models), the fits can be poor even though covergence has been acheived.  nlmixr does some things to help this like a `theta` reset for mu-referenced models, and possibly NONMEM have done some things to help this too (though I am unclear on the latter).

**Comment by mattfidler** [comment]
Hopefully this answers your question, please close the issue if it does, if not, please ask a more specific question.
