### ISSUE TITLE
If else statements in FOCEi

### ISSUE THREAD

**Issue by karthikl6** [nlmixrdevelopment/nlmixr#196]
Hi @mattfidler,

With the current version of nlmixr, when I use if else statement in the model code with FOCEi, it throws an error shown below. It worked in the older version, could you please let me know if there any workaround for this?

![image](https://user-images.githubusercontent.com/20660426/60920583-87c96f00-a266-11e9-80e7-b37933bff3a6.png)

**Comment by mattfidler** [comment]
Hi @karthikl6 

While it worked in the older version, the `ETAs` and no sensitivity so the `CWRES` estimates were likely off.  

You could run using `SAEM`.  I am working through this now.

**Comment by karthikl6** [comment]
@mattfidler 

Thank you for the quick reply. I have some time-varying covariates in the data, as far as I remember, SAEM won't support this right?

**Comment by mattfidler** [comment]
Unfortunately, not yet. 

Also unfortunately my guess, if you reverted to the last version the `ETAs` that depend on the `if/else` condition were all `0`

**Comment by karthikl6** [comment]
Ohh, Thank you for letting me know. I was thinking about switching to the older version.

**Comment by mattfidler** [comment]
The sensitivities  (aka gradients) for the `ETAs` that depend on if/else were not calculated so they were assumed to be zero.  This means the initial zero estimate of `ETA` would not change.
