### ISSUE TITLE
How to fix the number of iterations for the smoothing phase in SAEM in nlmixr ?

### ISSUE THREAD

**Issue by MorganePhilipp** [nlmixrdevelopment/nlmixr#199]
Dear @mattfidler,

Is it possible to fix the number of iterations for the smoothing phase in SAEM in nlmixr (equivalent to Monolix's K_2 )?

I found in the guidelines available on r how to fix seed, nBurn, nEm, nmc but I find nothing about how to fix the number of iterations for the smoothing phase.
![image](https://user-images.githubusercontent.com/52911686/61216157-f0a06380-a70c-11e9-8be3-e50b3f27b3af.png)

I would like to fix it also in my code which is currently as follows:  
fit <- nlmixr(f, data, est="saem", saemControl(seed=123456, n.burn=5, n.em=300, nmc=5), table = tableControl(cwres=TRUE, npde=TRUE))

Regards,
MP

**Comment by mattfidler** [comment]
Can you provide the link to the monolix documentation?  I couldn't find information on Monolix's smoothing phase.

One point, I think yo need to change your `saem` options to:

```R
fit <- nlmixr(f, data, est="saem", saemControl(seed=123456, nBurn=5, nEm=300, nmc=5), table = tableControl(cwres=TRUE, npde=TRUE))
```

I can't recall if `n.burn` works or not.

**Comment by MorganePhilipp** [comment]
Dear @mattfidler,

Here is the link to the monolix documentation where the informations about the smoothing phase appear:
http://monolix.lixoft.com/single-page/?section=population-parameter-estimation-using-saem

Thank you, I did the modifications. 

Thank you for your help, 
Regards, 
MP

**Comment by mattfidler** [comment]
Monolix may have changed their `K` numbering with recent releases, and I don't think they refer to them any longer.  

I couldn't find the `K_2` in the link you provided.  However, I found the discussion of the smoothing phase.  I believe `nEm` is the same as the smoothing phase.  The documentation that I was using in monolix was much older than the new online help.

**Comment by mattfidler** [comment]
I assume this answers your question @MorganePhilipp .  Let me know if I'm mistaken.

**Comment by MorganePhilipp** [comment]
Dear @mattfidler,

Yes, thank you very much for your answer. 
I'm sorry I thought I already answered you.

Best regards, 
MP

**Comment by mattfidler** [comment]
Great! thanks.
