### ISSUE TITLE
Issues with installation instructions under OSX

### ISSUE THREAD

**Issue by guiastrennec** [nlmixrdevelopment/nlmixr#2]
In the [Installing_nlmixr.pdf](https://github.com/nlmixrdevelopment/nlmixr/blob/master/inst/Installing_nlmixr.pdf) file they are a couple issues for the OSX instructions:

1) Is it currently not possible to copy and paste commands in R from the online pdf version on github > Suggest to change to an HTML format
2) To install packages from github I believe that the syntax should be: `devtools::install_github('nlmixrdevelopment/nlmixr ')` not `devtools::install_github('nlmixrdevelopment/nlmixr', repos = NULL, type = 'source')` which gave erros. The same thing applies to the `RxODE`.
3) For `RxODE` I got the following error even though I have gfortran (v.6.1) installed.
```
* installing *source* package ‘RxODE’ ...
** libs
** arch - 
echo "make libodeaux.a in ode/ ..."
make libodeaux.a in ode/ ...
(cd ode; make CC="`"/Library/Frameworks/R.framework/Resources/bin/R" CMD config CC`" FC="`"/Library/Frameworks/R.framework/Resources/bin/R" CMD config FC`" CFLAGS="`"/Library/Frameworks/R.framework/Resources/bin/R" CMD config CFLAGS` -fPIC" FFLAGS="`"/Library/Frameworks/R.framework/Resources/bin/R" CMD config FFLAGS` -fPIC" libodeaux.a)
gfortran-4.8 -g -O2 -fPIC  -c -o opkda2.o opkda2.f
make[1]: gfortran-4.8: No such file or directory
make[1]: *** [opkda2.o] Error 1
make: *** [libodeaux] Error 2
ERROR: compilation failed for package ‘RxODE’
```
I was able to solve the issue using this [StackOverflow post](http://stackoverflow.com/questions/37753941/os-x-package-installation-issue-cant-find-gfortran-4-8-to-build-package).

4) I just came to realize that `RxODE` is now available on CRAN and this should be mentioned in the instructions it would prevent the installation issues.

**Comment by RikSchoemaker** [comment]
Dear Benjamin,

Thank you for sharing your experience in installing on OS X! I have updated the installation instructions, mentioning that RxODE is now available on CRAN (make sure you get the version after 1 December), and I have added an rtf version of the installation document as well to make copying commands easier.

Kind regards,

Rik

**Comment by guiastrennec** [comment]
Great thanks !
