### ISSUE TITLE
Fitting sparse PK data

### ISSUE THREAD

**Issue by WangdaZ** [nlmixrdevelopment/nlmixr#20]
Dear All,

nlmixr works pretty well with rich PK data. I wonder what is performance with relative sparse sampling schemes. Like using codes below:

library(nlmixr)

f <- function(){
  ini({
    lCl <- -3    # log Cl (L/hr)
    lVc <- -1    # log Vc (L)
    lKA <- 1     # log Ka (1/hr)
    add.err <- c(0, 0.2, 1)
    eta.Cl ~ 0.1 # BSV Cl
    eta.Vc ~ 0.1 # BSV Vc
    eta.KA ~ 0.1 # BSV Ka
  })
  model({
    ## First parameters are defined in terms of the initial estimates
    ## parameter names.
    Cl <- exp(lCl + eta.Cl)
    Vc <- exp(lVc + eta.Vc)
    KA <- exp(lKA + eta.KA)
    ## Next, the differential equations are defined
    d/dt(depot)  = -KA*depot;
    d/dt(centr)  =  KA*depot-Cl/Vc*centr;
    ## And the concentration is then calculated
    cp = centr / Vc;
    ## Last, nlmixr is told that the plasma concentration follows
    ## an additive error (estimated by the parameter add.err)
    cp ~ add(add.err)
  })
}

fit <- nlmixr(f, theo_sd, est="saem")
plot(fit)
A<-data.frame(theo_sd)
B<-subset(A,TIME>1)
B<-subset(B,TIME<4|TIME>12)
fit1 <- nlmixr(f, B, est="saem")

It doesn't fit for me, is there any other function or coding I can try?

Thanks,
Wangda

**Comment by RikSchoemaker** [comment]
Dear Wangda,

My apologies for taking so long to reply. I wanted to provide a big example of using nlmixr on sparse datasets (see issue #21 for the results), but in your case, running your code, you have generated a non-working example by removing the dosing information :).

The following code works just fine:
```{r}
library(nlmixr)

f <- function(){
ini({
lCl <- -3 # log Cl (L/hr)
lVc <- -1 # log Vc (L)
lKA <- 1 # log Ka (1/hr)
add.err <- c(0, 0.2, 1)
eta.Cl ~ 0.1 # BSV Cl
eta.Vc ~ 0.1 # BSV Vc
eta.KA ~ 0.1 # BSV Ka
})
model({
## First parameters are defined in terms of the initial estimates
## parameter names.
Cl <- exp(lCl + eta.Cl)
Vc <- exp(lVc + eta.Vc)
KA <- exp(lKA + eta.KA)
## Next, the differential equations are defined
d/dt(depot) = -KA*depot;
d/dt(centr) = KA*depot-Cl/Vc*centr;
## And the concentration is then calculated
cp = centr / Vc;
## Last, nlmixr is told that the plasma concentration follows
## an additive error (estimated by the parameter add.err)
cp ~ add(add.err)
})
}

fit <- nlmixr(f, theo_sd, est="saem")
plot(fit)
A<-data.frame(theo_sd)
B<-subset(A,EVID==101|TIME>1)
B<-subset(B,TIME<4|TIME>12)
fit1 <- nlmixr(f, B, est="saem")
```

Kind regards,

Rik
