### ISSUE TITLE
How to code a PK model with an absorption delay? 

### ISSUE THREAD

**Issue by MorganePhilipp** [nlmixrdevelopment/nlmixr#200]
Dear @mattfidler, 

I would like to code a model with a Tlag in nlmixr but I have some issues.

First to be more precise, it is a one-compartment model, with first-order absorption kinetics and linear elimination kinetics. 
The drug is administered orally. 

I coded my model as follows: 
![image](https://user-images.githubusercontent.com/52911686/61216951-ea12eb80-a70e-11e9-8b03-2a2eefb9f975.png)

However, when I launch my fit thanks to the following instructions:
fit <- nlmixr(f, data, est="saem", saemControl(seed=123456, n.burn=5, n.em=300, nmc=5), table = tableControl(cwres=TRUE, npde=TRUE))

I receive the error message below: 
![image](https://user-images.githubusercontent.com/52911686/61217057-3100e100-a70f-11e9-80f1-d63a4f5e87a3.png)

Is the synthesis of the model with a Tlag correct? Indeed, I did not find any model with a Tlag, so I was inspired by the guidelines with a model without Tlag (so a ka, v, cl model) and I do not know if the code I wrote is correct.
I know that a closed form solution exists because I estimate the population parameter with this model with a Tlag with other software. 

I also tried to code the model in ODE form. I ended up with the following code: 
![image](https://user-images.githubusercontent.com/52911686/61217782-bf299700-a710-11e9-90b7-e5e4900af5c7.png)

The fit was done correctly. I still wonder if the syntax is correct or should I code the model differently? 
 
Regards, 
MP

**Comment by mattfidler** [comment]
Hi @MorganePhilipp 

`nlmixr`/`RxODE` support absorption lags on depots;  The code is:

```R
alag(depot) = tlag
```
This should work for both the solved system and the differential equations (assuming you name the depot compartment `depot` in the ODEs).

This shows the other types of properties that you can model in `nlmixr` like rate, duration, bioavailability, etc.

```R
## Model from RxODE tutorial
m1 <-RxODE({
    KA=2.94E-01;
    CL=1.86E+01;
    V2=4.02E+01;
    Q=1.05E+01;
    V3=2.97E+02;
    Kin=1;
    Kout=1;
    EC50=200;
    ## Added modeled bioavaiblity, duration and rate
    fdepot = 1;
    durDepot = 8;
    rateDepot = 1250;
    C2 = centr/V2;
    C3 = peri/V3;
    d/dt(depot) =-KA*depot;
    f(depot) = fdepot
    dur(depot) = durDepot
    rate(depot) = rateDepot
    d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
    d/dt(peri)  =                    Q*C2 - Q*C3;
    d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
    eff(0) = 1
});
```

In general for solved systems `nlmixr`/`RxODE` name the solved compartments `depot` and `central`.

**Comment by mattfidler** [comment]
Examples of events are:

https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-events.html

**Comment by MorganePhilipp** [comment]
Dear @mattfidler, 

Thank you for your answer. It works for the ODE model. However it can't figure out how to implement lag time in a solved system.

I tried to define "depot" with a differential expression as follows: d/dt(depot) =-ka*depot
But I got a message error:
![image](https://user-images.githubusercontent.com/52911686/61296487-7f2ee680-a7da-11e9-8904-6db3fd398c77.png)

So I tried to code it like that:
![image](https://user-images.githubusercontent.com/52911686/61297887-7c81c080-a7dd-11e9-9496-09119e3015a3.png)


However "amt" is not recognized:
![image](https://user-images.githubusercontent.com/52911686/61296644-cfa64400-a7da-11e9-9e72-ed1884ffbf06.png)

So I tried to define "amt" and the "t" by extracting the data column: amt <- data[,3], t <- data [,2]
But I got the same error message as for "amt" when it's not recognized. 

Can you help me to figure out how to code a tlag in a solved system? 

Thank you for your help, 
Regards, 
MP

**Comment by mattfidler** [comment]
Hi @MorganePhilipp,

You don't have to define the depot in the model,  the `linCmt()` function defines two psuedo-compartments `depot` and `central` so you simply drop the `depot=` line and the model should work.

So in theory
```R
model({
ka=exp(tka+etaKa)
cl=exp(tcl+etaCl)
v=exp(tv+etaV)
lagDepot = exp(tLag+etaLag)
alag(depot)=lagDepot
linCmt()~prop(prop.err) + add(add.err)
})
```
should be sufficient.  Currently reserved data items cannot be used in a `nlmixr`/`RxODE` model

**Comment by MorganePhilipp** [comment]
Dear @mattfidler,

Thank you very much for your answer. I'm sorry to bother you with this.

I changed my code according to your advice:
![image](https://user-images.githubusercontent.com/52911686/61315310-c9c25a00-a7fe-11e9-88cb-79c132b5dabd.png)

However, I get the following error message:
![image](https://user-images.githubusercontent.com/52911686/61315338-da72d000-a7fe-11e9-80b8-cfdc1fa0e04f.png)

Did I make a mistake? 

Regards, 
MP

**Comment by mattfidler** [comment]
It seems OK, can you paste it as text?

For me, the following code works just fine:

``` r
library(nlmixr)
one.cmt <- function() {
    ini({
        tka <- 0.45 # Log Ka
        tcl <- 1 # Log Cl
        tv <- 3.45    # Log V
        lagDepot <- -3
        eta.ka ~ 0.6
        eta.cl ~ 0.3
        eta.v ~ 0.1
        eta.lag ~ 0.01
        add.err <- 0.7
    })
    model({
        ka <- exp(tka + eta.ka)
        cl <- exp(tcl + eta.cl)
        v <- exp(tv + eta.v)
        lag(depot) <- exp(lagDepot + eta.lag)
        linCmt() ~ add(add.err)
    })
}

fit <- nlmixr(one.cmt, theo_sd, est="saem", control=list(print=0))
#> Compiling RxODE equations...done.
#> Calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====
#> Calculating residuals/tables
#> done.

print(fit)
#> ── nlmixr SAEM(Solved); OBJF not calculated fit ─────────────────────────── 
#>  Gaussian/Laplacian Likelihoods: AIC() or $objf etc. 
#>  FOCEi CWRES & Likelihoods: addCwres() 
#> 
#> ── Time (sec; $time): ───────────────────────────────────────────────────── 
#>          saem    setup table covariance    other
#> elapsed 0.713 0.677331 0.008      0.005 0.279669
#> 
#> ── Population Parameters ($parFixed or $parFixedDf): ──────────────────────
#> Registered S3 method overwritten by 'R.oo':
#>   method        from       
#>   throw.default R.methodsS3
#>          Parameter  Est.     SE %RSE Back-transformed(95%CI) BSV(CV%)
#> tka         Log Ka 0.627  0.222 35.5       1.87 (1.21, 2.89)     78.3
#> tcl         Log Cl     1 0.0832 8.28       2.73 (2.32, 3.21)     27.2
#> tv           Log V  3.47 0.0446 1.29           32 (29.4, 35)     13.5
#> lagDepot           -2.72  0.417 15.3   0.0657 (0.029, 0.149)     13.9
#> add.err            0.621                               0.621         
#>          Shrink(SD)%
#> tka          -1.79% 
#> tcl           2.85% 
#> tv            5.11% 
#> lagDepot      76.4% 
#> add.err              
#> 
#>   Covariance Type ($covMethod): linFim
#>   No correlations in between subject variability (BSV) matrix
#>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs) 
#>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink 
#> 
#> ── Fit Data (object is a modified tibble): ──────────────────────────────── 
#> # A tibble: 132 x 19
#>   ID     TIME    DV  EVID  PRED     RES IPRED   IRES  IWRES eta.ka eta.cl
#>   <fct> <dbl> <dbl> <int> <dbl>   <dbl> <dbl>  <dbl>  <dbl>  <dbl>  <dbl>
#> 1 1     0      0.74     0  0     0.74    0     0.74   1.19  0.0917 -0.494
#> 2 1     0.25   2.84     0  2.89 -0.0498  3.39 -0.554 -0.893 0.0917 -0.494
#> 3 1     0.570  6.57     0  5.95  0.619   6.87 -0.305 -0.491 0.0917 -0.494
#> # … with 129 more rows, and 8 more variables: eta.v <dbl>, eta.lag <dbl>,
#> #   rx1c <dbl>, ka <dbl>, cl <dbl>, v <dbl>, depot <dbl>, central <dbl>
```

<sup>Created on 2019-07-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattfidler** [comment]
You cal also try using `rxClean()` which will clear out any caches, or restarting R which should effectively do the same thing.

**Comment by MorganePhilipp** [comment]
Dear @mattfidler, 

Thank you very much for your code!! I saw my error and I made the correction. Now it works!!

I put the code correct if it can help someone else:
![image](https://user-images.githubusercontent.com/52911686/61326261-a3a8b400-a816-11e9-9727-6a43812377a5.png)

I would really like to thank you for your patience and time.

Best regards, 
MP

**Comment by mattfidler** [comment]
No problem.  Can you clarify what the error was?  I wasn't too clear.

**Comment by MorganePhilipp** [comment]
Dear @mattfidler,

Sure. 

Here is a comparison of the two codes:
![image](https://user-images.githubusercontent.com/52911686/61356647-134e8b80-a877-11e9-823a-b94a3e2146fc.png)

It doesn’t work when the code is splited into two lines when the distribution of the variable is defined as on the left picture.
So the distribution of the variable should be coded in one line as on the right picture:
lag(depot) <- exp(llagDepot + eta.lag)

Regards, 
MP
