### ISSUE TITLE
Fitting fails with multiple models

### ISSUE THREAD

**Issue by DimitrisVoul** [nlmixrdevelopment/nlmixr#202]
Hello,

I have encountered a very peculiar error. A few days ago I was fitting different models using nlmixr one after the other successfully. After a crash from R this is now impossible. I run the code and only the first models that I run gets fitted and the rest give an error that nlmixr could not fit the data. Even if I try to fit the same model that just fitted it fails.

If I restart the session and pick another model then it will fit that the first time I run and then the same all over again.

I tried reinstalling and it didn't help

**Comment by mattfidler** [comment]
Did you upgrade anything on your system?  There is a compiler bug with one of the new gcc compilers. This was observed in #191 and elsewhere on the internet.

**Comment by mattfidler** [comment]
If you could provide a reproducible example, it would be helpful.

**Comment by DimitrisVoul** [comment]
There has been an upgrade but this is a company laptop so I am not sure what it was and nothing I can change.

I am afraid I don't have anything that can be easily reproduced. Is there a way round this bug?

**Comment by mattfidler** [comment]
Are you using windows?  Or a Mac?

**Comment by DimitrisVoul** [comment]
I am using windows

**Comment by mattfidler** [comment]
I would suggest using the installer at 

https://github.com/nlmixrdevelopment/nlmixr/releases

To see if you can reproduce a sane environment if so, then you can try to update if you need to.

**Comment by mattfidler** [comment]
Make sure to uninstall any others and follow the advice in the readme.

**Comment by DimitrisVoul** [comment]
I am afraid that didn't work. still have the same issue

**Comment by mattfidler** [comment]
Can you share a bit more information.  Its hard to fix something I cannot reproduce.

**Comment by mattfidler** [comment]
Perhaps provide a `sessionInfo()`, `Sys.getenv("PATH")` and `.libPaths()`

**Comment by DimitrisVoul** [comment]
Sure so in order you asked:

sessionInfo:

> R version 3.6.0 (2019-04-26)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 17763)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
> [4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] RxODE_0.9.0-6    openxlsx_4.1.0.1 ggplot2_3.1.1    nlmixr_1.1.0-9  
> 
> loaded via a namespace (and not attached):
>  [1] zip_2.0.2                 Rcpp_1.0.1                pillar_1.4.1              compiler_3.6.0            plyr_1.8.4               
>  [6] PreciseSums_0.3           tools_3.6.0               mvnfast_0.2.5             digest_0.6.19             nlme_3.1-139             
> [11] lattice_0.20-38           huxtable_4.5.0            memoise_1.1.0             tibble_2.1.1              gtable_0.3.0             
> [16] pkgconfig_2.0.2           rlang_0.3.4               Matrix_1.2-17             rex_1.1.2                 rstudioapi_0.10          
> [21] parallel_3.6.0            xfun_0.7                  RcppArmadillo_0.9.400.3.0 n1qn1_6.0.1-3             withr_2.1.2              
> [26] knitr_1.23                dplyr_0.8.1               lbfgs_1.2.1               generics_0.0.2            grid_3.6.0               
> [31] tidyselect_0.2.5          glue_1.3.1                R6_2.4.0                  polyclip_1.10-0           dparser_0.1.8            
> [36] purrr_0.3.2               tweenr_1.0.1              farver_1.1.0              magrittr_1.5              vpc_1.1.0                
> [41] scales_1.0.0              MASS_7.3-51.4             units_0.6-3               assertthat_0.2.1          ggforce_0.2.2            
> [46] colorspace_1.4-1          brew_1.0-6                lotri_0.1.1               lazyeval_0.2.2            munsell_0.5.0            
> [51] crayon_1.3.4          

Sys.getnv("PATH")

> "c:\\R\\NLMIXR~1.0-9\\R\\rxPython;C:\\Rtools\\bin;C:\\Rtools\\mingw_64\\bin;C:\\Rtools\\mingw_64\\opt\\bin;c:\\R\\NLMIXR~1.0-9\\R\\bin\\x64;C:\\PROGRA~2\\COMMON~1\\Oracle\\Java\\javapath;C:\\PROGRA~3\\Oracle\\Java\\javapath;C:\\Windows\\System32;C:\\Windows;C:\\Windows\\System32\\wbem;C:\\PROGRA~1\\MATLAB\\R2018b\\runtime\\win64;C:\\PROGRA~1\\MATLAB\\R2018b\\bin;C:\\Users\\kpwp689\\AppData\\Local\\MICROS~1\\WINDOW~1"

.libPaths()

> "c:/R/nlmixr_1.1.0-9/R/library"
