### ISSUE TITLE
Modeling in logit domain: Back-transform VPC object

### ISSUE THREAD

**Issue by karthikl6** [nlmixrdevelopment/nlmixr#203]
Hi @mattfidler ,

I'm modeling my PD data which are scores and had to constrain them between certain limits. So, I'm modeling them in logit domain by transforming both sides approach. Now, when I do VPC, is there any way that I back-transform my VPC plot from logit domain? I tried to access data in VPC object and could transform the simulation statistics (q5, median, q95) but not the observed data statistics. Could you help me if there is a work-around?

**Comment by mattfidler** [comment]
It would be ideal if this was done for you, as in the case of `log`-transformed data with `f ~ lnorm(err)`  Something like `f~logitNorm(err)` would be ideal.

I will look at the VPC object again to see if I can get the simulation object;  You should be able to do it. 

Do you have a simple example I can work with?

**Comment by mattfidler** [comment]
Related Issue #207

**Comment by karthikl6** [comment]
Hi @mattfidler ,

In the current model, I used add.err() for the error structure. But, I'm not sure how to interpret the value here. I'm transforming predictions into logit domain and then at the end adding the error. So, now my additive error estimate is logit(add.err_normal) ??

**Comment by mattfidler** [comment]
In theory, in the simulation you should
-  Transform to logit
- Add the logit normal simulation
- Transform back with expit

Both logit and expit actually don't exist in base R.  I might add them.

**Comment by mattfidler** [comment]
But, this is a bit far off currently, even though it shouldn't be terribly hard.

**Comment by karthikl6** [comment]
Hi @mattfidler ,

I"m able to convert simulated statistics from logit domain using: 
 `myvpv_train$data[,3:11] <- apply(myvpv_train$data[,3:11],2,function(x){(exp(x)/(1+exp(x)))*34})`
But, when I use this command
 `myvpv_train$plot_env$db$aggr_obs[,3:5] <- pply(myvpv_train$plot_env$db$aggr_obs[,3:5],2,function(x){(exp(x)/(1+exp(x)))*34})`, 
for observed data statistics, it did convert but in the plot it still shows DV in logit domain but simulated values back-transformed from logit domain.

Am I missing anything?? How can I access observed data and its statistics in VPC object?

**Comment by mattfidler** [comment]
You should be able to use the original data and then transform it directly.  Once it is transformed you would change the vpc to 
```R
vp <- vpc(model,obs=transData)
## Then modify the simulated stats
vp$data[,3:11] <- apply(vp$data[,3:11],2,function(x){(exp(x)/(1+exp(x)))*34})
## Note this is theoretical since I haven't made a logit-transformed example.
```

**Comment by karthikl6** [comment]
I'm getting below error if I use "obs" argument:

![image](https://user-images.githubusercontent.com/20660426/61762705-dddafe00-ada0-11e9-9d0f-5046048c2219.png)

**Comment by karthikl6** [comment]
Finally, I was able to get it done by using simulated object instead of model object in vpc.

First performed a normal VPC,
`myvpv_train <-   nlmixr::vpc(myEmaxgammafoceifit,obs=mydat_vpc, n=500)`

Then, extracted simulated object and re-done (only summary statistics) VPC using transformed original data
`myvpv_train<-nlmixr::vpc(myvpv_train$plot_env$db$sim, obs=transData)`

**Comment by mattfidler** [comment]
Thank you @karthikl6  for the report.
