### ISSUE TITLE
Error during installation: non-empty 'configure.win' file

### ISSUE THREAD

**Issue by tamas-ferenci** [nlmixrdevelopment/nlmixr#209]
When trying to upgrade `nlmixr` from Github, I get the following:

```
--------[[end src/Makevars.win]]-------- 
** libs
Error: (converted from warning) this package has a non-empty 'configure.win' file,
so building only the main architecture
* removing 'C:/Users/<username>/Documents/R/win-library/3.6/nlmixr'
Error: Failed to install 'nlmixr' from GitHub:
   (converted from warning) installation of package ‘C:/Users/<templocation>/nlmixr_1.1.1-0.tar.gz’ had non-zero exit status
```

Just an idea: this seems to be already documented [here](https://github.com/r-lib/remotes/issues/272), and @mattfidler changed `RxODE` to resolve this (by including `Biarch: true` in `DESCRIPTION`), but I don't see this in `nlmixr`... could this be the problem? (Although it was working well up to the recent days, so perhaps a new commit might rather be the culprit...)

**Comment by mattfidler** [comment]
It was an oversight on my part. Thank you for letting me know.

**Comment by tamas-ferenci** [comment]
I say thanks, it is working perfectly now.
