### ISSUE TITLE
source code for Acop poster

### ISSUE THREAD

**Issue by vjd** [nlmixrdevelopment/nlmixr#21]
do you have a github repository for the simulation and estimation models for the ACoP poster in 2016? Curious about results of the sparse datasets, so it would be great if you could provide a repo of all the work that generated the datasets and the model files for nonmem and nlmixr

**Comment by RikSchoemaker** [comment]
Hi Vijay,
The github site currently contains the material for all the rich datasets and associated old syntax, and datafiles are also inside the CRAN package.  I plan to upload the syntax for the new universal user interface soon (for my ACoP 2017 poster). The sparse sample analysis is for 500 datasets with NONMEM results and nlmixr analogs (nlme and SAEM). I also plan too upload those when I have it regenerated using the UUI.
Cheers,
Rik

On 10 Nov 2017, at 05:59, Vijay Ivaturi <notifications@github.com<mailto:notifications@github.com>> wrote:


do you have a github repository for the simulation and estimation models for the ACoP poster in 2016? Curious about results of the sparse datasets, so it would be great if you could provide a repo of all the work that generated the datasets and the model files for nonmem and nlmixr

**Comment by RikSchoemaker** [comment]
Hi Vijay,

I have now cleaned up the code and rerun all the sparse sample analyses using the new UUI. We plan to be uploading the 500 source data files soon, and plan to have the results in an nlmixr bookdown document. The code should allow you to reproduce all the analyses :). In the meantime, please find a pdf attached with the code and primary results.
[SparseUUI_171221.pdf](https://github.com/nlmixrdevelopment/nlmixr/files/1579013/SparseUUI_171221.pdf)

Seasons greetings!

Rik
