### ISSUE TITLE
Different results after new nlmixr installation with identical code and data 

### ISSUE THREAD

**Issue by WenYao-Mak** [nlmixrdevelopment/nlmixr#218]
I am new to using nlmixr and is excited to know there is an open-source package to run nonlinear mixed effect modeling. 

I was working with nlmxir (ver. 1.0.0-7) and had to update one of the package (RxODE), which unfortunately caused the program to cease working. I uninstalled all program (including R itself) and reinstall nlmixr using the Windows installer (ver. 1.1.0-9), and re-run the identical code with identical data. The results baffled me as the Objective Function Value and Visual Predictive Check were significantly different from the previous version. 

Below is the code that I used for a 1-compartment model, which was identical between both runs.  
```{r, eval=TRUE, echo=F, cache=T, results=FALSE, warning=FALSE, message=FALSE}
library(lattice)
library(nlmixr)
library(xpose.nlmixr)
library(ggplot2)
met.fast<-read.csv("met_fast-M6.csv", as.is = TRUE)
met.fed<-read.csv("met_fed-M6.csv", as.is=TRUE)

met.merged2<-rbind(met.fast, met.fed)
met.merged2$DV<-log(met.merged2$DV) #log-transformed DV

library(nlmixr)

#STEP 1
model.1cptc.ode<-function(){

  ini({
#lower boundaries were set for initial estimates but system said saem 
#will ignore boundaries? 
    tka<-c(0,log(1.5))  #typical value of absorption 
    tcl<-c(0,log(74))   #typical value of clearance
    tv<-c(0,log(190))   #typical value of volumen of distribution 
  
    eta.cl~0.1     #interindividual variability on clearance
    eta.v ~0.1     #interindividual variability on volumne of distribution 

    add.err <- c(0, 0.001) #additive error structure 

  })
  model({
    ka<-exp(tka)
    cl<-exp(tcl + eta.cl) #individual value on clearance 
    v<-exp(tv + eta.v)    #individual value of volume of distribution 
    
    d/dt(depot)=-ka*depot;  #solved system --> what is this?
    d/dt(centr)=ka*depot - cl/v*centr;   #model inferred from parameters,
                                         #cl/v= elimination rate constant
    cp=centr/v; 
    lcp=log(cp)              #log-transformed model equation 
    lcp ~ add(add.err)       #model equation defined by additive error 
  })
}

#STEP 2: check the model
nlmixr(model.1cptc.ode)

#STEP 3
fit.1cptc.ode.saem <- nlmixr(model.1cptc.ode, data=met.merged2, est="saem",
                             table=tableControl(cwres=TRUE, npde=TRUE))
```

Below is the results with the first run (ver. 1.0.0-7) with vpc: 

![VPC ver 1 0 0-7](https://user-images.githubusercontent.com/50729979/62640689-0aaf1980-b93a-11e9-821b-81b9281b1243.png)

The OFV given was -1621.541

However, with ver. 1.1.0-9, the vpc looked like this
![VPC ver 1 1 0-9](https://user-images.githubusercontent.com/50729979/62640735-274b5180-b93a-11e9-9c36-0963e270bd19.png)

And the OFV given was 104.404

This significant difference between the two version is very puzzling. Any help or guidance as to why this happens will be very helpful. Thank you.

**Comment by mattfidler** [comment]
I am unsure why this occurred.

It is also difficult to reproduce without the data.  

When looking at the two VPCs it seems the data are different between the models.  The range of DV are different.  The "good" model has a max `DV` of 3 whereas the "bad" model has a max `DV` of 6.5.

Please check that the data are in fact the same.

If that is true, perhaps there is some mis-translation of the data.  If you can share the data, I can help more.

Since this is SAEM, it is also possible the results are due to the different random number generators between R 3.6 and R 3.5.  You can test this by swapping back to the random number generation of R 3.5 with:

```R
RNGkind(sample.kind="Rounding")
```

Hopefully this helps.

**Comment by WenYao-Mak** [comment]
Thanks for your reply. Yes you are right. I have gone back to reinstall the program and realised there was a slight alteration in my R script, which had caused the DV to deviate. Now the program works perfectly.  Thank you very much.

**Comment by mattfidler** [comment]
Great!  Thank you.
