### ISSUE TITLE
Can we get a s.e. that is not directly returned by the fit function (e.g. s.e. on the proportional error)? 

### ISSUE THREAD

**Issue by MorganePhilipp** [nlmixrdevelopment/nlmixr#219]
Dear @mattfidler ,

I would like to know if it is possible to get the s.e. on the proportional error, additive error, BSV and correlation that are not returned directly by the fit function?

![image](https://user-images.githubusercontent.com/52911686/62728738-cc3e5b00-ba1c-11e9-906b-5ec95fa763f1.png)

Best regards,
Morgane PHILIPP

**Comment by mattfidler** [comment]
Not currently.  

I'm not sure these quantities make sense.  They make the implicit assumption of multivariate normal, when they are often an estimate of a variance standard deviation or covariance.

For simulation uncertanty in these parameters are taken into account by the inverse wishart distribution.

**Comment by MorganePhilipp** [comment]
Dear @mattfidler ,

Ok I see!
Thank you for your explanations and your response.

Best regards, 
MP

**Comment by mattfidler** [comment]
Great
