### ISSUE TITLE
What is called with AIC(fit)?

### ISSUE THREAD

**Issue by tamas-ferenci** [nlmixrdevelopment/nlmixr#223]
(First if all, sorry if it turns out that this question is R-programming related, and not `nlmixr`-specific...)

I was interested to see what's going on under the hood when one calls `AIC(fit)` with a usual model estimated with SAEM. What I found was that `AIC.default` is called from package `stats` which will call `logLik(fit)`. Now, `logLik(fit)` will actually call `logLik.nlmixrFitData` from the package `nlmixr` (the fitted object has another class, to which a `logLik` method pertains, the `nlmixrFitCore` but it is listed *after* `nlmixrFitData` in `class(fit)`). This function will call `fit$logLik` and this is the point where I'm stuck.

First of all, I was under the impression that `$` can be used as an extractor, but `str(fit)` doesn't show that `fit` has any component named `logLik`, more importantly it is quite clear that `fit$logLik` not only extracts something stored, but performs an operation, it seems it calls a function. Is it possible to achieve that extracting a component induces a function call...?? If so, how to find the code? (I can't use `methods`, `getAnywhere` etc. for this situation.)

**Comment by mattfidler** [comment]
> I was interested to see what's going on under the hood when one calls AIC(fit) with a usual model estimated with SAEM.

It is here

https://github.com/nlmixrdevelopment/nlmixr/blob/3a605e4317ef61fa42e0c81edad6af071adbd769/R/saem_fit_aux.R#L24

> If so, how to find the code? (I can't use methods, getAnywhere etc. for this situation.)

The extracting component `$` is also a function so it can be used to call a function.  In this case, this calls the s3 method below:

https://github.com/nlmixrdevelopment/nlmixr/blob/3a605e4317ef61fa42e0c81edad6af071adbd769/R/foceiFit.R#L2122

You can still use `methods` to get this information
```R
> library(nlmixr)
> methods(`$`)
 [1] $,C++Class-method           $,envRefClass-method       
 [3] $,Module-method             $,refObjectGenerator-method
 [5] $.bibentry*                 $.complain*                
 [7] $.crayon*                   $.DLLInfo                  
 [9] $.ggproto*                  $.ggproto_parent*          
[11] $.knitr_strict_list*        $.nlmixrBounds*            
[13] $.nlmixrFitCore*            $.nlmixrFitCoreSilent*     
[15] $.nlmixrFitData*            $.nlmixrGill83*            
[17] $.nlmixrUI*                 $.nlmixrVpc*               
[19] $.package_version           $.person*                  
[21] $.rlang_ctxt_pronoun*       $.rlang_data_pronoun*      
[23] $.rlang_fake_data_pronoun*  $.rxEt*                    
[25] $.rxSolve*                  $.rxSymInvCholEnv*         
[27] $.tbl_df*                   $.xfun_strict_list*        
see '?methods' for accessing help and source code
```

The `str` is also a s3 method.  Since a nlmixr data object is a data frame with properties attached most of the properties do not show up in a standard `str` command.  I have tried to put the things that I will not change, that is the "public" api:

https://github.com/nlmixrdevelopment/nlmixr/blob/3a605e4317ef61fa42e0c81edad6af071adbd769/R/foceiFit.R#L2261

**Comment by tamas-ferenci** [comment]
Amazing! Thank you very much Matt, I'd have never thought that it is possible to "overload" (if this is the correct word here) `$` this way.

What I still don't get is how to set `nnodes.gq` and `nsd.gq`...? I can't access them via `AIC` (if I understand everything correctly).

**Comment by mattfidler** [comment]
You can see how in the broom vignette:

https://nlmixrdevelopment.github.io/nlmixr/articles/broom.html

```R
setOfv(x,"gauss_8_2")
```
Where:
- `nnodes.gq=8`
- `nsd.gq=2`

Of course you can add the `FOCEi` objective function too:

```R
addCwres(x)
```

**Comment by tamas-ferenci** [comment]
Ahh! Of course. Thank you very much!
