### ISSUE TITLE
Errors installing SnakeCharmR 

### ISSUE THREAD

**Issue by melmelie** [nlmixrdevelopment/nlmixr#227]
@mattfidler @mntrame 
I'd appreciate your help with the install, it appears that I am stuck and I have spent a full day already on this. Here's my session info: I am running 64-bit Windows, R Version [64-bit] C:\Program Files\R\R-3.5.0. My question is whether it's possible to not have SnakeCharmR installed and still have successful installation?
Running [source("test_install.R")], I get:
Correct R version: Yes, R version 3.5.0 (2018-04-23)
RxODE installed: Yes
Python installed: Yes, Python 3.7.1
sympy installed: Yes
devtools package installed: Yes
RxODE package installed: Yes
Rtools installed or not needed: Yes
SnakeCharmR package installed: No
To install, use install_github('nlmixrdevelopment/SnakeCharmR') to do so
Note SnakeCharmR seems to work better on windows than reticulate...
reticulate package installed: Yes
units package installed: Yes
nlmixr package installed: Yes
xpose.nlmixr package installed: Yes
shinyMixR package installed: Yes
nlmixr run under nlme: Yes
nlmixr run under saem: Yes
nlmixr run under focei: Yes
---- Installation test finished! ----

As you can see, SnakeCharmR is not installed and library(SnakeCharmR) returns Error in library(SnakeCharmR) : there is no package called ‘SnakeCharmR’.
devtools::install_github("nlmixrdevelopment/SnakeCharmR") gives an error:
Error: Failed to install 'SnakeCharmR' from GitHub:
(converted from warning) installation of package ‘C:/Users/elmelm01/AppData/Local/Temp/1/RtmpayAiD2/file2708392b4476/SnakeCharmR_1.0.7.tar.gz’ had non-zero exit status.
Note that I am using Anaconda and nlmixr appears to be seeing this:

installing source package 'SnakeCharmR' ...
Found Python version 3.7
Detected EXEC_PREFIX=c:\R\NLMIXR1.0-7\python
Detected library dir c:\R\NLMIXR1.0-7\python/libs
Detected library name python37
Detected include dir c:\R\NLMIXR1.0-7\python/include
--------[[begin src/Makevars.win]]--------
PKG_LIBS=-L'c:\R\NLMIXR1.0-7\python/libs' -lpython37
PKG_CPPFLAGS=-I'c:\R\NLMIXR~1.0-7\python/include'
CXX_STD=CXX11
--------[[end src/Makevars.win]]--------
** libs.
I am concerned that the package isn't installed correctly especially that I get error message when running focei:
unhandled error message: EE:lsoda -- at t = 0 and step size _C(h) = 1.60517e-010, the
corrector convergence failed repeatedly or
with fabs(_C(h)) = hmin
@(lsoda.c:897)¢ƒÉ¼Îñ?šD§*

yet, I get the following successful installation note even after these error messages:
nlmixr run under nlme: Yes
nlmixr run under saem: Yes
nlmixr run under focei: Yes
---- Installation test finished! ----
Begin Session Info:
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats graphics grDevices utils datasets methods base

other attached packages:
[1] nlmixr_1.1.1-1 RxODE_0.9.1-3 reticulate_1.13

loaded via a namespace (and not attached):
[1] Rcpp_1.0.2 lattice_0.20-35 prettyunits_1.0.2
[4] ps_1.3.0 vpc_1.1.0 assertthat_0.2.1
[7] rprojroot_1.3-2 digest_0.6.20 ggforce_0.3.1
[10] R6_2.4.0 backports_1.1.4 sys_3.3
[13] ggplot2_3.2.1 pillar_1.4.2 rlang_0.4.0
[16] curl_4.0 lazyeval_0.2.2 rstudioapi_0.10
[19] callr_3.3.1 Matrix_1.2-14 mvnfast_0.2.5
[22] desc_1.2.0 devtools_2.1.0 dparser_0.1.8
[25] PreciseSums_0.3 polyclip_1.10-0 munsell_0.5.0
[28] compiler_3.5.0 xfun_0.9 pkgconfig_2.0.2
[31] pkgbuild_1.0.5 tidyselect_0.2.5 tibble_2.1.3
[34] crayon_1.3.4 dplyr_0.8.3 withr_2.1.2
[37] MASS_7.3-49 lbfgs_1.2.1 grid_3.5.0
[40] nlme_3.1-137 jsonlite_1.6 gtable_0.3.0
[43] huxtable_4.6.1 magrittr_1.5 units_0.6-4
[46] scales_1.0.0 cli_1.1.0 n1qn1_6.0.1-3
[49] farver_1.1.0 fs_1.3.1 RcppArmadillo_0.9.600.4.0
[52] remotes_2.1.0 rex_1.1.2 testthat_2.2.1
[55] brew_1.0-6 generics_0.0.2 lotri_0.1.1
[58] tools_3.5.0 glue_1.3.1 tweenr_1.0.1
[61] purrr_0.3.2 processx_3.4.1 pkgload_1.0.2
[64] parallel_3.5.0 yaml_2.2.0 colorspace_1.4-1
[67] sessioninfo_1.1.1 memoise_1.1.0 knitr_1.24
[70] usethis_1.5.1

**Comment by melmelie** [comment]
Update: it seems that install_github("asieira/SnakeCharmR") fixed the issue. SnakeCharmR is installed.
I am still getting an error message though:
unhandled error message: EE:lsoda -- at t = 0 and step size _C(h) = 1.60517e-010, the
         corrector convergence failed repeatedly or
         with fabs(_C(h)) = hmin
 @(lsoda.c:897)

**Comment by mattfidler** [comment]
Hi @melmelie 

We will be releasing a windows installer soon.  It is always the preferred way to setup nlmixr in Windows.

These are always located at:

https://github.com/nlmixrdevelopment/nlmixr/releases

We will have a nlmixr-1.1.1-2 release with an installer.

**Comment by mattfidler** [comment]
The test script needs to be updated since the theo_sd dataset was updated.

**Comment by melmelie** [comment]
Thanks so much @mattfidler! I will update the installation when the 1-2 release is available. I understood from you that my current installation is ok, will start testing then.

**Comment by mattfidler** [comment]
Yes.  The current installation is OK.

**Comment by mattfidler** [comment]
There is a new installer for windows
