### ISSUE TITLE
adding categorical covariate

### ISSUE THREAD

**Issue by WenYao-Mak** [nlmixrdevelopment/nlmixr#228]
Hi all, 

I am new to nlmixr and I am not sure about the appropriate way to fit a dichotomous covariate into a model. 

I have two covariates which I would like to include in the model: (1) Weight (WT) which I coded in a way similar to issue #55, and (2) A dichotomous covariate, "fasting" versus "fed" status (appear as a column "FOOD" in the dataset). 

The structural model is a 1-compartment, transit absorption model. I used "f" to estimate the relative bioavailability between the two feeding status, but at the same time, I also want to find out if the covariate "FOOD" will affect absorption parameter (at the moment, only "n"), and use "ncov" to estimate the effect. 

```{r, eval=TRUE, results=FALSE, warning=FALSE, message=FALSE, cache=F, echo=T}
library(nlmixr)
model.mod17.ode<- function(){
ini({
    tktr<-log(0.5) 
    tn<-log(0.5)
    tka <- log(0.3)
    tcl <- log(64)
    tv <- log(150)
    f1<-log(0.2)     
    ncov <- log(1.1)

    eta.cl~0.1
    eta.v~0.1
    eta.ka~0.1
    eta.n~0.1
 
    add.err<-0.02
    prop.err<-0.02
    
  })

model({
    ktr=exp(tktr) 
    n=exp(tn*(1+ncov*FOOD)+eta.n)                       
    ka=exp(tka+eta.ka)
    cl=exp(tcl+eta.cl)
    v=exp(tv+eta.v)
    f=(1+f1*FOOD)
    
    Dose=250          #all subjects received 250mg 
    lnfac=log(2.5066) + (n+0.5)*log(n) - n 
    cla=(cl*(WT/70)^0.75)/f  
    va=(v*(WT/70))/f          
    
     #begin RxODE    
    d/dt(depot)=exp(log(Dose)+log(ktr)+n*log(ktr*t)-ktr*t-lnfac)-ka*depot
    d/dt(center)=ka*depot - cla/va*center  
    cp=center/va
    cp~prop(prop.err)+add(add.err)
  })
}

fit.mod17.ode.saem <- nlmixr(model.mod17.ode, data=met.merged2, est="saem",
                             table=tableControl(cwres=TRUE, npde=TRUE))
```

However, nlmixr showed an error saying "Cannot run SAEM since some of the parameters are not mu-referenced (eta.n)". 

Is there any specific way to do mu-referencing in nlmixr? Or is there any specific way to fit dichotomous covariate into the model? Any help will be much appreciated, thank you.

**Comment by mattfidler** [comment]
Hi @WenYao-Mak 

The way to do mu-refereced covariates in nlmixr is to express them in the form:

```R
n=exp(tn+ncov*FOOD+eta.n)  
```

You can check the mu-referencing by calling `nlmixr(model)` before you begin it should show how nlmixr interprets the `mu`-referencing

**Comment by mattfidler** [comment]
Hopefully this was helpful.  If not feel free to re-open the issue.

**Comment by WenYao-Mak** [comment]
@mattfidler It works well and the model is running smoothly, thank you very much for your feedback!
