### ISSUE TITLE
CRAN version does not work with nlme estimation

### ISSUE THREAD

**Issue by IntiQuan** [nlmixrdevelopment/nlmixr#23]
Hi! 

Saw NLMIXR was now on CRAN. Tested the source version on Linux (R3.4.1) and Windows and the binary version on Windows in R3.3.3 and 3.4.1.

None of the versions worked on my machines and on my example. I had a self compiled version previously which worked nicely on all my NLMIXR examples ... bit weird ... especially as it had the same version number as the one on CRAN now. 

Example available here: http://web.intiquan.com/Stuff/NLMIXR/exampleNLMIXR.zip

Cheers,
Henning

**Comment by IntiQuan** [comment]
Had a closer look ... installed an older version of NLMIXR (early June) - worked on my 3.3.3 windows but not on 3.4.1 on windows. main difference was that on 3.4.1 I had a newer RxODE version. after updating RxODE on 3.3.3 to the newest CRAN version NLMIXR stopped working there as well.

Its really confusing ... it would be great to provide a step by step guide on how to install it so that it runs. The solution to package NLMIXR with RxODE and R together might not be the best solution for people who already have R installed on their systems.

The main thing that worries me is that in the CRAN version I cannot even run it on Linux anymore - which so far was fairly stable.

HELP!

**Comment by mattfidler** [comment]
You can use the windows installer

https://github.com/nlmixrdevelopment/nlmixr/releases
There should be step by step instructions on the Readme for
nlmixrdevelopment.

**Comment by mattfidler** [comment]
Did you get this figured out Henning?

**Comment by IntiQuan** [comment]
Hi Matt,

We are working on it. So far we have ensured that we have an installer for
IQRtools including NLMIXR for R 3.3.0 through to R 3.4.3 that is
reproducibly working and that we will need for our PAGE workshop. For
Windows it takes binaries from our server. And it still uses the NLMIXR and
RxODE versions from last July. But at least it can be installed and used.

When I get to it I will try to do the same for the new version of NLMIXR
but might need to wait a little to find time. Also need to see if I can
reproducibly generate the Windows binaries again for the old NLMIXR version
... it worked before as I generated them but inbetween it stopped working
... well thats R ... can be figured out. Expensive Open Source Software :)

Cheers,
Henning







________________________________________________________________________________



IntiQuan GmbH
Spalenring 150
4055 Basel, Switzerland
Web: www.intiquan.com
Tel: +41 76 603 28 06

Confidentiality Note: This message is intended solely for the designated
recipient(s). It may contain confidential or proprietary information and
may be subject to attorney-client privilege or other confidentiality
protections. If you are not a designated recipient you may not review, copy
or distribute this message. If you receive this in error, please notify the
sender by reply e-mail and delete this message. Thank you.

**Comment by mattfidler** [comment]
Thanks Henning.  We can catch up at page if you would like.

**Comment by IntiQuan** [comment]
Yes absolutely!

You planning to have the new Syntax included in the release version until
page?

Am 30.01.2018 11:57 vorm. schrieb "Matthew Fidler" <notifications@github.com

**Comment by mattfidler** [comment]
Yes, the new syntax is in the CRAN release right now.  Not every estimation method is fully supported yet, though.  Currently it supports `nlme` and `saem` with experimental `FOCEi`.

**Comment by mattfidler** [comment]
This was fixed on your end (I think).  Also there is a new cran release today (with minor bug fixes)
