### ISSUE TITLE
1.1.1-2 Installer version: APPCRASH Windows Server 2012

### ISSUE THREAD

**Issue by nholford** [nlmixrdevelopment/nlmixr#232]
A previously working R script (warfarin PKPD model) last successfully tested with nlmixr installer version 1.1.0-9 now fails with 1.1.1.-2.  The error causes a Windows Server 2012 APPCRASH when attempting to run nlmixr from the command line and from Rstudio (see image).
![image](https://user-images.githubusercontent.com/26332480/65013180-30363680-d96e-11e9-88b9-b82fe0f504a1.png).
The same R script works OK with Windows 10 and installer 1.1.1-2.

**Comment by mattfidler** [comment]
Hi Nick,

To be clear the version on CRAN seems to crash, but the version on the installer does not crash, is that correct?

Could be related to Issue #230

**Comment by nholford** [comment]
Hi Matt,

I am afraid I do not understand the difference between "CRAN" and "installer".  What I download is an installer exe from the nlmixr releases page.  Since version 1.1.0-8 the word "CRAN" appears. Sometimes it is followed by a version number. More recently the version number is missing on the "CRAN" line but appears on a separate line for 1.1.1.-2. Can you explain what "CRAN" means in this context?

When I tested the CRAN 1.1.0-9 installer it worked fine on Windows 10 and Windows Server 2012. The problems I have reported (#232, #233 ) are with CRAN 1.1.1-2.

To clarify my remarks above: the installer 1.1.1-2 works on Windows 10 for the line ("pk.fit.ka1t ...") on Windows Server 2012 that causes the APPCRASH but  on Windows 10  the script fails with the vpc_ui error reported in #233.

**Comment by mattfidler** [comment]
Hi Nick,

CRAN packages come from when you update `nlmixr` by using R, that is

```R
install.packages(c("RxODE", "nlmixr"))
```
The installer may or may not contain CRAN packages.

**Comment by nholford** [comment]
I find it confusing to mention CRAN for these installer releases simply because the release was submitted and accepted by CRAN. This also caused you confusion because athough I clearly identified I was using the installer and gave you the specific version numbers you mistakenly assumed I was updating my system by installing packages from CRAN.

The installer may contain packages from CRAN but the installer is built by you and its contents are known and tested by you. So as far as I am concerned the installer has nothing to do with CRAN. It is an executable distributed by the nlmixr project.

I have learned by trial and error (with days of wasted time) that attempting to install or modify nlmixr by installing packages from CRAN never works for me. I only ever use the installer versions which I obtain from the nlmixr release page https://github.com/nlmixrdevelopment/nlmixr/releases
