### ISSUE TITLE
1.1.1-3 release

### ISSUE THREAD

**Issue by mattfidler** [nlmixrdevelopment/nlmixr#234]
- [ ] Deprecate old functions and arguments with `.Deprecated()`.
- [ ] Update & rebuild pkgdown files.
- [ ] Check spelling in the package with spelling::spell_check_package(".").
- [ ] Check good practices noting camel case instead of snake case.
- [ ] Check with `wch/r-debug` `RDvalgrind`
- [ ] Check with `rch/r-debug` `RDvalgrind` `valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 ` 
- [ ] Check with `RDsan`
- [ ] Check with `RDcsan`
- [ ] Check with `RDstrictbarrier`
- [ ] Check with `RDthreadcheck`
- [ ] Build Windows installer
- [ ] Build docker image

**Comment by nholford** [comment]
Should RDsctrictbarrier  read RDstrictbarrier?

**Comment by mattfidler** [comment]
I think so.  I thought I copied it.
