### ISSUE TITLE
Objective function value for individuals IDs

### ISSUE THREAD

**Issue by DimitrisVoul** [nlmixrdevelopment/nlmixr#238]
Hello,

Is there a way to extract the value of the fitting objective function for each ID in the dataset in addition to the total objective function value?

**Comment by mattfidler** [comment]
Yes, if you have calcuated the `focei` objective function

``` r
options("huxtable.knitr_output_format"="md")
library(nlmixr)

one.compartment <- function() {
    ini({
        tka <- 0.45 # Log Ka
        tcl <- 1 # Log Cl
        tv <- 3.45    # Log V
        eta.ka ~ 0.6
        eta.cl ~ 0.3
        eta.v ~ 0.1
        add.sd <- 0.7
    })
    model({
        ka <- exp(tka + eta.ka)
        cl <- exp(tcl + eta.cl)
        v <- exp(tv + eta.v)
        d/dt(depot) = -ka * depot
        d/dt(center) = ka * depot - cl / v * center
        cp = center / v
        cp ~ add(add.sd)
    })
}

fit2 <- nlmixr(one.compartment, theo_sd, est="saem", control=list(print=0))
#> Compiling RxODE equations...done.
#> Calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====
#> Calculating residuals/tables
#> done.

fit2 <- fit2 %>% addCwres()
#> Calculating residuals/tables
#> done.

## etaObf
fit2$etaObf
```

<table style="width:69%;">
<colgroup>
<col width="11%" />
<col width="15%" />
<col width="15%" />
<col width="13%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th align="right"><strong>ID</strong></th>
<th><strong>eta.ka</strong></th>
<th><strong>eta.cl</strong></th>
<th><strong>eta.v</strong></th>
<th align="left"><strong>OBJI</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td>0.105</td>
<td>-0.487</td>
<td>-0.08</td>
<td align="left">12.6</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td>0.221</td>
<td>0.144</td>
<td>0.0206</td>
<td align="left">18</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td>0.368</td>
<td>0.0311</td>
<td>0.058</td>
<td align="left">0.37</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td>-0.277</td>
<td>-0.015</td>
<td>-0.00723</td>
<td align="left">11.1</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td>-0.0458</td>
<td>-0.155</td>
<td>-0.142</td>
<td align="left">29.3</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td>-0.382</td>
<td>0.367</td>
<td>0.203</td>
<td align="left">7.85</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td>-0.791</td>
<td>0.16</td>
<td>0.0466</td>
<td align="left">2.17</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td>-0.181</td>
<td>0.168</td>
<td>0.0958</td>
<td align="left">7.11</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td>1.42</td>
<td>0.0423</td>
<td>0.0121</td>
<td align="left">8.33</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td>-0.738</td>
<td>-0.391</td>
<td>-0.17</td>
<td align="left">7.69</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td>0.79</td>
<td>0.281</td>
<td>0.146</td>
<td align="left">3.48</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td>-0.527</td>
<td>-0.126</td>
<td>-0.198</td>
<td align="left">9.01</td>
</tr>
</tbody>
</table>

``` r

## obf
fit2$obf
#> [1] 117.0254
```

<sup>Created on 2019-09-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DimitrisVoul** [comment]
Great, thank you very much!
