### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by JSC67** [nlmixrdevelopment/nlmixr#24]
[installation_tests.txt](https://github.com/nlmixrdevelopment/nlmixr/files/1605347/installation_tests.txt)
[failure at step 7.txt](https://github.com/nlmixrdevelopment/nlmixr/files/1605348/failure.at.step.7.txt)

I was following along in "Installation on Windows" (https://github.com/nlmixrdevelopment/nlmixr) and things were basically working okay, although there were a few unit tests that failed (after a long time) in Step 6 (Install RxODE), last sub-step.  Then at Step 7, to actually install nlmixr, the other packages got installed fine, but nlmixr compilation failed.  I do not know why.

I pasted the output for Steps 1-6 in its own file (which is relatively big because of all the testing in Step 6), and the problematic Step 7 in its own file, both attached.

By the way, as for the Windows installer, it installs its own version of R and was invisible to the version of R I already had running just fine seen by RStudio, so I uninstalled all that prior to following the steps in "Installation on Windows".

**Comment by JSC67** [comment]
P.S.: I then downloaded the file nlmixr_0.9.0-1.tar.gz from CRAN and tried to install it, but this also failed.  I then went in to my already-installed RBuildTools and renamed the 32-bit stuff and tried again, still it had non-zero exit status.  File for the output is attached.
[failure_for_nlmixr_from_CRAN.txt](https://github.com/nlmixrdevelopment/nlmixr/files/1605312/failure_for_nlmixr_from_CRAN.txt)

**Comment by mattfidler** [comment]
For me, the version of R that is installed by nlmixr install is shown in the Rstudio session.  If you go to "Tools->Global Options" Then  changing the "R version".  Then, you can select which version of R that Rstudio runs:

![image](https://user-images.githubusercontent.com/514778/34594612-bd651410-f197-11e7-968f-62d1182d9677.png)

Typically could be compatability issues in the versions of packages installed from other sources.  To duplicate what is in the nlmixr installer in your own installation you can also run the following:

```R
library(devtools)
install_github("nlmixrdevelopment/RxODE",ref="v0.6-2")
install_github("nlmixrdevelopment/nlmixr",ref="v0.9.0-2")
```
However, the dependencies usually are the most recent on CRAN and could cause compatability issues.  I haven't found an easy way around this on vanilla R.  If you have administrator access, the MRAN installation freezes the CRAN packages and can be used to have some more stabilitiy in the packages you install.

In this case, there may be some drift in RxODE that causes nlmixr to not function appropriately.  I thought there wasn't an issue, but I may have to track it down.

**Comment by mattfidler** [comment]
Let me know if either solution works for you.

**Comment by JSC67** [comment]
Hi Matt,

It's been a few days since I've been able to return to this, but thank-you for your help.  I tried the second approach you offered, had to repeat the command 'install_github("nlmixrdevelopment/RxODE",ref="v0.6-2")' because some things needed to be installed first, and it seems to have worked insofar as installing nlmixr, at least mostly.  If you look carefully at the installation.txt file I attach, there are various complaints thrown back, so I think that something(s) is amiss and needs attention by someone.  I then proceeded to test the installation with the tutorial at https://cran.r-project.org/web/packages/nlmixr/vignettes/running_nlmixr.html and got very different results from those shown.  When I copied and pasted the line 'plot(fit)' I got warning messages saying that "object 'DV' not found" and got a plot with DV as the Y-axis and it was very different from what it should've been.  (This was all in a fresh R session, same as the installation commands.)  I attach the plot and the copied text of the output file.  Basically, the results from the SAEM algorithm were very, very different from what they should've been, not just the plot.

In the tutorial there are 4 lines beginning with "c:/Rtools/mingw_64/bin/gcc ".  How are these supposed to be entered or acted on?  I suspect that this is where things departed between my results and the tutorial's.  Pasting certainly didn't work.

Thanks again for your help.

James
[Rplot for plot(fit) line.pdf](https://github.com/nlmixrdevelopment/nlmixr/files/1619819/Rplot.for.plot.fit.line.pdf)

[installation.txt](https://github.com/nlmixrdevelopment/nlmixr/files/1619797/installation.txt)
[tutorial output.txt](https://github.com/nlmixrdevelopment/nlmixr/files/1619800/tutorial.output.txt)

**Comment by mattfidler** [comment]
For me, I also get a different result than what was written in the vignette.  I have observed in testing that platform differences cause different results on certain models, as discussed in Issue #25.  Still, the result you are getting seems reasonable as the plot for the fit seems resonable.   

We are exploring the effects of platform now.  I created the https://github.com/nlmixrdevelopment/PreciseSums package to try to address the platform inconsistencies by doing more accurate floating point math.  Currently this is not turned on because it increases the run-time speed.  However, you can easily turn it on by:

```R
fit <- nlmixr(uif, theo_md, est="saem",sum.prod=TRUE)
```

The platform issue may take some time to sort out and confirm.

**Comment by mattfidler** [comment]
I think this has been figured out, right?
