### ISSUE TITLE
Functional tests for nlmixr and question about one example, saem_theo1.R

### ISSUE THREAD

**Issue by bruc** [nlmixrdevelopment/nlmixr#25]
I'm working to install nlmixr for a client of mine, and I'm not sure if the installation was successful. Is there a set of functional tests for nlmixr that I could run to confirm the installation is correct? 

Also, I've tried running one of the examples, saem_theo1.R, and it appears to be broken. I get this error:

Error in numeric(neq) : invalid 'length' argument

in the statement, cfg   = configsaem(model, nmdat, inits)

This statement is problematic:

neq = attr(model$saem_mod, "neq")

I'm using the version on CRAN running on R-3.4.3 on Red Hat Linux 6.9.

Thank you.

**Comment by mattfidler** [comment]
Hi @bruc, we are working toward functional tests that will make sure that the package is installed correctly.  

One set of packages that we use is `RxODE`;  That functionality is better tested;  To test to see if that is setup correctly, you should run the command:
```
library(RxODE)
rxTest()
```
Note that these tests are quite extensive and you should excpect this to take some time to complete.

While we have not completed testing for everything for nlmixr, some tests can be run with:
```
library(nlmixr)
nlmixrValidate()
```
Some platform differences in numbers are known to exist.  When we are satisfied with the nlmixr testing library, we will put more detailed instructions in documentation.

**Comment by mattfidler** [comment]
Also note that these tests expect all of the suggested dependencies are included in your installation; Otherwise the test may fail.

**Comment by mattfidler** [comment]
As for your specific issue about running saem_theo1.R, it is hard to determine without being able to traceback the issue to a source.

**Comment by JSC67** [comment]
Hi Matt, do you get error-free results with library(RxODE); rxTest()?  I don't.  I had 64-bit R 3.4.2 installed in the default C:\Program Files\ location and decided to install version 3.4.3 in C:\R, but first I ran this test and saved the output using sink("R_output_from_rxTest") (and also one other command: getwd()).  (I think that the red warning texts sent to the screen were not captured by the file, however.)  After installing the latest 64-bit R to C:\R I did this again, but I forgot to sink it so I did it again, but the output seemed to be a bit different at the end, so then I did it again (file is "R_output_from_rxTest_3.4.3").  The problems are at the bottom of the long files.  I hope that this is helpful in your debugging.  (I also pasted some warning messages in red font into a file, and also output from sessionInfo().)  Please, could you let me know the answer to the question of whether you get error-free results when you run these tests?  I'd really like to get RxODE and especially nlmixr working.

Thanks,
James

[R_output_from_rxTest_3.4.3.txt](https://github.com/nlmixrdevelopment/nlmixr/files/1666587/R_output_from_rxTest_3.4.3.txt)
[R_output_from_rxTest.txt](https://github.com/nlmixrdevelopment/nlmixr/files/1666588/R_output_from_rxTest.txt)
[copied warnings in red font.txt](https://github.com/nlmixrdevelopment/nlmixr/files/1666589/copied.warnings.in.red.font.txt)
[output from sessionInfo after R 3.4.3 upgrade.txt](https://github.com/nlmixrdevelopment/nlmixr/files/1666624/output.from.sessionInfo.after.R.3.4.3.upgrade.txt)

**Comment by JSC67** [comment]
Just a follow-up after I've cleaned up my PATH variable as so (which, strangely to me, is different from the output using RStudio for the command Sys.getenv('PATH'), also below):

C:\RTools\3.4\bin;C:\RTools\3.4\mingw_64\bin;C:\RTools\3.4\mingw_32\bin;C:\RBuildTools\3.4\bin;C:\RBuildTools\3.4\mingw_64\bin;C:\RBuildTools\3.4\mingw_32\bin;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Pharsight\MPICH2\bin;C:\Program Files (x86)\Pharsight\MPICH2\lib;C:\PHSTMinGW\bin;C:\Program Files (x86)\Pharsight\Phoenix\application\lib\NLME\Executables\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Broadcom\Broadcom 802.11\Driver;%USERPROFILE%\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\MATLAB\R2017a\bin;C:\Program Files (x86)\Skype\Phone

The output from RStudio is thus—I'm not sure why Anaconda now comes first:

> Sys.getenv('PATH')
[1] "C:\\ProgramData\\Anaconda3;C:\\RTools\\3.4\\bin;C:\\RTools\\3.4\\mingw_64\\bin;C:\\RTools\\3.4\\mingw_64\\opt\\bin;C:\\R\\R-3.4.3\\bin\\x64;C:\\RTools\\3.4\\mingw_32\\bin;C:\\RBuildTools\\3.4\\bin;C:\\RBuildTools\\3.4\\mingw_64\\bin;C:\\RBuildTools\\3.4\\mingw_32\\bin;C:\\ProgramData\\Anaconda3\\Library\\bin;C:\\ProgramData\\Anaconda3\\Scripts;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Pharsight\\MPICH2\\bin;C:\\Program Files (x86)\\Pharsight\\MPICH2\\lib;C:\\PHSTMinGW\\bin;C:\\Windows\\System32;C:\\Windows;C:\\Windows\\System32\\wbem;C:\\Program Files\\Broadcom\\Broadcom 802.11\\Driver;C:\\Program Files\\MATLAB\\R2017a\\bin;C:\\Program Files (x86)\\Skype\\Phone"

In any case the contents I got from sink('filename') are very different from what went to the terminal and very different from the earlier uploaded files.  I hope this is helpful.

[R rxTest output after correcting RTools v3.txt](https://github.com/nlmixrdevelopment/nlmixr/files/1668241/R.rxTest.output.after.correcting.RTools.v3.txt)

**Comment by JSC67** [comment]
Hi Matt,

I think that nlmixr is working, but the numbers I get are definitely different from those in the "Running PK models with nlmixr" tutorial at https://cran.r-project.org/web/packages/nlmixr/vignettes/running_nlmixr.html.  I think that the issue with the tests was with my PATH variable.  I'd like to say that all is well, but there are two issues I have with the tutorial, but I think that those are probably far enough removed from the topic here that it would merit making another issue request, which I'll do now.

**Comment by mattfidler** [comment]
Great! I'm glad to hear this got setup for you.
