### ISSUE TITLE
Same error for different runs

### ISSUE THREAD

**Issue by DimitrisVoul** [nlmixrdevelopment/nlmixr#259]
Hello,

I am encountering a peculiar situation. this goes back to a previous issue I raised about having trying to calculate the effect of multiple covariates. I was interested in the covariates whose calculated value had confidence interval that do not cross zero.

The issues was that with different initial estimates different covariates and different number of covariates were quantified, i.e. had a confidence interval that didn't cross zero. 

So I performed multiple runs with varying random seed and FOCEi. But in all of these I get the same estimation of proportional error to a 3 decimal place accuracy. the objective function is different, the BSV is different but the error remains the same. Is there a reason for that?

**Comment by mattfidler** [comment]
Hi @DimitrisVoul 

As far as I can tell, this is a simulated dataset.  To me this means that the individual effects are characterized in the same manner (possibly by different effects) and the remaining unexplained errors are described in the same way since it was simulated in the same way.

What do you think?

**Comment by DimitrisVoul** [comment]
Sorry there might have been some misunderstanding. The dataset is real experimental data of tumour growth. The multiple runs are simply multiple attempts to fit the data with the same model just different initial estimates for the effect of some covariates.

So I understand how part of the variability can be explained by different effects in each run but the same unexplained error value to 3 significant digits seems a bit strange.

**Comment by mattfidler** [comment]
It is probably the same explanation with a real and simulated data-set.

How different are the objective functions, significantly different?

**Comment by DimitrisVoul** [comment]
they vary from -19700 to -19900 which taking into account the chi-squared distributions is quite significant

**Comment by mattfidler** [comment]
Hm.  What about the `eta` values.  Are they quite different?

The objective function is a function of the random, individual values, and random effect values.

**Comment by DimitrisVoul** [comment]
haven't saves the etas but there are only to parameters with random effects. One of the is the initial condition which is almost the same in every run and the other some growth rate. I can see that the BSV for the growth rate can change between 36%-43% which I guess depends to some extend on the quantification of other effects

**Comment by mattfidler** [comment]
Since the FOCEi objective function is conditioned on the `eta`s that is part of the picture for the objective function.  For 2 objective functions to be the same the have to have the same `eta`s as well as estimated population and random parameters.  One explanation is the ETAs are fit better with these effects even though the random effect doesn't change very much.

**Comment by mattfidler** [comment]
In short, I'm unsure it is really a `nlmixr` error but rather an artifact of the data and model.

**Comment by DimitrisVoul** [comment]
So what would that mean for the calculation of these effects? Does it mean that it make no different to have them on not have them in the model since the error is the same or the difference in the objective function can justify the use of these effects?

**Comment by mattfidler** [comment]
In my estimation, objective function is an approximation, you can only really answer this question by examining the vpcs.

**Comment by mattfidler** [comment]
The `vpc`s use the modeled distributions exactly to create its diagnostic plot.

**Comment by DimitrisVoul** [comment]
I see, thank you for your help.

**Comment by mattfidler** [comment]
No problem. Let me know if it makes sense after looking at the `vpc`s.
