### ISSUE TITLE
SymPy Installation Issues

### ISSUE THREAD

**Issue by dionnajacobson** [nlmixrdevelopment/nlmixr#26]
I installed and updated all recommended packages from the installation page on a MacOS Sierra. When attempting to run nlmixr examples, there is an issue loading sympy via snakecharmR . I keep getting the following error message:

Error in SnakeCharmR::py.exec(...) : Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named sympy

/usr/bin/python: No module named pip
Error in SnakeCharmR::py.exec(...) : Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named sympy

I'm assuming the error has to do with the Path snakecharmR uses when retrieving sympy. I installed pip, SnakeCharmR, and sympy  successfully, but I can't figure out why SnakeCharmR isn't able to load sympy. Any suggestions on how to fix this issue/ update the path?

**Comment by mattfidler** [comment]
Hi @dionnajacobson thank you for your report.

To be clear, I have never used this on a mac, but I think you are right it is likely a path issue.  

My guess is tha you may need to setup SnakeCharmR to use the right version of Python.  

As I understand the process, this can de done as follows:

```R
Sys.setenv(SNAKECHARMR_PYTHON_VERSION="/path/to/python/with/sympy/installed")
devtools::install_github("nlmixrdevelopment/SnakeCharmR")
```

You may also have to adjust the following python variables to match the version with sympy installed:

Environmental Variable |  Correct value
--------------------------|---------------------------
`PYTHON_EXE`  | Path where the python with sympy is installed
`PYTHONHOME` | Path where the python with sympy is installed
`PYTHON_INCLUDE` | Path where the python libaries are installed; In windows this is `PYTHONHOME\include`
`PYTHON_LIB` | Path where python libraries are installed; In wondows this is `PYTHONHOME\libs`
`PYTHONPATH` | Path where python searches.  In windows this is a path-style varible including `PYTHONHOME\DLLs`, `PYTHONHOME\Lib` and `PYTHONHOME\Lib\site-packages`.  
`PYTHONSTARTUP` | In windows, this value is unset if present

I believe you could also unset some of these variables and python can figure them out.  Please be warned if these variables are not setup correctly a call to python will abort python.  The python abort does not respect R's way of doing things and will also abort/crash R.  

To test without running a model you may wish to try

```R
library(SnakeCharmR)
```
If it doesn't crash R, then python is likely setup correctly.  

After that point you can then type 
```R
library(RxODE)
rxSymPyVersion()
```
To make sure sympy is installed.  It will show the version of sympy that you are using..

**Comment by dionnajacobson** [comment]
Hi @mattfidler ,

Thanks for your response - the issue was definitely path related. I ended up deleting all versions of python not supplied by the Mac Operating system and now SymPy is functioning normally! I think changing the path like you suggested above would work as well.

**Comment by mattfidler** [comment]
Thanks for your feedback.  Paths can be frustrating.
