### ISSUE TITLE
Can nlmixr handle duration of infusion estimation (D1)?

### ISSUE THREAD

**Issue by nsk64** [nlmixrdevelopment/nlmixr#262]
Hi all,
I would like to estimate a model with a D1 parameter (nonmem wording) using linCmt() and I would like to know if it's allowed with nlmixr.
Best regards
Nicolas

**Comment by mattfidler** [comment]
Yes.

Currently duration with etas are supported with `saem`.  The key is `dur(cmt)=`

This is explained in the RxODE vignette [here](https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-event-types.html)

It also supports a `dur` column as well as a `rate` column.

**Comment by mattfidler** [comment]
With `linCmt()`  it has to be `dur(central)`

**Comment by nsk64** [comment]
Hi Matthew,


with linCmt() I have the following error message:


RxODE Model Syntax Error:
================================================================================
:001: 'dur' cannot be a variable in an RxODE model:
          dur = THETA[1]
          ^~~


My code is below:


one.cmt.add <- function() {
  ini({
    dur <- 0.45  ; label("duration")
    tcl <- log(5); label("log Cl")
    tv <- log(20); label("log V")
    eta.dur ~ fixed(0.6)
    eta.cl ~ 0.3
    eta.v  ~ 0.1
    add.err <- 0.7
    prop.err <- .1
  })
  model({
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    dur(central) <- exp(dur + eta.dur)
    linCmt() ~ add(add.err) + prop(prop.err)
  })
}
nlmixr(one.cmt.add)


I have never used RxODE...


In my data RATE is set to -2 when AMT>0.


Many thanks

Nicolas



________________________________
De : Matthew Fidler <notifications@github.com>
Envoyé : mercredi 11 décembre 2019 17:23
À : nlmixrdevelopment/nlmixr
Cc : SIMON Nicolas; Author
Objet : Re: [nlmixrdevelopment/nlmixr] Can nlmixr handle duration of infusion estimation (D1)? (#262)


With linCmt() it has to be dur(central)

-

**Comment by mattfidler** [comment]
`dur` cannot be a variable in RxODE or `nlmixr` because it is a reserved data item.  

You can change your parameter from `dur` to `tdur` to have a different (supported) name.

If you think the error message could be more informative, let me know.

**Comment by mattfidler** [comment]
Here is what I get after changing the infusion estimation

``` r
library(nlmixr)
one.cmt.add <- function() {
  ini({
    tdur <- c(0, 0.45)  ; label("duration")
    tcl <- log(5); label("log Cl")
    tv <- log(20); label("log V")
    eta.dur ~ fixed(0.6)
    eta.cl ~ 0.3
    eta.v  ~ 0.1
    add.err <- 0.7
    prop.err <- .1
  })
  model({
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    dur(central) <- exp(tdur + eta.dur)
    linCmt() ~ add(add.err) + prop(prop.err)
  })
}
nlmixr(one.cmt.add)
#> ▂▂ RxODE-based 1-compartment model ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
#> ── Initialization: ───────────────────────────────────────────────────────────── 
#> Fixed Effects ($theta): 
#>     tdur      tcl       tv 
#> 0.450000 1.609438 2.995732 
#> 
#> Omega ($omega): 
#>         eta.dur eta.cl eta.v
#> eta.dur     0.6    0.0   0.0
#> eta.cl      0.0    0.3   0.0
#> eta.v       0.0    0.0   0.1
#> ── μ-referencing ($muRefTable): ──────────────────────────────────────────────── 
#> ┌─────────┬─────────┐
#> │ theta   │ eta     │
#> ├─────────┼─────────┤
#> │ tdur    │ eta.dur │
#> ├─────────┼─────────┤
#> │ tcl     │ eta.cl  │
#> ├─────────┼─────────┤
#> │ tv      │ eta.v   │
#> └─────────┴─────────┘
#> ── Model: ────────────────────────────────────────────────────────────────────── 
#>     cl <- exp(tcl + eta.cl)
#>     v <- exp(tv + eta.v)
#>     dur(central) <- exp(tdur + eta.dur)
#>     linCmt() ~ add(add.err) + prop(prop.err) 
#> ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
```

<sup>Created on 2019-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by nsk64** [comment]
Many thanks.
The thing is that I didn’t find on the website that dur was a reserved data item.

As an example I tried to fit a previous analysis, I did not succeed to find the same results but I still work on it and I would not bother you.

Thanks
Nicolas


Le 11 déc. 2019 à 20:16, Matthew Fidler <notifications@github.com> a écrit :

﻿

dur cannot be a variable in RxODE or nlmixr because it is a reserved data item.

You can change your parameter from dur to tdur to have a different (supported) name.

If you think the error message could be more informative, let me know.

**Comment by mattfidler** [comment]
It will likely not reproduce NONMEM since the optimization algorithm is different, though the objective function is usually identical

**Comment by mattfidler** [comment]
Let me know if you have any other questions.
