### ISSUE TITLE
Baseline value

### ISSUE THREAD

**Issue by nsk64** [nlmixrdevelopment/nlmixr#263]
Is it possible to add a baseline (from the dataset) value to add()?
I tried different options but none was successful.

In the ini block
.../...
add.err <- .1 + BSL
.../...
with in the model block
.../...
linCmt() ~ prop(prop.err) + add(add.err)
OR
directly (without anything in the ini block):
linCmt() ~ prop(prop.err) + add(add.err) + BSL

**Comment by mattfidler** [comment]
Hi @nsk64 

It is possible;  Currently for the model language:

- You may only have covariates specified in the `model({})` block (so adding to the `ini({})` block won't work)
- You can only specify an error in the model block after the `~` block, therefore `linCmt() ~ prop(prop.err) + add(add.err) +BSL` does't work

To make it work you specify the following in the `model` block that is:

```r
prd = linCmt() - BL
prd ~ add(add.err)
```
I don't know why you want to subtract baseline (it is the equivalent code to what you had);  You can also add baseline values:

```r
prd = linCmt() + BL
prd ~ add(add.err)
```

Below is a silly example.  

``` r
library(nlmixr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

theo_sd %>%
    mutate(BL=ID * 0.01) ->
    d

one.cmt <- function() {
    ini({
        ## You may label each parameter with a comment
        tka <- 0.45 # Log Ka
        tcl <- 1 # Log Cl
        ## This works with interactive models
        ## You may also label the preceding line with label("label text")
        tv <- 3.45; label("log V")
        ## the label("Label name") works with all models
        eta.ka ~ 0.6
        eta.cl ~ 0.3
        eta.v ~ 0.1
        add.sd <- 0.7
    })
    model({
        ka <- exp(tka + eta.ka)
        cl <- exp(tcl + eta.cl)
        v <- exp(tv + eta.v)
        prd <- linCmt() + BL
        prd ~ add(add.sd)
    })
}


fit <- nlmixr(one.cmt, d, est="focei", control=list(print=0))
#> Needed Covariates:
#> [1] "BL"
#> Calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00 
#> done
#> Calculating residuals/tables
#> done.
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =
#> FALSE, : Initial ETAs were nudged; (Can control by foceiControl(etaNudge=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod
#> = FALSE, : ETAs were reset to zero during optimization; (Can control by
#> foceiControl(resetEtaP=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =
#> FALSE, : Gradient problems with initial estimate and covariance; see $scaleInfo
print(fit)
#> ── nlmixr FOCEi (outer: nlminb) fit ──────────────────────────────────────────── 
#>           OBJF     AIC      BIC Log-likelihood Condition Number
#> FOCEi 117.9962 374.596 394.7756       -180.298         80.55448
#> 
#> ── Time (sec; $time): ────────────────────────────────────────────────────────── 
#>            setup optimize covariance table    other
#> elapsed 0.785153  0.29502   0.295021 0.101 1.086806
#> 
#> ── Population Parameters ($parFixed or $parFixedDf): ─────────────────────────── 
#>        Parameter  Est.     SE %RSE Back-transformed(95%CI) BSV(CV%) Shrink(SD)%
#> tka       Log Ka 0.455  0.192 42.3        1.58 (1.08, 2.3)     70.6      1.76% 
#> tcl       Log Cl  1.03  0.074 7.17       2.81 (2.43, 3.25)     27.4      3.82% 
#> tv         log V  3.46 0.0367 1.06       31.9 (29.7, 34.3)     13.9      10.9% 
#> add.sd           0.698                               0.698                      
#> 
#>   Covariance Type ($covMethod): r,s
#>   Some strong fixed parameter correlations exist ($cor) :
#>     cor:tcl,tka  cor:tv,tka  cor:tv,tcl 
#>          0.129       0.432       0.704   
#> 
#>   No correlations in between subject variability (BSV) matrix
#>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs) 
#>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink 
#>   Minimization message ($message):  
#>     relative convergence (4) 
#> 
#> ── Fit Data (object is a modified tibble): ───────────────────────────────────── 
#> # A tibble: 132 x 24
#>   ID     TIME    DV  EVID    BL  PRED    RES   WRES IPRED   IRES  IWRES CPRED
#>   <fct> <dbl> <dbl> <int> <dbl> <dbl>  <dbl>  <dbl> <dbl>  <dbl>  <dbl> <dbl>
#> 1 1     0      0.74     0  0.01  0.01  0.73   0.385  0.01  0.73   1.05   0.01
#> 2 1     0.25   2.84     0  0.01  3.23 -0.394 -0.208  3.85 -1.01  -1.45   3.18
#> 3 1     0.570  6.57     0  0.01  5.78  0.790  0.416  6.78 -0.214 -0.306  5.72
#> # … with 129 more rows, and 12 more variables: CRES <dbl>, CWRES <dbl>,
#> #   eta.ka <dbl>, eta.cl <dbl>, eta.v <dbl>, rx1c <dbl>, ka <dbl>, cl <dbl>,
#> #   v <dbl>, prd <dbl>, depot <dbl>, central <dbl>
```

<sup>Created on 2019-12-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by nsk64** [comment]
The Baseline corresponds to a remaining constant endogenous synthesis.
So I wanted to add it as a residual error.

The compound administered is a supplementation.



De : Matthew Fidler [mailto:notifications@github.com]
Envoyé : lundi 16 décembre 2019 15:32
À : nlmixrdevelopment/nlmixr <nlmixr@noreply.github.com>
Cc : SIMON Nicolas <Nicolas.SIMON@ap-hm.fr>; Mention <mention@noreply.github.com>
Objet : Re: [nlmixrdevelopment/nlmixr] Baseline value (#263)


Hi @nsk64<https://urldefense.com/v3/__https:/github.com/nsk64__;!!JQ5agg!PH_ITxR_oFCaANY9xYU7Um3XWmh7NN4mv5LSXcya_KX6LjytbukmuSmpwbnglqoLRp1h$>

It is possible; Currently for the model language:

  *   You may only have covariates specified in the model({}) block (so adding to the ini({}) block won't work)
  *   You can only specify an error in the model block after the ~ block, therefore linCmt() ~ prop(prop.err) + add(add.err) +BSL does't work

To make it work you specify the following in the model block that is:

prd = linCmt() - BL

prd ~ add(add.err)

I don't know why you want to subtract baseline (it is the equivalent code to what you had); You can also add baseline values:

prd = linCmt() + BL

prd ~ add(add.err)

Below is a silly example.

library(nlmixr)

library(dplyr)

#>

#> Attaching package: 'dplyr'

#> The following objects are masked from 'package:stats':

#>

#>     filter, lag

#> The following objects are masked from 'package:base':

#>

#>     intersect, setdiff, setequal, union



theo_sd %>%

    mutate(BL=ID * 0.01) ->

    d



one.cmt <- function() {

    ini({

        ## You may label each parameter with a comment

        tka <- 0.45 # Log Ka

        tcl <- 1 # Log Cl

        ## This works with interactive models

        ## You may also label the preceding line with label("label text")

        tv <- 3.45; label("log V")

        ## the label("Label name") works with all models

        eta.ka ~ 0.6

        eta.cl ~ 0.3

        eta.v ~ 0.1

        add.sd <- 0.7

    })

    model({

        ka <- exp(tka + eta.ka)

        cl <- exp(tcl + eta.cl)

        v <- exp(tv + eta.v)

        prd <- linCmt() + BL

        prd ~ add(add.sd)

    })

}





fit <- nlmixr(one.cmt, d, est="focei", control=list(print=0))

#> Needed Covariates:

#> [1] "BL"

#> Calculating covariance matrix

#> [====|====|====|====|====|====|====|====|====|====] 0:00:00

#> done

#> Calculating residuals/tables

#> done.

#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =

#> FALSE, : Initial ETAs were nudged; (Can control by foceiControl(etaNudge=.))

#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod

#> = FALSE, : ETAs were reset to zero during optimization; (Can control by

#> foceiControl(resetEtaP=.))

#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =

#> FALSE, : Gradient problems with initial estimate and covariance; see $scaleInfo

print(fit)

#> ── nlmixr FOCEi (outer: nlminb) fit ────────────────────────────────────────────

#>           OBJF     AIC      BIC Log-likelihood Condition Number

#> FOCEi 117.9962 374.596 394.7756       -180.298         80.55448

#>

#> ── Time (sec; $time): ──────────────────────────────────────────────────────────

#>            setup optimize covariance table    other

#> elapsed 0.785153  0.29502   0.295021 0.101 1.086806

#>

#> ── Population Parameters ($parFixed or $parFixedDf): ───────────────────────────

#>        Parameter  Est.     SE %RSE Back-transformed(95%CI) BSV(CV%) Shrink(SD)%

#> tka       Log Ka 0.455  0.192 42.3        1.58 (1.08, 2.3)     70.6      1.76%

#> tcl       Log Cl  1.03  0.074 7.17       2.81 (2.43, 3.25)     27.4      3.82%

#> tv         log V  3.46 0.0367 1.06       31.9 (29.7, 34.3)     13.9      10.9%

#> add.sd           0.698                               0.698

#>

#>   Covariance Type ($covMethod): r,s

#>   Some strong fixed parameter correlations exist ($cor) :

#>     cor:tcl,tka  cor:tv,tka  cor:tv,tcl

#>          0.129       0.432       0.704

#>

#>   No correlations in between subject variability (BSV) matrix

#>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs)

#>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink

#>   Minimization message ($message):

#>     relative convergence (4)

#>

#> ── Fit Data (object is a modified tibble): ─────────────────────────────────────

#> # A tibble: 132 x 24

#>   ID     TIME    DV  EVID    BL  PRED    RES   WRES IPRED   IRES  IWRES CPRED

#>   <fct> <dbl> <dbl> <int> <dbl> <dbl>  <dbl>  <dbl> <dbl>  <dbl>  <dbl> <dbl>

#> 1 1     0      0.74     0  0.01  0.01  0.73   0.385  0.01  0.73   1.05   0.01

#> 2 1     0.25   2.84     0  0.01  3.23 -0.394 -0.208  3.85 -1.01  -1.45   3.18

#> 3 1     0.570  6.57     0  0.01  5.78  0.790  0.416  6.78 -0.214 -0.306  5.72

#> # … with 129 more rows, and 12 more variables: CRES <dbl>, CWRES <dbl>,

#> #   eta.ka <dbl>, eta.cl <dbl>, eta.v <dbl>, rx1c <dbl>, ka <dbl>, cl <dbl>,

#> #   v <dbl>, prd <dbl>, depot <dbl>, central <dbl>

Created on 2019-12-16 by the reprex package<https://urldefense.com/v3/__https:/reprex.tidyverse.org__;!!JQ5agg!PH_ITxR_oFCaANY9xYU7Um3XWmh7NN4mv5LSXcya_KX6LjytbukmuSmpwbnglr89cKCG$> (v0.3.0)

**Comment by mattfidler** [comment]
> The Baseline corresponds to a remaining constant endogenous synthesis.
> So I wanted to add it as a residual error.
>
> The compound administered is a supplementation.

So does that mean it is a multiple endpoint?  That is you wish to model an error on the endogenous sythensis which is an additive error?

If so you could do something like this:

```R
BL ~ add.err(add.err.BL)
CP ~ linCmt()
CP ~ add(add.err.CP) + prop(prop.err.CP)
```

You will have to rearrange your data to be in a column that has BL in the DV column and `CP` in your `DV` column differentiated by `DVID` or `CMT`.  For an example see:

https://nlmixrdevelopment.github.io/nlmixr/articles/multiple-endpoints.html

**Comment by mattfidler** [comment]
If not, I'm afarid I'm not sure what you are trying to do.

**Comment by nsk64** [comment]
The patients have a residual constant synthesis of a hormone leading to a flat concentration. Meaning that without any treatment the concentrations are not below the limit of quantification but with a constant value.
We gave them a supplementation with the same molecule.
In my model I should not ignore the residual flat concentrations coming from the endogenous synthesis.


De : Matthew Fidler [mailto:notifications@github.com]
Envoyé : lundi 16 décembre 2019 19:22
À : nlmixrdevelopment/nlmixr <nlmixr@noreply.github.com>
Cc : SIMON Nicolas <Nicolas.SIMON@ap-hm.fr>; Mention <mention@noreply.github.com>
Objet : Re: [nlmixrdevelopment/nlmixr] Baseline value (#263)


If not, I'm afarid I'm not sure what you are trying to do.

**Comment by mattfidler** [comment]
Ok, I understand now.  I think that subtracting off the value would be OK and would make the residuals ignore the value;  That is:

``` r
library(nlmixr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

theo_sd %>%
    mutate(BL=ID * 0.01) ->
    d

one.cmt <- function() {
    ini({
        ## You may label each parameter with a comment
        tka <- 0.45 # Log Ka
        tcl <- 1 # Log Cl
        ## This works with interactive models
        ## You may also label the preceding line with label("label text")
        tv <- 3.45; label("log V")
        ## the label("Label name") works with all models
        eta.ka ~ 0.6
        eta.cl ~ 0.3
        eta.v ~ 0.1
        add.sd <- 0.7
    })
    model({
        ka <- exp(tka + eta.ka)
        cl <- exp(tcl + eta.cl)
        v <- exp(tv + eta.v)
        prd <- linCmt() - BL
        prd ~ add(add.sd)
    })
}


fit <- nlmixr(one.cmt, d, est="focei", control=list(print=0))
#> Using sympy via reticulate
#> Calculate ETA-based prediction and error derivatives:
#> Calculate Jacobian
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> Calculate Sensitivities
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> Load into sympy...
#> done
#> Calculate ∂(f)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> Calculate ∂(R²)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> Freeing Python/SymPy memory...
#> done
#> ################################################################################
#> Optimizing expressions in Predictions/EBE model...done
#> Compiling Predictions/EBE model...done
#> Optimizing expressions in Inner model...done
#> Compiling Inner model...done
#> The model-based sensitivities have been calculated.
#> Needed Covariates:
#> [1] "BL"
#> Calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00 
#> done
#> Calculating residuals/tables
#> done.
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =
#> FALSE, : Initial ETAs were nudged; (Can control by foceiControl(etaNudge=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod
#> = FALSE, : ETAs were reset to zero during optimization; (Can control by
#> foceiControl(resetEtaP=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =
#> FALSE, : Gradient problems with initial estimate and covariance; see $scaleInfo
print(fit)
#> ── nlmixr FOCEi (outer: nlminb) fit ──────────────────────────────────────────── 
#>           OBJF      AIC      BIC Log-likelihood Condition Number
#> FOCEi 116.0002 372.5999 392.7795         -179.3         64.46069
#> 
#> ── Time (sec; $time): ────────────────────────────────────────────────────────── 
#>            setup optimize covariance table    other
#> elapsed 12.55095  0.30391   0.303912 0.102 1.449231
#> 
#> ── Population Parameters ($parFixed or $parFixedDf): ─────────────────────────── 
#>        Parameter  Est.     SE %RSE Back-transformed(95%CI) BSV(CV%) Shrink(SD)%
#> tka       Log Ka 0.483  0.192 39.8       1.62 (1.11, 2.36)     70.5      2.11% 
#> tcl       Log Cl 0.992  0.083 8.37        2.7 (2.29, 3.17)     26.3      4.57% 
#> tv         log V  3.46 0.0431 1.25       31.7 (29.1, 34.5)     14.0      10.1% 
#> add.sd           0.691                               0.691                      
#> 
#>   Covariance Type ($covMethod): r,s
#>   Some strong fixed parameter correlations exist ($cor) :
#>     cor:tcl,tka  cor:tv,tka  cor:tv,tcl 
#>          0.162       0.397       0.750   
#> 
#>   No correlations in between subject variability (BSV) matrix
#>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs) 
#>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink 
#>   Minimization message ($message):  
#>     false convergence (8) 
#>   In an ODE system, false convergence may mean "useless" evaluations were performed.
#>   See https://tinyurl.com/yyrrwkce
#>   It could also mean the convergence is poor, check results before accepting fit
#>   You may also try a good derivative free optimization:
#>     nlmixr(...,control=list(outerOpt="bobyqa"))
#> 
#> ── Fit Data (object is a modified tibble): ───────────────────────────────────── 
#> # A tibble: 132 x 24
#>   ID     TIME    DV  EVID    BL  PRED    RES   WRES IPRED   IRES  IWRES CPRED
#>   <fct> <dbl> <dbl> <int> <dbl> <dbl>  <dbl>  <dbl> <dbl>  <dbl>  <dbl> <dbl>
#> 1 1     0      0.74     0  0.01 -0.01  0.75   0.396 -0.01  0.75   1.09  -0.01
#> 2 1     0.25   2.84     0  0.01  3.31 -0.473 -0.250  3.84 -1.00  -1.45   3.28
#> 3 1     0.570  6.57     0  0.01  5.91  0.663  0.350  6.79 -0.218 -0.315  5.86
#> # … with 129 more rows, and 12 more variables: CRES <dbl>, CWRES <dbl>,
#> #   eta.ka <dbl>, eta.cl <dbl>, eta.v <dbl>, rx1c <dbl>, ka <dbl>, cl <dbl>,
#> #   v <dbl>, prd <dbl>, depot <dbl>, central <dbl>
```

<sup>Created on 2019-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
