### ISSUE TITLE
Unclear Error message with pmx_nlmixr

### ISSUE THREAD

**Issue by nsk64** [nlmixrdevelopment/nlmixr#264]
Hi
the command 
ctr <- pmx_nlmixr(fit_ka_saem)
gave:
compiling model...done
Compiling VPC model...done
done (1.28 sec)
Error in pmx_nlmixr(fit_ka_saem) :+1:  
cannot merge nlmixr fit with observation dataset

Any suggestion explaining why the merge could not be done will be helpful.

Best regards
Nicolas

**Comment by mattfidler** [comment]
Where does `pmx_nlmixr` come from?  It isn't form `nlmixr` so I can't explain it.  

You can find out where it comes from by typing `pmx_nlmixr` on the command line.  

For instance with `nlmixr` you get:

```R
> nlmixr
function (object, data, est = NULL, control = list(), table = tableControl(), 
    ..., save = NULL, envir = parent.frame()) 
{
    assignInMyNamespace(".nlmixrTime", proc.time())
    RxODE::.setWarnIdSort(FALSE)
    on.exit(RxODE::.setWarnIdSort(TRUE))
    force(est)
    UseMethod("nlmixr")
}
<bytecode: 0x55fd7f0b5838>
<environment: namespace:nlmixr>
```

You can see what package it comes from by looking at the last line`namespace:nlmixr`

My guess is `shinyMixR` but I'm unsure since I don't have `shinyMixR` installed on this computer right now.

**Comment by mattfidler** [comment]
Please open the issue in the repository that `pmx_nlmixr` came from so you can get help.

**Comment by mattfidler** [comment]
Please let me know where it comes from so I can know where to send people in the future

**Comment by nsk64** [comment]
It comes from
library<https://rdrr.io/r/base/library.html>(ggPMX)


https://nlmixrdevelopment.github.io/nlmixr/articles/xgxr-nlmixr-ggpmx.html



De : Matthew Fidler [mailto:notifications@github.com]
Envoyé : lundi 16 décembre 2019 15:38
À : nlmixrdevelopment/nlmixr <nlmixr@noreply.github.com>
Cc : SIMON Nicolas <Nicolas.SIMON@ap-hm.fr>; Author <author@noreply.github.com>
Objet : Re: [nlmixrdevelopment/nlmixr] Unclear Error message with pmx_nlmixr (#264)


Please let me know where it comes from so I can know where to send people in the future

**Comment by mattfidler** [comment]
Please file a bug here:

https://github.com/ggPMXdevelopment/ggPMX
