### ISSUE TITLE
nlmixr log fitting

### ISSUE THREAD

**Issue by DimitrisVoul** [nlmixrdevelopment/nlmixr#268]
Hello,

Are there any vignettes for fitting on the log scale using nlmixr? I have a proportional model that will change to an additive and a column in the data will be added for the log transform of the volume but what else needs to change?

Does the ODE part stay the same and just return the log(V)? i.e. d/dt(V)=f(V) or I need to transform the ODE d/dt(e^y)=f(e^y) where e^y=V and return y?

I imagine that would give the same result

**Comment by mattfidler** [comment]
Hi @DimitrisVoul,

There is a [lognormal section of the mavoglurant model](https://nlmixrdevelopment.github.io/nlmixr.examples/articles/mavoglurant.html#lognoral)

If you truly wish to transform and use the NONMEM-style of models you can do the following:
- Transform `DV` to `log(DV)`
- For the concentration you would log-transform it, ie `lcp = log(cp)`
- Define the error on the log-scale `lcp ~ add(add.sd)`

However, I don't suggest it.  Rather I suggest changing the model as follows:
- `cp ~ lnorm(lnorm.sd)`

This way no transformations are required from your side **and** the objective function is compatible between the proportional model you have and the lognormal model you are trying.

This works for `saem` and `focei`.  For `focei` you can also do dynamic transformation of both sides for a cox-box model with `lambda` estimated as well.

**Comment by DimitrisVoul** [comment]
Thank you very much. the second choice seems very convenient. So for the second case all I do is add that code to the end of the model section of the code:

> ...
>  })
>   model({
> d/dt(cp)=k*cp
> cp ~ lnorm(lnorm.sd)

**Comment by mattfidler** [comment]
Yes, and add an estimate for `lnorm.sd`

**Comment by DimitrisVoul** [comment]
Thank you
