### ISSUE TITLE
Parent/metabolite estimate

### ISSUE THREAD

**Issue by lilytif** [nlmixrdevelopment/nlmixr#274]
Hi

Does nlmixr support estimating parameters for parent/metabolite drugs simultaneously? If so, how to write the modeling code, assuming the rate of metabolite formation was equal to the rate of parent drug elimination? Should the CMT for the metabolite be specified as 2 in the data?

Please help!

Thank you!

**Comment by mattfidler** [comment]
Hi @lilytif,

`nlmixr` does allow estimating parent/metabolite drugs simultaneously.  

The details on how to estimate multiple-endpoint models are [here](https://nlmixrdevelopment.github.io/nlmixr/articles/multiple-endpoints.html).  This details how to specify the 2 `CMT` values as well as how to have your model tell you what `CMT` number you need to use.

After reading the documentation if there is anything that is confusing, please report it as a separate issue and we will expand the documentation to be clearer.

**Comment by lilytif** [comment]
Thanks for your quick reply.  From your answer, I understand that even if nlmixr doesn't allow parent/metabolite drug estimation simultaneously,  we can still use multiple end-point models to estimate parent/metabolite simultaneously.  Is that right?

Thanks!

**Comment by mattfidler** [comment]
You can specify a parent/metabolite model with ODEs and will estimate the parent/metabolite through the multiple endpoint estimation.

What has not been implemented is the solved parent/metabolite model.

**Comment by lilytif** [comment]
Thank you @mattfidler  
I was reading the article of "Working with multiple endpoints", and I don't think I fully understand how to specify 'cmt' in the data to link with the model. 
If I have a parent/metabolite model, should I specify the cmt data column as 1, 2, and 3, with 1 corresponding to depot with DV=0, 2 corresponding to center compartment (parent drug concentration), and 3 corresponding to metabolite concentration? I don't have dvid in the data. In the model, I should specify "| center" and "| meta" to link the model with the data. Is that right?
cp ~  add(add.err) | center
meta ~ add(add2.err) | meta

Below is the code I'm using.   I'm not sure if I did correctly because it ran into convergence issue and the estimates for f1, f2, and f3 don't make sense.  Could you please take a look at the code below and let me know if I did something wrong?  Thank you! 

Mymod<-function()
{
	ini({
		tka<-1
		tcl<-6
		tv<-3
		tkm<-1
		tvm<-4
		eta.cl~2
		add.err<-0.1
		add2.err<-0.1
		f1<-c(0,0.5,1)
		f2<-c(0,0.5,1)
		f3<-c(0,0.5,1)
		#beta<-c(-5,0.1,5)
		})
	model({
		ka<-exp(tka)
		km<-exp(tkm)
		vm<-exp(tvm)
		#cl<-exp(tcl+beta*SEX+eta.cl)
		cl<-exp(tcl+eta.cl)
		v<-exp(tv)		
		d/dt(depot)=-ka*depot
		f(depot)=path0+path1*f1+path2*f2+path3*f3
		d/dt(center)=ka*depot-cl/v*center
		d/dt(meta)=cl/v*center-km*meta
		cp=center/v
		cpm=meta/vm
		cp~add(add.err)| center
		cpm~add(add2.err)| meta
		})
}
fit <- nlmixr(Mymod, dt, calc.resid=FALSE,est="focei")

**Comment by mattfidler** [comment]
You can always check what `nlmixr` expects by simply using `nlmixr(Mymod)` .  In this case:

``` r
library(nlmixr)
Mymod<-function()
{
    ini({
        tka<-1
        tcl<-6
        tv<-3
        tkm<-1
        tvm<-4
        eta.cl~2
        add.err<-0.1
        add2.err<-0.1
        f1<-c(0,0.5,1)
        f2<-c(0,0.5,1)
        f3<-c(0,0.5,1)
        #beta<-c(-5,0.1,5)
        })
    model({
        ka<-exp(tka)
        km<-exp(tkm)
        vm<-exp(tvm)
        #cl<-exp(tcl+beta*SEX+eta.cl)
        cl<-exp(tcl+eta.cl)
        v<-exp(tv)
        d/dt(depot)=-ka*depot
        f(depot)=path0+path1*f1+path2*f2+path3*f3
        d/dt(center)=ka*depot-cl/v*center
        d/dt(meta)=cl/v*center-km*meta
        cp=center/v
        cpm=meta/vm
        cp~add(add.err)| center
        cpm~add(add2.err)| meta
        })
}

nlmixr(Mymod)
#> ▂▂ RxODE-based ODE model ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ 
#> ── Initialization: ───────────────────────────────────────────────────────────── 
#> Fixed Effects ($theta): 
#> tka tcl  tv tkm tvm  f1  f2  f3 
#> 1.0 6.0 3.0 1.0 4.0 0.5 0.5 0.5 
#> 
#> Omega ($omega): 
#>        eta.cl
#> eta.cl      2
#> 
#>  Covariates or Uninitialized Parameters ($all.covs)
#> [1] "path0" "path1" "path2" "path3"
#> ── Multiple Endpoint Model ($multipleEndpoint): ──────────────────────────────── 
#> ┌─────────────────────────┬─────────────────────────┬─────────────────────────┐
#> │ variable                │ cmt                     │ dvid*                   │
#> ├─────────────────────────┼─────────────────────────┼─────────────────────────┤
#> │ cp ~ …                  │ cmt='center' or cmt=2   │ dvid='center' or dvid=1 │
#> ├─────────────────────────┼─────────────────────────┼─────────────────────────┤
#> │ cpm ~ …                 │ cmt='meta' or cmt=3     │ dvid='meta' or dvid=2   │
#> └─────────────────────────┴─────────────────────────┴─────────────────────────┘
#>   * If dvids are outside this range, all dvids are re-numered                  
#>   sequentially, ie 1,7, 10 becomes 1,2,3 etc                                   
#> ── μ-referencing ($muRefTable): ──────────────────────────────────────────────── 
#> ┌─────────┬─────────┐
#> │ theta   │ eta     │
#> ├─────────┼─────────┤
#> │ tcl     │ eta.cl  │
#> └─────────┴─────────┘
#> ── Model: ────────────────────────────────────────────────────────────────────── 
#>      ka<-exp(tka)
#>      km<-exp(tkm)
#>      vm<-exp(tvm)
#>      #cl<-exp(tcl+beta*SEX+eta.cl)
#>      cl<-exp(tcl+eta.cl)
#>      v<-exp(tv)
#>      d/dt(depot)=-ka*depot
#>      f(depot)=path0+path1*f1+path2*f2+path3*f3
#>      d/dt(center)=ka*depot-cl/v*center
#>      d/dt(meta)=cl/v*center-km*meta
#>      cp=center/v
#>      cpm=meta/vm
#>      cp~add(add.err)| center
#>      cpm~add(add2.err)| meta 
#> ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
```

<sup>Created on 2020-02-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This says the model assumes `cmt=2` is for the central compartment and `cmt=3` is for the metabolite compartment, as you thought.

I am not sure why the bioavailability is behaving different.  Perhaps each route has a different bioavailibility and ka.
