### ISSUE TITLE
Multiple compartments

### ISSUE THREAD

**Issue by XimenezJP** [nlmixrdevelopment/nlmixr#280]
Dear nlmixr-team
I have concentrations from a prodrug and three metabolites.
Is it currently possible to use nlmixr with observations in 4 compartments? Or is this related to something else? Any additional thoughts?
Thx!

**Comment by mattfidler** [comment]
Yes you can use `nlmixr` with a pro-drug and three metabolites;  

There is documentation about how to do it [here](https://nlmixrdevelopment.github.io/nlmixr/articles/multiple-endpoints.html).  While the documentation is about a Pk/PD model, the methods are the same to create a prodrug + 3 metabolite PK model.

If the documentation is not clear, please let me know what you are struggling with.
