### ISSUE TITLE
Not compatible with requested type: [type=list; target=double].

### ISSUE THREAD

**Issue by nanwu-yxdzh** [nlmixrdevelopment/nlmixr#288]
I ran a model with multiple endpoint by using fo method. Because it is a non-population model fit so I fix one eta to 0. Then it gives me errors as follow:

Error in .fitFun(.ret) : 
  Evaluation error: On initial gradient evaluation, one or more parameters have a zero gradient
Change model, try different initial estimates or use outerOpt="bobyqa").
Restart 1
Error in .fitFun(.ret) : 
  Not compatible with requested type: [type=list; target=double].
Restart 2
Error in .fitFun(.ret) : 
  Not compatible with requested type: [type=list; target=double].
Restart 3
Error in .fitFun(.ret) : 
  Not compatible with requested type: [type=list; target=double].

Any help would be appreciated!

**Comment by mattfidler** [comment]
Hi @nanwu-yxdzh 

If you could provide a reproducible example, I would be happy to help.  One way to do this is with the `reprex` pacakge.

**Comment by mattfidler** [comment]
I haven't seen an issue yet.
