### ISSUE TITLE
Value threshold for VPCs

### ISSUE THREAD

**Issue by DimitrisVoul** [nlmixrdevelopment/nlmixr#290]
Hello,

This might be an odd question but is there a way to introduce a cut off for the simulated values of the VPC?

What I mean is for example ignore all simulated values above some welfare limit (maximum tumour volume). Because obviously these are not present in the data whereas the models allows for them and that makes the VPCs look sub-optimal.

**Comment by mattfidler** [comment]
`xpose.nlmixr` simply re-exports the `nlmixr` method, so this is where the issue belongs.

**Comment by DimitrisVoul** [comment]
Hello,

So if I get this right, I can use the output of the nlmixr fitting to simulate the VPC using RxODE and set limits to the parameters? I am not sure why though I would have a limit for theta. I understand restricting the omegas during the simulation but not the thetas. Wouldn't they be fixed to the value found through the fitting with nlmixr?

One more question. After the fitting with nlmixr what would be the easiest way to perform the Monte Carlo simulations needed to get the data for the VPC plot. Doing that manually and saving the data will allow me to reject the values and recalculate the CIs and percentiles.

**Comment by mattfidler** [comment]
> So if I get this right, I can use the output of the nlmixr fitting to simulate the VPC using RxODE and set limits to the parameters? I am not sure why though I would have a limit for theta. I understand restricting the omegas during the simulation but not the thetas. Wouldn't they be fixed to the value found through the fitting with nlmixr?

Yes. This is true for a typical VPC.  If you sample from the uncertanty in your parameters in a simulation though this is useful.

> One more question. After the fitting with nlmixr what would be the easiest way to perform the Monte Carlo simulations needed to get the data for the VPC plot. Doing that manually and saving the data will allow me to reject the values and recalculate the CIs and percentiles.

You can get the data from the vpc plot.  If you save it to an object it will include the simulation data.  If you print it it will describe how to get the data.
