### ISSUE TITLE
Could not start SymPy

### ISSUE THREAD

**Issue by jianxinwang** [nlmixrdevelopment/nlmixr#292]
Hi Matt,

I'm installing on CentOS 7 using environment modules approach (as apposed to system install with sudo). Installation is fine, however the rxTest and nlmirxValidate all complaining with not being able to start SymPy. Sympy has been installed under python3 with "pip install sympy" command and can be imported under Python console:

<text>:1: error: Equiv syntax 'exp'
Could not start SymPy
Backtrace:
 1. testthat::expect_equal(rxToSymPy(exp(a)), "exp(a)")
 4. RxODE::rxToSymPy(exp(a))
 6. RxODE:::sympyEnv(expr)
 7. RxODE::rxSymPyReserved()
 8. RxODE::rxSymPyStart()

What could be wrong with my setup? Thanks!

By the way, here is my env:
 module list

Currently Loaded Modules:
  1) Python3/3.6.9   2) gcc/8.3.0-avx   3) R/3.6.3-gcc8.3.0-avx

**Comment by jianxinwang** [comment]
I set some python environmental variables as suggested, however, RxODE always looking for sympy installed on system directory, like /usr/bin/python:

> rxSymPyVersion()
Error in python_config(python_version, required_module, python_versions) : 
  Error 1 occurred running /usr/bin/python 
In addition: Warning message:
In system2(command = python, args = paste0("\"", config_script,  :
  running command ''/usr/bin/python' "/projects/industry/epd/software/R/3.6.3/lib64/R/library/reticulate/config/config.py" 2>/dev/null' had status 1
RxODE requires SymPy for this function.
We recommend you install SymPy for Python and then interact with Python using reticulate.
In Windows you can have help setting this up by typing: `rxWinPythonSetup()`.
Another option is to use SnakeCharmR
Error in rxSymPyStart() : Could not start SymPy

I'm installing on a HPC therefore installing python and sympy in a system location is not an option.

**Comment by mattfidler** [comment]
Hi @jianxinwang,

I have found `reticulate` to be more reliable on unix systems.  Are use using `reticulate` or `SnakeCharmR`?

**Comment by jianxinwang** [comment]
Hi Matt,

I'm using reticulate. I have tried a few install options so far. Using
minicoda2, after I installed SnakeCharmR, rxTest() can find sysmpy
installed under python2.7. But since SnakeCharR is to be deprecated, we
prefer not to use it anymore. And since ppython2 has reached end of life,
we prefer to use python3 entirely. However, I found install python3 version
of sympy has no use. Looks RxODE has code hard-coded to search sympy under
python2, not python3. I feel SnakeCharmeR has a mechanism to overwrite the
python environment to make it search python installed on other locations.
This raised another question: Why both python2 and python3 (and some python
packages) required in the installation doc in your github site? Can nlmixr
be deployed with python3 only?

Thanks

**Comment by mattfidler** [comment]
Hi @jianxinwang,

The python can be `python3` only.  I believe both the docker image and I know the installer uses `python3`. 

RxODE actually is only "hard-coded" to look for it in windows.  Anything else is entirely up to the system administrator. 

I would suggest setting the environment variable `RETICULATE_PYTHON` as suggested in the following document:

https://rstudio.github.io/reticulate/articles/versions.html#providing-hints-1

Then you may be able to see the python3 with sympy.

In the future this step will no longer be required.  I am working toward a python free `RxODE` (which is where the `nlmixr` python dependency comes from).

**Comment by mattfidler** [comment]
If you installed `SnakeCharmR`, please uninstall it.  I think the CRAN version will use `SnakeCharmR` over `reticulate` if it finds it.

**Comment by jianxinwang** [comment]
Hi Matt,

Thanks for helping me out. Yes, the problem get solved by setting
RETICULATE_PYTHON environment variable to point to my python3 binaries.

Jason

**Comment by mattfidler** [comment]
Awesome.
