### ISSUE TITLE
predict/estimate  concentration at the time point 

### ISSUE THREAD

**Issue by Mak1071** [nlmixrdevelopment/nlmixr#297]
Hello,

I am fitting two compartment model to the subject data. I obtained fixed parameters and random parameters.
I would like to predict/estimate the concentration at the time point which is not included in my subject level data  for a specific subject and for population. Is it possible using nlmixr?
I saw there is nlmixrPred() but it is not very well documented and I wanted to ask for advice.

Thank you very much for help.
Kind regards,
Mak

**Comment by mattfidler** [comment]
Hi @Mak1071,

You can use `EVID=2` to simulate a subject time-point in your dataset like you can in `NOMEM` and `Monolix`

You can also access the underlying `RxODE` machinery, all the model information you need can be found in the `fit$simInfo`

**Comment by Mak1071** [comment]
Thank you!

Best regards,
Mak
