### ISSUE TITLE
Question: Are dataset requirements documented in a single location?

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#302]
I'm trying to determine what is required to put together my dataset correctly for `nlmixr`, but I'm having trouble determining exactly what will be required where.  For example, I get an error if I forget to name a column "TIME" (or "time"), and the description of the `data` argument in `?nlmixr` indicates that "Dataset to estimate. Needs to be RxODE compatible in EVIDs.".

I have not been able to find a single reference for how to setup my data, though, and I'm having trouble putting the parts together.  Can you please help me find that reference if it exists, or if not, can you please give a few pointers?

I think that ideally, that reference would be linked in some way from the `data` argument documentation in `?nlmixr` (whether it is a vignette, another help file, or whatever the resource is).

**Comment by mattfidler** [comment]
Yes.  

https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-event-types.html

If you think it is useful you can add the data requirements there in the documentation.

**Comment by mattfidler** [comment]
If you have any specific problems let me know.

**Comment by billdenney** [comment]
That helps a lot.  With that link in mind, I think that it would help to change "Needs to be RxODE compatible in EVIDs" to "See the RxODE documentation for how to format the dataset (https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-event-types.html)." or something similar because based on the statement in the `nlmixr()` document, I thought that I was only looking for EVID definitions in the RxODE doc-- not everything.
