### ISSUE TITLE
Improve Error Message for SAEM Fitting with One Subject

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#308]
Currently, fitting an SAEM model requires more than one subject in the dataset.  When I just (accidentally) tried to fit a model with a single subject, I got the following error that wasn't clear as to the problem.

From a code-perspective, `statphi` here is expected to be a matrix, but it is not when there is a single subject.  I see two fixes that are preferred here, I think:

1. Catch single-subject data for an SAEM model earlier and give an informative error message.
2. Ensure that `statphi` is a matrix for the potential future state where SAEM models can be used to fit fixed-effect-only models.  As coded, it is a vector when `length(unique(ID)) == 1`.

https://github.com/nlmixrdevelopment/nlmixr/blob/a6e154cf77593ab44c4d5678961b57b83bf60ad8/R/saem_fit.R#L1197-L1198

``` r
library(nlmixr)
  model_onecmt <- function(){
    ini({
      tvka <- c(-10, -2, 10) # log(Absorption rate (1/hr))
      tvcl <- c(-10, -5, 10) # log(Clearance (L/hr))
      tvv <- c(-10, -3, 10) # log(Volume of Distribution (L/kg))
      tvf_sc <- c(0, 0.5, 1) # subcutaneous bioavailability
      prop.err <- c(0, 0.1, 1) # Proportional error
      eta_cl ~ 0.3 # IIV in clearance
    })
    model({
      cl = exp(tvcl + eta_cl)
      ka = exp(tvka)
      v = exp(tvv)
      kel = cl/v
      d/dt(SC) = -ka*SC
      d/dt(C) = ka*SC - kel*C
      F(SC) = tvf_sc
      cp = C/v
      cp ~ prop(prop.err)
    })
  }
  
fit <- nlmixr(object=model_onecmt, data=Oral_1CPT[Oral_1CPT$ID == 1, ], est="saem")
#> Compiling RxODE equations...done.
#> Error in statphi[, i1]: incorrect number of dimensions
```

<sup>Created on 2020-06-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattfidler** [comment]
I agree.  This should actually error before it gets to this point.

**Comment by mattfidler** [comment]
This should be fixed.
