### ISSUE TITLE
NAs introduced by coercion warning after fit

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#310]
After running my model successfully!  (Woohoo! :) )  I saw a warning message of NAs introduced by coercion.  In my code, this usually means that there is an `as.numeric()` call that has non-numeric input.

For the model I'm running, I anticipated that the fit would not be great because I'm fitting a simple 1-compartment model, but there is a huge anti-drug antibody effect on clearance which the initial model ignored.  Do you know of a good way to track down where this warning originates to confirm that it is not a problem?

```
Calculating covariance matrix
[====|====|====|====|====|====|====|====|====|====] 0:00:00 
Error in RxODE::rxProgressAbort("Error calculating covariance via linearization") : 
  Error calculating covariance via linearization
creating full model...pruning branches (if/else)...done
loading into symengine environment...done
finding duplicate expressions in EBE model...
[====|====|====|====|====|====|====|====|====|====] 0:00:00 

optimizing duplicate expressions in EBE model...
[====|====|====|====|====|====|====|====|====|====] 0:00:00 

compiling EBE model...done
Calculating residuals/tables
done.
Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod = FALSE,  :
  Covariance matrix non-positive definite, corrected by sqrtm(fim %*% fim)
Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod = FALSE,  :
  Linearization of FIM could not be used to calculate covariance.
Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod = FALSE,  :
  Some variances were zero, replaced with 1.
Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod = FALSE,  :
  NAs introduced by coercion
Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod = FALSE,  :
  Bounds are ignored in SAEM
```

**Comment by mattfidler** [comment]
Yes.  You can by:

```r
options(warn=2)
```
This converts warnings into errors;  The troublesome thing is that some of these warnings occur earlier than `NA`s were introduced by coercion, so it will error out earlier than it should.  Therefore these warnings need to be commented out or skipped.

**Comment by billdenney** [comment]
I've done some attempts to figure out where the warning is coming from, including writing replacement `as.numeric()` and `as.integer()` functions which capture changes and show me a browser when they occur.  I haven't found what is generating the warning, but I did find some other rows that make me curious.  What is the goal of these lines and could the be written with something not using `suppressWarnings()`?

https://github.com/nlmixrdevelopment/nlmixr/blob/cf5c05d95e152b538cd5ab2a73b1a9acffe77e35/R/ui.R#L1097

https://github.com/nlmixrdevelopment/nlmixr/blob/cf5c05d95e152b538cd5ab2a73b1a9acffe77e35/R/ui.R#L1131-L1133

https://github.com/nlmixrdevelopment/nlmixr/blob/cf5c05d95e152b538cd5ab2a73b1a9acffe77e35/R/ui.R#L1166-L1171

https://github.com/nlmixrdevelopment/nlmixr/blob/cf5c05d95e152b538cd5ab2a73b1a9acffe77e35/R/ui.R#L1213-L1221

https://github.com/nlmixrdevelopment/nlmixr/blob/cf5c05d95e152b538cd5ab2a73b1a9acffe77e35/R/ui.R#L1993

**Comment by mattfidler** [comment]
The UI is moving, so I will close this for now
