### ISSUE TITLE
Unusual Error Message from focei

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#311]
When I was transitioning to focei to get time-varying covariates, I got the following error message.  The reprex takes a while to run, so I'm just providing the code and the message that was a problem.  (I was trying to generate another reprex when I found this, so I'm going to try to re-create that issue separately.)

I think that the ideal would be to catch this message and inform about what, if anything, is the problem.  As I was using this to try to generate a different reprex, I didn't think much about what the initial conditions or bounds were (not think much = just typed some numbers without looking at the data), so there is a great chance that this is due to horrible initial conditions relative to the data.  Watching the fit progress was an exercise in watching ODE solver and steepest descent solver pain.  (As I actually look at what I put in, I see that I fit bioavailability with only one route of administration-- this was impossible.  Again, I was trying to generate an example of something else.)

### Code

```r
library(nlmixr)
library(tidyverse)
  model_onecmt <- function(){
    ini({
      tvka <- c(-10, -2, 10) # log(Absorption rate (1/hr))
      tvcl <- c(-10, -5, 10) # log(Clearance (L/hr))
      tvv <- c(-10, -3, 10) # log(Volume of Distribution (L/kg))
      tvf_sc <- c(0, 0.5, 1) # subcutaneous bioavailability
      prop.err <- c(0, 0.1, 1) # Proportional error
      eta_cl ~ 0.3 # IIV in clearance
    })
    model({
      cl = exp(tvcl + eta_cl)
      ka = exp(tvka)
      v = exp(tvv)
      kel = cl/v
      d/dt(SC) = -ka*SC
      d/dt(C) = ka*SC - kel*C
      F(SC) = tvf_sc
      cp = C/v
      cp ~ prop(prop.err)
    })
  }
  
fitdata <-
  Oral_1CPT %>%
  filter(ID %in% c(50:70))
  
fit <- nlmixr(object=model_onecmt, data=fitdata, est="focei")
```

### Problem message

```
|    F| Forward Diff. |    -89.19 |     66.12 |    -38.86 |         1101. |    -246.8 |    -82.53 |
|  108|     13099.435 |   -0.7628 |     5.471 |    -1.960 |   -0.3867 |     5.567 |     1.074 |
|    U|     13099.435 |    -3.026 |    -5.340 |    -9.509 |  0.001179 |    0.3078 |     1.100 |
|    X|     13099.435 |   0.04850 |  0.004798 | 7.421e-05 |  0.001179 |    0.3078 |     1.100 |
|  109|     13099.153 |   -0.7628 |     5.471 |    -1.960 |   -0.3865 |     5.567 |     1.074 |
|    U|     13099.153 |    -3.026 |    -5.340 |    -9.509 |  0.001192 |    0.3078 |     1.100 |
|    X|     13099.153 |   0.04850 |  0.004798 | 7.421e-05 |  0.001192 |    0.3078 |     1.100 |
[====|====|=IDID=-1, excess work done on this call (perhaps wrong jt).
unhandled error message: EE:[lsoda] 50000 steps taken before reaching tout
 @(lsoda.c:746)
IDID=-1, excess work done on this call (perhaps wrong jt).
unhandled error message: EE:[lsoda] 50000 steps taken before reaching tout
 @(lsoda.c:746)e.rds
===|====|====|====|====|====|====|====] 0:00:02 
```

**Comment by mattfidler** [comment]
This is due to the internals of `RxODE`; `NONMEM` suppresses this output, I have also thought of suppressing the output.

When there are problems in ODE solving, nlmixr reduces the accuracy to try to a solution anyway, so it doens't stop the fit.

As far as waiting, it is much different in R than in NONMEM.  For those people using Rstudio, I was thinking of putting into a job; See https://github.com/nlmixrdevelopment/nlmixr/issues/291  Most people are not happy about it "stealing the R console", because of how Rstudio runs.  I personally just fire up another R session, but in Rstudio it isn't quite as easy as it is in emacs.

**Comment by billdenney** [comment]
Ah, OK.  I don't mind the output as long as I know how to understand if it is a real problem or not.  If NONMEM suppresses it, then I will assume that the output is added information that can be helpful for diagnosing the situation.

I don't have a big problem with it "stealing the R console", but I can understand it.  In RStudio, there is an option in the "Session" menu to start a "New Session".  I use that several times a day for situations like this.  I also use `drake` for almost everything that I do now (which I'm about to test with nlmixr), and that makes many of these types of issues go away, too by preventing the need to rerun jobs.

That said, I would like some form of sending it off to compute while I work on other things-- it would be a step simpler.

**Comment by mattfidler** [comment]
Yes.  `drake` does not work with nlmixr.

There was some rudimentary support that I added (that you could play with if you want to track down the issue):

https://github.com/nlmixrdevelopment/nlmixr/blob/f25d3b8b19b546213819658c250547908ad1ca3d/R/ui.R#L1-L35

**Comment by mattfidler** [comment]
This function is applied when parsing the nlmixr function:

https://github.com/nlmixrdevelopment/nlmixr/blob/f25d3b8b19b546213819658c250547908ad1ca3d/R/ui.R#L629-L630

But you can call `.drakeCompat(fun)` to modify the `nlmixr` function to allow it to run drake.

For me, it couldn't restart the run.

**Comment by mattfidler** [comment]
I think you would have to call it first:

```r
f <- nlmixr(.drakeCompat(nlmixrModelFun))
```

And then run the model

**Comment by billdenney** [comment]
I'll admit that I'm mostly out of my depth in these issues (drake not working with some packages).  What I have seen as a common thread (where drake doesn't work well with mrgsolve or rstan) is that custom-compiled Rcpp code is not available when drake runs a subsequent time.  My impression is that is what is happening with nlmixr:  There is custom Rcpp compilation for the model, and then the compiled version is not available anymore.

There are also issues where Rcpp puts things into the global namespace for the compiled code, too.

If you're interested, Will Landau (the author of drake) is especially responsive and helpful.  Starting a drake-specific issue may get nlmixr closer to drake compatibility.  (I'd be happy to start the introduction with a reprex when I have it-- which based on this thread will be in the next couple of hours.)

**Comment by mattfidler** [comment]
Its up to you;  I have opened issues in Drake in the past:

https://github.com/ropensci/drake/issues/910

Will is a good guy.  I was waiting until the python-free `nlmixr` was on `CRAN` before starting a conversation with him.  I think it is unfair to try this and have a large setup to reproduce on his end.

This isn't high on my priority list.  I created a cache option for nlmixr that you can use as a work-around if you are interested.

**Comment by billdenney** [comment]
Ah, you're a step ahead, and that's a good point.  In that case, I'll wait for python-free `nlmixr` on CRAN.

**Comment by mattfidler** [comment]
I think this complete for now.  We can revisit drake later.
