### ISSUE TITLE
Add other rows to to focei key

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#312]
Thank you for the key at the top of the focei output.

While watching the output run, I saw a few items that are not in the key:

* **M**: labeled as "Mixed Diff."
* **F**: labeled as "Forward Diff"

They appear to be other forms of the gradient.  While a minor request, it would be nice to have all possible rows specified in that key.  I think that the location is here:

https://github.com/nlmixrdevelopment/nlmixr/blob/a6e154cf77593ab44c4d5678961b57b83bf60ad8/src/inner.cpp#L5369-L5371

**Comment by mattfidler** [comment]
I do not mind;  The key is below:

https://github.com/nlmixrdevelopment/nlmixr/blob/a6e154cf77593ab44c4d5678961b57b83bf60ad8/src/inner.cpp#L3231-L3242

I think it was simply not updated to represent what gradients were eventually calculated
