### ISSUE TITLE
Incomplete parFixed for focei

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#313]
In a model that had problems fitting, the `$parFixed` and `$parFixedDf` elements had several issues.

I can't share the model, but the warnings that I saw at the end of minimization were:

```
Warning messages:
1: In (function (uif, data, est = NULL, control = list(), ..., sum.prod = FALSE,  :
  Initial ETAs were nudged; (Can control by foceiControl(etaNudge=.))
2: In (function (uif, data, est = NULL, control = list(), ..., sum.prod = FALSE,  :
  ETAs were reset to zero during optimization; (Can control by foceiControl(resetEtaP=.))
3: In (function (uif, data, est = NULL, control = list(), ..., sum.prod = FALSE,  :
  Parameter estimate near boundary; covariance not caculated. Use getVarCov to calculate anyway.
4: In (function (uif, data, est = NULL, control = list(), ..., sum.prod = FALSE,  :
  Gradient problems with initial estimate; see $scaleInfo
```

The output that I got back in `fit_twocmt_ada$parFixed` only had columns for `Est.` and `Back-transformed` but not `Parameter`, `SE`, `%RSE`, `Back-transformed(95%CI)`, `BSV(CV%)`, or  `Shrink(SD)%`.  I understand that in this case, the model probably would not provide the following columns, `SE`, `%RSE`, and `Back-transformed(95%CI)`, but I would have expected them to be present but all `NA_character_` or `NA_real_` (for `$parFixed` or `$parFixedDf`, respectively).

Also, some but not all of the Back-transformed parameters were back-transformed.  Specifically, `tvcl` and `tvcl_ada` were not back-transformed while all the other log-scale parameters were correctly exponentiated.  As I am guessing it matters, the model looks like this:

```r
model_twocmt_ada <- function() {
  ini({
    tvka <- c(-10, -3, 10) # log(Absorption rate (1/hr))
    tvcl <- c(-10, -8, 10) # log(Clearance without ADA (L/kg/hr))
    tvcl_ada <- c(-10, -7, 10) # log(Clearance with ADA (L/kg/hr))
    tvv <- c(-10, -3, 10) # log(Volume of distribution (L/kg))
    tvvp <- c(-10, -3, 10) # log(Volume of distribution for peripheral compartment (L/kg))
    tvq  <- c(-10, -4, 10) # log(Intercompartmental clearance (L/kg/hr))
    tvf_sc <- c(0, 0.9, 2) # subcutaneous bioavailability
    prop.err <- c(0, 0.15, 1) # Proportional error
    add.err <- 3 # Additive error
    eta_cl ~ 0.3 # IIV in clearance
  })
  model({
    cl = exp(tvcl*(1-has_ADA) + tvcl_ada*has_ADA + eta_cl)
    ka = exp(tvka)
    v = exp(tvv)
    vp = exp(tvvp)
    q = exp(tvq)
    f_sc = tvf_sc # Parameter translation above ODE
    kel = cl/v
    k12 = q/v
    k21 = q/vp
    d/dt(SC) = -ka*SC
    d/dt(C) = ka*SC - kel*C - k12*C + k21*P
    d/dt(P) =                 k12*C - k21*P
    F(SC) = f_sc
    cp = C/v
    cp ~ prop(prop.err) + add(add.err)
  })
}
```

**Comment by mattfidler** [comment]
I will address some of the issues later, but I can quickly address the back-transformation; For expressions like:

```R
cl = exp(tvcl*(1-has_ADA) + tvcl_ada*has_ADA + eta_cl)
```

I cannot tell a covariate expression from a typical value of clearance.  All covariates estimates are not back-transformed (which is what I think *should* happen).  But, there are cases where this may not be ideal (like this one).

I have toyed with some way of indicating that something should or should not be back-transformed but haven't come up with something great.  If you have a suggestion, let me know.  I prefer not to put anything in the parameter labels since they aren't exactly as portable as I first expected.

The other arguments may be valid, but if you want standardized names, you can always use `tidy(fit)` or `glance(fit)`

**Comment by billdenney** [comment]
Ah, I had assumed that back-transformation was based on the label, not based on code inspection.  (Code inspection is so much better!)

The only thing that immediately occurs to me is to add a model section akin to what is used in Stan with "transformed parameters".  In that, you could have any transformations that you want.  Perhaps adding some form of option to force a transform along those lines.

I added

```r
  back_transform(
    tvcl=exp,
    tvcl_ada=exp,
    .default="automatic"
  )
```

Where the important parts that I think are:
* It is a list.
* The list has names that match the names of parameters.
* The values in the list are arbitrary functions where the numeric values is the first argument.  They can either by a normal function (e.g. `exp` in this case) or any user-defined function like `function(x) exp(-5*x) + 21`.
* There is some form of indicator (`.default` in the suggestion above) where the user can choose to make use of the automatic detection for all other parameters or turn off the automatic detection.

As it has nothing to do with the fitting itself, only the reporting, this should also be possible to modify on a completed model fit object.

```r
model_twocmt_ada <- function() {
  ini({
    tvka <- c(-10, -3, 10) # log(Absorption rate (1/hr))
    tvcl <- c(-10, -8, 10) # log(Clearance without ADA (L/kg/hr))
    tvcl_ada <- c(-10, -7, 10) # log(Clearance with ADA (L/kg/hr))
    tvv <- c(-10, -3, 10) # log(Volume of distribution (L/kg))
    tvvp <- c(-10, -3, 10) # log(Volume of distribution for peripheral compartment (L/kg))
    tvq  <- c(-10, -4, 10) # log(Intercompartmental clearance (L/kg/hr))
    tvf_sc <- c(0, 0.9, 2) # subcutaneous bioavailability
    prop.err <- c(0, 0.15, 1) # Proportional error
    add.err <- 3 # Additive error
    eta_cl ~ 0.3 # IIV in clearance
  })
  model({
    cl = exp(tvcl*(1-has_ADA) + tvcl_ada*has_ADA + eta_cl)
    ka = exp(tvka)
    v = exp(tvv)
    vp = exp(tvvp)
    q = exp(tvq)
    f_sc = tvf_sc # Parameter translation above ODE
    kel = cl/v
    k12 = q/v
    k21 = q/vp
    d/dt(SC) = -ka*SC
    d/dt(C) = ka*SC - kel*C - k12*C + k21*P
    d/dt(P) =                 k12*C - k21*P
    F(SC) = f_sc
    cp = C/v
    cp ~ prop(prop.err) + add(add.err)
  })
  back_transform(
    tvcl=exp,
    tvcl_ada=exp,
    .default=NULL
  )
}
```

**Comment by mattfidler** [comment]
As far as the warnings:

> - Initial ETAs were nudged; (Can control by foceiControl(etaNudge=.))

This means that when starting your minimization some ETAs were moved from zero to some nudged value to allow the `inner` problem's minimization to proceed. You can turn it off with `foceiControl(etaNudge=.)`


> ETAs were reset to zero during optimization; (Can control by foceiControl(resetEtaP=.))

FOCEi uses the prior `ETA` estimate to restart the inner problem.  When the ETA estimate is outside the realm of what it should be (based on the omega specification as well as the mean/sd of all the ETAs), they are reset to zero.  You can specify the `p-value` of what is outside the realm of normal to have this reset by `foceiControl(resetEtaP=.)`

> Parameter estimate near boundary; covariance not calculated. Use getVarCov to calculate anyway.

(FIXME spelling)

This is similar to `NONMEM` parameter estimate near the boundary but you can calculate the covariance anyway.
 
> Gradient problems with initial estimate; see $scaleInfo

This says some of the gradients on the initial estimates are inaccurate (based on the Gill differences algorithm).  In theory you *could* adjust the scaling parameters to get a better initial gradient value using `foceiControl(scaleC=c(...))` but I haven't personally had luck with this

**Comment by mattfidler** [comment]
Lastly,

>The output that I got back in fit_twocmt_ada$parFixed only had columns for Est. and Back-transformed but not Parameter, SE, %RSE, Back-transformed(95%CI), BSV(CV%), or Shrink(SD)%. I understand that in this case, the model probably would not provide the following columns, SE, %RSE, and Back-transformed(95%CI), but I would have expected them to be present but all NA_character_ or NA_real_ (for $parFixed or $parFixedDf, respectively).

Currently I only add the columns if they are calculated;  By the logic you use, I should add the bootstrap SEs that my intern is working on to this table, and any other metrics of SE (like importance sampling SE) that you can calculate after the model is complete.  To me, my choice is more logical and maintainable, but maybe you can convince me otherwise.

Also, if you wish to have standardized columns

**Comment by billdenney** [comment]
I think that my logic is a bit different from adding the bootstrap SEs, but I agree that it shouldn't go too far.

For the starting point, I think that the `Parameter` column should be there since I gave parameter comments.  (That one seems likely to be fully agreeable.)

For the others that are there now (i.e. not including bootstrap), I won't push much for them, but I do see value, so I'll state my thoughts.

I view these types of things as informative vs. uninformative missing columns.  If they are not added when they are not calculated because e.g. the covariance matrix was unobtainable, then that is missing, but it may not be informative missing.

For example, there are some columns which would not apply to some types of model fitting (`BSV(CV%)` for fixed-effect only modeling, for instance).  If the column were there but all values were `NA`, then I would have an indicator that the attempt was made to calculate it, the model type supported it, and it was not possible to calculate (for some reason).  If it were there for model types that supported it but all values were `NA`, then it would be informative missing because the existence of the column gives the info that the model type supports it while the NA values give the info that it was not calculated (or not possible to calculate).

I see bootstrap as different.  It is a separate operation that adds additional information.  The lack of a `bootstrap` column is an informative indicator that bootstrap was not performed.  The existence of a `bootstrap` column would indicate that bootstrap was attempted, and all `NA` values would indicate that the bootstrap was tried and failed for some reason (and non-NA would indicate the success).

After that soapbox... let me check out the `tidy()` methods.  :)

**Comment by mattfidler** [comment]
I will poll the `nlmixr` team for thoughts before thinking about this further.

**Comment by billdenney** [comment]
I should add:  I recognize that this is your package, and I'm jumping in and rattling the windows.  All these decisions are yours to make, and I will respect them.  My hope is that these comments are helpful as someone with fresh eyes on the package and its use.

**Comment by mattfidler** [comment]
It is perfectly OK.  I personally see it differently;  

My vision was that `$parFixed` would be very close to a report-ready table.  Adding the `NA_real_` would add more information but would not be a table I would want to have in a report.

However since this is a community effort, I will poll more people to see what their perspective is.

**Comment by billdenney** [comment]
That makes sense.

Maybe to achieve both of these (especially as I'm now enjoying using `$parFixed` as a table in a report), the Df version could have the NA columns while `$parFixed` would maintain its table-ready nature.

**Comment by mattfidler** [comment]
I forgot to mention that this already existed (mostly because I forgot).  

Here is an example:

``` r
library(nlmixr)
one.compartment <- function() {
  ini({
    tka <- 0.45 # Log Ka
    tcl <- 1 # Log Cl
    tv <- 3.45    # Log V
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    d/dt(depot) = -ka * depot
    d/dt(center) = ka * depot - cl / v * center
    cp = center / v
    cp ~ add(add.sd)
  })
}
fit2 <- nlmixr(one.compartment, theo_sd, est="saem",list(print=0))
#> ℹ parameter labels from comments will be replaced by 'label()'
#> ABC
#> RxODE 1.0.0.0 using 4 threads (see ?getRxThreads)
#> Calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> Calculating residuals/tables
#> done.

print(fit2$popDf)
#>         Estimate         SE      %RSE Back-transformed  CI Lower  CI Upper
#> tka    0.4503974 0.19331973 42.922038        1.5689355  1.074116  2.291707
#> tcl    1.0163540 0.08633835  8.494909        2.7631022  2.332951  3.272565
#> tv     3.4498616 0.04368753  1.266356       31.4960319 28.911389 34.311739
#> add.sd 0.6979448         NA        NA        0.6979448        NA        NA

print(fit2$omega)
#>           eta.ka     eta.cl      eta.v
#> eta.ka 0.4018279 0.00000000 0.00000000
#> eta.cl 0.0000000 0.07541039 0.00000000
#> eta.v  0.0000000 0.00000000 0.01584909
```

<sup>Created on 2020-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So I will not update `$parFixed` for this

**Comment by mattfidler** [comment]
It does not have parameter labels, but I'm sure it is easy to cobble the two datasets together for this.

**Comment by mattfidler** [comment]
Feel free to reopen an issue if you think I am missing something.
