### ISSUE TITLE
Questions about dynmodel

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#321]
I'm trying to troubleshoot the dynmodel code because I'm having another issue with initial conditions not being between the lower and upper bounds.  As you can see by the series of PRs, I'm trying to dive a bit deeper.  In this issue, I'm going to ask several specific questions about dynmodel code to try to understand and be able to help bring it up to speed...

**Comment by billdenney** [comment]
At this location, it's not clear why one would omit the first row of data if it is a zero observation.  I think of that decision as stylistic, and while it is sometimes uninformative, it can be informative in some scenarios.  (If interested, I can pull up the NMUSERS discussion where I gave a more detailed rationale.)

https://github.com/nlmixrdevelopment/nlmixr/blob/78883d0192a544ac171c17d700f3956e56f78eb7/R/utils.R#L1019-L1022

Question:  Could/should the filtering out of the first row of data in this case be removed?  (Meaning, delete the code, keep the row of data.)

**Comment by billdenney** [comment]
In the assignment below, it seems like since `scaleC[n.inits.err[1]]` is being tested for being NA, then the assignment should occur into the same and not `scaleC[i]` on lines 1131 and 1133, is that correct?  (If so, it's coming in a PR from me.  If not, then it should be reverted in that PR.)

https://github.com/nlmixrdevelopment/nlmixr/blob/78883d0192a544ac171c17d700f3956e56f78eb7/R/utils.R#L1326-L1336

**Comment by mattfidler** [comment]
> At this location, it's not clear why one would omit the first row of data if it is a zero observation. I think of that decision as stylistic, and while it is sometimes uninformative, it can be informative in some scenarios. (If interested, I can pull up the NMUSERS discussion where I gave a more detailed rationale.)
> Question: Could/should the filtering out of the first row of data in this case be removed? (Meaning, delete the code, keep the row of data.)

I agree.  I think it was removed because the `prop()` model didn't perform (though I cannot be sure) with zero-predictions.  Possibly a broader issue is should `nlmixr` handle zero predictions as `W=1` as is done in many NONMEM models.

**Comment by mattfidler** [comment]
> In the assignment below, it seems like since scaleC[n.inits.err[1]] is being tested for being NA, then the assignment should occur into the same and not scaleC[i] on lines 1131 and 1133, is that correct? (If so, it's coming in a PR from me. If not, then it should be reverted in that PR.)

I haven't looked at the code as recently as you, but the idea is `scaleC` should assign scaling for the error types.

**Comment by billdenney** [comment]
I think that nlmixr should handle zero predictions with proportional error with the weight = 1 because in all cases that I can think of for proportional error, it should not divide by zero and should be considered non-informative for the prediction.  For additive error and other errors that are not strictly proportional to the prediction, it should use the actual error weight (not set to 1).

But, I think that removing the initial row from the dataset would also remove it from having additive error which would not be fully accurate.

Perhaps a simplification for the removal of the first row question is that all dataset processing and management should occur separately from the estimation setup.

**Comment by mattfidler** [comment]
I agree Bill.

**Comment by mattfidler** [comment]
Now handled with focei estimation method.

**Comment by billdenney** [comment]
Great!  Thank you for all your work!
