### ISSUE TITLE
Simulation Question:  How do I perform a fixed-effects-only simulation?

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#326]
How do I perform a fixed-effects-only simulation?

I'd like to perform a fixed-effects-only simulation from my final model.  I just want the mean curve and no inter-individual or residual variability.

I thought that the way to do this would be to generate a zero matrix for both omega and sigma, and then to use that to do the simulations, but I'm getting an error:

```
omega <- lotri(eta_ka~0, eta_cl~0)
sigma <- lotri(prop.err~0, add.err~0)
nlmixrSim(mod_monkey_pk_best, omega=omega, sigma=sigma)
# Compiling model...done
# Error in rxSolveSEXP(object, .ctl, .nms, .xtra, params, events, inits,  : 
#   'omega' must be symmetric, positive definite
```

(Unfortunately, I can't share this reprex.)

**Comment by billdenney** [comment]
I was able to get around this by setting omega and sigma to be very small:

```
omega <- lotri(eta_ka~1e-8, eta_cl~1e-8)
sigma <- lotri(prop.err~1e-8, add.err~1e-8)
```

So, now that I'm thinking about it, the zero matrix is not positive definite, but perhaps a test for a zero matrix could be added for a fixed-effects-only simulation option?  (This would be similar to the `zero_re()` function in mrgsolve.)

**Comment by mattfidler** [comment]
This is a good feature to add.

**Comment by mattfidler** [comment]
I think this should work.
