### ISSUE TITLE
Simplify ini parsing?

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#336]
I think that this section of code does something similar to the parsing that I recently added in #322.  But, with quick inspection, I don't see exactly what is supposed to happen in this section.  Question:  Is this something that should be incorporated into the new bounds code?  If so, can you give the gist of what it is doing?  (I'm not sure how someone would fix or unfix a parameter in an existing model, but from a quick look, that appears to be the main intent of that code.)

https://github.com/nlmixrdevelopment/nlmixr/blob/15ae8563d35477f2ce7c0068db49e93e06fbdba4/R/ui.R#L169-L241

**Comment by mattfidler** [comment]
Hi Bill;  This is the piping;  An example of use would be:

https://nlmixrdevelopment.github.io/nlmixr/articles/modelPiping.html#changing-and-fixing-parameter-values-in-models

It could use the new functions (for brevity, matintainability, etc), but requires an input dataset to work with.

**Comment by mattfidler** [comment]
It is also supposed to work with `update()`, as suggested to me by Mike Smith.

**Comment by billdenney** [comment]
@MikeKSmith is his handle.  :)

Thanks for that pointer.  I think that it would be straight-forward to implement that as a special case of the general initial condition assignment.  It would get a bit more complex to alter an omega matrix if it changed size, but overall, that shouldn't be a problem.

I have a question about `fix` and `unfix` in updating a model, and what do you think that the user's main goal would be.  Overall, I think that I can see a few scenarios:

Set the parameter to a new value, but don't alter the fixed/not fixed.  In the example below, if `fixed` is not specified, it stays in whatever state it was previously:

```r
one.ka.0.5 <- fit %>%
    ini(tka=0.5)
```

`fixed` is still not mentioned, so do not change it

```r
one.ka.0.5 <- fit %>%
    ini(tka=c(0.1, 0.5, 1))
```

`fixed` is mentioned, so override the current status to `fixed` regardless of the current state:

```r
one.ka.0.5 <- fit %>%
    ini(tka=fixed(0.1, 0.5, 1))
```

```r
one.ka.0.5 <- fit %>%
    ini(tka=c(0.1, fixed(0.5), 1))
```

```r
one.ka.0.5 <- fit %>%
    ini(tka=unfixed(0.1, 0.5, 1))
```

Giving both fixed and unfixed in the same assignment when they overlap is an error:

```r
one.ka.0.5 <- fit %>%
    ini(tka=unfixed(0.1, fixed(0.5), 1))
```

Giving both fixed and unfixed when they do not overlap would be valid for omega assignment (but never valid for theta assignment):

```r
one.ka.0.5 <- fit %>%
    ini(eta~c(unfixed(0.1), 0.5, fixed(1)))
```

I *think* that the best way to implement this would be to have an `update()` function, and `ini()` calls the update function when its first argument is a model or a fit model.  The output of the `update()` function would have an option for being either an unevaluated model (not the default) or a fit (take that output model and try to estimate the parameters, the default).

**Comment by mattfidler** [comment]
So @billdenney `update` is already defined that depending on the syntax it will dispatch to `ini` to update the model conditions or `model` to modify a line in the model

**Comment by mattfidler** [comment]
(I simply haven't updated the vignette yet)

**Comment by mattfidler** [comment]
By the way, I agree with your assessment.

**Comment by MikeKSmith** [comment]
> It is also supposed to work with `update()`, as suggested to me by Mike Smith (don't know his handle off-hand)

Hello! The premise of the pipe `%>%` is that it takes the output from the left hand side as the first argument of the next function. So to be consistent with other usage, I think it ought to go to an `update( )` function rather than `model()` or `ini()`. Sounds like Matt has already achieved this.

**Comment by mattfidler** [comment]
We also have to back-check these fixes against the autocovariate search that vipul is working on.

**Comment by billdenney** [comment]
I like @MikeKSmith 's comment in that it would simplify the `ini()` function to be single-purpose and `update()` would cover all the other purposes.  Perhaps for the intermediate term, if the `ini()` use as an `update()` function could be deprecated and just have it call `update()`.

For Vipul's autocovariate search, perhaps it could focus around using `update()` extensively?  (I've not looked at the code at all, but it seems like using `update()` on both the initial conditions and the model is the main part of how the search works on models-- at least from the fitting side.)

**Comment by mattfidler** [comment]
That is fine with me;  You will be doing more with the `update()` function, so there needs to be some tests that the dispatch will go to the correct place. 

Vipul's code currently modifies the `$ini` dateset directly and uses the `model()` function to modify the model.  I would prefer splitting out the model update and the ini update to internal functions so he can use whatever the `model` update function is without much change.

**Comment by billdenney** [comment]
I think that modifying the `$ini` dataset directly will become fragile over time.  I'll work toward `update()` functionality that can be used for the `$ini` dataset.  I'd think that pushing the model through `update()` would also make sense in some fashion, but I've not worked with that, so maybe it could be as simple as `update.model <- model` (not the right names 😄).

**Comment by mattfidler** [comment]
Well the internal functions for translating to the correct syntax for the underlying `foceiFit`, `saemFit` etc, access the dataset directly.  I hope it doesn't become *too* fragile.

**Comment by mattfidler** [comment]
Also the model piping/update tests are currently here:

https://github.com/nlmixrdevelopment/nlmixr/blob/foceiDur/tests/testthat/test-piping.R

**Comment by mattfidler** [comment]
As you can see you can either modify initial conditions or a single line of the model with this syntax.

**Comment by billdenney** [comment]
For fragility, I think that reading the data.frame should be robust.  Writing to it would be more robust if it goes through something else.  (But, reading shouldn't be too fragile, regardless.)

**Comment by mattfidler** [comment]
Ok.  That makes sense.

**Comment by mattfidler** [comment]
I'm assuming this is done?

**Comment by billdenney** [comment]
I missed the status request comment.  I was focusing on `backTransform()`.  I hope to work on this after `backTransform()` is finished since that will have an interaction here.  (There are additional items for `backTransform()` that have not yet been completed including a direct `backTransform()` function and using the backTransform itself in reporting.)

**Comment by mattfidler** [comment]
I believe this is done.
