### ISSUE TITLE
backTransform() in ini block

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#337]
As initially discussed in https://github.com/nlmixrdevelopment/nlmixr/issues/322#issuecomment-650168520 :

I'd like to confirm what will occur with backTransform before implementing it (and it's easier to have it as a separate issue than to have it mixed in with the #322 discussion).

* Similar to `label()`, `backTransform()` will be an attribute that can be applied to a `theta`, `omega`, or `sigma` assignment.
* The backTransform attribute would be stored as a new list column in ini data.frame.  The elements of the list would be either `NULL` or a call.
* If there is no `backTransform()` attribute to the assignment, then the current code-detection method would be used.
    * No `backTransform()` attribute assignment would be stored as `NULL` in the ini data.frame.
* As the stored list element will not have an environment, we will need to be careful about the environment where it is evaluated.    I think that it should be `globalenv()`.
    * **Question**: Do you agree that the evaluation should be in `globalenv()` which would occur at the time of summary?
    * And if so, it would require the user to have the expected `backTransform()` environment available at the time of summary.  This would be a small hurdle if the model were saved in one session and summarized in a separate session, but that will be a problem for some user at some point.
* There are two ways (plus a combination of these) that I can imagine structuring the back-transform.  Which do you prefer (or do you see a preferred third way)?
   * A bare function call which will be evaluated with a single argument, such as: `backTransform(exp)` in the ini block would be evaluated as `exp(x)` when the back transformation occurs
    * A function call with a placeholder argument for the estimated parameter, such as: `backTransform(exp(.))` in the ini block would be evaluated as `exp(x)`.  More importantly, if another parameter were needed, it could be given like, `backTransform(dt(., df=10))`.
        * There are two options if no placeholder (`.` in this proposal) is present: then give an error (this may differ from expectations based on the magrittr pipe) or insert the parameter as an unnamed first argument (that is my preference as it seems more likely to align with expectations, and it is just as straight-forward to implement)..
    * And, the combination could also be possible where either is possible:  If given as a bare name (like, `exp`) evaluate it as a call with a single argument, and if given as a function call with a placeholder use that behavior.
* For back-transformation of omega blocks, I assume that the entire block would be passed as the argument to the back-transformation function rather than a single value at a time.
* If the user specifies the `backTransform()`, that would be used instead of the auto-detected back-transform.  (Always assume that the user knows best if they give information.)
    * Since the current behavior of back-transform relies on the model, in addition to the initial conditions, I think that both the default assignment of back-transformation and the assignment of the `err` column should occur in the same place in the code.  
    * **Question**: I don't know where the back-transform detection occurs in the current code.  Can you please help me find the correct location for assignment of both "err" and the current back-transform?

**Comment by mattfidler** [comment]
> Question: Do you agree that the evaluation should be in globalenv() which would occur at the time of summary?

That would be fine with me, though I know some people wrap some nlmixr functions inside other functions.  That could be problematic.  Perhaps `parent.frame(1)` would be safer, but it gets the environment saving problems.

> Question: I don't know where the back-transform detection occurs in the current code. Can you please help me find the correct location for assignment of both "err" and the current back-transform?

It is currently done in `c++`, hence it is harder to find:

https://github.com/nlmixrdevelopment/nlmixr/blob/15ae8563d35477f2ce7c0068db49e93e06fbdba4/src/inner.cpp#L5027-L5088

> Similar to label(), backTransform() will be an attribute that can be applied to a theta, omega, or sigma assignment.

I'm unsure the utility of the `omega` or `sigma` backtransformation.  It adds the complexity of applying to the whole block, or the block under conditions, etc.  To me I would limit this to `theta` only for now.

**Comment by mattfidler** [comment]
> There are two ways (plus a combination of these) that I can imagine structuring the back-transform. Which do you prefer (or do you see a preferred third way)?

Since this is currently in `c++` it may be more efficient to have it be `backtransform(exp)`.  This way you get around some `R`<->`C hurdles

**Comment by billdenney** [comment]
I think that we can solve the environment issue by adding an `envir` argument to the summary routines that would allow the user to specify the environment.  The default that most users would not touch would be `globalenv()`, but environment assignment would be available, if needed.  In general, I doubt it will be an issue because I don't know many people (anyone?) who transforms using complex code (`exp()`, `logit()`, and a few other common ones are likely to be generally available).

I may rely on you for a bit of help either translating that `c++` to R, or if it is better to stay in `c++`, use the new information on the `c++` side.

Definitely fair to limit it to `theta` for now.

**Comment by mattfidler** [comment]
> Since the current behavior of back-transform relies on the model, in addition to the initial conditions, I think that both the default assignment of back-transformation and the assignment of the err column should occur in the same place in the code.

That is fine, I will help with moving the code or making an accessibility.  In fact we can say that translation `x` is not currently supported.

**Comment by mattfidler** [comment]
I was also going to auto-convert `logit` which is a new feature of `RxODE` `nlmixr`

**Comment by mattfidler** [comment]
Logit may be more complex, because it can take bounds `?logit`

**Comment by billdenney** [comment]
The bounds on `logit()` would suggest that we may need the `fun(., ...)` form.

**Comment by mattfidler** [comment]
That is true since you could try to estimate the bound of `logit(.,...)` but in any case I can think of it would be unidentifiable

**Comment by billdenney** [comment]
Another option for `logit(., ...)` would be that the `backTransform()` could be `backTransform(function(x) logit(x, min=1, max=2))` and then, everything is self-contained (though that is a bit kludgy).

**Comment by billdenney** [comment]
Here's a thought:  Could the C++ side call a model-specific function like `backTransformFromC(x, "tvCL")` where `x` is the value that needs to be back-transformed, and "tvCL" is the parameter name?  Then the back-transform operation could happen on the R side.  If it returned a number, the transform occurred.  If it returned `NULL`, then the transform did not occur and the default transform on the C++ side should happen?

**Comment by mattfidler** [comment]
It could work like that;  It would require  call to R every time the transform is made, but that may be OK.  It will slow down the overall process.  I would prefer a `data.frame` entry.  If it is not "exp" or "logit", or the c-supported transformations then it would call `backTransformFromC(x, "tranformFunction")`, but it could send the `backTransformFromC(x, "parameterName")`

the `logit` could simply be `logit0,1` or `logit1,20` for a logit.

**Comment by billdenney** [comment]
This is starting to sound complex from a code maintenance perspective.

My concern is that back-transforming in multiple locations with anything more complex than "exp" being supported in those locations seems like it would cause more complexity to maintain and keep the code up to date.  I hear you that the cost of calling R from Rcpp should not be minimized.  If I understand correctly, the call would occur at the beginning or end of function evaluation, so it would be called between a few tens to a few thousand times.  It seems like as long as the R call were much less expensive than the evaluation of the model for a single iteration, then the cost may not matter much to the user.

A simplification of only using R for transformation could be that no transformation information would need to come back from C-- only the raw (untransformed) values would be required.  One direction (R to C++ or C++ to R) seems like it will be required for full functionality of transforming, but it seems like it would be easier to only have one and not both directions required/supported.

Do I understand the problem correctly?

**Comment by mattfidler** [comment]
I think if we are going to go the R route we should have one function that back-transforms everything.

If we go the C route we should only back-transform in C.

The more back and forth between R and C the more difficult it becomes to debug and maintain the code (because back-traces get increasingly unreliable, at least that is my experience/understanding). 

So, my proposal is to change the C code to simply store the un-transformed values somewhere, then with the R part of nlmixr  fit you would:

- Query the current `ini` (`fit$uif$ini`)
- Query the default back-transformation (stored somewhere, let me know where you want it to be); Also let me know what the `logit` transformations should be so they can be stored correctly.
- Query the un-transformed values (also stored somewhere let me know what you want it to be)
- Create the `parFixed` and `parFixedDf` data frames and store them in the nlmixr fit object.

This back-transformation would transform the `theta` values and the `%CV` values from the raw values. 

This will probably break the `broom` compatibility functions, but I think that is the most maintainable.

What do you think?

**Comment by mattfidler** [comment]
The "benefit" to this approach is that if you drop a transformation it will do back to the default  and you could specify the CI to update the parameters to.

**Comment by mattfidler** [comment]
I guess I'm going back on the utility of `omega`/`sigma` in this statement. I had forgotten that `%CV` was calculated based on `theta+eta` vs  `exp(theta+eta)`

**Comment by billdenney** [comment]
I do prefer having everything in R for the reasons stated above.  If we go this way, then I think we could do something like:

In the initial conditions block the following would be valid (the model is not valid in this example-- I'm just trying to show some minimal points here):

```r
function() {
  ini({
    a <- 1; backTransform(logit(low=1, high=20))
    b <- 2; backTransform(exp)
    c <- 3
    d <- 4
    e ~ 5
    f ~ 6
  })
  model({
    cInModel <- exp(c + e)
    dInModel <- d + f
  })
}
```

That would yield an ini block after processing of `$ini` alone as follows (only showing the name and backTransform columns; all the other columns would remain as previously defined):

```r
data.frame(
name=c("a", "b", "c", "d", "e", "f"),
backTransform=list(str2lang("logit(low=1, high=20)"), str2lang("exp"), NULL, NULL, NULL, NULL)
)
```

After processing the model block, the ini block would be modified to look like (the difference is `c`, `e`, and `f` now have `backTransform` values; note that the code doesn't work as written because R tries to evaluate the calls).  There is not enough definition of the `omega_cv_exp()` function yet; it would also have to accept the theta values, too.

```r
data.frame(
  name=c("a", "b", "c", "d", "e", "f"),
  backTransform=
    list(
      quote(logit(low=1, high=20)),
      quote(exp),
      quote(exp),
      NULL,
      quote(omega_cv_exp(theta='c')),
      quote(omega_cv_linear)
    )
)
```

Then outside of the ini and model blocks, the following function could be used from C++ or R to get the back-transformed values.

`backTransform(unTransformedValues, model, parameterNames)`

If we could assume that the parameter `unTransformedValues` and `parameterNames` are always in the order from the `$ini` block, then we could drop the `parameterNames` argument.

The use of `backTransform()` differently in different places (ini block vs R function/script) could be confusing.

**Comment by mattfidler** [comment]
> The use of backTransform() differently in different places (ini block vs R function/script) could be confusing.

It could be;  There should be some access point to transform these values, though.  In that access point, it should have `model` as the first argument so it could be piped if they wanted to pipe it.

> If we could assume that the parameter unTransformedValues and parameterNames are always in the order from the $ini block, then we could drop the parameterNames argument.

If we make a user-facing function I don't know if we can assume this. 


> note that the code doesn't work as written because R tries to evaluate the calls

I suggest we store them as strings instead;  That way the defaults will match what I can easily put into C and there will not be a mismatch between the C generated values and the `ini` expressions.  When there is no transformation it would simply be an empty string `""`

**Comment by mattfidler** [comment]
One possibly confusing point is the back-transformation while running the optimization.  For the reasons discussed above, I don't favor a R back-transformation while doing the printout.  Therefore, the user-specified back-transformations  will not be honored in C while back-transforming the values.

**Comment by billdenney** [comment]
All of your points 2 comments ago make sense.

> One possibly confusing point is the back-transformation while running the optimization. For the reasons discussed above, I don't favor a R back-transformation while doing the printout. Therefore, the R-based user-specified back-transformations will not be honored in C while back-transforming the values.

I agree that this will be confusing to the user.  We would need to have something printed out to say something like "Not all values will be back-transformed for printing during optimization" or better yet "The following values will not be back-transformed during optmization: foo, ..." (Or something more translatable 😄.)

That said, I think that we have enough here to take some steps forward.

**Comment by mattfidler** [comment]
The untransformed values can be a data.frame with the following columns:

- `Estimate`  (numeric)
- `Standard Error` (numeric; NA_REAL for missing values that were not calculated)
- `Fixed` logical (may not necessarily match the requested fixed parameters)
- `Transform` string based on inferred back-transformation or specified back-transformation if it exists (which may be honored in C if it can be easily parsed in C).

But this would simply be the un-transformed fixed effects.  

When trying to track this down, the `omega` transformations are handled here:

https://github.com/nlmixrdevelopment/nlmixr/blob/15ae8563d35477f2ce7c0068db49e93e06fbdba4/R/foceiFit.R#L1534-L1628


Here:
- the etas are matched up with mu-referenced fixed effect values
- the transformation is applied

I actually don't have a good way to show:
-  the non-`mu`-referenced items
- the different nesting levels (when they are allowed to be estimated, which is actually getting closer for `focei`)

**Comment by mattfidler** [comment]
The un-transformed values are stored in `fit$popDf`
