### ISSUE TITLE
Add `cor()` option for omega initial conditions

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#338]
And if you want to give a new feature to bounds, you could consider:
 
```r
a + b ~ cor(...)
```

To specify the correlation matrix/Sd values and then translate them to the covariance matrix

_Originally posted by @mattfidler in https://github.com/nlmixrdevelopment/nlmixr/issues/322#issuecomment-649461526_

**Comment by billdenney** [comment]
Originally from https://github.com/nlmixrdevelopment/nlmixr/issues/322#issuecomment-650218788 :

The only unhandled case I can think of otherwise is if you add cor to a matrix; Then:

```r
cor(fixed(...)) 
fixed(cor(...))
cor(..,fixed(.),...)
```

should all work.

**Comment by mattfidler** [comment]
Since nlmixr translates cor->var the onlly way you can have fixed components is if the full submatrix is fixed.

Is this implemented now?

**Comment by billdenney** [comment]
Does your comment mean that these are valid

```r
cor(fixed(...)) 
fixed(cor(...))
```

while this is invalid

```r
cor(..,fixed(.),...)
```

It's not yet implemented.  I hope to implement it tomorrow.

**Comment by mattfidler** [comment]
Yes, because if you transform a sd/corr matrix you cannot fix any of the components (I think).  Perhaps you can fix a zero correlation.  I suppose the same is true for variances.

**Comment by mattfidler** [comment]
No pressure from my side (FYI).  Just read it and thought it was implemented in your fix.

**Comment by billdenney** [comment]
In general, I'd be surprised if someone intentionally fixed an off-diagonal in a covariance or correlation matrix.  But that said, I know that I do weird things all the time, and others may as well.

I can implement a rule that no off-diagonals can be fixed, but that said, I can imagine some methods (mainly Bayesian ones) could support fixed off-diagonal elements.

With a quick look, I think that this is a new feature that has not been previously implemented in nlmixr.  In terms of implementing this:

* I assume that when processing a `cor(...)`, it would be interpreted such that the diagonals are variances and the off-diagonals are correlations.
* To store the actual values, they would be transformed to variances.
    * So, there would be no indication in `$ini` that it started as a correlation.
* Since it would be similar effort in the same part of the code, should `sd(...)` be supported so that standard deviations are provided instead of variances?  (So the matrix would be squared to compute variances.)
    * If yes, should sd(cor(...)) be handled similarly that off diagonals are correlations and diagonals are standard deviations?  (Order of calling the functions would not be important, so `sd(cor(fixed(...)))` could have any nesting order for the function calls.)

**Comment by mattfidler** [comment]
Typically the diagonals are standard deviations (like nonmem and elsewhere in R).  This is also what is stored in `fit$omegaR`.

I don't think you should support anything other than sd diagonals and correlation off-diagonals.

**Comment by billdenney** [comment]
I'm working on this now, and I think that it would be simpler to use the `formulops::modify_formula()` function to investigate the use of `cor()` (and it could also simplify the `fixed()` code).  Would it be OK to add that package as a dependency?  (https://cran.r-project.org/package=formulops)

It depends on nothing else (other than R), and for disclosure, I'm the author (and maybe the only user).

**Comment by mattfidler** [comment]
Hi Bill;  

I do not wish to add any dependencies to `nlmixr`, in fact I wish to remove dependencies because of the shifting CRAN requirements. So, no I do not want to add the package as a dependency. 

At the same time, I appreciate that it may make it easier for you to work with this code.  So, as a compromise I wouldn't mind moving all of this to `lotri` and having `lotri` depend on `formulops`.  Since `lotri`  only depends on `R` at the moment, there is no risk to CRAN with this change. 

As a benefit of this move, the long-term maintenance one package that does the same or similar things is better than doing the same or similar things in different places.

What do you think?

**Comment by billdenney** [comment]
I fully understand not wanting to have more dependencies.

Given the specific need right now, I'll just write some additional custom code within nlmixr.  I may change my mind on this in the future in which case I'll either add the function to `nlmixr` or `lotri`.  (I'd hesitate to add it to `lotri` due to the fact that it's not exactly in the scope of the `lotri` package, but that can be discussed later.)

**Comment by mattfidler** [comment]
I believe this is fixed.
