### ISSUE TITLE
Error running nlmixr

### ISSUE THREAD

**Issue by rxtms** [nlmixrdevelopment/nlmixr#34]
Hello,

I've been trying to run the example to test the newly installed nlmixr package but keeping seeing this error message quickly after this part:

> fit <- nlmixr(uif, theo_sd, est="nlme", calc.resid=FALSE)
Error: 'rxIs' is not an exported object from 'namespace:RxODE'

 I've even tried reinstalling but still no luck. Does anyone know what's the problem?

**Comment by wwang-at-github** [comment]
may need to install the most recent version of RxODE.

**Comment by rxtms** [comment]
I've tried reinstalling using the Windows binary download and check update of the packages but till no luck. Even got this error message when loading RxODE:

> Loading required package: nlme
Loading required package: RxODE
Warning message:
package ‘RxODE’ was built under R version 3.4.3 

So I think that should be the most recent RxODE package, but still getting the same error as above.

**Comment by mattfidler** [comment]
Could you please put your R session information in so we can help you a bit
more.  The command for this should be sessionInfo()

**Comment by rxtms** [comment]
This is the session info I have right after having the error message:

sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252 
[2] LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252
[4] LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] nlmixr_0.9.0-2 RxODE_0.6-1    nlme_3.1-131   ggplot2_2.2.1 

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15     lattice_0.20-35  digest_0.6.12   
 [4] lbfgs_1.2.1      grid_3.4.2       plyr_1.8.4      
 [7] gtable_0.2.0     magrittr_1.5     scales_0.5.0    
[10] rlang_0.1.2      lazyeval_0.2.0   rex_1.1.2       
[13] brew_1.0-6       labeling_0.3     munsell_0.4.3   
[16] parallel_3.4.2   compiler_3.4.2   colorspace_1.3-2
[19] memoise_1.1.0    tibble_1.3.4    

>

**Comment by mattfidler** [comment]
You can likely fix this by

devtools::install_github("nlmixrdevelopment/RxODE", ref="v0.6-2")

If you have the devtools package installed

**Comment by rxtms** [comment]
This is the error I got when trying to use the devtools command:

devtools::install_github("nlmixrdevelopment/RxODE", ref="v0.6-2")
Downloading GitHub repo nlmixrdevelopment/RxODE@v0.6-2
from URL https://api.github.com/repos/nlmixrdevelopment/RxODE/zipball/v0.6-2
Installing RxODE
"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/más/AppData/Local/Temp/RtmpqUi0Hk/devtools1d047cc1551b/nlmixrdevelopment-RxODE-09c7274"  \
  --library="C:/Users/más/Documents/R/win-library/3.4"  \
  --install-tests 

* intalling *source* package 'RxODE' ...
Warning in file(file, if (append) "a" else "w") :
  cannot open file 'C:/Users/mas/Documents/R/win-library/3.4/RxODE/DESCRIPTION': No such file or directory
Error in file(file, if (append) "a" else "w") : 
  cannot open the connection
ERROR: installing package DESCRIPTION failed for package 'RxODE'
* removing 'C:/Users/más/Documents/R/win-library/3.4/RxODE'
* restoring previous 'C:/Users/más/Documents/R/win-library/3.4/RxODE'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by rxtms** [comment]
This is the error I got when trying to use the devtools command:

devtools::install_github("nlmixrdevelopment/RxODE", ref="v0.6-2")
Downloading GitHub repo nlmixrdevelopment/RxODE@v0.6-2
from URL https://api.github.com/repos/nlmixrdevelopment/RxODE/zipball/v0.6-2
Installing RxODE
"C:/Users/más/AppData/Local/nlmixr/R/bin/x64/R" --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/más/AppData/Local/Temp/RtmpoLWHbL/devtools17ec722435ff/nlmixrdevelopment-RxODE-09c7274"  \
  --library="C:/Users/más/Documents/R/win-library/3.4"  \
  --install-tests 

* installing *source* package 'RxODE' ...
Warning in file(file, if (append) "a" else "w") :
  cannot open file 'C:/Users/mas/Documents/R/win-library/3.4/RxODE/DESCRIPTION': No such file or directory
Error in file(file, if (append) "a" else "w") : 
  cannot open the connection
ERROR: installing package DESCRIPTION failed for package 'RxODE'
* removing 'C:/Users/más/Documents/R/win-library/3.4/RxODE'
* restoring previous 'C:/Users/más/Documents/R/win-library/3.4/RxODE'
Installation failed: Command failed (1)

**Comment by mattfidler** [comment]
Hm.   I haven't seen that error before;

Since you are having problems and you seem to be on windows I *highly* suggest you use the installer.  Note that it does not require administrator access

https://github.com/nlmixrdevelopment/nlmixr/releases/download/v0.9.0-2/nlmixr_0.9.0-2_i386_install.exe

or 

https://github.com/nlmixrdevelopment/nlmixr/releases/download/v0.9.0-2/nlmixr_0.9.0-2_x86_64_install.exe

**Comment by rxtms** [comment]
I've been using the version installed by the Windows installer this whole time already as suggested, and the error messages were from that. I do have another R installation on my computer, not sure if that's a problem?

Could I please check if the location I install the nlmixr package (using the Windows installer) would make a difference?

**Comment by mattfidler** [comment]
I'm not sure if the issue is with where you installed it, but it could be likely.  

The location you install nlmixr to must have write access for all users.  Places like "Program Files" do not have write access.  

The default install location *should* have read-write capabilities for the curren user.

**Comment by mattfidler** [comment]
I have multiple R installations on my computer so this shouldn't be an issue.

**Comment by kestrel99** [comment]
Are you still having issues running nlmixr?

**Comment by rxtms** [comment]
Thanks for checking. Yes, the issues above remain unresolved but I'm out of ideas what else I can try..

**Comment by rxtms** [comment]
Hello,

Thanks so much for your reply. I tried the installation again with your suggestions. 

I used the Windows installer, but this time, instead of the default location, I installed the nlmixr package in C:/. Then I edited the Rprofile.site file as you suggested and it worked!

When checking with the .libPaths() command, I realised the nlmixr R session was checking two library folders, one that came with the nlmixr installation and one with another R installation on my computer in the user folder with the accented "a" as you pointed out. After editing the Rprofile.site, the nlmixr R session now only refers to the library folder within the nlmixr installation and it worked without the error message. 

I was testing the nlmixr installation with codes in this example:
https://cran.r-project.org/web/packages/nlmixr/vignettes/running_nlmixr.html

As another note, I saw an error message when trying to install the xpose.nlmixr extension in the example. Having said that, the plot functions in the example still seem to work ok though. Not sure if the example on the website is up-to-date?

Thanks so much for the help again!

**Comment by mattfidler** [comment]
Thanks @rxtms ;  You are right; the example is out of sync with the installed version.

For the installed version you only need to include `library(xpose)` for the nlmixr/xpose functionality.

The `xpose` developers wanted to have the `nlmixr` integration in a separate package, so we created a separate package `xpose.nlmixr`.

We are about to create a new installer package with `xpose.nlmixr` and `xpose`; In that version you would need to have both libraries

**Comment by rxtms** [comment]
Thank you. I look forward to the new version then.
