### ISSUE TITLE
(Long term) Feature Request: QR reparameterization to Improve Sampling Efficiency

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#340]
nlmixr has many of the components already available that could be used to automatically perform QR-reparameterization as is done described in the Stan manual (https://mc-stan.org/docs/2_23/stan-users-guide/QR-reparameterization-section.html) and as I believe is done with the PsN `precond` command (https://github.com/UUPharmacometrics/PsN/releases/download/4.9.0/precond_userguide.pdf).

1. As a first step, this could likely be done with something like the way that the PsN precond command works where it occurs on a completed model, but
2. I could imagine a step better where the initial Hessian for the model is calculated based on the initial conditions, and that is then preconditioned, and that newly preconditioned model is what is actually estimated, or
3. It could occur at the end of estimation, similar to the way that `SADDLE_RESET` works with NONMEM, and
4. As a final augmentation, I could imagine that at every Hessian re-estimation (I assume Hessian re-estimations occur for at least some of the estimation types), it updates the preconditioning matrix and the estimate methods.

Doing this with a completed model sounds like it could be done approximately today with the `update()` command or even just code-generation from an existing model.  Doing this with the initial Hessian seems like it could be relatively feasible, if there is a way to get the Hessian before a model is first estimated.  Doing it during estimation seems... harder (and it may invalidate model estimation methods).

What are your thoughts?

**Comment by mattfidler** [comment]
In short it is doable, but will take alot of effort.

> I could imagine a step better where the initial Hessian for the model is calculated based on the initial conditions, and that is then preconditioned, and that newly preconditioned model is what is actually estimated,

I think the assumptions of the Hessian being a good estimate for the covariance makes the assumption that you are near a global/local minimum, so I don't think this is possible from a theoretical point of view, but may be possible if you can linearize your model (and you trust the linearization). 

This may be part of the reason why `PsN` only uses the end model.

The way I read the `PsN` manual, to calculate the `QR`-re-paramterization for the non-linear mixed effect we would have to:

- Linearize the nonlinear mixed effect model (which is not present in nlmixr currently), but is part of `PsN`.  Talking with Rikard, this requires calculating the focei problem, and then applying some math.  So it is doable, but hasn't even been looked at yet.
- Re-parameterize this nonlinear mixed effect problem to a linear problem, and then calculate the Hessian based on this linearized problem.
- Further re-parameterize to the `QR`-resampled problem.

This will assume the linearization is appropriate throughout the minimization process.

On the other hand, the linearized model may be more appropriate to calculate the covariance here because of the underlying assumptions of the Hessian being a good estimate for the covariance makes the underlying assumption of linearity.

This would require more research to get right.

> It could occur at the end of estimation, similar to the way that SADDLE_RESET works with NONMEM,

Possibly a waning that suggests the reset?  That would be possible;  You could also do other things like `SIR` or `bootstrap` for more accurate covariances too.

> As a final augmentation, I could imagine that at every Hessian re-estimation (I assume Hessian re-estimations occur for at least some of the estimation types), it updates the preconditioning matrix and the estimate methods.

The hessian re-estimation does not occur for `saem`, or `nlme`.

The hessian reset in `nlmixr`'s focei occurs in the inner problem, which doesn't apply here.  There is a possibility that hessians are reset in the outer-problem but it would be estimation specific, and would require modifying the estimation engines, which I didn't write myself and would be hard to reset.  Currently the global hessian is not stored for the re-estimation with a "theta" reset.

In some estimation routines the overall hessian is never reset. For example you can use `outerOpt="bobyqa"` and no hessian is stored, reset or used.

**Comment by billdenney** [comment]
Thank you for the detailed answer.  I didn't realize that linearization was a prerequisite; I thought that approximate linearity was assumed at the minimum (and as it applied at the minimum, I assumed that it was a reasonable approximation at other points).

I'll close this as it seems premature given the current state.

**Comment by mattfidler** [comment]
I will check with Rikard and others the next time I see them to make sure my understanding is correct.

**Comment by mattfidler** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4779107/pdf/12248_2016_Article_9866.pdf

Does not require linearization.  

Currently the matrices inverses are calculated using:
 - penrose moore decomposition
 - `sqrtm`

Perhaps pre-conditioning can be added here.

**Comment by mattfidler** [comment]
One other method is the generalized cholesky decomposition for inverses.

**Comment by mattfidler** [comment]
Code can be from here:

https://github.com/styvon/cPCG/blob/master/src/rcpparma_cPCG.cpp

**Comment by mattfidler** [comment]
Not the same type of preconditioning.

**Comment by mattfidler** [comment]
It is 99% complete;  You said modifying the `$ini` is "fragile", so I can't proceed until you say how it is fragile.

**Comment by mattfidler** [comment]
Also in the paper from Uppusla, the following is stated:

- Estimate the parameters and variance-covariance matrix of the preconditioned model using NONMEM (Is this a full estimation;  I could you a posthoc where the ETA values are fixed to simply calculate the covariance again, or have the option of both)

**Comment by billdenney** [comment]
Woah!

I was too harsh when I said that modifying `$ini` is fragile.  Modifying `$ini` is fragile in that it can have errors when manually modified (such as getting making estimates above lower or upper bounds).  I'd say at this point, if you modify it and then run `as.nlmixrBounds()` on the updated data.frame without error, everything should be fine.

**Comment by mattfidler** [comment]
Ok;  Once you fix the R-based back-transformation it could be added back to the original fit

Here is it running now:

``` r
library(nlmixr)
one.compartment <- function() {
  ini({
    tka <- 0.45 # Log Ka
    tcl <- 1 # Log Cl
    tv <- 3.45    # Log V
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    d/dt(depot) = -ka * depot
    d/dt(center) = ka * depot - cl / v * center
    cp = center / v
    cp ~ add(add.sd)
  })
}

fit2 <- nlmixr(one.compartment, theo_sd, est="focei",control=list(print=0))
#> ℹ parameter labels from comments will be replaced by 'label()'
#> creating full model...pruning branches (if/else)...done
#> loading into symengine environment...done
#> creating full model...pruning branches (if/else)...done
#> loading into symengine environment...done
#> calculate jacobian
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> calculate sensitivities
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> calculate ∂(f)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> calculate ∂(R²)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> finding duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> optimizing duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> finding duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> optimizing duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> compiling inner model...done
#> compiling EBE model...done
#> Calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00 
#> done
#> Calculating residuals/tables
#> done.
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =
#> FALSE, : Initial ETAs were nudged; (Can control by foceiControl(etaNudge=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod
#> = FALSE, : ETAs were reset to zero during optimization; (Can control by
#> foceiControl(resetEtaP=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =
#> FALSE, : Gradient problems with initial estimate and covariance; see $scaleInfo

fitP <- nlmixr:::preconditionFit(fit2)
#> creating full model...pruning branches (if/else)...done
#> loading into symengine environment...done
#> creating full model...pruning branches (if/else)...done
#> loading into symengine environment...done
#> calculate jacobian
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> calculate sensitivities
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> calculate ∂(f)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> calculate ∂(R²)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> finding duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> optimizing duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> finding duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> optimizing duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> compiling inner model...done
#> compiling EBE model...done
#> Calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====] 0:00:01 
#> done
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =
#> FALSE, : Initial ETAs were nudged; (Can control by foceiControl(etaNudge=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod
#> = FALSE, : ETAs were reset to zero during optimization; (Can control by
#> foceiControl(resetEtaP=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =
#> FALSE, : Gradient problems with initial estimate and covariance; see $scaleInfo


print(fit2$cov)
#>             tka         tcl          tv
#> tka 0.043635549 0.002590939 0.003330886
#> tcl 0.002590939 0.008896599 0.002698144
#> tv  0.003330886 0.002698144 0.001621235

print(fitP)
#>             tka         tcl          tv
#> tka 0.044345453 0.000208037 0.005235258
#> tcl 0.000208037 0.002307597 0.001696523
#> tv  0.005235258 0.001696523 0.003465803
```

<sup>Created on 2020-07-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattfidler** [comment]
I suppose I should add the `as.nlmixrBounds` to test this.

**Comment by mattfidler** [comment]
This likely won't work with `saem` as is in `nlmixr`.  The `theta`/`eta`s need to be mu-referenced.

**Comment by mattfidler** [comment]
``` r
library(nlmixr)
one.compartment <- function() {
  ini({
    tka <- 0.45 # Log Ka
    tcl <- 1 # Log Cl
    tv <- 3.45    # Log V
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    d/dt(depot) = -ka * depot
    d/dt(center) = ka * depot - cl / v * center
    cp = center / v
    cp ~ add(add.sd)
  })
}

fit2 <- nlmixr(one.compartment, theo_sd, est="focei",control=list(print=0))
#> ℹ parameter labels from comments will be replaced by 'label()'
#> → creating full model...
#> → pruning branches (`if`/`else`)...
#> ✔ done
#> → loading into symengine environment...
#> ✔ done
#> → creating full model...
#> → pruning branches (`if`/`else`)...
#> ✔ done
#> → loading into symengine environment...
#> ✔ done
#> → calculate jacobian
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → calculate sensitivities
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → calculate ∂(f)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → calculate ∂(R²)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → finding duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → optimizing duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → finding duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → optimizing duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → compiling inner model...
#> ✔ done
#> → compiling EBE model...
#> ✔ done
#> RxODE 0.9.2.0 using 4 threads (see ?getRxThreads)
#> calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00 
#> done
#> Calculating residuals/tables
#> done.
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =
#> FALSE, : initial ETAs were nudged; (can control by foceiControl(etaNudge=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod
#> = FALSE, : ETAs were reset to zero during optimization; (Can control by
#> foceiControl(resetEtaP=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =
#> FALSE, : gradient problems with initial estimate and covariance; see $scaleInfo

print(fit2$cov)
#>             tka         tcl          tv
#> tka 0.043635549 0.002590939 0.003330886
#> tcl 0.002590939 0.008896599 0.002698144
#> tv  0.003330886 0.002698144 0.001621235

preconditionFit(fit2)
#> → creating full model...
#> → pruning branches (`if`/`else`)...
#> ✔ done
#> → loading into symengine environment...
#> ✔ done
#> → creating full model...
#> → pruning branches (`if`/`else`)...
#> ✔ done
#> → loading into symengine environment...
#> ✔ done
#> → calculate jacobian
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → calculate sensitivities
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → calculate ∂(f)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → calculate ∂(R²)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → finding duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → optimizing duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → finding duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → optimizing duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → compiling inner model...
#> ✔ done
#> → compiling EBE model...
#> ✔ done
#> calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00 
#> done
#> → creating full model...
#> → pruning branches (`if`/`else`)...
#> ✔ done
#> → loading into symengine environment...
#> ✔ done
#> → creating full model...
#> → pruning branches (`if`/`else`)...
#> ✔ done
#> → loading into symengine environment...
#> ✔ done
#> → calculate jacobian
#> [====|====|====|====|====|====|====|====|====|====
#> → calculate sensitivities
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → calculate ∂(f)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → calculate ∂(R²)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → finding duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → optimizing duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → finding duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → optimizing duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → compiling inner model...
#> ✔ done
#> → compiling EBE model...
#> ✔ done
#> Warning in foceiFitCpp_(.ret): initial ETAs were nudged; (can control by
#> foceiControl(etaNudge=.))
#> Warning in foceiFitCpp_(.ret): ETAs were reset to zero during optimization; (Can
#> control by foceiControl(resetEtaP=.))
#> calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00 
#> ] 0:00:00
#> Warning in foceiFitCpp_(.ret): gradient problems with covariance; see $scaleInfo
#> Updated original fit object fit2

print(fit2$cov)
#>             tka         tcl          tv
#> tka 0.042932728 0.002836711 0.003183212
#> tcl 0.002836711 0.010167710 0.002893438
#> tv  0.003183212 0.002893438 0.001549105
```

<sup>Created on 2020-07-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Currently the maximum number of retries is `10`

**Comment by mattfidler** [comment]
https://github.com/nlmixrdevelopment/nlmixr/pull/384

**Comment by billdenney** [comment]
This looks nice!

**Comment by mattfidler** [comment]
It doesn't have:
- cholesky decomposition of R matrix (in PsN)
- lu factorization of R matrix (in PsN)
- reparamterization of bounds, reset to infinite (as in PsN)
- only preconditions `theta` bounds (but nlmixr only estimates covariance for theta terms)
- Only works with `fo` methods of calculating covariances.
