### ISSUE TITLE
linCmt() with bioavailability?

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#344]
I'm trying to do simultaneous fitting of oral and IV data.  I'd like to do it with `linCmt()` to speed things up a bit.  But, I don't see where the arguments required for `linCmt()` are documented.  (They seem to borrow from the `pmxTools` library, which also does not support bioavailability that I know of.)

So the questions are:

* Can `linCmt()` fit with multiple routes of administration simultaneously?
* Can `linCmt()` fit bioavailability?  (Not relevant if the first answer is "no".)
* Are/where are the arguments required for `linCmt()` documented?  (I checked `?nlmixr::linCmt` (which doesn't exist), `?nlmixr::lincmt`, and I got to `?RxODE::rxGetLin`.

**Comment by mattfidler** [comment]
- `linCmt()` allows multiple routes of administration and defines 2 compartments:  `depot` and `central`.  You can mix doses to each type of compartment (though I'm unsure the utility of infusions to the depot compartment).
- If you want to add bio-availability you can add `f(depot)=` or `f(central)=`;  This is also true of `rate` `dur` `alag`
- `linCmt()`  has no arguments.  It infers the type of model from the parameters defined;  This is outdated but https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-model-types.html#solved-compartment-models shows what that means. (it would be helpful to document, I  agree, even if it is in a pseudo function `linCmt()`.
- `linCmt()`  does not borrow any code or solutions from `pmxTools`.  Instead it use the so-called `advan` solutions which solve based on the last concentrations in each of the tracked solutions (which means you can use time varying covariates).  The 3 compartment model sensitivities are too large to parse and are not supported at this time (or rather use the autodifferentiation solutions from stan whcih are slower than solving the ode). 
- For the `fo` family of methods, the bioavailibility, rate, duration and lag times will work *as long as there is only one for the whole population*.   The sensitivities of these additional parameters are a work in progress for the 1-3 compartment solutions.
- For `saem` and `nlme` the `linCmt()` will work with  individual differences of `f`, `rate`, `dur`, etc.  However `cwres` is unreliable until the senstivities are calculated.

**Comment by jpryby** [comment]
> * For the `fo` family of methods, the bioavailibility, rate, duration and lag times will work _as long as there is only one for the whole population_.   The sensitivities of these additional parameters are a work in progress for the 1-3 compartment solutions.

Do this exclude covariate modeling for these parameters (e.g., formulation-based bioavailability), or just sensitivities (e.g., eta.F1 will be ignored)? Just clarifying, thanks!

**Comment by mattfidler** [comment]
Covariates are OK.  Only etas are problematic.

**Comment by mattfidler** [comment]
This applies to the development branches. If you need instructions about installing them let me know.

**Comment by jpryby** [comment]
Will do. I'm just keeping track of the ongoing changes. Do the current production branches not support covariate modeling on bioavailability (etc)?

**Comment by mattfidler** [comment]
Yes.  Stepwise covariate modeling is being worked on now.

Matt

**Comment by jpryby** [comment]
> This applies to the development branches. If you need instructions about installing them let me know.

Hi Matt, I'm now wanting to test some of this on the development branch. Mind sharing those instructions? I couldn't find a more recent branch than master. Also, is the dev branch python-free? That would be a plus.

**Comment by mattfidler** [comment]
Yes the dev branch is python free;  

The instructions are in a RxODE issue:

https://github.com/nlmixrdevelopment/RxODE/issues/170#issuecomment-598264024

**Comment by filippo-ciceri** [comment]
> * `linCmt()` allows multiple routes of administration and defines 2 compartments:  `depot` and `central`.  You can mix doses to each type of compartment (though I'm unsure the utility of infusions to the depot compartment).
> * If you want to add bio-availability you can add `f(depot)=` or `f(central)=`;  This is also true of `rate` `dur` `alag`

Where exactly do we need to add `f(central)=` to change bio-availability  for the model?
I am trying to fit a model adjusting F based on the dose administered. So the idea is to do something like this:

```
one.cmt <- function() {
  ini({
    ...
    f_mod <- c(0, 0.5, 1)
    ...
  })
  model({
    cl <- tcl*exp(eta.cl) * ...
    ka <- tka*exp(eta.ka)
    v <- tv*exp(eta.v) * ...
    f(central) <- 1 - f_mod * (DOSE > ...)
    linCmt() ~ prop(prop_err)
  })
}
```

Thank you very much in advance.
Filippo

**Comment by mattfidler** [comment]
Yes. This is the idea.  

Let me know if there is some problem in the way this works for you.

Matt

**Comment by filippo-ciceri** [comment]
With the setup above I get the following error message:

`Error in rxModelVars_(obj) : Evaluation error: syntax errors (see above).`

**Comment by mattfidler** [comment]
It should show where the error is located.  

If this is not enough, you could try to make a reproducible example with github

**Comment by filippo-ciceri** [comment]
Thank you I eventually worked out the error.

**Comment by pharmax-lisa** [comment]
Hi I'm trying to use rxode2 to create a model that is a modified release model with two depots. We were able to use NONMEM to estimate F1(bioavailability of modified release)  and F3 (bioavailability of immediate release). The model works great but it's not picking up F1 or F3. 

ode <- "
C2=centr/V2;

C4=peri1/V4;

d/dt(depot) = -K12*depot*F1;   #F1 and K12 and ALAG are MR
alag(depot) = lag1;

d/dt(centr)= F1*depot*K12+F3*depot2*K32-CL*C2-Q*(C2-C4);
d/dt(depot2) = -K32*depot2*F3;   #F3 is IR

d/dt(peri1) = Q*(C2-C4);
"
And this dosing event:
ev$add.dosing(dose = dose, nbr.doses = ncyc, dosing.interval = reg,
                start.time=0,cmt="depot")
  ev$add.dosing(dose = dose, nbr.doses = ncyc, dosing.interval = reg,
                start.time=0,cmt="depot2")

Please help! Thanks in advance.
Lisa

**Comment by mattfidler** [comment]
As a note, etas on bioavailability is implemented in `nlmixr2`
