### ISSUE TITLE
drake/nlmixr Interaction Can Fail

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#354]
This issue is intended to accumulate questions and issues related to the interaction between nlmixr and drake.  There are likely several different subtle ways that nlmixr and drake do not interact well, and they can be parsed out into separate issues as it becomes the right time to try to fix them (as discussed in #311).

Other pointers to interaction issues are:

* ropensci/drake#910 (initial conditions cannot be set)
    * duplicate: ropensci/drake#1318
* #311
* #314

Generally, to work well with drake, code must be self-contained and must be able to restart without any external interactions.  Examples of typical errors are:

* Assignment to the global environment (or more generally an environment that is not local to the drake target)
* Loading external files and code from disk (for example, if a model was previously compiled, the cached, compiled model object may no longer exist)

**Comment by billdenney** [comment]
One issue is:

When attempting to calculate the log-likelihood on a model in a `drake` plan (in a new session), a file in the temporary directory no longer exists:

```r
In addition: Warning message:
In file(file, "r") :
  cannot open file 'C:\Users\BILLDE~1\AppData\Local\Temp\RtmpWeOqmC\filee084954317e': No such file or directory
```

I am guessing that this is the compiled model (but since it does not end in .dll, I'm not sure).  If that is correct, one fix could be to check for the file and regenerate it, if required.

The full traceback is:

```
     x
  1. \-global::make_aic_table(...)
  2.   \-`%>%`(...)
  3.     +-base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  4.     \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
  5.       \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
  6.         \-`_fseq`(`_lhs`)
  7.           \-magrittr::freduce(value, `_function_list`)
  8.             \-function_list[[i]](value)
  9.               \-PKNCA:::AIC.list(., assess.best = FALSE)
 10.                 \-base::lapply(...)
 11.                   \-PKNCA:::FUN(X[[i]], ...)
 12.                     +-stats::AIC(subobject, ...)
 13.                     \-stats:::AIC.default(subobject, ...)
 14.                       +-stats:::ll(object)
 15.                       \-nlmixr:::logLik.nlmixrFitData(object)
 16.                         +-object$logLik
 17.                         \-nlmixr:::`$.nlmixrFitData`(object, "logLik")
 18.                           \-nlmixr:::`$.nlmixrFitCore`(.env, arg, exact)
 19.                             \-nlmixr::setOfv(obj, paste0("gauss", .nnodes, "_", .nsd))
 20.                               \-nlmixr::calc.2LL(x$saem, nnodes.gq = .nnode, nsd.gq = .nsd)
 21.                                 +-base::matrix(...)
 22.                                 \-base::scan(saem.cfg$phiMFile, quiet = TRUE)
 23.                                   \-base::file(file, "r")
```

I haven't looked into the code for why the `$phiMFile` is written to disk instead of being stored in the object, but another option could be to store the matrix in the object (maybe it can get huge... would be a reason not to store it in the object).

**Comment by mattfidler** [comment]
I put the file in the `RxODE.cache.directory`;  

Depending on what CRAN requires it will be the R cache directory (or the temporary directory), but you can  set it to a location that will not be deleted.  This may help.

**Comment by mattfidler** [comment]
Is this working @billdenney ?

**Comment by billdenney** [comment]
I haven't had a chance to specifically test for this recently, but I have run SAEM within drake recently without issue.  I'm guessing it is okay now.

**Comment by mattfidler** [comment]
Right now it is in the R cache directory
