### ISSUE TITLE
Catch no eta in `fo` methods earlier

### ISSUE THREAD

**Issue by mattfidler** [nlmixrdevelopment/nlmixr#356]
See https://github.com/nlmixrdevelopment/RxODE/issues/234#issuecomment-654512502

**Comment by billdenney** [comment]
I'm not sure how much earlier you wanted to catch it, but the error message is now clear to me with:

```
Error: cannot identify parameters for sensitivity analysis
   with nlmixr an 'eta' initial estimate must use '~'
```

If this was the goal, it can be closed.

**Comment by mattfidler** [comment]
Probably saves time if it is before in nlmixr.  Also can dispatch to a
different method.

**Comment by mattfidler** [comment]
Not applicable anymore

**Comment by billdenney** [comment]
Woohoo! 😄
