### ISSUE TITLE
Feature request: Keep subjects with no data in post-hoc simulations

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#357]
Related to #32 and #81.

I'm trying to make prediction-observation figures subset by or contingent on other data.  For that, I'm wanting to merge the post-hoc results back into the source data.  I think that the preferred method would be to use this:

```
foo <- nlmixr(model, data=data, est="posthoc")
```

or just to get the `$PRED` or `$IPRED` values from the fit object itself.

The issue that I'm coming up against is that I have 3 placebo subjects in the dataset who have no observations, but I want them there for other reasons.

When I estimate the model or try to do a posthoc estimate, I get the following warning:

```
4: In (function (uif, data, est = NULL, control = list(), ..., sum.prod = FALSE,  :
  IDs without observations dropped: 12 10 1
```

And, those subjects have no data in the output (the number of rows of `foo` is lower than the number of rows in `data`).

My feature request is that those subjects without observations are not dropped, but are set to `NA` in the output.  If that isn't reasonable or feasible, is there a preferred method for combining the data back together?  (Perhaps just convert it to a data.frame and merge it?)

**Comment by mattfidler** [comment]
It is reasonable, but may not be completely doable;  I remember some errors with `SAEM` (though my memory here is fuzzy).

 If you have a merge at the end of course you could put it back together, but the warning may not be suppressed.

You could always add one `EVID=2` to these patients.

**Comment by billdenney** [comment]
Thanks for the quick response.  The EVID=2 solution is probably the easiest.
