### ISSUE TITLE
R 3.6.3

### ISSUE THREAD

**Issue by skarel92** [nlmixrdevelopment/nlmixr#358]
Nlmixr doesn't install on R 3.6.3

**Comment by mattfidler** [comment]
I have reports of it running on R 3.6.3;  Can you share more details?

If you are on windows you could always use the installer:

https://github.com/nlmixrdevelopment/nlmixr/releases/tag/v1.1.1-3

**Comment by skarel92** [comment]
I have Ubuntu 20

**Comment by mattfidler** [comment]
That isn't enough information to help you.  Perhaps you can say what happens when you try to install.

**Comment by skarel92** [comment]
I use R version 3.6.3 with RStudio Version 1.3.959
Platform: x86_64-pc-linux-gnu (64-bit) Ubuntu 20.04 LTS

Usually i just get a message saying it s not available for R 3.6.3 when i install.packages("nlmixr")
However i just did and got this error:

ERROR: lazy loading failed for package ‘nlmixr’
* removing ‘/usr/local/lib/R/site-library/nlmixr’
* restoring previous ‘/usr/local/lib/R/site-library/nlmixr’
Warning in install.packages :
  installation of package ‘nlmixr’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp5rIg7H/downloaded_packages’
> library(nlmixr)
Error: package or namespace load failed for ‘nlmixr’ in readRDS(nsInfoFilePath):
 error reading from connection

**Comment by mattfidler** [comment]
That means it didn't install correctly.  

I still don't have enough information to figure out why. 

You probably have to setup the C++14 compiling environment as described below:

https://nlmixrdevelopment.github.io/nlmixr/#installation-on-linux

**Comment by skarel92** [comment]
I followed this guide yesterday before just trying to directly install (install.package nlmixr) and got error with Redxo and SnakeCharm packs. I ll try again and feedback error logs

**Comment by skarel92** [comment]
Following the guide from step one everything went well until i got to SnakeCharm getting this error 

python.cpp:4:10: fatal error: Python.h: No such file or directory
    4 | #include <Python.h>

However i have both python dev installed. What can i do?

**Comment by mattfidler** [comment]
Ignore the `SnakeCharmR` and install `reticulate` from CRAN.

**Comment by skarel92** [comment]
Thank you very much that worked out great!!!

**Comment by skarel92** [comment]
Issue is closed. Its currently running!!! Thanks for time and great working package.
