### ISSUE TITLE
AMT in theo_sd and theo_md are not the doses administered.

### ISSUE THREAD

**Issue by JSC67** [nlmixrdevelopment/nlmixr#36]
I used the theophylline data as given by theo_sd from nlmixr and fit them in NONMEM.  (Unfortunately I still need to use NONMEM because of its MAXEVALS= 0 feature; when Issue #32 is resolved, please let me know!)  I took the AMT column at face value and got a THETA vector, no problem.  I then put this THETA vector into Madonna but used the known amount of the dose for my Madonna code, 320 mg.  The curve was way off from the data.  This was puzzling until I realized that the AMT column in the theo_sd data is wrong; the actual amount should be AMT * WT.  The AMT is really normalized by weight: if you take AMT times WT you get very close to 320 (mg) for all patients except one.  In the original experiment 12 volunteers were given a dose of 320 mg.  I don't know why patient 9 is off from that; his value of AMT*WT is 267.840 mg.

If you look at the documentation of these data just from R, ?Theoph says that the Dose column is normalized for weight, but when the Theoph dataset was made more NONMEM-like by the addition of EVID and CMT and renamed columns, apparently Dose was taken as AMT directly.

Thanks for your efforts!

**Comment by kestrel99** [comment]
Hi! You're exactly right. Our `theo_sd` dataset matches NONMEM's `THEOPP` dataset, but if you have a look inside the corresponding NONMEM example (`CONTROL5`), you'll see that it's very oddly parameterized and uses `WT` to scale the amounts in the central compartment. The value in the `AMT` column is dose/kg, rather than absolute dose.

From `CONTROL5`:
```
$PK
;THETA(1)=MEAN ABSORPTION RATE CONSTANT (1/HR)
;THETA(2)=MEAN ELIMINATION RATE CONSTANT (1/HR)
;THETA(3)=SLOPE OF CLEARANCE VS WEIGHT RELATIONSHIP (LITERS/HR/KG)
;SCALING PARAMETER=VOLUME/WT SINCE DOSE IS WEIGHT-ADJUSTED
   CALLFL=1
   KA=THETA(1)+ETA(1)
   K=THETA(2)+ETA(2)
   CL=THETA(3)*WT+ETA(3)
   SC=CL/K/WT 
```

**Comment by mattfidler** [comment]
Thanks for pointing this out @JSC67.  I think some doumentation about this would be warrented.  Related To Issue #37

**Comment by JSC67** [comment]
You're very welcome.  Again, when Issue #32 is resolved, please let me know.  Thanks. -JSC

**Comment by mattfidler** [comment]
Ok
