### ISSUE TITLE
Theophylline PK parameter estimates

### ISSUE THREAD

**Issue by mercifr1** [nlmixrdevelopment/nlmixr#37]
Hello,
First, thank you for the terrific work in developing this package!
I’m fitting the Theophylline concentration data using _nlmixr_ and comparing the results to the ones I obtain with _saemix_ or _nlme_. The parameter estimates are similar between _saemix_ and _nlme_, but differ (too much to be due to approx. or algorithmic differences) with _nlmixr_ – see the estimates for lCl and lV in the attachment. 
I suspect it is a simple variable transformation which is too obvious for me to spot (sic), but I can’t find it. Your insights on this would be much appreciated.
Thanks a lot!

Snippet of _nlme_ code:
```R
startvec1<-c(lKa=0.5, lCl=0.75, lV=3.45)
nform<- ~(Dose*exp(lKa)*(exp(-(exp(lCl)/exp(lV))*Time)-exp(-exp(lKa)*Time)))/(exp(lV)*(exp(lKa)-(exp(lCl)/exp(lV))))
nlme.theomod<-deriv(nform, namevec=c("lKa", "lCl", "lV"), function.arg=c("Dose", "Time", "lKa", "lCl", "lV"))
Theo.nlme<-nlme(Concentration~nlme.theomod(Dose, Time, lKa, lCl, lV), 
                data=groupedData(Concentration~Time|Id, data=theodf), 
                fixed=list(lKa~1, lCl~1, lV~1), random=pdDiag(lKa+lCl+lV~1), start=startvec1)
```
Snippets of _nlmixr_ code:
```R
uif1 <- function() {
  ini({
    lka <- 0.45
    lCl <- 1
    lV  <- 3.45
    eta.lka ~ 0.6
    eta.lCl ~ 0.3
    eta.lV  ~ 0.1
    add.err <- 0.7
  })
  model({
    ka <- exp(lka+eta.lka)
    cl <- exp(lCl+eta.lCl)
    v <- exp(lV+eta.lV)
    linCmt() ~ add(add.err)
  })
}
nlmxir.fit1<-nlmixr(uif1, indf, est="nlme", calc.resid=FALSE)
```
[TheoCompare.pdf](https://github.com/nlmixrdevelopment/nlmixr/files/1883473/TheoCompare.pdf)

**Comment by kestrel99** [comment]
Hi Francois,

Trying to reproduce this issue. Can you upload a copy of theodf?

**Comment by mercifr1** [comment]
Hi Justin,

Here is how I create theodf (from theo.saemix which is contained in the _saemix_ package):

`library(saemix)
desn<-theo.saemix %>% 
  group_by(Id) %>% filter(row_number()==1) %>% ungroup()
desn$Time<-0
desn$Concentration<-0
theodf<-rbind(theo.saemix, desn) %>% arrange(Id, Time)
`
and here is how I created indf:
`library(nlmixr)
library(saemix)
theodf<- theo.saemix %>% select(ID=Id, DV=Concentration, TIME=Time) %>% mutate(SRC="SAEMIX")
sexdf<-theo.saemix %>% select(ID=Id, SEX=Sex) %>% distinct(ID, SEX)
indf<-left_join(theo_sd, sexdf, by="ID")
`
