### ISSUE TITLE
can not install snakeCharmR

### ISSUE THREAD

**Issue by dingying85** [nlmixrdevelopment/nlmixr#370]
Tried to install snakeCharmR according to the tutorial and did not succeed, tried on another computer and does not work either

install_github("nlmixrdevelopment/SnakeCharmR")

C:\Users\yding\AppData\Local\r-miniconda\envs\r-reticulate/include/pyconfig.h:61:0: warning: "HAVE_HYPOT" redefined
 #define HAVE_HYPOT
 ^
In file included from C:/Users/yding/Documents/R/win-library/3.6/Rcpp/include/RcppCommon.h:72:0,
                 from C:/Users/yding/Documents/R/win-library/3.6/Rcpp/include/Rcpp.h:27,
                 from python.cpp:1:
C:/PROGRA~1/R/R-3.6.3/include/Rmath.h:62:0: note: this is the location of the previous definition
 # define HAVE_HYPOT 1
 ^
c:/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o SnakeCharmR.dll tmp.def RcppExports.o init.o python.o -LC:\Users\yding\AppData\Local\r-miniconda\envs\r-reticulate/libs -lpython36 -LC:/PROGRA~1/R/R-3.6.3/bin/i386 -lR
C:/Rtools/mingw_32/bin/../lib/gcc/i686-w64-mingw32/4.9.3/../../../../i686-w64-mingw32/bin/ld.exe: C:\Users\yding\AppData\Local\r-miniconda\envs\r-reticulate/libs/python36.lib(python36.dll): Recognised but unhandled machine type (0x8664) in Import Library Format archive
C:\Users\yding\AppData\Local\r-miniconda\envs\r-reticulate/libs/python36.lib: error adding symbols: File format not recognized
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'SnakeCharmR'
* removing 'C:/Users/yding/Documents/R/win-library/3.6/SnakeCharmR'
Error: Failed to install 'SnakeCharmR' from GitHub:
  (converted from warning) installation of package ‘C:/Users/yding/AppData/Local/Temp/RtmpWOGHW7/filed7f810c0126/SnakeCharmR_1.0.7.tar.gz’ had non-zero exit status

**Comment by mattfidler** [comment]
Hi @dingying85 

You can try to install with `reticulate`.  Simply install with:

```r
install.packages("reticulate")
```

At the same time, I find it easier to use a installer for `nlmixr` on Windows:

https://github.com/nlmixrdevelopment/nlmixr/releases/tag/v1.1.1-3

**Comment by mattfidler** [comment]
Let me know if you need more help.
