### ISSUE TITLE
about flow of focei program (a question)

### ISSUE THREAD

**Issue by TodaRikiya** [nlmixrdevelopment/nlmixr#388]
I would like to know the contents of the operation of program FOCEi.
Could you tell me the parts which are written FOCEi code if you can?

**Comment by mattfidler** [comment]
Can you be a bit more specific?  If you want to know about the FOCEi likelihood it is written about in:

(Almquist, Leander, and Jirstrand 2015  <doi:10.1007/s10928-015-9409-1>). `nlmixr` uses the NONMEM approximation and the `eta` sensitivities.

The code is in both RxODE and nlmixr so there isn't just one file that runs focei.

**Comment by TodaRikiya** [comment]
Thank you for your kind answer.
I would like to ask you that ...
1. how did you express the difference between foce and focei.
2. how did you calculate focei likelihood.
Since the latter matter was solved thanks to your answer, could I ask you the former question (for example, code which interacts omega and sigma)?

**Comment by mattfidler** [comment]
The foce problem differences are described here:

https://link.springer.com/article/10.1007/s10928-007-9060-6

There is a slight difference between the NONMEM focei and the focei in the paper.  This is not present in the almquist paper or in nlmixr.

**Comment by mattfidler** [comment]
The foce and lower methods are the same in nlmixr as https://link.springer.com/article/10.1007/s10928-007-9060-6

**Comment by TodaRikiya** [comment]
You mean that you didn't build focei program as extended foce program by taking into account interaction between eta and epsilon. However you built focei and foce program individually?
(I'm sorry for my clumsy English.)

**Comment by mattfidler** [comment]
They are intertwined and cover many source files;  Much of the setup is in RxODE and the options input and algorithm is in nlmixr.

**Comment by mattfidler** [comment]
It isn't simply one file

**Comment by TodaRikiya** [comment]
I get it. I appreciate your answer.
