### ISSUE TITLE
Feature Request: Allow A(initial) or A[0] for setting initial conditions

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#395]
Currently `A(0)` type syntax is required to set initial conditions.  But as described in ropensci/drake#1318 and ropensci/drake#910, that style is not valid R syntax.

To work with `drake` and more generally to align the `nlmixr` syntax with R, I would suggest that `A[0]` would communicate the same information while allowing the code to look like valid R.  If that is not reasonable for some reason (we don't allow vectorized assignment, I don't think, so it shouldn't be a conflict, I don't think), then perhaps we could use something like `A(initial)` or `A(INIT)` or similar.  The downside to `initial` or `INIT` are that they could conflict with user variables.

What are your thoughts?

**Comment by mattfidler** [comment]
Will has a point that you wouldn't use this in R outside of a domain specific language.  

However, I disagree that is invalid R syntax. It is parsed by the R parser and doesn't error out so it is valid in that sense,  (and you can walk over the parsing tree).

If I changed `A(0)` to `A[0]` everything I would have to change `d/dt(x) <- ...` and likely to be consistant `alag()`, `dur()` etc. because that is definitely not idomatic R either (nor is `A[0]` for that matter)

This would either require a large rewrite of:
- RxODE parser
- RxODE <-> symengine parser
- RxODE pruning of braching expressions (if/else)
- RxODE expression optimization
- nlmixr model parser 

as well as many backward compatibility requirements and possible errors that are accidentality introduced. 

I do have an option to check the input model syntax as well as the data md5 to save the results. If the data/model didn't change it will load the results. This should work in a similar way to drake and would not require any new code (though it wouldn't technically use drake directly).

So, no I don't think it is worthwhile.

**Comment by billdenney** [comment]
Thank you for the thoughtful response.  I was thinking to augment the current options rather than to require new syntax so that either is allowed.

The challenge that I would like to overcome is that I find drake to be remarkably useful and I find nlmixr to be remarkably useful.  I want them to play well together.

I get that the DSL for nlmixr is approximately valid R (in that it will parse and that you can traverse the tree).  But, I wonder if there is a way to also work within drake?

I cba imagine a solution that I could write where I would have a personal-specific extension that would traverse the parse tree and do an on-the-fly conversion.  But, that seems problematic in that it would solve my problem but become fragile to nlmixr changes (I see a few ways that would become relatively simple).  And, it wouldn't help others.

**Comment by mattfidler** [comment]
I completely understand;  There was some rudimentary support for drake at some time:

https://github.com/nlmixrdevelopment/nlmixr/commit/3ef5dcf5789dbd0ab96cfe53a9d38227360eb0ff

But it wasn't working.   The `no_deps` seemed to be the best option based on Will's last comment to me.

**Comment by mattfidler** [comment]
If you want to resurrect the idea, that would be OK with me.

**Comment by mattfidler** [comment]
Note the `no_deps` doesn't interfere with nlmixr currently;  For example:

``` r
library(nlmixr)
library(drake)

rxClean() # Clear out cached models

one.compartment <- function() {
  ini({
    tka <- 0.45 # Log Ka
    tcl <- 1 # Log Cl
    tv <- 3.45    # Log V
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  no_deps(model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    d/dt(depot) = -ka * depot
    d/dt(center) = ka * depot - cl / v * center
    cp = center / v
    cp ~ add(add.sd)
  }))
}

f <- nlmixr(one.compartment)
#> ℹ parameter labels from comments will be replaced by 'label()'

fit <- nlmixr(f, theo_sd, est="focei", list(print=0))
#> singleOde
#> → creating full model...
#> → pruning branches (`if`/`else`)...
#> ✔ done
#> → loading into symengine environment...
#> ✔ done
#> → creating full model...
#> → pruning branches (`if`/`else`)...
#> ✔ done
#> → loading into symengine environment...
#> ✔ done
#> → calculate jacobian
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → calculate sensitivities
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → calculate ∂(f)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → calculate ∂(R²)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → finding duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → optimizing duplicate expressions in inner model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → finding duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → optimizing duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> → compiling inner model...
#> ✔ done
#> → compiling EBE model...
#> ✔ done
#> RxODE 0.9.2.0 using 4 threads (see ?getRxThreads)
#> calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00 
#> done
#> Calculating residuals/tables
#> done.
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =
#> FALSE, : initial ETAs were nudged; (can control by foceiControl(etaNudge=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod
#> = FALSE, : ETAs were reset to zero during optimization; (Can control by
#> foceiControl(resetEtaP=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =
#> FALSE, : gradient problems with initial estimate and covariance; see $scaleInfo

print(fit)
#> ── nlmixr FOCEi (outer: nlminb) fit ────────────────────────────────────────────
#> 
#> 
#>           OBJF      AIC      BIC Log-likelihood Condition Number
#> FOCEi 116.8139 373.4137 393.5933      -179.7068         73.85496
#> ── Time (sec $time): ───────────────────────────────────────────────────────────
#> 
#> 
#>            setup optimize covariance table    other
#> elapsed 2.274581 0.899834   0.899836 0.011 3.251749
#> ── Population Parameters ($parFixed or $parFixedDf): ───────────────────────────
#> 
#> 
#>        Parameter  Est.     SE %RSE Back-transformed(95%CI) BSV(CV%) Shrink(SD)%
#> tka       Log Ka 0.474  0.209 44.1       1.61 (1.07, 2.42)     68.9     0.384% 
#> tcl       Log Cl  1.01 0.0943 9.32       2.75 (2.29, 3.31)     26.8      3.87% 
#> tv         Log V  3.46 0.0403 1.16       31.8 (29.4, 34.4)     13.9      10.3% 
#> add.sd           0.696                               0.696                     
#>  
#>   Covariance Type ($covMethod): r,s
#>   Some strong fixed parameter correlations exist ($cor) :
#>     cor:tcl,tka  cor:tv,tka  cor:tv,tcl 
#>      0.131       0.396       0.710  
#>  
#> 
#>   No correlations in between subject variability (BSV) matrix
#>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs) 
#>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink 
#>   Minimization message ($message):  
#>     false convergence (8) 
#>   In an ODE system, false convergence may mean "useless" evaluations were performed.
#>   See https://tinyurl.com/yyrrwkce
#>   It could also mean the convergence is poor, check results before accepting fit
#>   You may also try a good derivative free optimization:
#>     nlmixr(...,control=list(outerOpt="bobyqa"))
#> ── Fit Data (object is a modified tibble): ─────────────────────────────────────
#> 
#> # A tibble: 132 x 24
#>   ID     TIME    DV  EVID  PRED    RES   WRES IPRED   IRES  IWRES CPRED   CRES
#>   <fct> <dbl> <dbl> <int> <dbl>  <dbl>  <dbl> <dbl>  <dbl>  <dbl> <dbl>  <dbl>
#> 1 1     0      0.74     0  0     0.74   0.391  0     0.74   1.06   0     0.74 
#> 2 1     0.25   2.84     0  3.29 -0.449 -0.237  3.85 -1.01  -1.45   3.25 -0.409
#> 3 1     0.570  6.57     0  5.87  0.705  0.372  6.79 -0.216 -0.310  5.81  0.756
#> # … with 129 more rows, and 12 more variables: CWRES <dbl>, eta.ka <dbl>,
#> #   eta.cl <dbl>, eta.v <dbl>, ka <dbl>, cl <dbl>, v <dbl>, cp <dbl>,
#> #   tad <dbl>, dosenum <dbl>, depot <dbl>, center <dbl>
```

<sup>Created on 2020-09-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by billdenney** [comment]
I've now had a chance to play with `no_deps()`, and I understand more that it is the right solution.  Thank you for your patience with me while I was figuring that out.
