### ISSUE TITLE
Installing nlmixr on macOS Catalina version 10.15.6

### ISSUE THREAD

**Issue by Jwetherington** [nlmixrdevelopment/nlmixr#397]
Would you please provide the most current procedure for installing nlmixr under macOS version 10.15.6?  Also what versions of software (i.e., Python) are required.  I've attempted to install using various posted procedures and have had no success.  Your guidance would be greatly appreciated.

**Comment by mattfidler** [comment]
Hi @Jwetherington

I have helped people install on Catalina, but I have forgotten the procedure.

Please let me know where you get to so we can debug together.

**Comment by Jwetherington** [comment]
Also, cannot successful load the SnakeCharmR package.

**Comment by mattfidler** [comment]
Don't worry about `SnakeCharmR` on a mac `reticulate` works better

**Comment by mattfidler** [comment]
@Jwetherington 

You can use the Xcode toolset instead of using the:
```
sudo installer -pkg
/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
-target /
```

**Comment by mattfidler** [comment]
I think it is on the app store or something similar.

**Comment by Jwetherington** [comment]
Do I need to complete the following?

Change ~/.Rprofile to have the following line to adjust the paths in R to use the CRAN compilers (if not present, create the .Rprofile file):
# make sure to adjust the version number of clang based on the downloaded version in step 3 (e.g. clang8/bin)
Sys.setenv("PATH"=paste0("/usr/local/clang8/bin:/usr/local/gfortran/bin:", Sys.getenv("PATH")))
Make Sure you have an extra line at the end of this file; Otherwise R will not pick up the correct paths.

You also need to create a directory ~/.R and then put a file Makevars in it; The context of the file should contain:

# ~/.R/Makevars
CXX14FLAGS=-O2 -march=native -mtune=native -arch x86_64 -ftemplate-depth-256 -fPIC

**Comment by mattfidler** [comment]
The cran compilers should not be needed anymore (I think)

https://cran.r-project.org/bin/macosx/tools/

has a note of this change.  

You can try to compile without changing `~/.R/Makevars` and see where you get.

**Comment by Jwetherington** [comment]
I've the code loaded and compiled.  And I've successfully tested the code with an example. 

I'm trying to generate Xpos plots in my example which generated the following error:

Error in xpose_data_nlmixr(fit) : 
  could not find function "xpose_data_nlmixr"

I noticed that the library xpose.nlmixr has been archived.  Could this be the root cause of the error?

Thank you for taking the time to help me.  Much appreciated.

**Comment by mattfidler** [comment]
Yes this is the cause of the error;  You can always install with:

```r
devtools::install_github("nlmixrdevelopment/xpose.nlmixr")
```

You could also use ggPMX

**Comment by Jwetherington** [comment]
I'm attempting to fit a 2-compartment PK model using data collected as part of a phase 1 clinical trial.  Drug was administered as a continuous infusion over a 30 minute time interval.  What data table format is nlmixr expecting:
- A table format following the layout in Table 1 in Fidler et al 2019
- An RxODE event table as described in a posting on 2020-04-10 for RxODE version 0.9.2.0
- Both formats are acceptable

Thanks in advance for taking the time to respond to my questions.  Very much appreciated.

**Comment by mattfidler** [comment]
Both formats are acceptable:

https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-event-types.html

https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-events-classic.html

**Comment by Jwetherington** [comment]
Thank you for your quick response.
