### ISSUE TITLE
Cannot run two SAEM jobs simultaneously

### ISSUE THREAD

**Issue by RikSchoemaker** [nlmixrdevelopment/nlmixr#4]
In contrast to nlmixr/nlme it is currently not possible to run two or more nlmixr/SAEM instances at the same time under windows. For instance, when using Microsoft R Open with nlmixr, there is the possibility of setting up a temporary cluster and running nlme jobs in parallel, like with the following syntax:

```
library(doParallel)
library(foreach)

cl <- makeCluster(15)
registerDoParallel(cl)

do_nlmixr<-function(i){
datr <- read.csv(paste("D:\\nmrun\\nmrun4\\runN024\\m1\\bs_pr1_",i,".dta",sep=""), header=TRUE,stringsAsFactors=F)
fit <- nlme_lin_cmpt(datr, par_model=specs4b, ncmt=1, verbose=TRUE,oral=TRUE,weight=varPower(fixed=c(1)),control = nlmeControl(pnlsTol = .1))
save(fit,file=paste("fit_",i,".Rdata",sep=""))
}

nlmixr_out<-foreach(i=1:500, .combine='rbind', .packages=c('RxODE','nlmixr','nlme')) %dopar% do_nlmixr(i)
```
When you try to do something like that with SAEM, it crashes immediately, because a single dll is generated in the run directory that is then shared (?): nlme runs create temporary directories that store the material, but SAEM does not. It would be extremely useful if these processes were separated.

**Comment by mattfidler** [comment]
Jobs should be able to be run simultaneously with the dparser-saem branch.

**Comment by RikSchoemaker** [comment]
Your update to SAEM indeed makes it possible to run SAEM simultaneously, and it is also possible to use parallelisation within R (for windows) to run all these in parallel!

I have just run my sparse sample SAEM model with your code and a single run takes 162 secs (2.7 mins). With doParallel and foreach I can set up a virtual cluster with 15 nodes (I have 16 physical cores) that runs 30 of these in 8 mins; that’s 0.27 mins/run, a ten-fold speedup!!!

Here’s the code:

```
library(nlmixr)

do_SAEM<-function(i){
  datr <- read.csv(paste("D:\\nmrun\\nmrun4\\m1\\bs_pr1_",i,".dta",sep=""), header=TRUE,stringsAsFactors=F) 
  datr$WT<-1
  model = list(saem_mod=saem_fit, res.mod=2,covars="WT")
  inits = list(theta=c(5,90,1),omega=c(0.1,0.1,0.1),bres=0.2)
  cfg   = configsaem(model, datr, inits)
  timeS<-Sys.time()
  save(fit,file=paste("fit_",i,".Rdata",sep=""))
  NM = fit$Plambda
  NM
}

```
You need to first set up the workers to have 'saem_fit' instances waiting to be called

```
worker.init <- function() {
  library(nlmixr)
  assign('saem_fit', gen_saem_user_fn(model=lincmt(ncmt=1, oral=TRUE)), .GlobalEnv)
  NULL
}

NClusters<-15
library(doParallel)
cl <- makePSOCKcluster(NClusters)
clusterCall(cl, worker.init)
registerDoParallel(cl)
```

And then you can run them all in parallel!!

`nlmixr_out<-foreach(i=1:500, .combine='rbind') %dopar% do_SAEM(i)
`

I am over the moon :D

Cheers,

Rik
