### ISSUE TITLE
After lsoda convergence errors, OFV increases and does not decrease notably again

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#403]
Maybe related to #401.

I have a model that should not be very stiff.  After a couple of iterations, the OFV is 1559.8967.  Then, I get the error below, and the OFV increases to 2.1380084e+09 and never decreases back.  Is there a way to protect from these types of convergence errors and their effects on OFV?

```
unhandled error message: EE:lsoda -- at t = 0 and step size _C(h) = 4.99894e-015, the
 corrector convergence failed repeatedly or
 with fabs(_C(h)) = hmin
 @(lsoda.c:885)
```

**Comment by mattfidler** [comment]
I have tried to protect focei against these convergence errors by:
- Reducing `atol`/`rtol` when there is a poor ODE solution
- Keep the `atol`/`rtol` reduced when the system 
- Keep away from stiff areas by returning a very high number when the system cannot be solved.

I think you are getting to the 3rd situation;  Another option there is to abort the `focei` run which NONMEM does.  I'm unsure how they handle the systems that can't be solved with the NOABORT option (they talk about resetting the hessian, but that doesn't really work the same in nlmixr).

I suppose you could return an object that has the best OFV returned.

**Comment by billdenney** [comment]
I'd guess that you're right that I'm in the third situation.

This seems like it could violate some aspects of minimization theory (not my area of expertise), and it would not work well without an explicit Hessian (which may not always be available).  But, would it be possible to choose the second best eigenvalue direction for the gradient when something unreasonably high comes back?

Perhaps another way to help the user with this would be to store the best OFV observed during minimization, and if the final OFV is not that or very close (e.g. final OFV < best OFV + 0.0001) then give a very prominent warning.  (This would only apply to maximum likelihood methods and not stochastic approximation/Bayesian methods.)

**Comment by mattfidler** [comment]
I found the suggestion about large objective function values on a few minimization websites (in engineering, not mixed effects modelling).  

In this case, you jumped in the plateau of the stiff region of the system.  I have seen other cases where it steers the optimization in a better direction.

While it seems reasonable that you could take the Hessian to change gradient,  nlmixr doesn't currently have access to the population gradient estimate since the optimization routines are outside of nlmixr.  The Hessian resets only come from the inner optimization problem (n1qn1).  So option 2 is impossible without a custom optimization routine (also not my area of expertise).

In `SAS` I think the best value is optionally returned with a warning if it isn't near the final minimum.

**Comment by mattfidler** [comment]
What would be "best" would depend on the optimization procedure "bobyqa" doesn't even use gradients and does a pretty good job optimizing;  Perhaps something else could be done here.

**Comment by billdenney** [comment]
You do provide the trace plot as one of the standard plots to make.  That should give the user a hint that something went wrong (though it requires looking there).

Up to you if you think that there is something that would be reasonable to do here.  If not, feel free to close this issue.

**Comment by mattfidler** [comment]
That is true. Perhaps returning the best value may be useful;  However, that requires duplicate ETAs for every ID so it isn't as trivial as it may seem.

**Comment by billdenney** [comment]
I don't think that it needs to necessarily return the best value (and, that seems tough to do, like you say) especially because what it really means is that there was a minimization problem that the user needs to figure out.

I think that some very prominent warning would be most useful to the user.

**Comment by mattfidler** [comment]
It isn't perfect, but now it will issue a warning and skip the covariance step
