### ISSUE TITLE
Missing Observations

### ISSUE THREAD

**Issue by Jwetherington** [nlmixrdevelopment/nlmixr#405]
I'm fitting a 2-compartment PK model in conjunction with an indirect PD model.  When the PK observations are merged with the PD observations using ID and TIME as merging variables, missing values are generated for both PK and PD observations as PK and PD samples were taken at different times.  How do I inform the model fitting algorithms that the dataset contains missing values for both PK and PD observations and to ignore these missing values?

**Comment by mattfidler** [comment]
Flag these with `EVID=2` or drop them entirely
