### ISSUE TITLE
PKPD model

### ISSUE THREAD

**Issue by Jwetherington** [nlmixrdevelopment/nlmixr#406]
I'm fitting to an observed dataset a 2-compartment PK model in conjunction with an indirect PD model. I've a dataset of PK and PD observations collected from multiple patients.  What name should be used to designate the column of observed PD data or can a pointer to the PD column included in the model code?  How are missing PD values handled (e.g., flagged)?  Thanks you for your help.  Very much appreciated.

**Comment by mattfidler** [comment]
This should be explained here:

https://nlmixrdevelopment.github.io/nlmixr/articles/multiple-endpoints.html

**Comment by Jwetherington** [comment]
Thank you.
