### ISSUE TITLE
Minor: Extra printing

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#416]
I assume that this was for debugging and got left in a merge, but there is printing of "res.mod" and "yj" that appears to come from here:

https://github.com/nlmixrdevelopment/nlmixr/blob/ac94e3368aad34e3c7f437b577dfad16538c318c/src/saem_class_rcpp.h#L410-L411

https://github.com/nlmixrdevelopment/nlmixr/blob/ac94e3368aad34e3c7f437b577dfad16538c318c/src/saem_class_rcpp.h#L417-L418

**Comment by mattfidler** [comment]
Indeed;  Testing/aligning `focei` and `saem` residual error structures.  It will probably be accidentally commented in and out of code until the unit test for SAEM is complete.
