### ISSUE TITLE
RxODE fails in example...

### ISSUE THREAD

**Issue by jranke** [nlmixrdevelopment/nlmixr#427]
This is with the current master branch of nlmixr installed. I did change the name of the fit from fit_linCmt_nlme to fit_ode_nlme in the code below. Maybe it was not intended to use the ode version of the model in the nlme example? The ode version of the model works fine when using saem. However, saem takes about six minutes on my system, even with the reduced iterations and only uses one core.

``` r
library(nlmixr)
f_ode <- function(){
    ini({
        lCl <- 1.6      #log Cl (L/hr)
        lVc <- log(90)   #log Vc (L)
        lKA <- 0.1      #log Ka (1/hr)
        prop.err <- c(0, 0.2, 1)
        eta.Cl ~ 0.1 ## BSV Cl
        eta.Vc ~ 0.1 ## BSV Vc
        eta.KA ~ 0.1 ## BSV Ka
    })
    model({
        ## First parameters are defined in terms of the initial estimates
        ## parameter names.
        Cl <- exp(lCl + eta.Cl)
        Vc = exp(lVc + eta.Vc)
        KA <- exp(lKA + eta.KA)
        ## After the differential equations are defined
        kel <- Cl / Vc;
        d/dt(depot)    = -KA*depot;
        d/dt(centr)  =  KA*depot-kel*centr;
        ## And the concentration is then calculated
        cp = centr / Vc;
        ## Last, nlmixr is told that the plasma concentration follows
        ## a proportional error (estimated by the parameter prop.err)
        cp ~ prop(prop.err)
    })
}

# Use nlme algorithm
fit_ode_nlme <- nlmixr(f_ode, Oral_1CPT, est="nlme")
#> 
#> **Iteration 1
#> LME step: Loglik: -39596.42, nlminb iterations: 29
#> reStruct  parameters:
#>         ID1         ID2         ID3 
#> -0.05068504 -0.13515729 -0.43635181 
#>  Beginning PNLS step: .. IDID=-1, excess work done on this call (perhaps wrong jt).
#> Error in rxSolve_(object, .ctl, .nms, .xtra, params, events, inits, setupOnly = .setupOnly): Could not solve the system.
```

<sup>Created on 2020-10-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.3 (2020-10-10)
#>  os       Debian GNU/Linux 10 (buster)
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language en                          
#>  collate  de_DE.UTF-8                 
#>  ctype    de_DE.UTF-8                 
#>  tz       Europe/Berlin               
#>  date     2020-10-29                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package       * version    date       lib source        
#>  assertthat      0.2.1      2019-03-21 [1] CRAN (R 4.0.0)
#>  backports       1.1.10     2020-09-15 [1] CRAN (R 4.0.2)
#>  brew            1.0-6      2011-04-13 [1] CRAN (R 4.0.0)
#>  callr           3.5.1      2020-10-13 [1] CRAN (R 4.0.3)
#>  cli             2.1.0      2020-10-12 [1] CRAN (R 4.0.3)
#>  colorspace      1.4-1      2019-03-18 [1] CRAN (R 4.0.0)
#>  crayon          1.3.4      2017-09-16 [1] CRAN (R 4.0.0)
#>  data.table      1.13.2     2020-10-19 [1] CRAN (R 4.0.3)
#>  desc            1.2.0      2018-05-01 [1] CRAN (R 4.0.0)
#>  devtools        2.3.2      2020-09-18 [1] CRAN (R 4.0.2)
#>  digest          0.6.27     2020-10-24 [1] CRAN (R 4.0.3)
#>  dparser         0.1.8      2017-11-13 [1] CRAN (R 4.0.0)
#>  dplyr           1.0.2      2020-08-18 [1] CRAN (R 4.0.2)
#>  ellipsis        0.3.1      2020-05-15 [1] CRAN (R 4.0.1)
#>  evaluate        0.14       2019-05-28 [1] CRAN (R 4.0.0)
#>  fansi           0.4.1      2020-01-08 [1] CRAN (R 4.0.0)
#>  fs              1.5.0      2020-07-31 [1] CRAN (R 4.0.2)
#>  generics        0.0.2      2018-11-29 [1] CRAN (R 4.0.0)
#>  ggplot2         3.3.2      2020-06-19 [1] CRAN (R 4.0.2)
#>  glue            1.4.2      2020-08-27 [1] CRAN (R 4.0.2)
#>  gtable          0.3.0      2019-03-25 [1] CRAN (R 4.0.0)
#>  highr           0.8        2019-03-20 [1] CRAN (R 4.0.0)
#>  htmltools       0.5.0      2020-06-16 [1] CRAN (R 4.0.2)
#>  knitr           1.30       2020-09-22 [1] CRAN (R 4.0.2)
#>  lattice         0.20-41    2020-04-02 [1] CRAN (R 4.0.0)
#>  lazyeval        0.2.2      2019-03-15 [1] CRAN (R 4.0.0)
#>  lifecycle       0.2.0      2020-03-06 [1] CRAN (R 4.0.0)
#>  lotri           0.2.2      2020-05-29 [1] CRAN (R 4.0.2)
#>  magrittr        1.5        2014-11-22 [1] CRAN (R 4.0.0)
#>  memoise         1.1.0      2017-04-21 [1] CRAN (R 4.0.0)
#>  munsell         0.5.0      2018-06-12 [1] CRAN (R 4.0.0)
#>  mvnfast         0.2.5.1    2020-10-14 [1] CRAN (R 4.0.3)
#>  n1qn1           6.0.1-9    2020-07-02 [1] CRAN (R 4.0.2)
#>  nlme            3.1-150.1  2020-10-28 [1] local         
#>  nlmixr        * 1.1.1-9    2020-10-29 [1] local         
#>  pillar          1.4.6      2020-07-10 [1] CRAN (R 4.0.2)
#>  pkgbuild        1.1.0      2020-07-13 [1] CRAN (R 4.0.2)
#>  pkgconfig       2.0.3      2019-09-22 [1] CRAN (R 4.0.0)
#>  pkgload         1.1.0      2020-05-29 [1] CRAN (R 4.0.1)
#>  PreciseSums     0.4        2020-07-10 [1] CRAN (R 4.0.2)
#>  prettyunits     1.1.1      2020-01-24 [1] CRAN (R 4.0.0)
#>  processx        3.4.4      2020-09-03 [1] CRAN (R 4.0.2)
#>  ps              1.4.0      2020-10-07 [1] CRAN (R 4.0.2)
#>  purrr           0.3.4      2020-04-17 [1] CRAN (R 4.0.0)
#>  R6              2.5.0      2020-10-28 [1] CRAN (R 4.0.3)
#>  Rcpp            1.0.5      2020-07-06 [1] CRAN (R 4.0.2)
#>  RcppArmadillo   0.10.1.0.0 2020-10-20 [1] CRAN (R 4.0.3)
#>  remotes         2.2.0      2020-07-21 [1] CRAN (R 4.0.2)
#>  rex             1.2.0      2020-04-21 [1] CRAN (R 4.0.0)
#>  rlang           0.4.8      2020-10-08 [1] CRAN (R 4.0.3)
#>  rmarkdown       2.5        2020-10-21 [1] CRAN (R 4.0.3)
#>  rprojroot       1.3-2      2018-01-03 [1] CRAN (R 4.0.0)
#>  RxODE           0.9.2-1    2020-10-15 [1] CRAN (R 4.0.3)
#>  scales          1.1.1      2020-05-11 [1] CRAN (R 4.0.2)
#>  sessioninfo     1.1.1      2018-11-05 [1] CRAN (R 4.0.0)
#>  stringi         1.5.3      2020-09-09 [1] CRAN (R 4.0.2)
#>  stringr         1.4.0      2019-02-10 [1] CRAN (R 4.0.0)
#>  sys             3.4        2020-07-23 [1] CRAN (R 4.0.2)
#>  testthat        2.3.2      2020-03-02 [1] CRAN (R 4.0.0)
#>  tibble          3.0.4      2020-10-12 [1] CRAN (R 4.0.3)
#>  tidyselect      1.1.0      2020-05-11 [1] CRAN (R 4.0.2)
#>  units           0.6-7      2020-06-13 [1] CRAN (R 4.0.2)
#>  usethis         1.6.3      2020-09-17 [1] CRAN (R 4.0.2)
#>  vctrs           0.3.4      2020-08-29 [1] CRAN (R 4.0.2)
#>  withr           2.3.0      2020-09-22 [1] CRAN (R 4.0.2)
#>  xfun            0.18       2020-09-29 [1] CRAN (R 4.0.2)
#>  yaml            2.2.1      2020-02-01 [1] CRAN (R 4.0.0)
#> 
#> [1] /usr/local/lib/R/site-library
#> [2] /usr/lib/R/site-library
#> [3] /usr/lib/R/library
```

</details>

**Comment by mattfidler** [comment]
You have to adjust `atol` and `rtol` to get this to work;  The `contrrol` list can be used to supply ODE solving options.

`atol=1e-3, rtol=1e-3, pnlsTol=0.7` works well:

``` r
library(nlmixr)
f_ode <- function(){
    ini({
        lCl <- 1.6      #log Cl (L/hr)
        lVc <- log(90)   #log Vc (L)
        lKA <- 0.1      #log Ka (1/hr)
        prop.err <- c(0, 0.2, 1)
        eta.Cl ~ 0.1 ## BSV Cl
        eta.Vc ~ 0.1 ## BSV Vc
        eta.KA ~ 0.1 ## BSV Ka
    })
    model({
        ## First parameters are defined in terms of the initial estimates
        ## parameter names.
        Cl <- exp(lCl + eta.Cl)
        Vc = exp(lVc + eta.Vc)
        KA <- exp(lKA + eta.KA)
        ## After the differential equations are defined
        kel <- Cl / Vc;
        d/dt(depot)    = -KA*depot;
        d/dt(centr)  =  KA*depot-kel*centr;
        ## And the concentration is then calculated
        cp = centr / Vc;
        ## Last, nlmixr is told that the plasma concentration follows
        ## a proportional error (estimated by the parameter prop.err)
        cp ~ prop(prop.err)
    })
}

# Use nlme algorithm
fit <- nlmixr(f_ode, Oral_1CPT, est="nlme", control=list(atol=1e-3, rtol=1e-3, pnlsTol=0.7))
#> ℹ parameter labels from comments will be replaced by 'label()'
#> 
#> **Iteration 1
#> LME step: Loglik: -39966.67, nlminb iterations: 21
#> reStruct  parameters:
#>         ID1         ID2         ID3 
#> -0.02130775 -0.15397660  2.31911637 
#>  Beginning PNLS step: ..  completed fit_nlme() step.
#> PNLS step: RSS =  625.6639 
#>  fixed effects: 1.398694  4.230472  0.1043277  
#>  iterations: 7 
#> Convergence crit. (must all become <= tolerance = 1e-05):
#>       fixed    reStruct 
#>   0.1439241 149.8061321 
#> 
#> **Iteration 2
#> LME step: Loglik: -38184.2, nlminb iterations: 11
#> reStruct  parameters:
#>        ID1        ID2        ID3 
#> -0.2000962 -0.2638377  3.7197970 
#>  Beginning PNLS step: ..  completed fit_nlme() step.
#> PNLS step: RSS =  320.2507 
#>  fixed effects: 1.402225  4.233129  0.1054113  
#>  iterations: 3 
#> Convergence crit. (must all become <= tolerance = 1e-05):
#>     fixed  reStruct 
#> 0.0102803 1.5382365 
#> 
#> **Iteration 3
#> LME step: Loglik: -37976.7, nlminb iterations: 10
#> reStruct  parameters:
#>        ID1        ID2        ID3 
#> -0.2265113 -0.3018928  4.2458562 
#>  Beginning PNLS step: ..  completed fit_nlme() step.
#> PNLS step: RSS =  321.1545 
#>  fixed effects: 1.402225  4.233129  0.1054113  
#>  iterations: 1 
#> Convergence crit. (must all become <= tolerance = 1e-05):
#>      fixed   reStruct 
#> 0.00000000 0.06460031 
#> 
#> **Iteration 4
#> LME step: Loglik: -37976.7, nlminb iterations: 2
#> reStruct  parameters:
#>        ID1        ID2        ID3 
#> -0.2265226 -0.3019400  4.2456799 
#>  Beginning PNLS step: ..  completed fit_nlme() step.
#> PNLS step: RSS =  321.1545 
#>  fixed effects: 1.402225  4.233129  0.1054113  
#>  iterations: 1 
#> Convergence crit. (must all become <= tolerance = 1e-05):
#>        fixed     reStruct 
#> 0.000000e+00 2.058394e-07
#> RxODE 0.9.2.2 using 4 threads (see ?getRxThreads)
#> Calculating residuals/tables
#> done.

print(fit)
#> ── nlmixr nlme by maximum likelihood (ODE; μ-ref & covs) nlme OBF fit ──────────
#> 
#> 
#>          OBJF      AIC      BIC Log-likelihood Condition Number
#> nlme 63185.66 75967.39 76015.31       -37976.7         2463.743
#> ── Time (sec $time): ───────────────────────────────────────────────────────────
#> 
#> 
#>           nlme    setup table    other
#> elapsed 30.045 0.639115 0.047 0.177885
#> ── Population Parameters ($parFixed or $parFixedDf): ───────────────────────────
#> 
#> 
#>              Parameter  Est.       SE  %RSE Back-transformed(95%CI) BSV(CV%)
#> lCl      log Cl (L/hr)   1.4   0.0244  1.74       4.06 (3.87, 4.26)     27.1
#> lVc         log Vc (L)  4.23   0.0265 0.625       68.9 (65.4, 72.6)     29.3
#> lKA      log Ka (1/hr) 0.105 0.000533 0.506       1.11 (1.11, 1.11)    0.304
#> prop.err               0.212                                  0.212         
#>          Shrink(SD)%
#> lCl        -0.0338% 
#> lVc           1.57% 
#> lKA           28.7% 
#> prop.err            
#>  
#>   Covariance Type ($covMethod): nlme
#>   No correlations in between subject variability (BSV) matrix
#>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs) 
#>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink
#> ── Fit Data (object is a modified tibble): ─────────────────────────────────────
#> 
#> # A tibble: 6,960 x 23
#>   ID     TIME    DV  EVID  PRED    RES IPRED   IRES   IWRES eta.Cl eta.Vc
#>   <fct> <dbl> <dbl> <int> <dbl>  <dbl> <dbl>  <dbl>   <dbl>  <dbl>  <dbl>
#> 1 1      0.25  205.     0  209.  -4.70  179.  25.7   0.676  0.0985  0.156
#> 2 1      0.5   311.     0  365. -54.5   312.  -1.77 -0.0266 0.0985  0.156
#> 3 1      0.75  389.     0  480. -90.8   411. -21.7  -0.249  0.0985  0.156
#> # … with 6,957 more rows, and 12 more variables: eta.KA <dbl>, Cl <dbl>,
#> #   Vc <dbl>, KA <dbl>, kel <dbl>, cp <dbl>, tad <dbl>, dosenum <dbl>,
#> #   depot <dbl>, centr <dbl>, rxLambda <dbl>, rxYj <dbl>
```

<sup>Created on 2020-10-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Note, both `focei` and `saem` are within `nlmixr` and will skip bad solves or reduce `atol`/`rtol` automatically, so they are more ODE solving error resistant.  Also in our tests focei and saem both perform better than nlme in estimating a simulated example.

The testing results for `nlme` are found in https://github.com/nlmixrdevelopment/PAGE-2018/blob/master/Presentations_PAGE2018.zip with the nlmixr-overview.pdf document on slide 8 - 21.  The comparisons were done by Rik Shoemaker in 2017.  Both FOCEi and SAEM have reasonable results compared to commercial software

**Comment by mattfidler** [comment]
Also tested is that `nlme` is faster than `foecei` and `saem`

**Comment by mattfidler** [comment]
Hopefully this clarifies some of the issues/remedies in `nlme`

**Comment by jranke** [comment]
Thanks for looking into that! I remember that in mkin I had notable differences to the analytical solutions until I specified lower values for atol and rtol, so I wonder if it is safe to use these high values for RxODE. Since a couple of years I am using atol = 1e-8, rtol = 1e-10 per default which is passed to deSolve::lsoda() which uses higher defaults.

**Comment by jranke** [comment]
Good to know that saem and focei are more resistant wrt ODE solving problems. I will have a look into that comparison, thanks a lot for the link.

**Comment by mattfidler** [comment]
It is safe to use higher values for lsoda with rxode it is the same algorithm as the deSolve algorithm. You can use the thread safe liblsoda or the original Fortran.

It is hard to say why you saw the differences.  It could be the nlme routine...?

**Comment by jranke** [comment]
Sorry if I wasn't clear - I am using low values for atol and rtol because this is safer in the sense that I will get results that will hardly be perceived as significantly different from an analytical solution if compared to it. But I think using atol=1e-3 and rtol=1e-3 will not give very precise results. Of course it depends on the application if this matters or not.

**Comment by mattfidler** [comment]
Speaking of `mkin`, you could use `RxODE` and pre-compile the models into your package instead of using `deSolve`.  In this way you wouldn't have to worry about users having the C stack installed.

**Comment by mattfidler** [comment]
Looking at your package more the kinetic equations are generated then C is generated, so it isn't as necessary as I thought it might be.

**Comment by mattfidler** [comment]
Here is a comparison of nlmixr to commercial software solutions:

https://ascpt.onlinelibrary.wiley.com/doi/10.1002/psp4.12471

It doesn't have nlme, though.

**Comment by jranke** [comment]
> Looking at your package more the kinetic equations are generated then C is generated, so it isn't as necessary as I thought it might be.

Yes. I have considered to ship pre-compiled models for the most common scenarios, but as the compilation from C is pretty fast on my own system, I have not gotten to that. This may change if we start using mixed models in degradation kinetics, as the current standard packages do not support that.

**Comment by jranke** [comment]
Thanks for the link to the paper. Good to see that open source alternatives are developed. I wonder why you did not mention saemix or include it in the comparison? It would be interesting to see a comparison of performance (computational and statistically) of saem as impemented in nlmixr and saemix.

**Comment by mattfidler** [comment]
In pharmacometrics, the gold standards are monolix for `saem` and NONMEM for `focei`, that is the reason they were compared.

**Comment by mattfidler** [comment]
If you have the time, you could compare the models to `saemmix`.  My guess is you have to code your own differential equations using `RxODE`, `mrgsolve` or `deSolve`.  `saemmix` is written in R where as nlmixr's `saem` is compiled C code.  While it isn't conclusive, often `C` code is faster than `R` code.  I believe there are also differences between the algorithmic approaches as well which could cause differences in results.

**Comment by jranke** [comment]
I already have an experimental interface to saemix in my package https://pkgdown.jrwb.de/mkin/dev/reference/saemix.html which uses my compiled ODE models (the multicore version has problems, so at the moment I am using core = 1 with that). My rough first impression is that it is not slower than nlmixr, but I would need to check.

**Comment by mattfidler** [comment]
>Yes. I have considered to ship pre-compiled models for the most common scenarios, but as the compilation from C is pretty fast on my own system, I have not gotten to that. This may change if we start using mixed models in degradation kinetics, as the current standard packages do not support that.

RxODE supports package-based compiled models.

**Comment by jranke** [comment]
Well, this can of course also be done with compiled deSolve models, for which I could automatically generate the C code for a variety of standard models... I do not use standard variable names, so I would need to map those, but this is doable. First I want to get to grips with the mixed models which is still a rather new and exciting area for me.

**Comment by mattfidler** [comment]
> already have an experimental interface to saemix in my package https://pkgdown.jrwb.de/mkin/dev/reference/saemix.html which uses my compiled ODE models (the multicore version has problems, so at the moment I am using core = 1 with that). My rough first impression is that it is not slower than nlmixr, but I would need to check.

You may be right; I haven't made the comparison; It may even be faster.  I was simply speaking in generalities here.

As far as parallel processing, the next release of nlmixr will bring thread-based parallel solving to SAEM, which in our tests has shown good improvement in the test models.

**Comment by jranke** [comment]
This is good to hear! Using SAEM in practice will be a lot more convenient if more performant!

**Comment by mattfidler** [comment]
The solved systems were approximately the same speed as the parallel ode solving (as a reference). But this depends on processor, number of cores, etc etc.  

Speed comparisons are actually dependent on many things and are a moving target.

**Comment by jranke** [comment]
Yes, I agree, it really depends! I spent quite some time on this stuff this year, see https://jrwb.de/performance-improvements-mkin ...

**Comment by mattfidler** [comment]
Great work. I know it takes a lot of work for this.

I'm unsure if the solved systems in PK are the same as the ones usually used in chemical kinetics, but these are very complementary disciplines;  If they are the 1-3 compartment PK models have been built-in to RxODE, though they use the "advan" solutions instead of using superpositioning.



If so, there is

**Comment by jranke** [comment]
Yes, these disciplines are very similar - except that mixed models have been used in PK for ages, while in chemical degradation kinetics, this is almost uncharted territory which we are in the process of exploring. Solving the systems is not really the problem, we can do that quite fast, with analytical solutions, eigenvalue based solutions and compiled C code for deSolve.
