### ISSUE TITLE
miscellaneous issues fitting

### ISSUE THREAD

**Issue by ronkeizer** [nlmixrdevelopment/nlmixr#43]
Hi all, a few more things I encountered during testing. Instead of separating into different issues I combined them in single document, as I'm not sure if they're somehow related or not. 

See docs (md + csv) here:  https://gist.github.com/ronkeizer/8d34453fc3b133a570ffc56581519146#file-test-rmd

In summary:
- SAEM works great, but calc.residuals not working / taking very long time
- FOCEI seems unable to handle infusions events
- nlme and focei both crash on the full model. A reduced model does slightly better, but still crashes after many iterations.

**Comment by mattfidler** [comment]
Thanks @ronkeizer 

I will look into this soon;  Note:
- FOCEi is still in development.
- nlme is created by the R core team and has some problems with large models
- Full models are more likely to be fit by SAEM

**Comment by ronkeizer** [comment]
Thanks Matt, appreciate it!
I'm also primarily interested in SAEM, so I'm happy that that seems to be working well mostly.

**Comment by mattfidler** [comment]
Hi Ron,

I did look into it;  A few notes:
- I'm not sure what eta effects on covariates will do.. (though it may have fit with SAEM)
- It is currently better to specify blocks of the `omega` covariance matrix instead of the full covariance matrix with zeros at the non-estimated paramters.  If you specify covariates in this manner, `nlmixr` calculates the symbolic inverse of the full matrix (which is quite expensive).
- Currently mu referencing is prefered for all covariates and parameters, that is:
```R
V = exp(lV + etaV + covV*Wt)
```
This changes the math for how `nlme` and `SAEM` runs the covariates calculations.  While I don't have evidence about how this particular paramterization performs, for mu-referenced fixed/variable components this is more accurate for `nlme` and is required for `SAEM`.  My suggestion is to use this for all covariates with nlmixr;  This covariate calculation does not take into account ETA effects on covariate effects (as in your full model).  

These models also are easier to calculate symbolic sensitivites.  Therefore, the FOCEi approximation step that calculates OBJF and CWRES/CPRED at then end is quite smooth and completes easily (no more 1/2 hour wait for sensitivities to be calculated).

The reworked full model without the ETA estimate on the covariate parameter is given below:

```R
pk_test <- function() {
    ini({
        logCL <- log(3)
        logV <- log(0.7)
        TH_CRCL <- 0.02
        logQ <- log(2)
        logV2 <- log(0.8)
        err_prop <- c(0, 0.1, 1)
        err_add <- c(0, 1, 10)
        eta_CL + eta_V ~ c(0.0729,
                           0.01, 0.0225);
        eta_Q ~ 0.2401
        eta_V2 ~ 0.2
    })
    model({
        CL <- exp(logCL + eta_CL +  covCRCL * TH_CRCL)
        V <- exp(logV + eta_V + logWt)
        Q <- exp(logQ + eta_Q)
        V2 <- exp(logV2 + eta_V2 + logWt)
        d/dt(A0) = - (CL/V) * A0 - (Q/V) * A0
        d/dt(A1) = + (Q/V) * A0 - (Q/V2) * A1
        d/dt(A2) = A0/V
        cp = A0 / V
        cp ~ prop(err_prop) + add(err_add)
    })
}
fit1 <- nlmixr(pk_test, nm_dat, est="saem")
```
![image](https://user-images.githubusercontent.com/514778/39505265-bc6babf4-4d96-11e8-997e-27e05acc541b.png)

Note some of the %RSEs are missing since there were `NA`s in the FIM/covarinace matrix.  This is a sign of overparamterizaiton.

**Comment by ronkeizer** [comment]
Thanks for the guidance Matt!
With the mu-modeled covariates and the simpler covariance block it does indeed progress much better. However, at the final stage it now shows another crash... any ideas? (running on Linux)

```
...
The model-based sensitivities have been calculated.
Needed Covariates:
[1] "logWt"   "covCRCL"
file4add3e9f42d1.cpp:69:5: error: stray ‘`’ in program
     REAL(ret)[0] = -2 /( (R_pow_di(REAL(theta)[0], 3) == 0) ? 2.22044604925031e-16 : R_pow_di(REAL(theta)[0], 3)) - 4 * R_pow_di(REAL(theta)[1], 2) /( ((R_pow_di(REAL(theta)[0], 5) * (R_pow_di(REAL(theta)[2], 2) - R_pow_di(REAL(theta)[1], 2) /( (R_pow_di(REAL(theta)[0], 2) == 0) ? 2.22044604925031e-16 : R_pow_di(REAL(theta)[0], 2)))) == 0) ? 2.22044604925031e-16 : (R_pow_di(REAL(theta)[0], 5) * (R_pow_di(REAL(theta)[2], 2) - R_pow_di(REAL(theta)[1], 2) /( (R_pow_di(REAL(theta)[0], 2) == 0) ? 2.22044604925031e-16 : R_pow_di(REAL(theta)[0], 2))))) - 2 * R_pow_di(REAL(theta)[1], 4) /( ((R_pow_di(REAL(theta)[0], 7) * R_pow_di(R_pow_di(REAL(theta)[2], 2) - R_pow_di(REAL(theta)[1], 2)/(`?`((R_pow_di(REAL(theta)[0],      2) == 0), 2.22044604925031e-16:R_pow_di(REAL(theta)[0], 2))), 2)) == 0) ? 2.22044604925031e-16 : (R_pow_di(REAL(theta)[0], 7) * R_pow_di(R_pow_di(REAL(theta)[2], 2) - R_pow_di(REAL(theta)[1], 2)/(`?`((R_pow_di(REAL(theta)[0],      2) == 0), 2.22044604925031e-16:R_pow_di(REAL(theta)[0], 2))), 2)));
     ^
file4add3e9f42d1.cpp:69:5: error: stray ‘`’ in program
file4add3e9f42d1.cpp:69:5: error: stray ‘`’ in program
file4add3e9f42d1.cpp:69:5: error: stray ‘`’ in program
file4add3e9f42d1.cpp:70:5: error: stray ‘`’ in program
.... (there's more similar output)
```

**Comment by mattfidler** [comment]
Did you use the same model posted above?

If not could you post it.  Also please update nlmixr and RxODE.

**Comment by ronkeizer** [comment]
yes, just copy-pasted. Even tried rewriting code manually as i thought there might be some special character issue with the copy from GitHub. Same issue though.
Ran with latest revision of nlmixr and RxODE.

**Comment by mattfidler** [comment]
What version of python/smypy do you have?

**Comment by ronkeizer** [comment]
That could be it... I'm using Python 2.7 and SymPy 0.7.
I'll install python3 as well and update sympy.
Thanks for checking.

**Comment by mattfidler** [comment]
I think upgrading sympy should do it.  I don't think you need to upgrade
python.

**Comment by ronkeizer** [comment]
I didn't manage to upgrade sympy in python2. However, I noticed I actually had installed python3 (as I followed the install procedure for nlmixr in the docs), it just wasn't pointing to the right python. I think I now managed to finally point SnakeCharmR to use python3, but get the following:

```
Error in SnakeCharmR::py.exec(...) : Traceback (most recent call last):
  File "/home/ron@insight-rx.com/.local/lib/python3.5/site-packages/sympy/__init__.py", line 18, in <module>
    import mpmath
  File "/home/ron@insight-rx.com/.local/lib/python3.5/site-packages/mpmath/__init__.py", line 5, in <module>
    from .ctx_fp import FPContext
  File "/home/ron@insight-rx.com/.local/lib/python3.5/site-packages/mpmath/ctx_fp.py", line 1, in <module>
    from .ctx_base import StandardBaseContext
  File "/home/ron@insight-rx.com/.local/lib/python3.5/site-packages/mpmath/ctx_base.py", line 5, in <module>
    from .functions.functions import SpecialFunctions
  File "/home/ron@insight-rx.com/.local/lib/python3.5/site-packages/mpmath/functions/__init__.py", line 1, in <module>
    from . import functions
  File "/home/ron@insight-rx.com/.local/lib/python3.5/site-packages/mpmath/functions/functions.py", line 333, in <module>
    import cmath
ImportError: /usr/lib/python3.5/lib-dynload/cmath.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf
```

Does this ring a bell? I do have sympy and mpmath installed for python3

**Comment by mattfidler** [comment]
No,

But apparantly you have 2 versions of numpy installed:

https://github.com/scikit-learn/scikit-learn/issues/7542

**Comment by mattfidler** [comment]
Did you ever get this figured out @ronkeizer ?

**Comment by ronkeizer** [comment]
nope,  it seemed the two python versions kept bugging each other... Switched to docker version instead, which worked fine out-of-the-box.
Closing ticket.
