### ISSUE TITLE
Issue when trying to install SnakeCharmR

### ISSUE THREAD

**Issue by jbwoillard** [nlmixrdevelopment/nlmixr#437]
Dear nlmixR devleoppers, I have trouble to install SnakeCharmR, I do not fell confortable with Python and does not understand the error message, could you please help^me with that?
All the best
jb

> devtools::install_github("nlmixrdevelopment/SnakeCharmR")
Downloading GitHub repo nlmixrdevelopment/SnakeCharmR@master
√  checking for file 'C:\Users\AdminInserm\AppData\Local\Temp\RtmpsdyPyA\remotes3ea45be16f85\nlmixrdevelopment-SnakeCharmR-b88ef0c/DESCRIPTION' (750ms)
-  preparing 'SnakeCharmR': (709ms)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'SnakeCharmR_1.0.7.tar.gz'
   Warning: file 'SnakeCharmR/cleanup' did not have execute permissions: corrected
   Warning: file 'SnakeCharmR/configure' did not have execute permissions: corrected
   
Installing package into ‘C:/Users/AdminInserm/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'SnakeCharmR' ...
** using staged installation
Found Python version 2.7
Detected EXEC_PREFIX=C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt
PYTHONHOME is not defined, this might cause an error when loading the package.
Please try setting it to C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt on a system level if you have issues.
Detected library dir C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt/lib/python2.7/config
Detected library name python2.7
Detected include dir C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt/include/python2.7
--------[[begin src/Makevars.win]]--------
PKG_LIBS=-L'C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt/lib/python2.7/config' -lpython2.7
PKG_CPPFLAGS=-I'C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt/include/python2.7'
CXX_STD=CXX11
--------[[end src/Makevars.win]]--------
** libs
"C:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG -I'C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt/include/python2.7' -I'C:/Users/AdminInserm/Documents/R/win-library/4.0/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
"C:/rtools40/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG -I'C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt/include/python2.7' -I'C:/Users/AdminInserm/Documents/R/win-library/4.0/Rcpp/include'        -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c init.c -o init.o
"C:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG -I'C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt/include/python2.7' -I'C:/Users/AdminInserm/Documents/R/win-library/4.0/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c python.cpp -o python.o
C:/rtools40/mingw64/bin/g++ -shared -s -static-libgcc -o SnakeCharmR.dll tmp.def RcppExports.o init.o python.o -LC:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt/lib/python2.7/config -lpython2.7 -LC:/PROGRA~1/R/R-40~1.2/bin/x64 -lR
installing to C:/Users/AdminInserm/Documents/R/win-library/4.0/00LOCK-SnakeCharmR/00new/SnakeCharmR/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'SnakeCharmR'
    finding HTML links ... done
    SnakeCharmR                             html  
    py.assign                               html  
    py.call                                 html  
    py.exec                                 html  
    py.get                                  html  
    py.load                                 html  
    py.rm                                   html  
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'SnakeCharmR' in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Users/AdminInserm/Documents/R/win-library/4.0/00LOCK-SnakeCharmR/00new/SnakeCharmR/libs/x64/SnakeCharmR.dll':
  LoadLibrary failure:  Le module spécifié est introuvable.

**Comment by mattfidler** [comment]
Sure, since you are on windows the easiest option is to use the nlmixr installer:

https://github.com/nlmixrdevelopment/nlmixr/releases/tag/v1.1.1-3

Has the most recently built installer.

By the way, we will be removing python dependency soon.

**Comment by mattfidler** [comment]
Let me know if you need anything else.
