### ISSUE TITLE
Updating nlmixr without exe download file available

### ISSUE THREAD

**Issue by DuyTran16** [nlmixrdevelopment/nlmixr#441]
My current version of nlmixr is 1.1.1-3 installed from easy installation file nlmixr_1.1.1-3_x86_64_install.exe and using R-studio to global option to select ` [64-bit] C:\R\nlmixr_1.1.1-3\R` when using nlmixr

I would like to update to current **v1.1.1-7**  
Can you advise how to update since there are no .exe files for this version under Assets for version v1.1.1-7 located https://github.com/nlmixrdevelopment/nlmixr/releases.
Thank you!

**Comment by mattfidler** [comment]
Typically you can use CRAN to update `nlmixr`.  We are working to publish the python free and the python version is not available on CRAN currently.  `RxODE` was removed today because we were focusing on the python free release over fixing the python branch.

**Comment by DuyTran16** [comment]
Thanks!  I'll watch on the new release when updated version will have less dependency.
