### ISSUE TITLE
amt in 'model' statement?

### ISSUE THREAD

**Issue by VMOrca** [nlmixrdevelopment/nlmixr#458]
Hi community, 

I'm new to nlmixr, just wondering if there is a way to specify `amt` in the model statement? i.e. the differential equation is a function of the initial dose, e.g. 
`d/dt(s) = (a * amt)/(b + amt) * s`
This example has analytical solution, but I need a general solution for analytically unsolvable differential equations.

Many thanks in advance!
Min

**Comment by mattfidler** [comment]
Hi,

Typically I would make a Dose column and then use that for your equation.
Amt typically has missing values which would cause this approach to fail.

Let me know if you have any other questions

**Comment by mattfidler** [comment]
If you want dose dependent absorption/bioavailibilty you could use

```r
f(s) = d50/(dose+d50)
```

**Comment by VMOrca** [comment]
Many thanks Matthew - it worked like a charm!

Just a side question, do you have any update on the following issue https://github.com/nlmixrdevelopment/nlmixr/issues/45? 
I'm having a very similar question there: essentially one of the differential equation is a function of dose (which you've already solved) and time. 

I hand coded a weighted least square loss function and solved via optimx package, but the result is heavily dependent on initial values of the system of ODEs (as there are quite a lot of parameters so there might be many local extremas) and the fit is not really satisfactory. Hence I was thinking to try out SAEM...

Again many thanks for your help!
Min

**Comment by mattfidler** [comment]
Time varying covariates are supported in the development version of SAEM, if that is your question.

**Comment by mattfidler** [comment]
You can also use custom optimization methods with focei if you are interested.

**Comment by VMOrca** [comment]
Thanks very much Matthew - I'll close the ticket now. Many thanks for your help again!

**Comment by mattfidler** [comment]
No problem
