### ISSUE TITLE
completely lost on how to install nlmixr

### ISSUE THREAD

**Issue by PaiboonJ** [nlmixrdevelopment/nlmixr#459]
Hi,

am quite new to R. I try to follow https://github.com/nlmixrdevelopment/nlmixr/releases, and I could not even able to find nlmixr installer.
I could say that the only thing I got it done was to install R at C:/R/R-4.0.3. 
I really need a very simple step-by-step instruction if possible.
Please advice. 

PJ

**Comment by mattfidler** [comment]
The last release is here:

https://github.com/nlmixrdevelopment/nlmixr/releases/download/v1.1.1-3/nlmixr_1.1.1-3_x86_64_install.exe

**Comment by PaiboonJ** [comment]
Thank you Matt,

I was using the R-4.0 version. I have remove and install 3.6.1 version. and follow the instruction. It seemed to work until I got the error message below:

> library(SnakeCharmR)
Error: package or namespace load failed for ‘SnakeCharmR’ in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'c:/R/nlmixr_1.1.1-3/R/library/SnakeCharmR/libs/x64/SnakeCharmR.dll':
  LoadLibrary failure:  The specified module could not be found.

I check the path and it is "c:/R/nlmixr_1.1.1-3/R/library".

How do I fix this?

Thank you
PJ

**Comment by mattfidler** [comment]
So, the path:
```
c:/R/nlmixr_1.1.1-3/R/library/SnakeCharmR/libs/x64/SnakeCharmR.dll
```

exists?  If not, then likely a over-zealous virus checker removed the dll.

Otherwise, perhaps you are running in `i386` mode?

**Comment by PaiboonJ** [comment]
Thank you Matt,

I am running on a 64-bit.
Perhaps I did something incorrectly. Let me tell you exactly how I did the installation.
1) downloaded the installer 1.1.1-3 (am I suppose to do anything after running the file? All of the command lines below were done through RStudio)
2) installed R-3.5.0 (may be R-4.0.3 could be an issue) at C:\R
3) installed Rtools4.0
- writeLines('PATH="${RTOOLS40_HOME}\\usr\\bin;${PATH}"', con = "~/.Renviron")
4) installed anaconda 3.0
5) installed devtools
6) installed RxODE and failed

** libs
Error in .shlib_internal(args) : 
  C++14 standard requested but CXX14 is not defined
* removing 'C:/tmp/R/win-library/3.6/RxODE'
Error: Failed to install 'RxODE' from GitHub:
  (converted from warning) installation of package ‘C:/Users/paiboon/AppData/Local/Temp/RtmpOeB9Kg/file3a24159c5cd1/RxODE_1.0.1.tar.gz’ had non-zero exit status

Thank you,

PJ

**Comment by mattfidler** [comment]
You simply run the installer and it will install python and R and the
correct interaction. The Readme shows how to use the nlmixr R with Rstudio.

I would run the uninstaller for R 3.5, Rtools 4.0 and Anaconda. R 3.5 isn't
compatible with Rtools 4.0.  Anaconda may interfere with the nlmixr version
of python.

Hopefully it works for you.

**Comment by PaiboonJ** [comment]
Thank you very much for clarification. 

What really threw me off was the instruction for windows steps 1 to 3 on the instruction on  https://github.com/nlmixrdevelopment/nlmixr#readme. 

Ignore steps 1-3 if using the installer for windows.

PJ

**Comment by mattfidler** [comment]
I'm glad it worked for you @PaiboonJ 

Soon python will no longer be required and the installation instructions will be greatly reduced.
