### ISSUE TITLE
Calculate TAD as an option

### ISSUE THREAD

**Issue by mattfidler** [nlmixrdevelopment/nlmixr#46]
See Issue #45

**Comment by sliao99** [comment]
I need to get t after the last dose for Weibull-type absorption model, where t is a continuous variable in ODE.  Just want to point out that it is different from TAD. How can we do this in RxODE?

Sam Liao

**Comment by mattfidler** [comment]
Tad can be calculated by:

```R
tad = t-tlast
```
For example:
```R
mod1 <-RxODE({
    C2 = centr/V2;
    C3 = peri/V3;
    tad = t - tlast;
    d/dt(depot) =-KA*depot;
    d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
    d/dt(peri)  =                    Q*C2 - Q*C3;
    d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
});

inits <- c(eff=1);
ev <- eventTable(amount.units='mg', time.units='hours')
ev$add.dosing(dose=10000, nbr.doses=10, dosing.interval=12)
ev$add.dosing(dose=20000, nbr.doses=5, start.time=120, dosing.interval=24)
ev$add.sampling(0:240)

theta <- 
   c(KA=2.94E-01, CL=1.86E+01, V2=4.02E+01, # central 
     Q=1.05E+01,  V3=2.97E+02,              # peripheral
     Kin=1, Kout=1, EC50=200)               # effects

x <- solve(mod1,theta, ev, inits);

```
You will have to upgrade RxODE to see it output in the data frame of RxODE solve, but it will work for the ODE solving, so a weibull absorption should work just fine.

You can see from the code it is only in the post-processing step that the tlast was not captured.

https://github.com/nlmixrdevelopment/RxODE/commit/1e6762ed7a611c8552edb63e6214af511d6c2c3a
