### ISSUE TITLE
Error RxODE doesn't know how to translate 'expit' to SymPy.

### ISSUE THREAD

**Issue by krinaj** [nlmixrdevelopment/nlmixr#461]
Hello,

I am a new user to nlmixr. I am trying to code a model (non-population) using fo method and fixed etas to 0. I am trying to logit transform a parameter and am running into issue with the above error message. Any help will be appreciated. Please see code snippet below.

Thanks,
Krina

`f <- function() {
 ini({
   lFRC <- logit(0.5)
   lKpoth <- log(5)
   eta.Kpoth ~ fix(0)
   eta.FRC ~ fix(0)

 prop.err <- 0.075
 })
  
model({
        FRC <- expit(lFRC + eta.FRC)
        Kpoth <- exp(lKpoth + eta.Kpoth)

rest of the code
`

**Comment by mattfidler** [comment]
Hi @krinaj,

The `expit` feature is in the development version of `RxODE`/`nlmixr` and doesn't work unless you install them.
