### ISSUE TITLE
nlmixr transit compartment absorption amt

### ISSUE THREAD

**Issue by krinaj** [nlmixrdevelopment/nlmixr#464]
Hello,

I am trying to follow the similar code to this for transit absorption in nlmixr: https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-transit-compartments.html

podo is reserved variable in nlmixr, but how do I connect podo to AMT column from dataset? I am using EVID = 101 as bolus abs to 1st cmt depot, but am not sure if that is the correct way for transit. I also put podo in CMT for dosing records, which I am not sure if correct. The model is running, but running into numerical difficulties (losda 50000 steps taken before reaching tout) and I am not sure if that is related to dosing for transit or something else in the model.

Thanks,
Krina

**Comment by mattfidler** [comment]
I would personally use the `transit()`.  I believe the transit model used is actually more difficult to solve;  A more commonly used transit compartment model is where you have the ODEs define the number of transit compartments as in [Yates2008](https://www.sciencedirect.com/science/article/abs/pii/S09280987080017110).

**Comment by krinaj** [comment]
Thank you, Matthew for your quick response. I will give that a try.

**Comment by krinaj** [comment]
Hello Matthew,

I am suspecting that I am doing something wrong with the dataset in terms
of the dosing events based on the fit output (depot cmt stays near 0). It
seems like dose is not going in the right compartment. Attached are both
model code and data. Can you please suggest if there is anything wrong with
the dosing?

Thanks a bunch,
Krina

**Comment by mattfidler** [comment]
I did not recieve any files.  You need to upload them to github as a zip file.

**Comment by krinaj** [comment]
Oops, sorry, I thought attaching to email would go through. Here it is attached in github.
[RIF_mPBPK.zip](https://github.com/nlmixrdevelopment/nlmixr/files/5785294/RIF_mPBPK.zip)

Many thanks,
Krina

**Comment by mattfidler** [comment]
I didn't get a chance to look at this @krinaj did you figure this out?

**Comment by krinaj** [comment]
Hello Matt,

Thanks for checking. I changed the strategy (i.e. fitting to IV mean data
and then using simulations as I did not need to estimate any absorption
parameters; they are available from literature).

BTW, I am running into a different issue with dynmodel that I am trying out
right now. If I am unable to figure it out, I will start a new post.

Many thanks,
Krina

**Comment by mattfidler** [comment]
Great;  You can use `focei` without etas in the development `nlmixr` as well.

Good luck.
