### ISSUE TITLE
nlmixr has been removed from the CRAN

### ISSUE THREAD

**Issue by Generalized** [nlmixrdevelopment/nlmixr#466]
Dear Authors,

I noticed the package has been removed from the CRAN.
I read that this depends on another package, RxODE.
Do you plan to restore it to the central R repository? How would you estimate it? Weeks, months - this year?

This is incredibly awesome package, it would be a great loss if it's removed permanently from the CRAN. Why? I have to follow SOPs that disallow installation anything outside the CRAN or that is not "active" on the CRAN (I mean that only archival versions are available). I requested the SOP to be changed, but it may take months...

> Package ‘nlmixr’ was removed from the CRAN repository.
> Formerly available versions can be obtained from the archive.
> Archived on 2020-10-07 as depends on archived package 'RxODE' by the same author.
> A summary of the most recent check results can be obtained from the check results archive.
> Please use the canonical form https://CRAN.R-project.org/package=nlmixr to link to this page.

**Comment by mattfidler** [comment]
Yes.  We plan to resubmit.  We are scrambling to do this now.

**Comment by mattfidler** [comment]
RxODE is on CRAN today.  Now we will retest and submit nlmixr.

**Comment by mattfidler** [comment]
We haven't announced this yet, but it is on cran now;  Wait for a general announcement soon.
