### ISSUE TITLE
RxODE::rxC14() Not working

### ISSUE THREAD

**Issue by billchenxi** [nlmixrdevelopment/nlmixr#469]
Error: 'rxC14' is not an exported object from 'namespace:RxODE'

I think RxODE changed after the version update, and the read me is still old. Can you update the instruction on how to install the package?
Thank you.

**Comment by mattfidler** [comment]
The package installation is straight-forward with the new version of R, unless you are using the mac.  The instructions have not made it to nlmixr yet;  They are located here:

https://github.com/nlmixrdevelopment/RxODE#installation

They will be updated with the github method as well.

**Comment by mattfidler** [comment]
Removed the rxC14 description for now.
