### ISSUE TITLE
Ka estimated separately for fed and fasted states

### ISSUE THREAD

**Issue by claireava** [nlmixrdevelopment/nlmixr#474]
Hi, I tried to construct a base model for my dataset with separate Ka for fed/fasted states (and/or formulation types). Below is a simple model structure:
>model.2cptp<- function() {
  ini({
    tvKaFED <- log(4)
    tvKaFAST <-log(1)
    tcl <- log(4.5)
    tv2  <- log(25)
    tv3  <- log(9)
    tq   <- log(0.9)
    wteff<-0.9
    eta.KaFED ~ 1
    eta.KaFAST <-1
    eta.cl ~ 1
    eta.v2 ~ 1
    prop.err <- 0.5
  })
  model({
    if (FOOD ==1) {ka <- exp(tvKaFED + eta.KaFED) } else
    if (FOOD ==0) {ka <- exp(tvKaFAST + eta.KaFAST) }  
    cl <- exp(tcl + eta.cl)
    v2 <- exp(tv2 + eta.v2 + wteff*lnWT)
    v3 <- exp(tv3)
    q  <- exp(tq)
    d/dt(depot) = -ka * depot
    d/dt(center) = ka * depot - cl / v2 * center + q/v3 * periph - q/v2 * center
    d/dt(periph) = q/v2 * center - q/v3 * periph
    cp = center / (v2/1000)
    cp ~ prop(prop.err)
  })
} 
> datTot <- read.csv("TotData.csv")
> fit.s <-  nlmixr(model.2cptp.ode,datTot,est="saem")
Error in nlmixr_fit0(uif = uif, data = data, est = est, control = control,  : SAEM does not support time-varying covariates (yet)
> fit.s <-  nlmixr(model.2cptp.ode,datTot,est="focei")
...
Freeing Python/SymPy memory...done
Error in nlmixr_fit0(uif = uif, data = data, est = est, control = control,  : 
  SAEM does not support time-varying covariates (yet)

It looked like no types of fit worked for me. Does RxODE support if/else in the model? why SAEM sees it as time-varying covariate?
Thanks for your help,

**Comment by mattfidler** [comment]
Rxode supports the `if` and `else` you have.

Saem does not support changes in covariate values within the subject for the version of nlmixr that you are using.

The development version we are working to submit does support this with Saem.
