### ISSUE TITLE
Error: package or namespace load failed for ‘nlmix

### ISSUE THREAD

**Issue by dervieux1** [nlmixrdevelopment/nlmixr#475]
Getting this error after installation.

library(nlmixr)
Error: package or namespace load failed for ‘nlmixr’:
 .onLoad failed in loadNamespace() for 'vctrs', details:
  call: NULL
  error: The vctrs package is not properly installed.
x The DLL version (0.3.2) does not correspond to the package version (0.3.1).
i Please update vctrs to the latest version.
i Updating packages on Windows requires precautions:
  <https://github.com/jennybc/what-they-forgot/issues/62>
In addition: Warning message:
package ‘nlmixr’ was built under R version 4.0.2

**Comment by diabloyg** [comment]
I didn't see this during my installation so just a guess. When I do installation several months before similar issues happened to my "lotri" packages, though I forgot the details. My recommendation is that uninstall the package "vctrs" and reinstall it again manually. If it didn't work, then back to R 3.6.3 might help. I am not sure whether R version above 4.0 would lead to compatibility issues. @mattfidler

**Comment by mattfidler** [comment]
Typically you should restart R and even run R in console mode to make sure that no packages are installed.  You should then uninstall vctrs and then reinsall it.  

It seems you are keeping your old R libraries and upgrading R.  This is a bad pratctice.  Sometimes packages don't work if you install in this manner, though it is less likely in minor upgrades like R `4.0.2` to R `4.0.3`

**Comment by dervieux1** [comment]
Still having error message after reinstalling "vctrs"

devtools::install_github("nlmixrdevelopment/nlmixr")
...
package ‘digest’ successfully unpacked and MD5 sums checked
Error: Failed to install 'nlmixr' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘digest’

**Comment by mattfidler** [comment]
You have to reinstall `digest` now;  

Since `digest` is used in **many** packages, you will need to restart R/windows for this as well.

**Comment by dervieux1** [comment]
thank you
