### ISSUE TITLE
mrgsolve and nlmixr

### ISSUE THREAD

**Issue by KyleBarrett** [nlmixrdevelopment/nlmixr#48]
I have been attempting to write the ODE's and model inputs using mrgsolve while using nlmixr for parameter estimation, similar to this link: https://github.com/metrumresearchgroup/mrgsolve/issues/307

However, Im working with a two-compartment ODE-based model and prefer to use saem over nlme. Saem() requires the ODE's be in RxODE format, so I think it would be easier to use nlmixr(est="saem") as it allows additional model classes to be used. I was wondering if you had any examples similar to the above link, but using the saem method instead.

**Comment by mattfidler** [comment]
We have a PBPK and semi-mechanistic model example that we plan to share after the PAGE meeting.  I think those would qualify, but will be shared in ~2 weeks.

**Comment by KyleBarrett** [comment]
Hi Matt,
I think that would clarify some of my questions as well. Looking forward to their release!

**Comment by mattfidler** [comment]
A draft is availble here:

https://github.com/nlmixrdevelopment/PAGE-2018

It may change the location, if so I will update the url for you.
