### ISSUE TITLE
Failure to install nlmixr due to RxODE/dparser incompatibility

### ISSUE THREAD

**Issue by MichalR07** [nlmixrdevelopment/nlmixr#492]
Hello,

I was trying to install nlmixr v. 2.0.2 from GitHub using devtools in RStudio 1.4.1106 (R v. 4.0.5), but failed. At a certain step of instalation, I am getting this:
"
installing to C:/Program Files/R/R-4.0.5/library/00LOCK-nlmixr/00new/nlmixr/libs/x64
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
ERROR: .onLoad failed in loadNamespace() for 'RxODE', details:
  call: NULL
  error: RxODE compiled with dparser '0.1.8' but dparser '1.3.1.3' is loaded
Recompile RxODE with the this version of dparser
Execution suspended
ERROR: lazy loading failed for package 'nlmixr'
* removing 'C:/Program Files/R/R-4.0.5/library/nlmixr'
"
I have RxODE v. 1.0.6 and dparser v. 1.3.1-3. I've tried to downgrade dparser to 0.1.8 but got warning that this is not available for my version of R (4.0.5). What can I do?

**Comment by mattfidler** [comment]
Hi @MichalR07 

You simply install from source:

```r
install.packages("RxODE", type="source")
```

If we didn't have this binary compatibility check whenever RxODE would parse a model, R would crash.  

Cran has assured us that the binaries will be updated (but you may have downloaded an incompatible binary).
