### ISSUE TITLE
vpc error:  "NAs are not allowed in subscripted assignments"

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#493]
I can't readily make a reprex that I can share due to proprietary data, but I'm getting an error with creating a vpc.  I'm currently trying to trace where it comes from (the final error occurs within the `vpc` package, but it's not clear if it is an input issue from `nlmixr` or a calculation issue in `vpc`.

```r
> nlmixr::vpc(mod_pk_threecmt)
Compiling VPC model...done
done (4.06 sec)
Error in sim$sim[sim[[id]] == i] <- cumsum(stats::ave(1:length(sim_id[sim[[id]] ==  : 
  NAs are not allowed in subscripted assignments
In addition: Warning message:
In as.num(sim[[id]]) : NAs introduced by coercion
> traceback(max.lines=10)
6: add_sim_index_number(sim, id = "id", sim_label = sim_cols$sim)
5: (function (sim = NULL, obs = NULL, psn_folder = NULL, bins = "jenks", 
       n_bins = "auto", bin_mid = "mean", obs_cols = NULL, sim_cols = NULL, 
       software = "auto", show = NULL, stratify = NULL, pred_corr = FALSE, 
       pred_corr_lower_bnd = 0, pi = c(0.05, 0.95), ci = c(0.05, 
           0.95), uloq = NULL, lloq = NULL, log_y = FALSE, log_y_min = 0.001, 
       xlab = NULL, ylab = NULL, title = NULL, smooth = TRUE, vpc_theme = NULL, 
       facet = "wrap", scales = "fixed", labeller = NULL, vpcdb = FALSE, 
       verbose = FALSE, ...) 
   {
       if (!is.null(psn_folder)) {
    ...
4: do.call(getFromNamespace(vpcn, "vpc"), c(sim, call), envir = parent.frame(1))
3: vpc_ui(fit = sim, ...)
2: vpc.nlmixrSaem(mod_pk_threecmt)
1: nlmixr::vpc(mod_pk_threecmt)
```

**Comment by mattfidler** [comment]
There is a problem with both `RxODE` and `vpc` (and possibly `nlmixr`):

- `RxODE` produces `NA` subjects when it cannot solve a problem (note that nlmixr temporarily reduces `atol`/`rtol` with FOCEi to help solve the problem in a pinch;  This could be ported to a more general solution in RxODE https://github.com/nlmixrdevelopment/RxODE/issues/394);  
- `nlmixr` doesn't filter the `NA` subjects before sending it to `vpc`
- `vpc` does not calculate quantiles with `na.rm=TRUE`

The easiest solution is to fork `vpc` and allow `na.rm=TRUE` during the summary;  At the same time the drifting `atol`/`rtol` would be very nice (I think).

**Comment by mattfidler** [comment]
At the same time, the NAs could be elsewhere;  Unfortunately it requires some sort of summary.

You could do a debug to try to capture the simulated dataset to summarize and see where the `NA`s are coming from.

**Comment by billdenney** [comment]
I'm diving in...

None of the IDs are `NA`:

```r
Browse[1]> sapply(sim$sim, FUN=function(x) any(is.na(x)))
 sim.id      id    time   ipred      dv      sc central      p1      p2 
  FALSE   FALSE   FALSE   FALSE   FALSE   FALSE   FALSE   FALSE   FALSE 
Browse[1]> sapply(sim$obs, FUN=function(x) any(is.na(x)))
   id  time  evid   amt    ii    dv   cmt 
FALSE FALSE FALSE  TRUE FALSE FALSE FALSE 
```

**Comment by mattfidler** [comment]
None of the simulations seem to be `NA` either. 

I am guessing that the problem is in the `vpc` package then.  You could specify bins manually instead and you may get past this issue.

**Comment by billdenney** [comment]
I'm getting closer.  The issue appears to be in the `vpc` package: that it doesn't seem to like factors in the `id` column.

Specifically, doing this at the vpc call (https://github.com/nlmixrdevelopment/nlmixr/blob/ea56f82cc11e9d8a6e25d01d9b7c0548ed5f5a01/R/vpc.ui.R#L213) fixed it:

```r
  class(sim) <- "list"
  sim$sim$id <- as.integer(factor(sim$sim$id))
  p <- do.call(vpc_fun, c(sim, call), envir = parent.frame(1))
```

**Comment by billdenney** [comment]
I have confirmed that this is an issue in `vpc`.  Issue opened there, and closing this one.

**Comment by mattfidler** [comment]
Thanks Bill!
