### ISSUE TITLE
Crash During `vpc()` in Windows

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#494]
Running on Windows 10 with `nlmixr` and `RxODE` installed about 10 minutes ago, running `vpc()` on my model crashes the R session.

Specifically:

```r
> vpc_test <- nlmixr::vpc(mod_pk_twocmt_mm, stratify="ACTARM", bins="none")
Compiling VPC model...> creating RxODE include directory
> getting R compile options
> precompiling headers
v done
done
```
*crash*

The data are the same as the previous issue (so I can't share a reprex easily).  Any suggestions to help track down the crash?

The same crash happened with nlmixr and RxODE versions from ~2 months ago (what I had before installing the current versions).

**Comment by mattfidler** [comment]
You could have upgraded `qs` which crashes some versions of `RxODE` since it used to link to the binary.  Now it no longer links.

**Comment by mattfidler** [comment]
If you recompile `RxODE` with the same version of `qs` installed then this issue will go away.

**Comment by mattfidler** [comment]
If that doesn't work, provide some more details about the setup.

**Comment by billdenney** [comment]
I installed from source about an hour before submitting the issue, so I would guess that `qs` is not the issue (and, I don't know what `qs` is).

My setup details are:

* Windows 10 (current patches)
* R 4.0.3
* Rtools version 4.0.0.28

What other details are helpful?

When I just reran it, the RxODE messages were not in the middle before the crash.  It was just:

```
Compiling VPC model...done
```
*crash*

**Comment by billdenney** [comment]
```r
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] assertr_2.8           bsd.report_0.0.0.9093 janitor_2.1.0         zoo_1.8-9             Rsdtm_0.0.0.9010      rio_0.5.26           
 [7] lubridate_1.7.10      forcats_0.5.1         stringr_1.4.0         dplyr_1.0.5           purrr_0.3.4           readr_1.4.0          
[13] tidyr_1.1.3           tibble_3.1.0          ggplot2_3.3.3         tidyverse_1.3.0       drake_7.13.1          nlmixr_2.0.3         

loaded via a namespace (and not attached):
  [1] colorspace_2.0-0    ellipsis_0.3.1      lbfgsb3c_2020-3.2   snakecase_0.11.0    htmlTable_2.1.0     base64enc_0.1-3     fs_1.5.0           
  [8] rstudioapi_0.13     farver_2.1.0        fansi_0.4.2         xml2_1.3.2          splines_4.0.3       cachem_1.0.4        knitr_1.31         
 [15] polyclip_1.10-0     Formula_1.2-4       jsonlite_1.7.2      broom_0.7.5         cluster_2.1.1       dbplyr_2.1.0        png_0.1-7          
 [22] ggforce_0.3.3       compiler_4.0.3      httr_1.4.2          backports_1.2.1     assertthat_0.2.1    Matrix_1.2-18       fastmap_1.1.0      
 [29] cli_2.4.0           tweenr_1.0.2        htmltools_0.5.1.1   prettyunits_1.1.1   tools_4.0.3         igraph_1.2.6        xpose_0.4.12       
 [36] gtable_0.3.0        glue_1.4.2          Rcpp_1.0.6          lotri_0.3.1         cellranger_1.1.0    vctrs_0.3.7         n1qn1_6.0.1-10     
 [43] nlme_3.1-152        xfun_0.22           openxlsx_4.2.3      rvest_1.0.0         PKNCA_0.9.4.9001    lifecycle_1.0.0     sys_3.4            
 [50] MASS_7.3-53.1       scales_1.1.1        hms_1.0.0           parallel_4.0.3      RColorBrewer_1.1-2  qs_0.24.1           yaml_2.2.1         
 [57] curl_4.3            memoise_2.0.0       gridExtra_2.3       rpart_4.1-15        latticeExtra_0.6-29 stringi_1.5.3       checkmate_2.0.0    
 [64] filelock_1.0.2      zip_2.1.1           storr_1.2.5         rlang_0.4.10        pkgconfig_2.0.3     PreciseSums_0.4     evaluate_0.14      
 [71] lattice_0.20-41     RxODE_1.0.7         htmlwidgets_1.5.3   cowplot_1.1.1       tidyselect_1.1.0    magrittr_2.0.1      R6_2.5.0           
 [78] generics_0.1.0      Hmisc_4.5-0         base64url_1.4       txtq_0.2.4          DBI_1.1.1           pillar_1.5.1        haven_2.3.1        
 [85] foreign_0.8-81      withr_2.4.1         units_0.7-1         survival_3.2-10     nnet_7.3-15         modelr_0.1.8        crayon_1.4.1       
 [92] utf8_1.2.1          RApiSerialize_0.1.0 rmarkdown_2.7       jpeg_0.1-8.1        progress_1.2.2      grid_4.0.3          readxl_1.3.1       
 [99] data.table_1.14.0   qpdf_1.1            reprex_2.0.0        digest_0.6.27       brew_1.0-6          RcppParallel_5.0.3  munsell_0.5.0      
[106] stringfish_0.15.1   askpass_1.1  
```

**Comment by mattfidler** [comment]
Qs is quick serialization, by the way.  It is a way to write an R object to a compressed serialized object quickly using Facebook's compression algorithm.  I use it now because it also allows serialization into a string.  So instead of generating C code to create 
RxODE model information, I serialize and input the string into the C code.  Not only has it simplified code in RxODE it has sped up model parsing/generation.

**Comment by billdenney** [comment]
I'm having trouble making a reprex that crashes.

Here is the model and an attempt at a reprex, but it works correctly (i.e. no crash; the actual model is no good because the data don't support all of the parameters).

```r
library(nlmixr)

nlmixr_threecmt_mm <- function() {
  ini({
    tfsc <- log(0.6)
    tka <- log(0.008)
    tcl_low <- log(0.01)
    tcl_high <- log(0.1)
    tcl_c50 <- log(3000)
    tv <- log(4)
    tq1 <- log(0.1)
    tvp1 <- log(10)
    tq2 <- log(0.03)
    tvp2 <- log(20)
    eta_cl~0.05
    eta_v~0.05
    prop_err <- 0.3
    add_err <- 0.1
  })
  model({
    fsc <- exp(tfsc)
    ka <- exp(tka)
    cl_low <- exp(tcl_low + eta_cl)
    cl_high <- exp(tcl_high + eta_cl)
    cl_c50 <- exp(tcl_c50)
    v <- exp(tv + eta_v)
    q1 <- exp(tq1)
    vp1 <- exp(tvp1)
    q2 <- exp(tq2)
    vp2 <- exp(tvp2)
    
    ke_low <- cl_low/v
    ke_high <- cl_high/v
    kc_p1 <- q1/v
    kp1_c <- q1/vp1
    kc_p2 <- q2/v
    kp2_c <- q2/vp2
    
    cp <- CENTRAL/v*1e3 # 1e3 is for unit conversion
    ke <- ke_low + (ke_high - ke_low)*cp/(cp + cl_c50)
    d/dt(SC) =     -ka * SC
    d/dt(CENTRAL) = ka * SC - ke*CENTRAL - kc_p1*CENTRAL + kp1_c*P1 - kc_p2*CENTRAL + kp2_c*P2
    d/dt(P1) =                             kc_p1*CENTRAL - kp1_c*P1
    d/dt(P2) =                                                        kc_p2*CENTRAL - kp2_c*P2
    f(SC) <- fsc
    cp ~ prop(prop_err) + add(add_err)
  })
}

fit <-
  nlmixr(
    object=nlmixr_threecmt_mm,
    data=pheno_sd,
    est="saem",
    control=list(print=1), 
    table=list(cwres=TRUE, npde=TRUE)
  )
vpc(fit)
```

**Comment by billdenney** [comment]
Within `vpc()`, the crash occurs here:

https://github.com/nlmixrdevelopment/nlmixr/blob/ea56f82cc11e9d8a6e25d01d9b7c0548ed5f5a01/R/vpc.ui.R#L139

and more specifically, it occurs here:

https://github.com/nlmixrdevelopment/nlmixr/blob/ea56f82cc11e9d8a6e25d01d9b7c0548ed5f5a01/R/simulate.R#L254

**Comment by billdenney** [comment]
A major part that confuses me about this is that model estimation works and only the vpc has an issue.

**Comment by mattfidler** [comment]
The model that is run for `vpc` moves things about compared to the model that is run for estimation;  The issue is the dynamic transform of both sides that is used in estimation but not used in simulation.

However, even if it is the same model the simulation may choose different parameters (especially in poorly estimated models) so the solving may get to a bad place that isn't as well tested and causes the crashes.

You can get the `vpc` model from `fit$simInfo$rx` if you want to reproduce this with `RxODE`, which is where it is crashing.

**Comment by mattfidler** [comment]
You can try setting a different seed too and that will possibly alleviate the error in the near term.

**Comment by billdenney** [comment]
The model estimates seem reasonable and well-estimated except that the additive error is going close to zero (additive error went to 0.01 and stopped; nothing is going way out to infinitiy).

Might the problem be that I estimated a model with SAEM and the additive residual error went to the boundary?  (I'm about to test removing the additive error from the model to see if it still crashes.)

**Comment by mattfidler** [comment]
Ok let me know if it works.

**Comment by billdenney** [comment]
I am getting closer...

The error does not happen unless I use `stratify`.  There are placebo subjects in the PK model with all zero measurements, and I wonder if that is causing the problem (e.g. all predictions are zero for the entire stratification level).

**Comment by billdenney** [comment]
Well, the model without additive error is a definitively better model, but it still crashes when using `stratify` (and does not crash when not using `stratify`).

**Comment by mattfidler** [comment]
Hm.  Can you extract the RxODE model from `fit$simInfo$rx` and reproduce from there?

**Comment by mattfidler** [comment]
It seems that stratification adds the model variables to the model in a dummy variable:
https://github.com/nlmixrdevelopment/nlmixr/blob/999586b20c089b218787fe5ec965b4d7be5486ca/R/vpc.ui.R#L78-L80

Could you try running the model with a dataset that has lower case column names?  Maybe that is the issue?

**Comment by billdenney** [comment]
Running with lower case column names didn't fix it.

I'm not sure what you mean for "Can you extract the RxODE model from `fit$simInfo$rx` and reproduce from there?"  Can you please be more explicit?  (I tried `vpc_test <- vpc(mod_test$simInfo$rx, data=d_mod_pk)`, but that didn't work.)

**Comment by mattfidler** [comment]
I will produce an example.  I did fix a crash in RxODE with this issue https://github.com/nlmixrdevelopment/RxODE/issues/399  it is possible (though unlikely) upgrading RxODE to the version in github and reinstalling nlmixr will fix this for you.

You will likely have to do:

```r
remotes::install_github("nlmixrdevelopment/nlmixr", force=TRUE)
```

**Comment by mattfidler** [comment]
I mean when you run the model outside of the VPC does it crash;  Here is the example

``` r
library(nlmixr)

pheno <- function() {
  ini({
    tcl <- log(0.008) # typical value of clearance
    tv <-  log(0.6)   # typical value of volume
    ## var(eta.cl)
    eta.cl + eta.v ~ c(1,
                       0.01, 1) ## cov(eta.cl, eta.v), var(eta.v)
    # interindividual variability on clearance and volume
    add.err <- 0.1    # residual variability
  })
  model({
    cl <- exp(tcl + eta.cl) # individual value of clearance
    v <- exp(tv + eta.v)    # individual value of volume
    ke <- cl / v            # elimination rate constant
    d/dt(A1) = - ke * A1    # model differential equation
    cp = A1 / v             # concentration in plasma
    cp ~ add(add.err)       # define error model
  })
}

d_mod <- pheno_sd
d_mod$ACTARM <- factor(as.numeric(d_mod$ID <= median(d_mod$ID)) + 2, levels=1:4, labels=c("A", "B", "C", "D"))
d_mod$AMT[d_mod$ACTARM == "C"] <- 0
d_mod$DV[d_mod$ACTARM == "C"] <- 0
fit <- nlmixr(pheno, d_mod, "saem",
              control=list(print=0),
              table=list(cwres=TRUE, npde=TRUE))
#> ℹ parameter labels from comments will be replaced by 'label()'
#> RxODE 1.0.7.1 using 4 threads (see ?getRxThreads)
#> Calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> Calculating residuals/tables
#> Compiling NPDE model...done
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> done


simInfo <- fit$simInfo

model <- RxODE(paste0(simInfo$rx, "\ndummy~ACTARM"))

sim <- rxSolve(model, simInfo$params, d_mod, omega=simInfo$omega, sigma=simInfo$sigma,
               nstud=100)
```

<sup>Created on 2021-04-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by billdenney** [comment]
The model does not crash when run directly from the `simInfo$rx` model.  It also did not appear to run 100 studies-- it only appeared to run a single study worth of simulation (based on the fact that `nrow(sim) == sum(d_mod$EVID == 0)`).

I'm about to try reinstalling `RxODE` and `nlmixr`.

**Comment by mattfidler** [comment]
Sorry thats a typo on my part; It should be `nStud` not `nstud`:

``` r
library(nlmixr)

pheno <- function() {
  ini({
    tcl <- log(0.008) # typical value of clearance
    tv <-  log(0.6)   # typical value of volume
    ## var(eta.cl)
    eta.cl + eta.v ~ c(1,
                       0.01, 1) ## cov(eta.cl, eta.v), var(eta.v)
    # interindividual variability on clearance and volume
    add.err <- 0.1    # residual variability
  })
  model({
    cl <- exp(tcl + eta.cl) # individual value of clearance
    v <- exp(tv + eta.v)    # individual value of volume
    ke <- cl / v            # elimination rate constant
    d/dt(A1) = - ke * A1    # model differential equation
    cp = A1 / v             # concentration in plasma
    cp ~ add(add.err)       # define error model
  })
}

d_mod <- pheno_sd
d_mod$ACTARM <- factor(as.numeric(d_mod$ID <= median(d_mod$ID)) + 2, levels=1:4, labels=c("A", "B", "C", "D"))
d_mod$AMT[d_mod$ACTARM == "C"] <- 0
d_mod$DV[d_mod$ACTARM == "C"] <- 0
fit <- nlmixr(pheno, d_mod, "saem",
              control=list(print=0),
              table=list(cwres=TRUE, npde=TRUE))
#> ℹ parameter labels from comments will be replaced by 'label()'
#> RxODE 1.0.7.1 using 4 threads (see ?getRxThreads)
#> Calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> Calculating residuals/tables
#> Compiling NPDE model...done
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> done


simInfo <- fit$simInfo

model <- RxODE(paste0(simInfo$rx, "\ndummy~ACTARM"))

sim <- rxSolve(model, simInfo$params, d_mod, omega=simInfo$omega, sigma=simInfo$sigma,
               nStud=100)

print(sim)
#> ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ Solved RxODE object ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
#> ── Parameters ($params): ───────────────────────────────────────────────────────
#> # A tibble: 5,900 x 6
#>    sim.id id    eta.cl   tcl  eta.v    tv
#>     <int> <fct>  <dbl> <dbl>  <dbl> <dbl>
#>  1      1 1      1.23  -5.01  0.721 0.372
#>  2      1 2      0.774 -5.01  0.733 0.372
#>  3      1 3      0.130 -5.01  0.477 0.372
#>  4      1 4     -0.141 -5.01  0.168 0.372
#>  5      1 5      0.482 -5.01  0.287 0.372
#>  6      1 6      0.130 -5.01  0.348 0.372
#>  7      1 7      0.336 -5.01  0.408 0.372
#>  8      1 8      0.795 -5.01  0.515 0.372
#>  9      1 9      0.183 -5.01 -0.224 0.372
#> 10      1 10    -1.08  -5.01 -0.970 0.372
#> # … with 5,890 more rows
#> ── Initial Conditions ($inits): ────────────────────────────────────────────────
#> A1 
#>  0 
#> 
#> Simulation without uncertainty in parameters, omega, or sigma matricies
#> 
#> ── First part of data (object): ────────────────────────────────────────────────
#> # A tibble: 15,500 x 6
#>   sim.id    id  time ipred    sim    A1
#>    <int> <int> <dbl> <dbl>  <dbl> <dbl>
#> 1      1     1   2       0 -1.36      0
#> 2      1     1 112.      0  0.247     0
#> 3      1     2   2       0 -0.973     0
#> 4      1     2  63.5     0 -1.17      0
#> 5      1     2 136.      0 -2.16      0
#> 6      1     3   1.5     0  1.81      0
#> # … with 15,494 more rows
#> ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
```

<sup>Created on 2021-04-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mattfidler** [comment]
> I'm about to try reinstalling RxODE and nlmixr. Update: Reading the other issue, there is a chance that it could be the same issue as the model does use rate (though not dur).

I think it occurs when there is an interaction between `dur` and `f`;  While it was tested in `RxODE` apparently there are some untested edge cases.  I did add the test to the rather large testing suite in `RxODE`, so hopefully it wont happen again.

**Comment by billdenney** [comment]
Reinstalling fixed it!  I guess it was nlmixrdevelopment/RxODE#399.  Thank you for all your help!

**Comment by mattfidler** [comment]
Great!!!
