### ISSUE TITLE
Issues in saem as well as using CENS and LIMIT in the 2.0.3 version of nlmixr

### ISSUE THREAD

**Issue by diabloyg** [nlmixrdevelopment/nlmixr#499]
Hi@mattfidler

I have recently noticed the usage of CENS and LIMIT in dataset as discribed in https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-datasets.html. 

So I reinstalled nlmixr and RxODE to the latest version and modified my dataset to incorporate those BQL sample. For those, the DV is set to the LLOQ (400 ng/mL, 400 in dataset), and the corresponding MDV to 0, CENT to 1 and LIMIT to 0. For others, CENT and LIMIT are set to 0.

However, the model cannot work out with such messages:

focei: 
Error in .fitFun(.ret) : Evaluation error: infinite while evaluating initial objective function;
unhandled error message: EE:[lsoda] 500000 steps taken before reaching tout @(lsoda.c:748)
unhandled error message: EE:lsoda -- at t = 0 and step size _C(h) = 3.79444e-008, the corrector convergence failed repeatedly or
with fabs(_C(h)) = hmin;

saem: 
NaN in prediction; Consider: relax atol & rtol; change initials; change seed; change structure model;
unhandled error message: EE:[lsoda] 100000 steps taken before reaching tout@(lsoda.c:748)

At first I thought it was due to inappropriate initial value or model structure. However, after I deleted CENS and LIMIT column in my dataset, the focei running recovered as previously done, but saem still failed, even without CENS and LIMIT.

Then, I went back to the released nlmixr version 1.1.1.9, which requires reticulate/SnakecharmR to connect to python. To my surprise, both saem and fecei worked even using dataset with CENS and LIMIT column, although the OFV value seemed bigger compared those with same model but no CENS and LIMIT column in dataset, and in saem it tells:

DLSODA-  Warning..Internal T (=R1) and H (=R2) are such that in the machine, T + H = T on the next step  (H = step size). Solver will continue anyway.

So I suppose is there anything wrong in incorporation of the BQL data in the latest version of nlmixr. Or, there is something different with the new version 2.0.3. Have you got any idea about this?

**Comment by mattfidler** [comment]
The old version (with python) ignored the `CENS` and `LIMIT` columns.  All of these error messages you cite are saying you are having a difficult time solving your ODE system.  

Since the system now considers missing values differently, the solutions will be different and the search path will be different.  With `foeci`, the `atol`/`rtol` are adjusted down automatically;  With `saem` this is not the case.  

The test case for the BLQ data seems to work;  see:

https://nlmixrdevelopment.github.io/nlmixr/articles/xgxr-nlmixr-ggpmx.html

As for if they are correct, I believe they are;  If you wish you can check the equations yourself in the code:

https://github.com/nlmixrdevelopment/nlmixr/blob/0b5ffa4b236d8e5c4d6d95c853d0f21ebacb2325/src/saem.cpp#L1233-L1249

And for focei: 

https://github.com/nlmixrdevelopment/nlmixr/blob/0b5ffa4b236d8e5c4d6d95c853d0f21ebacb2325/src/inner.cpp#L690-L695

Both match the literature methods.

**Comment by mattfidler** [comment]
The `saem` algorithm also now uses `liblsoda` instead of `lsoda` by default.  This allows the parallel solving of the ODE systems while optimizing.

**Comment by diabloyg** [comment]
Thanks for your instant reply.

In that way, the old version with python just treat those previous missing DV as LLOQ value (400 in this case), since their MDV now equaled to 0, regardless of cens and limit column. That would definitely lead to change of ofv and estimates.

Another indication is probably that for my case, lsoda solver seems performed better than liblsoda, since even without cens and limit, the model just did not work out in new version. Next I will try figure out how this happened. Thank you.

**Comment by diabloyg** [comment]
I tried several approach but none of them worked with cens and limit column, perhaps due to the complexity of my dataset and model structure. One more thing is that, even for the same dataset without cens and limit column, the model seems run faster in old version given losda solver, although the estimates as well as OFV/AIC do not change a lot.

**Comment by diabloyg** [comment]
In contrast, focei with outerOpt="bobyqa" seemed faster than before, and for my case worked better than saem.

**Comment by mattfidler** [comment]
You can always use `lsoda` instead of `liblsoda` in `saem` by using `method="lsoda"`:

``` r
library(nlmixr)
one.cmt <- function() {
  ini({
    ## You may label each parameter with a comment
    tka <- 0.45 # Log Ka
    tcl <- log(c(0, 2.7, 100)) # Log Cl
    ## This works with interactive models
    ## You may also label the preceding line with label("label text")
    tv <- 3.45; label("log V")
    ## the label("Label name") works with all models
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    linCmt() ~ add(add.sd)
  })
}

fit <- nlmixr(one.cmt, theo_sd, est="saem", control=saemControl(method="lsoda", print=0))
#> ℹ parameter labels from comments will be replaced by 'label()'
#> RxODE 1.0.8.1 using 4 threads (see ?getRxThreads)
#> Calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> Calculating residuals/tables
#> done
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =
#> FALSE, : Bounds are ignored in SAEM


print(fit)
#> ── nlmixr SAEM(Solved); OBJF not calculated fit ────────────────────────────────
#> 
#>  Gaussian/Laplacian Likelihoods: AIC() or $objf etc. 
#>  FOCEi CWRES & Likelihoods: addCwres() 
#> 
#> ── Time (sec $time): ───────────────────────────────────────────────────────────
#> 
#>          saem    setup table covariance    other
#> elapsed 0.624 0.705911 0.008      0.006 0.528089
#> 
#> ── Population Parameters ($parFixed or $parFixedDf): ───────────────────────────
#> 
#>        Parameter  Est.     SE %RSE Back-transformed(95%CI) BSV(CV%) Shrink(SD)%
#> tka       Log Ka 0.447  0.194 43.4       1.56 (1.07, 2.29)     70.6    -0.900% 
#> tcl       Log Cl  1.02  0.087 8.54       2.77 (2.33, 3.28)     28.3      4.17% 
#> tv         log V  3.45 0.0426 1.24       31.4 (28.9, 34.1)     12.2      9.77% 
#> add.sd           0.699                               0.699                     
#>  
#>   Covariance Type ($covMethod): linFim
#>   Fixed parameter correlations in $cor
#>   No correlations in between subject variability (BSV) matrix
#>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs) 
#>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink 
#> 
#> ── Fit Data (object is a modified tibble): ─────────────────────────────────────
#> # A tibble: 132 x 16
#>   ID     TIME    DV  PRED    RES     IPRED   IRES  IWRES eta.ka eta.cl   eta.v
#>   <fct> <dbl> <dbl> <dbl>  <dbl>     <dbl>  <dbl>  <dbl>  <dbl>  <dbl>   <dbl>
#> 1 1     0      0.74  0     0.74  -1.96e-15  0.74   1.06   0.105 -0.481 -0.0783
#> 2 1     0.25   2.84  3.26 -0.419  3.85e+ 0 -1.01  -1.45   0.105 -0.481 -0.0783
#> 3 1     0.570  6.57  5.84  0.729  6.79e+ 0 -0.221 -0.316  0.105 -0.481 -0.0783
#> # … with 129 more rows, and 5 more variables: ka <dbl>, cl <dbl>, v <dbl>,
#> #   tad <dbl>, dosenum <dbl>
```

<sup>Created on 2021-04-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mattfidler** [comment]
There are many more optimization methods available to `focei`, just like with R the optimization methods have different results and speeds with various data types.

**Comment by diabloyg** [comment]
It seems that, for my dataset and model, if fewer censored data is incorporated, the model works fine with focei; however if more censored data is incorporated, there are some difficulties. This indicated that while the implementation of such approach is fine, my dataset and model seemed not working. Next I will try to figure out how to deal with this. Thanks for your help~ @mattfidler

**Comment by diabloyg** [comment]
Besides, according to my test, the incorporation of BQL data only in intensive sampling period seems feasible, while the incorporation of sparse BQL data (scenario where during one administration period there is only one sample available, with concentration lower than LLOQ), would be problematic.

**Comment by mattfidler** [comment]
I believe a subject with only one administration and only BLQ values would have numeric difficulties to figure out an optimal individual estimate.

**Comment by diabloyg** [comment]
> I believe a subject with only one administration and only BLQ values would have numeric difficulties to figure out an optimal individual estimate.

In my dataset every subject has both intensive and sparse sampling, for different dosing period. If the BQL sample is located in period with intensive sampling, the model works fine. However, If the BQL sample is located in period with no other sample, it is problematic. 

It seems that, the feasibility of incorporating BQL sample depends on whether there is other available concentrations within the same dose interval, which seems strange. 

After all, since EBEs could be obtained without these BQL information, then incorporation of those would help, rather than disturb the model optimization process.

**Comment by mattfidler** [comment]
In theory it is simply adding the liklihood of observing the BLQ at each time (and in the case of focei the gradient for the inner problem).  I don't see why that would be the case except for the direction of the search may go into a stiffer region of the model.

**Comment by diabloyg** [comment]
> 
> 
> In theory it is simply adding the liklihood of observing the BLQ at each time (and in the case of focei the gradient for the inner problem). I don't see why that would be the case except for the direction of the search may go into a stiffer region of the model.

That's exactly what I mean before ╮(╯-╰)╭. I have no idea yet, it just happened like this.

**Comment by mattfidler** [comment]
Hi @diabloyg 

Maybe you can try updating from the development version:

```r
remotes::install_github("nlmixrdevelopment/nlmixr")
```

This may fix your problems with `saem` if you are using `add() + prop()` or something more complex for your error model.

**Comment by diabloyg** [comment]
> 
> 
> Hi @diabloyg
> 
> Maybe you can try updating from the development version:
> 
> ```r
> remotes::install_github("nlmixrdevelopment/nlmixr")
> ```
> 
> This may fix your problems with `saem` if you are using `add() + prop()` or something more complex for your error model. (In #503)

Indeed. Since I do incorporated additive+proportional error, the saem running results are much more reasonable compared with those before update. Thanks very much~

**Comment by mattfidler** [comment]
Great;  Is it true with `CENS` too?

**Comment by diabloyg** [comment]
Yes it works for both saem and focei with cens and limit scenario, though sparse BQL still bring difficulties.

**Comment by mattfidler** [comment]
Well, I'm unsure why.  Perhaps there isn't enough of a grid for ODEs to be solved correctly.

**Comment by mattfidler** [comment]
You could try adjusting `hmax` and `hmin` so that they solve more slowly and precicely to help solve this point correctly.

**Comment by diabloyg** [comment]
Thanks for your kind reminder. I believe that it is not likely to propose a resolving approach appropriate for different scenarios. For my datasets, it seemed that deleting those sparse BQL data is helpful, but I don't know why, nor I know whether it is better than other solution. Since currently we don't know in detail, may I close this discussion or it is better to leave it here?

**Comment by mattfidler** [comment]
Sure
