### ISSUE TITLE
dll needs to be removed with nlmxr/SAEM before a new model can be run

### ISSUE THREAD

**Issue by RikSchoemaker** [nlmixrdevelopment/nlmixr#5]
When you create an SAEM model, e.g. using the following syntax:

`saem_fit <- gen_saem_user_fn(model=lincmt(ncmt=1, oral=FALSE,infusion=TRUE))`

and then want to run a new model, you need to explicitly remove the dll before this works using:

```
dyn.unload("saem_main.dll")
saem_fit <- gen_saem_user_fn(model=lincmt(ncmt=2, oral=FALSE,infusion=TRUE))

```
Although it is nice that the dll is persistent so it can be reused for new data with the same model, it would be much nicer if the dll can be referenced explicitly (like with nlme) and put in a separate subdirectory instead of being created in the run directory. This may also be related to the issue with running multiple SAEM instances in parallel (see other issue).

**Comment by mattfidler** [comment]
Should be fixed in the dparser-saem branch,
