### ISSUE TITLE
Feature Request: Rate-limit NaN warning

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#500]
Is it possible to rate-limit this warning to once per iteration?  While estimating a model just now, it showed about 20 times per iteration.

https://github.com/nlmixrdevelopment/nlmixr/blob/4ec38650baa06fa4d5822ebc977c6cad913518f4/src/saem.cpp#L1448

**Comment by mattfidler** [comment]
I can see the value, but it is a bit low on the priority list.

**Comment by mattfidler** [comment]
Once per `saem` problem now

**Comment by billdenney** [comment]
Thank you!
