### ISSUE TITLE
Simulation IDs are sometimes set from original fitting dataset

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#507]
I have a model where the original dataset used for fitting has values in the `ID` column that are character class.  When I run a simulation with id set to a numeric value, the simulation result has the character values from the fitting dataset instead of the numeric values from the simulation dataset that I was expecting.

I'm trying to generate a reprex, but if you have any pointers for where the issue may be coming from, I'd be very interested.

My versions of nlmixr and RxODE are several days old in case that matters.

**Comment by mattfidler** [comment]
I haven't seen it so I'm unsure.

**Comment by billdenney** [comment]
I just found that it was a user error (I was using the `data` instead of `events` to pass in my data).
