### ISSUE TITLE
Question: What is the best way to extract the original model function?

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#525]
When reporting, I want to provide a listing of the model used.  For that, I would prefer to extract the model function from the model (rather than tracking which model function goes with which fit manually).  The best way that I found to get the character listing of the model is below.  Is there a better way?

```r
# best_model_vehicle is the model that I fit
cat(as.character(attr(best_model_vehicle$uif$model, "srcref")), sep="\n")
```

**Comment by mattfidler** [comment]
Currently the full model function is not stored in the nlmixr fit object;

There is a reporting function that does something similar `nmLst` and `nmDocx`, I cannot recall how I handle it there.

**Comment by mattfidler** [comment]
One note, the code you are using requires `keep.source` is true.  Therefore this solution doesn't work with batch mode

**Comment by mattfidler** [comment]
Hopefully this is good enough for now
