### ISSUE TITLE
Compilation Terminated - RcppArmadillo.h

### ISSUE THREAD

**Issue by ortizem** [nlmixrdevelopment/nlmixr#53]
Hi,

I am trying to install nlmixr but I am getting the following error:

```
g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/dparser/include" -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppEigen/include" -I"/usr/lib64/R/library/StanHeaders/include" -I"/usr/lib64/R/library/BH/include" -I/usr/local/include  -Id -I../inst/include -DBOOST_DISABLE_ASSERTS -I"`"/usr/lib64/R/bin/Rscript" -e 'cat(file.path(system.file("", package = "RcppArmadillo"),"include"))'`" -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c RcppExports.cpp -o RcppExports.o
Rscript execution error: Exec format error
g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/dparser/include" -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppEigen/include" -I"/usr/lib64/R/library/StanHeaders/include" -I"/usr/lib64/R/library/BH/include" -I/usr/local/include  -Id -I../inst/include -DBOOST_DISABLE_ASSERTS -I"`"/usr/lib64/R/bin/Rscript" -e 'cat(file.path(system.file("", package = "RcppArmadillo"),"include"))'`" -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c focei_fit.cpp -o focei_fit.o
Rscript execution error: Exec format error
focei_fit.cpp:1:27: fatal error: RcppArmadillo.h: No such file or directory
compilation terminated.
make: *** [focei_fit.o] Error 1
ERROR: compilation failed for package ‘nlmixr’
* removing ‘/usr/lib64/R/library/nlmixr’
Installation failed: Command failed (1)
> q()

I located RcppArmadillo.h and I do have it in my library:

[root@amrvlp000005185 Python-3.6.5]# locate -i RcppArmadillo.h
/usr/lib64/R/library/RcppArmadillo/include/RcppArmadillo.h
/var/lib/rstudio-connect/packrat/3.4.3/v2/library/RcppArmadillo/06d74d305dc7f3c53054e88efd49b097/RcppArmadillo/include/RcppArmadillo.h
/var/lib/rstudio-connect/packrat/3.4.3/v2/library/RcppArmadillo/dd3c11bed5cee97ee28e5543659ed01a/RcppArmadillo/include/RcppArmadillo.h
/var/lib/rstudio-connect/packrat/3.4.3/v2/library/RcppArmadillo/f280a22174c410654514ef1860a246be/RcppArmadillo/include/RcppArmadillo.h
```

Please advise. Thank you in advance.

**Comment by mattfidler** [comment]
nlmixr gets the location of RcppArmdillo with the following command

```sh
/usr/lib64/R/bin/Rscript" -e 'cat(file.path(system.file("", package = "RcppArmadillo"),"include"))'
```

Which should give:
```
/usr/lib64/R/library/RcppArmadillo/include/
```

My guess is this is what is broken for you.

**Comment by ortizem** [comment]
Thank you @mattfidler. Is there a workaround to this issue? How can I fix it? I checked and I do have RcppArmadillo in the path.

**Comment by mattfidler** [comment]
Hi @ortizem 

So to be clear you ran the following command:

```
/usr/lib64/R/bin/Rscript" -e 'cat(file.path(system.file("", package = "RcppArmadillo"),"include"))'
```

and what did it give you?  This can help me figure out the next step for your system.

**Comment by ortizem** [comment]
Hi @mattfidler 

I ran the command but I don't get anything back. It jumps to a new empty line with the '>' symbol. 
For example:
[root@server] /usr/lib64/R/bin/Rscript" -e 'cat(file.path(system.file("", package = "RcppArmadillo"),"include"))'
'>'

**Comment by mattfidler** [comment]
Ok,  

It seems that the R session is not recognizing your libpaths from `Rscript`

Try
```sh
R_LIBS=/usr/lib64/R/library/ /usr/lib64/R/bin/Rscript -e 'cat(file.path(system.file("", package = "RcppArmadillo"),"include"))'
```

In theory that should give you the right result.  If so, you could run:

```sh
R_LIBS=/usr/lib64/R/library/ /usr/lib64/R/bin/R
```
And then

```R
devtools::install_github("nlmixrdevelopment/RxODE")
devtools::install_github("nlmixrdevelopment/nlmixr")
```

**Comment by ortizem** [comment]
Hi @mattfidler 

I tried to run the command with the R_LIBS path but now I get a "Rscript execution error:Exec format error".

` R_LIBS=/usr/lib64/R/library/ /usr/lib64/R/bin/Rscript -e 'cat(file.path(system.file("", package = 
'RcppArmadillo"),"include"))'`
`Rscript execution error: Exec format error
`
I am using R 3.4.3
`R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)`

**Comment by mattfidler** [comment]
You can try to look at the libpaths from within R

Start `R` and then type:

```R
.libPaths()
```

**Comment by ortizem** [comment]
Hi @mattfidler,

I have the right path for the R libraries. 
`> .libPaths()`
`[1] "/usr/lib64/R/library" "/usr/share/R/library"
`

**Comment by mattfidler** [comment]
Hm.  That is strange.  

Once you enter R, what do you get for:

`cat(file.path(system.file("", package = 'RcppArmadillo"),"include"))`

**Comment by mattfidler** [comment]
I can't see the differences in the first command and the third command.

**Comment by mattfidler** [comment]
I ave tried to use the `find.package` in the Makevars, I'm unsure if it will work for you.

**Comment by ortizem** [comment]
@mattfidler 

I still get the same error. I think it is Rscript that doesn't like the command because the command itself works in R but not with Rscript.
`g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/dparser/include" -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppEigen/include" -I"/usr/lib64/R/library/StanHeaders/include" -I"/usr/lib64/R/library/BH/include" -I/usr/local/include  -Id -I../inst/include -DBOOST_DISABLE_ASSERTS -I" "/usr/lib64/R/bin/Rscript" -e 'cat(file.path(find.package("RcppArmadillo"),"include"))'" -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c RcppExports.cpp -o RcppExports.o
Rscript execution error: Exec format error`
`g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/dparser/include" -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppEigen/include" -I"/usr/lib64/R/library/StanHeaders/include" -I"/usr/lib64/R/library/BH/include" -I/usr/local/include  -Id -I../inst/include -DBOOST_DISABLE_ASSERTS -I" "/usr/lib64/R/bin/Rscript" -e 'cat(file.path(find.package("RcppArmadillo"),"include"))'" -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c focei_fit.cpp -o focei_fit.o
Rscript execution error: Exec format error`
`focei_fit.cpp:1:27: fatal error: RcppArmadillo.h: No such file or directory`
`compilation terminated.`
`make: *** [focei_fit.o] Error 1`
`ERROR: compilation failed for package ‘nlmixr’`
`* removing ‘/usr/lib64/R/library/nlmixr’`
`Installation failed: Command failed (1)`

Command Itself:
`> cat(file.path(find.package("RcppArmadillo"),"include"))`
`/usr/lib64/R/library/RcppArmadillo/include>`

**Comment by ortizem** [comment]
@mattfidler 

Rscript execution error: 
`[root]# Rscript -e 'cat(file.path(find.package("RcppArmadillo"),"include"))'`
`Rscript execution error: Exec format error
`

Works if I use R:
`[root@]# R -e 'cat(file.path(find.package("RcppArmadillo"),"include"))'`
`R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> cat(file.path(find.package("RcppArmadillo"),"include"))
/usr/lib64/R/library/RcppArmadillo/include>`

**Comment by mattfidler** [comment]
Hi @ortizem When you use R does it echo the startup as well.  If so, I can't use that solution.  It also seems to continue the R session.

**Comment by ortizem** [comment]
Hi @mattfidler 
What do you recommend in this case? Should I try to upgrade R? Please let me know.

**Comment by mattfidler** [comment]
I'm not sure.  In theory they should have the same results for libpaths.  A possibility is you have multiple R installations and the `Rterm` that you are using is different from the one which uses `R`

To check, you can do the following for me:

```sh
which Rterm
```

```sh
which R
```

In theory the should point to a similar location.  Sometimes these are actually shell scripts;  Knowing the location can help me figure out if that is true or not.

**Comment by ortizem** [comment]
HI @mattfidler 

It loos like I don't have Rterm:
`[root@ctl rstudio-connect]# which R
/usr/bin/R
[root@ctl rstudio-connect]# which Rterm
/usr/bin/which: no Rterm in (/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/ortize35/bin:/root/packages/bin)
[root@ctl rstudio-connect]#
`

**Comment by mattfidler** [comment]
That could be the problem.  Perhaps you do have to reinstall R.

According to the "Writing R Extensions", you should have the `Rterm`.

>If you want to run R code in Makevars, e.g. to find configuration information, please do ensure that you  use the correct copy of R or Rscript: there might not be one in the path at all, or it might be the wrong version or architecture. The correct way to do this is via
```sh
"$(R_HOME)/bin$(R_ARCH_BIN)/Rscript" filename
"$(R_HOME)/bin$(R_ARCH_BIN)/Rscript" -e ‘R expression’
```

See 

https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-Makevars

**Comment by mattfidler** [comment]
FYI this is how it is done in the `Makevars`

**Comment by mattfidler** [comment]
You could see where the `R_HOME` should be located by looking at the link location for the R executable

My unix commands are a  bit rusty, but I think you type

```sh
ls -al /usr/bin/R
```
And it should show a link to a directory.  From this directory you can infer what the `R_HOME` should be and use that as an environmental variable to see if that fixes the installation for you.

**Comment by mattfidler** [comment]
Could try to use 

https://github.com/kevinushey/configure

Instead; Perhaps that will fix the issue.

**Comment by mattfidler** [comment]
That package is a bit broken for me at the moment;  However, I was wondering what is provided when you call:

```sh
ls `R RHOME`/bin
```

In theory there should be an `R` and `Rscript` present

**Comment by ortizem** [comment]
Hi @mattfidler 

I do see `R` and `Rscript` when I enter `ls `R RHOME`/bin`

`[@ctl ~]$ ls `R RHOME`/bin`
`BATCH  check    config  f77_f2c  javareconf  LINK           pager  Rcmd    Rdconv  REMOVE  Rscript  R.wrapped  Stangle
build  COMPILE  exec    INSTALL  libtool     mkinstalldirs  R      Rd2pdf  Rdiff   Rprof   rtags    SHLIB      Sweave`

**Comment by mattfidler** [comment]
Great.  Can you try the following: 
```
`R RHOME`/bin/Rscript -e 'cat(file.path(find.package("RcppArmadillo"),"include"))'
```

If it gives RcppArmadillo's include path, perhaps I can fix the build.

**Comment by ortizem** [comment]
I still get the same `Rscript execution error: Exec format error`

`[root@ctl ~]# `R RHOME`/bin/Rscript -e 'cat(file.path(find.package("RcppArmadillo"),"include"))'`
`Rscript execution error: Exec format error`

I tried to installed it using R 3.5.0 and it installed successfully. I believe it is a R 3.4.3 issue.

**Comment by mattfidler** [comment]
https://github.com/node-red/node-red/issues/1647

**Comment by mattfidler** [comment]
It seems to be happening on other platforms and distributions;  Perhaps it is an R issue... For now I'm closing the issue, but I'm still thinking about how to fix it for R 3.4

**Comment by mattfidler** [comment]
Hi @ortizem,  

I'm unsure why, but the following works for me in R 3.4:

```R
mylib <- paste0("~/R/x86_64-pc-linux-gnu-library/",R.version$major,".",sub('[.].','',R.version$minor))
Sys.setenv(R_LIBS_USER=mylib)

dir.create(file.path(mylib), showWarnings = FALSE, recursive=TRUE)
withr::with_libpaths(new = mylib, devtools::install_github("nlmixrdevelopment/PreciseSums@*release", force=TRUE))
withr::with_libpaths(new = mylib, devtools::install_github("nlmixrdevelopment/SnakeCharmR", force=TRUE))
withr::with_libpaths(new = mylib, devtools::install_github("ggrothendieck/rsympy", force=TRUE))
withr::with_libpaths(new = mylib, install.packages('rSymPy', destdir = mylib))
withr::with_libpaths(new = mylib, devtools::install_github("nlmixrdevelopment/RxODE@*release", force=TRUE))
withr::with_libpaths(new = mylib, devtools::install_github("nlmixrdevelopment/nlmixr@*release", force=TRUE))
```

**Comment by mattfidler** [comment]
However, it installs it in a personal library.  It may work if you use `install_github` instead of `install.packages`.  I am not at all sure why.

If you just want to test it with nlmixr (and the CRAN version of it) you could use:
```R
devtools::install_github("nlmixrdevelopment/nlmixr@*release", force=TRUE)
```

Currently the release is the CRAN release.
