### ISSUE TITLE
Any approah modeling PK-binominal PD or PK-ordered categorical PD data in nlmixr?

### ISSUE THREAD

**Issue by diabloyg** [nlmixrdevelopment/nlmixr#535]
Hi@mattfidler, recently I'd like to model the PK-adverse event model to demonstrate the exposure-safety relaionship. The preliminary approach was to first do popPK modeling, then have individual exposure prediction, and finally link individual exposure to adverse events using logistic regression or survival analysis. However, such approach disconnected PK and PD, and if logistic regression is used the time information of events is ignored.

Then I would like to try joint PK-PD model which incorporating individual predicted PK parameters and observed PD events with time record, which is PK-categorical PD model. As far as I know the ensence of such approach is to redefine the likelihood function as those in NONMEM. However, I have no idea whether it could be resolved in nlmixr. If it is allowed, could you please tell me how to handle this?

**Comment by mattfidler** [comment]
Currently the likelihood can be specified by lower level functions like `gnlmm` and `gnlmm2`.  However these haven't been ported to the function interface currently.  

There is a discussion on how to use the function here: 

https://github.com/nlmixrdevelopment/nlmixr/issues/261

**Comment by mattfidler** [comment]
Since this is a duplicate issue,  I will close this for now.  Let me know if this is helpful for you or you have any other questions
