### ISSUE TITLE
Documentation Request: Update lincmt docs

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#536]
I'm wanting to use `linCmt()` in a new model, but I'm having trouble figuring out how to make use of it specifically.  I looked to the `lin_cmt` documentation, but that didn't show how to use it.  I went to https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-model-types.html#solved-compartment-models, but in the original post where I found it, said that it is outdated.  (Maybe it is now up to date.)

So, the request is:  Where is use of `linCmt()` best documented?  And, can that be linked to or updated in the `?lin_cmt` docs?

**Comment by mattfidler** [comment]
This was updated to show that the RxODE documentation is what should be used.

**Comment by billdenney** [comment]
Thanks!
