### ISSUE TITLE
%RSE for IIV terms and residual variability

### ISSUE THREAD

**Issue by Andy00000000000** [nlmixrdevelopment/nlmixr#547]
Is there a way to get %RSE of ETA terms and the proportional residual error from a nlmixr fit (version 2.0.4)? I could not find these in the fit object or in any examples. Thanks in advance for any help.

**Comment by mattfidler** [comment]
Hi @Andy00000000000,

Since these are not calculated in nlmixr currently there is not any way to retrieve these values
