### ISSUE TITLE
ED50 using ML & AIC: Phoenix NLME and PROC NLMIXED

### ISSUE THREAD

**Issue by hrishikesh1985** [nlmixrdevelopment/nlmixr#552]
Hi,

I am very fresh to the r so please excuse my limitations for nlmixr and r.

My Interest is to calculate ED50 and Emax of dose response study (skin blanching) using ML and AIC criteria.

I have prepared SAS code using PROC NLMIXED for Emax and ED50 and results are matching with phoenix NMLE -Emax modeling.

Now I wanted to develop the code with r using nlmixr and need help from the experts.
Below is model text for NLME
test(){
	covariate(C)
	E = Emax * C / (EC50 + C)
	error(EEps = 1)
	observe(EObs(C) = E + EEps)
	stparm(EC50 = tvEC50)
	stparm(Emax = tvEmax + nEmax)
	fixef(tvEC50 = c(, 1, ))
	fixef(tvEmax = c(, 1, ))
	ranef(diag(nEmax) = c(1))
}

Please find data which were used for the calculation and result for Emax and ED50 were -6.4 and 52.5 .

Can anyone help me to build r code using nlmixr

[AUEC.zip](https://github.com/nlmixrdevelopment/nlmixr/files/6884707/AUEC.zip)

**Comment by mattfidler** [comment]
I am unaware or forgotten  the Pheonix NLME syntax.  Can you provide the context of the model you are trying to produce.

Thanks

**Comment by hrishikesh1985** [comment]
[Attach.docx](https://github.com/nlmixrdevelopment/nlmixr/files/6898008/Attach.docx)
Hi, Thanks for showing interest. 
Please find the attached for your reference.

**Comment by diabloyg** [comment]
Hi, I've checked your data and it seemed to me that it is too complicated to be discribed using a simple Emax model. In that case, total different estimation might be obtained if the software platform, algorithm and initials are changed. 

If you insist on working this out using an Emax model, which I don't think it's a good choice, please refer to #517 .

**Comment by mattfidler** [comment]
Thanks,

I agree with @diabloyg, if you wish to use Emax with the current version of nlmixr, follow the example in #517

**Comment by mattfidler** [comment]
I assume this has been figured out

**Comment by brazilianstudent** [comment]
> Hi,
> 
> I am very fresh to the r so please excuse my limitations for nlmixr and r.
> 
> My Interest is to calculate ED50 and Emax of dose response study (skin blanching) using ML and AIC criteria.
> 
> I have prepared SAS code using PROC NLMIXED for Emax and ED50 and results are matching with phoenix NMLE -Emax modeling.
> 
> Now I wanted to develop the code with r using nlmixr and need help from the experts. Below is model text for NLME test(){ covariate(C) E = Emax * C / (EC50 + C) error(EEps = 1) observe(EObs(C) = E + EEps) stparm(EC50 = tvEC50) stparm(Emax = tvEmax + nEmax) fixef(tvEC50 = c(, 1, )) fixef(tvEmax = c(, 1, )) ranef(diag(nEmax) = c(1)) }
> 
> Please find data which were used for the calculation and result for Emax and ED50 were -6.4 and 52.5 .
> 
> Can anyone help me to build r code using nlmixr
> 
> [AUEC.zip](https://github.com/nlmixrdevelopment/nlmixr/files/6884707/AUEC.zip)

Hey!

> 

Hey! How are you? I'm pretty new at statistics and PD study with blanching assay. I am trying to learn how to calculate Emax using SAS and I stopped by this post. Would you mind sharing the code you used to obtain Emax with PROC NLMIXED in SAS?
Thank you!

**Comment by mattfidler** [comment]
Hi,

I'm sorry but I don't use SAS so I cannot compare.

Matt
