### ISSUE TITLE
error with tidy(): Column name `effect` must not be duplicated

### ISSUE THREAD

**Issue by davja** [nlmixrdevelopment/nlmixr#554]
I'm getting the following error when using broom.mixed::tidy(fit.s, effects="fixed")
Error: Column name `effect` must not be duplicated.

where fit.s is the same as the example  in https://nlmixrdevelopment.github.io/nlmixr/articles/broom.html
i.e., 
`fit.s <- nlmixr(pheno, pheno_sd, "saem", control=list(logLik=TRUE, print=0),
                table=list(cwres=TRUE, npde=TRUE))`

Other functions like 
`broom.mixed::glance(fit.s)`
work fine

When running the same code on another computer broom.mixed works fine. Versions for broom.mixed and nlmixr are 0.2.7 and 2.0.4. Any ideas on how to troubleshoot this?

**Comment by mattfidler** [comment]
Seems difficult to debug.  I would suggest comparing the sessionInfo between the two machines.  Pay particular attention to the `generics`, `pillar` and `tibble`.

**Comment by davja** [comment]
Thanks, those were updated to latest version but the issue persisted. Reinstalling tidyverse did the trick though, not sure why. Thanks!

**Comment by mattfidler** [comment]
It is odd.  These things are hard to track down.  Thanks for reporting!
