### ISSUE TITLE
Error with nlmixr 2.0.5 - compiled against different version of RxODE

### ISSUE THREAD

**Issue by namtien0312** [nlmixrdevelopment/nlmixr#555]
Hi, nlmixr team,

I try to use the latest version - **nlmixr 2.0.5** - but it has an error with **RxODE 1.1.1**.

Thank you for your help to solve this problem.

```
library(nlmixr)
```
```
Error: package or namespace load failed for 'nlmixr':
 .onAttach failed in attachNamespace() for 'nlmixr', details:
  call: NULL
  error: nlmixr compiled against different version of RxODE, cannot run nlmixr
```

**Comment by mattfidler** [comment]
Hi @namtien0312,

First try:


```R
install.packages("nlmixr")
```  

CRAN has said that they update the binaries based on dependencies for windows builds and sometimes for mac builds.

If this doesn't work, try:

```R
install.packages("nlmixr", type = "source")
```  

This will recompile against the current version of `RxODE`.  This was added so that random crashes with nlmixr wouldn't happen because of binary mismatches between `RxODE` and `nlmixr`.

Perhaps the error message should be updated to say how to fix this.

**Comment by namtien0312** [comment]
Thank you for your help @mattfidler 

The code `install.packages("nlmixr", type = "source")` can solve this problems.

**Comment by mattfidler** [comment]
Great! In the next release these instructions will be included.

**Comment by rpang88** [comment]
Hi Matt and all,

I wondered whether someone can help. I am trying to use nlmixr on my macbook using Rstudio 2021.09.2. I installed using the command install.packages("nlmixr") with no issues. However when trying to open library the following error appears:

**Error: package or namespace load failed for ‘nlmixr’:
 .onAttach failed in attachNamespace() for 'nlmixr', details:
  call: NULL
  error: nlmixr compiled against different version of RxODE, cannot run nlmixr**

I have all tried as suggested to install `install.packages("nlmixr", type = "source")`

Following error appears at the end:

ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [nlmixr.so] Error 1
ERROR: compilation failed for package ‘nlmixr’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/nlmixr’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/nlmixr’
Warning in install.packages :
  installation of package ‘nlmixr’ had non-zero exit status


Either way, trying to run nlmixr again, with the same error. 

Any help would be appreciated. 

Many Thanks

**Comment by mattfidler** [comment]
For a Mac you have to setup the fortran tool-chain. , otherwise the compilation will not work.

The ones that R uses are here:

https://github.com/fxcoudert/gfortran-for-macOS/releases


Good luck.

**Comment by rpang88** [comment]
Thanks! Installed and now seems to be working:

The only error I seem to have is the following: 
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: dylib (/usr/local/gfortran/lib/libgfortran.dylib) was built for newer macOS version (12.0) than being linked (10.13)
ld: warning: dylib (/usr/local/gfortran/lib/libquadmath.dylib) was built for newer macOS version (12.0) than being linked (10.13)


Do you have any ideas how this could be fixed? 

Thanks!

**Comment by mattfidler** [comment]
This says you need to upgrade your mac OS version and likely reinstall all of R, Xcode, etc.  This could be time consuming and slow down your computer.

If it is working, maybe the mac internals are OK.  If it isn't working, maybe you may wish to consider this.

**Comment by AprilCCC** [comment]
Hi Matt and all,

I tried install.packages("nlmixr") AND install.packages("nlmixr", type = "source") in RGui windows. Both didn't work out. It shows error below:

nlmixr compiled against different version of RxODE, cannot run nlmixr
try `install.packages("nlmixr", type = "source")` to recompile

Any help would be appreciated.

Many Thanks

**Comment by namtien0312** [comment]
Hi @AprilCCC 

From my experience, It might seem that `nlmixr` version `2.` works on R >= 4.0.

Should you try to upgrade R and re-install `nlmixr`?

Tien.

**Comment by AprilCCC** [comment]
Hi @namtien0312 

Thanks for the suggestion. I misspelled the R version, which is 4.1.3, the most current one. How can I get nlmxr to be version 2. ?

**Comment by mattfidler** [comment]
You may have to restart R.  Then run:

```r
install.packages("nlmixr", type="source")
```

**Comment by AprilCCC** [comment]
It still did not work on Windows but works on Mac now. Thanks

**Comment by rpang88** [comment]
Dear all,

Wondered whether someone can help

I am trying to run nlmixr on my mac (OS 12.4) using RStudio
I have previously not had many issues with this.

I updated the gfortran v12.1 using the website https://github.com/fxcoudert/gfortran-for-macOS/releases, RStudio (Build 548) and R version 4.2.1 today but not sure whether there is some error now with the new gfortran as when i try to load nlmixr after reinstalling I have the following error:

> library(nlmixr)
Error: package or namespace load failed for ‘nlmixr’:
 .onLoad failed in loadNamespace() for 'RxODE', details:
  call: NULL
  error: RxODE compiled with PreciseSums '0.4' but PreciseSums '0.5' is loaded
Recompile RxODE with the this version of PreciseSums

I am not sure why this is occurring.
Does anyone have any advice?

When i try to run the model:
Error in nlmixr(run24.mod) : could not find function "nlmixr"

**Comment by mattfidler** [comment]
You can do the following:
1. Use `nlmixr2` (i.e. `install.pakcages("nlmixr2")`), which I am actively supporting
2. Use `nlmixr` but compile the binaries from source

If you want option #2 you can do the following:

```r 
install.packages("RxODE", type="source")
install.packages("nlmixr", type="source")
```
Which will compile it against whatever version of `PreciseSums` you are using.
