### ISSUE TITLE
Question: Obtaining individual parameter estimate without pop params estimation (MAXEVAL = 0 in NONMEM)

### ISSUE THREAD

**Issue by namtien0312** [nlmixrdevelopment/nlmixr#557]
Dear `nlmixr` team,

How can I obtain `individual parameters` without population parameters estimate, in `NONMEM` it is equivalent to:
```
$ EST METHOD=1 INTER MAXEVAL=0  
or
$EST METHOD=COND LAPLACE LIKE MAXEVAL=0  
```
Thank you for your help!

**Comment by mattfidler** [comment]
Hi @namtien0312 

You simply use the following

```r
fit <- nlmixr(nlmixrFun, nlmixrData, est="posthoc")
```

**Comment by namtien0312** [comment]
Thank you @mattfidler for your help!
