### ISSUE TITLE
Specify fitting compartment

### ISSUE THREAD

**Issue by DimitrisVoul** [nlmixrdevelopment/nlmixr#560]
Hello, I have a dataset with multiple CMTs inlcuding absorption, central and effect. It was created to fit the data simultaneously with multiple endpoints bit now I only want to fit the data of the 3rd CMT which is the effect. When I write

effect ~ prop(effect.prop)

Where do I specify which DV data to use for the fitting (namely only the CMT=3 ones)

**Comment by mattfidler** [comment]
Hi @DimitrisVoul 

In theory you can look at the multiple endpoints output.  This is discussed here:

https://nlmixrdevelopment.github.io/nlmixr/articles/multiple-endpoints.html

The table tells what `CMT` or `DVID` values correspond to an effect.

If there is something unclear there, please let me know.

**Comment by DimitrisVoul** [comment]
Hello,

No I don't want to fit with multiple endpoints. I am only interested in fitting one of the CMT. How can I specify which CMT/DVID nlmixr uses to fit the data?

**Comment by mattfidler** [comment]
In that case, the evid is sufficient to model the data.  If it doesnt work
it is a bug.
