### ISSUE TITLE
patients with multiple independent treatments

### ISSUE THREAD

**Issue by fernandoortega** [nlmixrdevelopment/nlmixr#576]
Hi,

I want to use nlmixr to determine the parameters of a PD model (I have the PK model). In this dataset, each patient receives several independent treatments. (please see a simplified table below). Would it be possible to use nlmixr to determine PD model parameters and the estimate for each patient?

Thank you very much in advance.
Fernando

EXP   ID   TIME   EVID   AMT    DV       CMT
1        1      0         0         0      100          3
1        1      1        101    100      0            1
1        1      2         0         0       80           3
1        1      3         0         0       75           3
2        1      0         0         0      120          3
2        1      1        101    150      0            1
2        1      2         0         0       115         3
2        1      3         0         0       116         3
3        2      0         0         0      100          3
3        2      1        101     25      0             1
3        2      2         0         0       80           3
3        2      3         0         0       75           3
4        2      0         0         0      120          3
4        2      1        101    100      0            1
4        2      2         0         0       115         3
4        2      3         0         0       116         3

**Comment by mattfidler** [comment]
Hi @fernandoortega 

In general the goal of nlmixr is to characterize the population and individual effects.  However many models are disease specific, so it is difficult to say without running a full analysis what the best PD model is for your dataset.

Nick Holford (@nholford) has an excellent example of this here:

http://holford.fmhs.auckland.ac.nz/research/nlmixr/

This is what the multiple endpoint model vignette is based on as well:

https://nlmixrdevelopment.github.io/nlmixr/articles/multiple-endpoints.html

I would also suggest looking at `xgxr` to explore your data.  An example is here:

https://nlmixrdevelopment.github.io/nlmixr/articles/xgxr-nlmixr-ggpmx.html
