### ISSUE TITLE
Estimate Bioavailability

### ISSUE THREAD

**Issue by KyleBarrett** [nlmixrdevelopment/nlmixr#59]
Hi nlmixr team,
As I understand it, nlmixr/RxODE is currently not able to estimate bioavailability or an eta associated with it. I was wondering if anyone had a work around for this yet or if it was still in the works.

**Comment by wwang-at-github** [comment]
Estimating bioavailability is a half-baked thing in nlmixr.  Rather than a general bioavailability, nlme_ode() supports "F1" as an optional parameter.  This functionality hasn't been included in the new Unified User Interface (UUI), yet.  Then there's the function gnlmm() using adaptive Gaussian quadrature.  gnlmm() takes an arbitrary use-defined log-likelihood, whatever parameters deemed necessary in your model.  Including bioavailability in saem is currently a bit trickier.

**Comment by KyleBarrett** [comment]
Hi Wenping,
We've currently been sticking to Saem over nlme due to its reliability. I completely understand why its difficult due to there being an saem and RxODE block within the model({}) section of the UUI that are solved differently, which is why I couldnt come up with a work around myself. Thanks so much for clarifying!

**Comment by mattfidler** [comment]
I have an idea you could try, though I haven't tested it myself.  It is a similiar trick to issue #55;  You would be estimating the parameters using indicators for effect:

```R

one.compartment.saem <- function() {
    ini({
        tka <- .5   # Log Ka
        tcl <- -3.2 # Log Cl
        tv <- -1    # Log V
        estF1 = 9
        eta.ka ~ 1
        eta.cl ~ 2
        eta.v ~ 1
        add.err <- 0.1
    })
    model({
        ka <- exp(tka + eta.ka)
        cl <- exp(tcl + eta.cl)
        v <- exp(tv + eta.v)
        d/dt(depot) = -ka * depot
        d/dt(center) = ka * depot - cl / v * center
        f1 = 1/(1+exp(-estF1))*covF1+covF2
        cp = center / v  * f1
        cp ~ add(add.err)
    })
}
````

`estF1` would be the logit estimate of F1 for a specific study/formulation/etc.

The `covF1` would be in the dataset with the `1` or `0` representing the study/formulation/etc that you are comparing. The `covF2` would be the second study/formulation/etc, the bioavailability term would be relative to that term.

**Comment by mattfidler** [comment]
If you wanted to add an eta you could do something similar, but you would probably want to move the ETA to make sure it can only be between 0 and 1 too.

**Comment by mattfidler** [comment]
Also we are still thinking about developing something more general too:

https://github.com/nlmixrdevelopment/RxODE/pull/25

**Comment by mattfidler** [comment]
Great!  Glad to hear it worked for you.

**Comment by KyleBarrett** [comment]
Didnt fully test this earlier, just that it could compile. Wanted to add this in case it was useful to anyone in the future...
In order for the estimation to properly work, I found that each covariate had to be added on a separate line.  I have implemented multiple fixed covariates on the same line per issue #55, so im not entirely sure why this is the case this time. Anyways, here are the fixes that worked flawlessly:

bioeval_nlmixr  <- function() {
  ini({
    #Initials Estimates
    lVc <- log(114) #log Vc (L)
    lVp <- log(211) #log Vp (L)
    lCl <- log(8.4) #log Cl (L/hr)
    lQ <- log(267) #log between CMT clearnace (L/hr)
    lKa <- log(0.540) #log Ka (1/hr)
    logitF1 <- 0.4 #2.19 # ~ bioavailability of 90% 
    #Error
    prop.err <- c(0,0.2,1) #0.12
    eta.Vc ~ 0.3 
    eta.Vp ~ 0.3
    eta.Cl ~ 0.3
    eta.Q  ~ 0.3
    eta.Ka ~ 0.2 # BSV Ka
    #eta.F1 ~ 0.1
    #eta.Vc + eta.Cl ~ c(0.3,0.005,0.3)
  })
  model({ 
    #Saem
    f1 <- 1/(1+exp(-(logitF1)));#*SC+IV  + eta.F1
    Vc <- exp(lVc + eta.Vc);
    Vp <- exp(lVp + eta.Vp);
    Cl <- exp(lCl + eta.Cl);
    Q <- exp(lQ + eta.Q);
    Ka <- exp(lKa + eta.Ka);
    #RxODE
    K23 <- Q / Vc;
    K32 <- Q / Vp;
    Kel <- Cl / Vc;
    F1 <- f1*SC; 
    F12 <- F1+IV;
    
    d/dt(depot)  = -Ka*depot; #CMT 1
    d/dt(centr)  =  Ka*depot - K23*centr + K32*periph - Kel*centr; #CMT 2
    d/dt(periph) =  K23*centr - K32*periph; #CMT 3
    
    cp = (centr/Vc)*F12;
    cp ~ prop(prop.err);
  })},

**Comment by mattfidler** [comment]
Thats a bit odd.  I will have to investigate.

**Comment by nholford** [comment]
@mattfidler  said: "If you wanted to add an eta you could do something similar, but you would probably want to move the ETA to make sure it can only be between 0 and 1 too."

I colleague who has managed to get nlmixr installed reports that adding an eta to an emax parameter which needs to be constrained between 0 and 1 causes a syntax error:

      ini({

     lgtemax <- 7.5 # estimate the logit of Emax

     eta.emax ~ .5

      })

      model({

     logit < - lgtemax + eta.emax # “mu” referencing style

     emax <- 1/(1 + exp(-logit)) # can only have a value between 0 and 1

     ...`

"Compiling RxODE differential equations...:13: syntax error after 'logit'".

So how exactly should this be done to have a logit distribution for a parameter like emax (or F)?

**Comment by mattfidler** [comment]
Hi @nholford,

In theory this should work.  If you can provide an example (if you cannot share it publically, you can email me at matthew.fidler@gmail.com) I will look into it.

A possibility is that nlmixr isn't parsing the model right.  A way to test this is to move the `emax` expression to right before the `ODE`s
```
  ini({

 lgtemax <- 7.5 # estimate the logit of Emax
 eta.emax ~ .5

  })

  model({
 logit < - lgtemax + eta.emax # “mu” referencing style
## All of the rest of theta/eta-referenced variables should be here

## Put this expression right before the ODEs
 emax <- 1/(1 + exp(-logit)) # can only have a value between 0 and 1
```

If this works then there is something I can do to make the model work more generally.

**Comment by KyleBarrett** [comment]
Hi @mattfidler,

Was this issue ever addressed? More specifically, does nlmixr still parse the model as two separate blocks - an saem portion and an RxODE portion? Or can we mix the two as long as the eta values are mu referenced?

**Comment by mattfidler** [comment]
This is still in the works.  Working through the sensitivity equations for parameter modified events.

**Comment by mattfidler** [comment]
Also havent worked through the mixed blocks, though it should be possible in some way.

**Comment by mattfidler** [comment]
You can now estimate bioavailibility by
```R
f(cmt) = parameter
```

**Comment by nholford** [comment]
Hi, is f(cmt) documented somewhere? Does it work with both SAEM and FOCEI? Are there any restrictions coding eta?

**Comment by mattfidler** [comment]
Hi @nholford ,

It isn't documented well yet;  It is discussed in passing on:

https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-events.html

Here they have an example of all the new model-based features available in RxODE/nlmixr:

```r
    f(depot) = fdepot
    dur(depot) = durDepot
    rate(depot) = rateDepot
```

Currently:
- All these new features work with all methods as long as these items do not have an `eta` assocated with the parameter.
- The `fo` family of estimation methods, including `focei` will not work with `etas`.  The math has been worked out, but the features haven't been added to RxODE right now.  I hope to add this in the next release.  This includes `FOCEi` objective functions and `CWRES` calculations.  
- The `SAEM` method does not require the gradients of these parameters so `eta`s on these parameters work just fine if you use `SAEM`. Although the `FOCEi` objective function cannot be added, you can get a likelihood calculation through adaptave Gaussian Quatardature for these models.  All you need to do is request AIC and the calculation will begin.

**Comment by mattfidler** [comment]
I just noticed it doesn't include the lag time that is also new.  

This has the same restrictions as above and is coded
```r
alag(depot) = lagDepot
```
