### ISSUE TITLE
Uniform interface for estimation methods

### ISSUE THREAD

**Issue by RikSchoemaker** [nlmixrdevelopment/nlmixr#6]
It would be a huge improvement if it were possible to provide a unified user interface for the different estimation algorithms. Naturally, as far as possible, because the different algorithms may build on different R packages: nlme for instance has its very well developed syntax that you would want to keep  being accessible, but some harmonisation should definitely be possible.

For instance: nlme requires parameters to be estimated in the log domain, a natural choice because it allows IIV to be implemented as additive on the log-scale corresponding to exponential-type IIV estimates. And while the SAEM module does basically the same, here parameter are specified on the original scale and are log-transformed internally.

nlme closed-form:
```
specs1<-list(fixed=lCL+lV~1, random = pdDiag(lCL+lV~1), start=c(lCL=1.6,lV=4.5))
fit <- nlme_lin_cmpt(dat, par_model=specs1, ncmt=1, verbose=TRUE,oral=FALSE,weight=varPower(fixed=c(1)))

```
nlme-ODE:
```
ode1 <- "
d/dt(centr)  = -(CL/V)*centr;
"
mypar1 <- function(lCL, lV )
{
    CL <- exp(lCL) 
    V <- exp(lV)
}
fitODE <- nlme_ode(dat, model=ode1, par_model=specs1, par_trans=mypar1, response="centr", response.scaler="V", verbose=TRUE,weight=varPower(fixed=c(1)))

```
SAEM closed-form:
```
saem_fit <- gen_saem_user_fn(model=lincmt(ncmt=1, oral=FALSE))
model = list(saem_mod=saem_fit, res.mod=2,covars="WT")
inits = list(theta=c(5,90),omega=c(0.1,0.1),bres=0.2)
cfg   = configsaem(model, nmdat, inits)
cfg$print = 50
fit = saem_fit(cfg)

```
SAEM ODE:
```
ode1 <- "
d/dt(centr)  = -(CL/V)*centr;
"
m1 = RxODE(ode1, modName="m1")
mypars1 <- function(lCL, lV )
{
    CL = exp(lCL) 
    V = exp(lV)
}
PRED = function() centr / V
dyn.unload("saem_main.dll")
saem_fit <- gen_saem_user_fn(model=m1, PKpars=mypars1, pred=PRED)

```

A suggestion would be:
-syntax to generate a compiled model with associated handle (e.g. m1)
-standard syntax to define parameter transformations
-standard syntax to provide inter-individual variability models
-standard syntax to describe residual variability models
-standard syntax to provide starting values
-standard syntax to start a model fit

Would it be an option to use exisiting nlme model definition as a starting point for this? It is well established syntax and it is probably easier to adapt new implementations to the exisiting standard than to try to adapt nlme syntax to newly developed conventions...

**Comment by mattfidler** [comment]
UI started and documented;  coming out soon `?nlmixr` in the new branch.
