### ISSUE TITLE
popPK Dose simulation and PK paramters calculation

### ISSUE THREAD

**Issue by AprilCCC** [nlmixrdevelopment/nlmixr#601]
Hi nlmixr team, 

Dose nlmixr can do popPK dose simulation from observed real data, and do the PK calculation based on the simulated results? A similar result shows below:
Figure 1 observed data compared with simulated data
Figure 2  PK parameters ratio between observed and simulated data
![image](https://user-images.githubusercontent.com/87253631/160863596-c3df177b-b533-4fa7-8af9-3ce887420f0f.png)
![image](https://user-images.githubusercontent.com/87253631/160863962-a3124c89-cd1b-4eb9-a4af-6c292995e145.png)

I've looked at all the samples from the nlmixr, but couldn't get any clue to do the simulation like this. Any idea would be appreciated!

**Comment by mattfidler** [comment]
Hi @AprilCCC 

Once the model has been fit, you can certainly directly simulate from it:

https://nlmixrdevelopment.github.io/nlmixr/articles/xgxr-nlmixr-ggpmx.html#simulation-of-a-new-scenario-with-rxode


Once the simulation is performed you can use any of the many NCA tools to get the noncompartmental values post and pre-simulation.

@billdenney  is working on a `PKNCA` and `nlmixr2` interaction and some function that performs this automatically may come in the future but isn't there now.

**Comment by AprilCCC** [comment]
Hi @mattfidler 
Thanks for the suggestion, that's very helpful.  
After the simulation was performed, as shown below, I tried to fit data into PKNCA, but the simulated data is lacking of the amount of dose for the PKNCAdose formula (formula=dose.amount~time|groups). 
Should I export the simulated data and then add the dose manually, or is there any other way to add the dose amount data for the simulated data set?  Also, How to export the simulated data set to csv. ?

<img width="260" alt="image" src="https://user-images.githubusercontent.com/87253631/161276213-8538e6c4-7737-4df4-977e-bf4d17ac1ca9.png">

**Comment by billdenney** [comment]
@AprilCCC , PKNCA doesn't require the dose, but you will likely want some ability to separate by treatment.  You can run `as.data.frame()` to get a data.frame from your simulation.  For PKNCA, it would likely be better to discuss how to use the data for NCA in a new issue over there: https://github.com/billdenney/pknca/issues

**Comment by mattfidler** [comment]
You can also add dosing information by `rxSolve(..., addDosing=TRUE)`

**Comment by mattfidler** [comment]
The documentation for this function is here: https://nlmixrdevelopment.github.io/RxODE/reference/rxSolve.html

**Comment by AprilCCC** [comment]
Hi @mattfidler and @billdenney , those are very helpful, thanks.
