### ISSUE TITLE
Error in example 3 of Modifying nlmixr models by piping

### ISSUE THREAD

**Issue by nskoch** [nlmixrdevelopment/nlmixr#606]
Hi,

I tried example 3 to fix Ka to the previously model estimated value (ie 1.61) and then re-estimate.
it appears that Ka is fixed to the initial value of the model not the estimated.
Did I forget something?

Best regards
Nicolas

**Comment by mattfidler** [comment]
Hi @nskoch 

I am unsure.  Could you provide your example data.  In the upcoming `nlmixr2` it tells you what it is doing so you are aware if you have made a mistake.

**Comment by nskoch** [comment]
Hi 
It's a web example 3 of nlmixr ([changing model via piping](https://nlmixrdevelopment.github.io/nlmixr/articles/modelPiping.html)):
## Example 3 -- Fix tka to model estimated value and re-estimate.
one.ka.0.5 <- fit %>%
    ini(tka=fix) %>%
    nlmixr(est="focei", control=list(print=0),
           table=list(cwres=TRUE, npde=TRUE))
print(one.ka.0.5)
Best regards
Nicolas

**Comment by mattfidler** [comment]
With `nlmixr2`, which is under submission it seems to be working fine:

https://nlmixr2.github.io/nlmixr2/articles/modelPiping.html

You can see that it is fixed to zero in the automatically run example.
