### ISSUE TITLE
confidence intervals for eta

### ISSUE THREAD

**Issue by miriamkhayam** [nlmixrdevelopment/nlmixr#612]
hi 
i'm a Master 2 student in pharmacokinetics and I'm currently working on nlmixr 2 for my internship and I have noticed that in the final results of an estimation PK or even PD with nlmixr and nlmixr 2 there's no eta confidence intervals . 

let me ask you if there is a way or a code to get the trust intervals of eta 

thank you in advance

**Comment by mattfidler** [comment]
Not yet.  It is a feature request I will probably add to nlmixr2.

**Comment by mattfidler** [comment]
It is currently in the development branch of `nlmixr2est` and will likely come out after the log likelihood estimation is complete.
