### ISSUE TITLE
SCM-When covariates are screened

### ISSUE THREAD

**Issue by junmoxiao66** [nlmixrdevelopment/nlmixr#648]
When covariates are filtered, the results of only two parameters appear in the results for three parameters, and the result name of the third parameter displays the name of the second parameter
<img width="376" alt="屏幕截图 2023-12-04 102200" src="https://github.com/nlmixrdevelopment/nlmixr/assets/140042718/c2b5c179-1675-4bbd-88b1-c23d4ce24518">
<img width="672" alt="屏幕截图 2023-12-04 102339" src="https://github.com/nlmixrdevelopment/nlmixr/assets/140042718/123515ad-c612-4ab7-a322-70221b60ba2a">

**Comment by mattfidler** [comment]
Hi @junmoxiao66 

I transfered this to `nlmixr2extra` since it seems you are using `nlmixr2` and the bug lives there.

If you could provide a rexpex so I don't have to type the code by hand it would be helpful.

**Comment by junmoxiao66** [comment]
@mattfidler How to solve the above problem？

**Comment by mattfidler** [comment]
Hi @junmoxiao66 

I haven't had time to debug this yet.  If you have time, feel free to submit a bug fix.

Best

Matt

**Comment by junmoxiao66** [comment]
@mattfidler Thank you very much. I may not be able to help

**Comment by mattfidler** [comment]
We may refactor soon, but it has not been done yet.
