### ISSUE TITLE
Error for `gen_saem_user_fn` on Unix

### ISSUE THREAD

**Issue by christineturner** [nlmixrdevelopment/nlmixr#66]
I have been having issues with using `gen_saem_user_fn` on a Unix server, yet could get it to work on a local Windows machine.  Upon looking into the code of this function I believe I have found the cause of the problem. 

The following code line ran on Windows as expected but raised an error when run on Unix:
 `saem_fit <- gen_saem_user_fn(model=lincmt(ncmt=1, oral=T))`

Raising the Unix error (where I have removed the exact file path):
`sh: R: command not found`
`Error in dyn.load(saem.dll) : `
  `unable to load shared object './saem5dc6774ee864.so':`
` ./saem5dc6774ee864.so: cannot open shared object file: No such file or directory`

Looking into the working directory revealed that the file created was a `.cpp` file and not the `.so` file expected, so I opened the function code to trace the problem. I found these two lines:
`shlib = sprintf("R CMD SHLIB %s -o %s", saem.cpp, saem.dll)` 
`system(shlib)`
These are Windows commands and do not work in Unix, yet there was no `if` statement checking the operating system at this point, hence the error. 

In addition, linking to issue #65 that I raised previously, the `plot.saemFit` function does not work in the same way on Unix and Windows, with it now working on Windows, but on Unix not plotting the same `fit` imported from Windows:
`#on Windows:`
`saem_fit <- gen_saem_user_fn(model=lincmt(ncmt=1, oral=T), trace = FALSE)`
`model <- list(saem_mod=saem_fit)`
`inits <- list(theta=c(.04, .7, 2))`
`cfg <- configsaem(model, theo_md, inits, seed = 50)`
` cfg$print <- 0`
` fit <- saem_fit(cfg) #export this fit to Unix for plotting`
`plot(fit) #plot in Unix`

Raising error (as before in #65):
`Error in .Primitive(".Call")(<pointer: (nil)>, a, b, c) : `
  `NULL value passed as symbol address`
Unfortunately I was not able to find the clear root of this problem in the function code, but I suspect it is linked to the above problem with not checking operating system. 

In light of these issues, could you please take a look at getting these functions running on Unix, or at least raising an appropriate error. 

My sessionInfo is:
`R version 3.4.3 (2017-11-30)`
`Platform: x86_64-redhat-linux-gnu (64-bit)`
`Running under: CentOS Linux 7 (Core)`
`Matrix products: default`
`locale:`
 `[1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       `
` [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   `
` [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              `
`[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C     `  
`attached base packages:`
`[1] stats     graphics  grDevices utils     datasets  methods   base   `  
`other attached packages:`
`[1] nlmixr_0.9.0-1        RxODE_0.6-1           nlme_3.1-131          validationTools_1.0.9`
`loaded via a namespace (and not attached):`
` [1] rex_1.1.2        Rcpp_0.12.15     knitr_1.19       magrittr_1.5     munsell_0.4.3    colorspace_1.3-2`
` [7] lattice_0.20-35  R6_2.2.2         brew_1.0-6       rlang_0.1.6      plyr_1.8.4       tools_3.4.3   `  
`[13] lbfgs_1.2.1      parallel_3.4.3   grid_3.4.3       gtable_0.2.0     png_0.1-7        digest_0.6.15  ` 
`[19] yaml_2.1.19      lazyeval_0.2.1   tibble_1.4.2     ggplot2_2.2.1    RUnit_0.4.31     testthat_2.0.0  `
`[25] memoise_1.1.0    compiler_3.4.3   pillar_1.1.0     scales_0.5.0     XML_3.98-1.9   `

Thank you!

**Comment by wwang-at-github** [comment]
could you create a soft link to your R executable, name it R, & put it to a
directory in your $PATH?

nlmixr calls "R" when doing compilation.

best,
wenping

**Comment by christineturner** [comment]
Yes that worked, thanks!
Christine

**Comment by mattfidler** [comment]
Great
