### ISSUE TITLE
how to programmatically get just the data frame used? And why is ID treated as factors?

### ISSUE THREAD

**Issue by JSC67** [nlmixrdevelopment/nlmixr#67]
I wrote some code that takes a population data set with ID as column 1 and bootstraps it.  I want to run nlmixr on each of the bootstrapped data sets, but it seems as if ID has been treated as a factor instead of a (character) vector.  The data I'm using (prior to bootstrapping) are just the theo_sd provided in nlmixr.  Some questions:

Q: How do I programmatically get just the data set used?  It seems to have name 'data.frame':
> str(trainfits[[1]])
nlmixr UI combined dataset and properties
'data.frame':	132 obs. of  22 variables:
 $ ID     : Factor w/ 7 levels "1","3","4","6",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ TIME   : num  0 0 0 0.25 0.25 0.25 0.57 0.57 0.57 1.12 ...
 ...

The tutorial at https://nlmixrdevelopment.github.io/nlmixr_bookdown/vignettes.html#rationale only says this:
"A table of fit data is also supplied. Please note:

    An nlmixr fit object is actually a data frame. Saving it as a Rdata object and then loading it without nlmixr will just show the data by itself. The additional fit information is still present, but nlmixr must be loaded in order to see it."
	
It does not say how to actually get the data set used.
 
Q: It seems to be a mistake to have $ID as factors.  I'd like the data frame to show the actual data used with $ID as a column with mode character just like in the original data.  Sorting the $ID values as factors isn't helpful.

Q: The above problem is NOT the case for the example seen at  https://nlmixrdevelopment.github.io/nlmixr_bookdown/vignettes.html#rationale .  What's the difference?

Q: typo - change $omgea to $omega; search for all instances of $omgea first.  This is seen at https://nlmixrdevelopment.github.io/nlmixr_bookdown/vignettes.html#rationale for one example.

**Comment by mattfidler** [comment]
> Q: How do I programmatically get just the data set used? It seems to have name 'data.frame':

Use 

```R
getData(fit)
```

>Q: It seems to be a mistake to have $ID as factors. I'd like the data frame to show the actual data used with $ID as a column with mode character just like in the original data. Sorting the $ID values as factors isn't helpful.

This is for the algorithm.  You can convert back to the original by `paste(fit$ID)`;  Or you can sort your data before it is used by nlmixr and it will retain this sorting.

> Q: The above problem is NOT the case for the example seen at

I don't know what you are talking about here.

**Comment by mattfidler** [comment]
@TeunP can you fix the bookdown?

**Comment by JSC67** [comment]
Hi Matt,

Thanks for your prompt reply!  I appreciate it.  I'll elaborate on what I see as confusing or undesirable.  Perhaps this should be a separate post.  In short, in https://nlmixrdevelopment.github.io/nlmixr_bookdown/vignettes.html#rationale under the section "nlmixr output objects" in the Fit Data portion of fit.s we see 3 rows for a modified data frame, and these rows are sorted first by ID then by TIME, and all looks well.  This is not always the case, as I show below.

Start with:

	fit.nlme.lin     <- nlmixr(uif.lin, theo_sd, est="nlme")

Now typing "fit.nlme.lin" shows this (plus other stuff):

	-- Fit Data (object fit.nlme.lin is a modified data.frame): --------------------
	# A tibble: 132 x 22
	  ID     TIME    DV  PRED    RES   WRES IPRED   IRES  IWRES CPRED  CRES  CWRES
	* <fct> <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl>  <dbl>
	1 1     0      0.74  0    0.74   1.07    0     0.74   1.07   0    0.74  1.07  
	2 1     0.25   2.84  2.82 0.0218 0.0130  3.86 -1.02  -1.47   2.65 0.185 0.0861
	3 1     0.570  6.57  5.05 1.52   0.684   6.78 -0.207 -0.299  4.82 1.75  0.637 
	# ... with 129 more rows, and 10 more variables: eta.cl <dbl>, eta.ka <dbl>,
	#   eta.v <dbl>, rx0 <dbl>, rx1 <dbl>, cl <dbl>, ka <dbl>, v <dbl>, rx1c <dbl>,
	#   Central <dbl>
	> 

Well and good; this is for the data file theo_sd only, and it starts with subject ID = 1 and in the same time order as the original data frame, theo_sd.  The tibble shows 3 rows and says that there are 129 more, so 132 total.  This is fewer than the 144 rows in theo_sd, but there are 12 subjects and 12 dosing records (one for each subject), so 144 - 12 = 132, which is the same number of rows in this tibble, which apparently omits the dosing records.  Also this:

	> str(getData(fit.nlme.lin))
	'data.frame':	144 obs. of  9 variables:
	 $ ID        : int  1 1 1 1 1 1 1 1 1 1 ...
	 $ TIME      : num  0 0 0.25 0.57 1.12 2.02 3.82 5.1 7.03 9.05 ...
	 $ DV        : num  0 0.74 2.84 6.57 10.5 9.66 8.58 8.36 7.47 6.89 ...
	 $ AMT       : num  4.02 0 0 0 0 0 0 0 0 0 ...
	 $ EVID      : int  101 0 0 0 0 0 0 0 0 0 ...
	 $ CMT       : int  1 2 2 2 2 2 2 2 2 2 ...
	 $ WT        : num  79.6 79.6 79.6 79.6 79.6 79.6 79.6 79.6 79.6 79.6 ...
	 $ nlmixr.grp: Factor w/ 1 level "Y02": 1 1 1 1 1 1 1 1 1 1 ...
	 $ nlmixr.num: int  1 2 3 4 5 6 7 8 9 10 ...
 
Again we see that everything is in the right order, the same as theo_sd and with 2 additional columns supplied by nlmixr.

Now bootstrap it with B = 1.  I have two functions I wrote to do this.  The first, funBS.IDs, returns a 2-column data frame with the bootstrap iteration b (1 <= b <= B where B is the total number of iterations).  The second takes as input the original data (theo_sd) and the output from funBS.IDs and returns the time courses (rows from theo_sd) for the selected IDs and in the same order as from funBS.IDs.  Here's an example:

	> ans1 <- funBS.IDs(theo_sd, 1)
	> ans1
	   BsIteration ID
	1            1  3
	2            1  8
	3            1  9
	4            1 10
	5            1  7
	6            1 10
	7            1  9
	8            1 10
	9            1  8
	10           1  2
	11           1  2
	12           1  5
	> ans2 <- funBSDS(theo_sd, ans1)
	> str(ans2)
	'data.frame':	144 obs. of  8 variables:
	 $ BsIteration: int  1 1 1 1 1 1 1 1 1 1 ...
	 $ ID         : int  3 3 3 3 3 3 3 3 3 3 ...
	 $ TIME       : num  0 0 0.27 0.58 1.02 2.02 3.62 5.08 7.07 9 ...
	 $ DV         : num  0 0 4.4 6.9 8.2 7.8 7.5 6.2 5.3 4.9 ...
	 $ AMT        : num  4.53 0 0 0 0 0 0 0 0 0 ...
	 $ EVID       : int  101 0 0 0 0 0 0 0 0 0 ...
	 $ CMT        : int  1 2 2 2 2 2 2 2 2 2 ...
	 $ WT         : num  70.5 70.5 70.5 70.5 70.5 70.5 70.5 70.5 70.5 70.5 ...
	> head(ans2, 27)
	   BsIteration ID  TIME   DV  AMT EVID CMT   WT
	1            1  3  0.00 0.00 4.53  101   1 70.5
	2            1  3  0.00 0.00 0.00    0   2 70.5
	3            1  3  0.27 4.40 0.00    0   2 70.5
	4            1  3  0.58 6.90 0.00    0   2 70.5
	5            1  3  1.02 8.20 0.00    0   2 70.5
	6            1  3  2.02 7.80 0.00    0   2 70.5
	7            1  3  3.62 7.50 0.00    0   2 70.5
	8            1  3  5.08 6.20 0.00    0   2 70.5
	9            1  3  7.07 5.30 0.00    0   2 70.5
	10           1  3  9.00 4.90 0.00    0   2 70.5
	11           1  3 12.15 3.70 0.00    0   2 70.5
	12           1  3 24.17 1.05 0.00    0   2 70.5
	13           1  8  0.00 0.00 4.53  101   1 70.5
	14           1  8  0.00 0.00 0.00    0   2 70.5
	15           1  8  0.25 3.05 0.00    0   2 70.5
	16           1  8  0.52 3.05 0.00    0   2 70.5
	17           1  8  0.98 7.31 0.00    0   2 70.5
	18           1  8  2.02 7.56 0.00    0   2 70.5
	19           1  8  3.53 6.59 0.00    0   2 70.5
	20           1  8  5.05 5.88 0.00    0   2 70.5
	21           1  8  7.15 4.73 0.00    0   2 70.5
	22           1  8  9.07 4.57 0.00    0   2 70.5
	23           1  8 12.10 3.00 0.00    0   2 70.5
	24           1  8 24.12 1.25 0.00    0   2 70.5
	25           1  9  0.00 0.00 3.10  101   1 86.4
	26           1  9  0.00 0.00 0.00    0   2 86.4
	27           1  9  0.30 7.37 0.00    0   2 86.4
	> 

As you can see, ans2 has the rows from theo_sd pertaining to the bootstrapped values from ans1, and in the same order.  (ID=2 was selected twice, and back to back.)  Now fit these data (uif.lin was as in tutorial):

	> fit1 <- nlmixr(uif.lin, ans2, est="nlme")
	> fit1
	-- nlmixr nlme fit by maximum likelihood (Solved; mu-ref & covs) ---------------
	FOCEi-based goodness of fit metrics:
		 OBJF      AIC      BIC Log-likelihood Condition Number
	 99.27192 113.2719 133.4515      -49.63596         19.43051

	nlme-based goodness of fit metrics:
		  AIC      BIC Log-likelihood
	 356.0019 376.1815      -171.0009

	-- Time (sec; fit1$time): ------------------------------------------------------
			nlme setup FOCEi Evaulate covariance table
	elapsed 6.52 48.55           0.11          0  0.09

	-- Parameters (fit1$par.fixed): ------------------------------------------------
							  Parameter Estimate    SE %RSE Back-transformed(95%CI) BSV(CV%) Shrink(SD)%
	logtcl  log typical value Cl (L/hr)    -2.74 0.137 5.02 0.0648 (0.0495, 0.0848)    35.7%     -4.30% 
	logtka  log typical value Ka (1/hr)    0.516 0.300 58.1      1.68 (0.931, 3.01)    88.7%     -5.07% 
	logtv      log typical value V  (L)   -0.314 0.143 45.7    0.730 (0.551, 0.968)    38.1%     -6.21% 
	add.err                     add.err    0.665                           0.665                  7.52% 

	  No correlations in between subject variability (BSV) matrix
	  Full BSV covariance (fit1$omega) or correlation (fit1$omega.R; diagonals=SDs)
	  Distribution stats (mean/skewness/kurtosis/p-value) available in fit1$shrink

	-- Fit Data (object fit1 is a modified data.frame): ----------------------------
	# A tibble: 132 x 22
	  ID     TIME    DV  PRED   RES   WRES IPRED  IRES IWRES CPRED  CRES  CWRES eta.cl eta.ka eta.v   rx0   rx1
	* <fct> <dbl> <dbl> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl>  <dbl> <dbl> <dbl> <dbl>
	1 2      0     0     0     0     0      0     0     0     0     0     0      0.313  0.147 0.187  4.4   0   
	2 2      0     0     0     0     0      0     0     0     0     0     0      0.313  0.147 0.187  8.8   0   
	3 2      0.27  1.72  4.33 -2.61 -0.837  4.02 -2.30 -3.45  4.33 -2.61 -0.923  0.313  0.147 0.187  5.21  3.54
	# ... with 129 more rows, and 5 more variables: cl <dbl>, ka <dbl>, v <dbl>, rx1c <dbl>, Central <dbl>


The Fit Data tibble begins with ID=2 rather than with ID=3, which was the first ID selected by the bootstrap procedure, as seen above in ans1.  Since there are 132 rows in this tibble (= 144 original - 12 dosing), I suppose ID=2 has *two* TIME=0 rows, which differ in rx0 column, because ID=2 was selected twice (back to back).  It's an aside, but what columns do rx0 and rx1 refer to?  Anyway, this tibble clearly treats ID as a factor, and we see as much when we do thus:

	> str(fit1$ID)
	 Factor w/ 7 levels "2","3","5","7",..: 1 1 1 1 1 1 1 1 1 1 ...
 
Here is ans1 again:

	> ans1
	   BsIteration ID
	1            1  3
	2            1  8
	3            1  9
	4            1 10
	5            1  7
	6            1 10
	7            1  9
	8            1 10
	9            1  8
	10           1  2
	11           1  2
	12           1  5

Notice that ID=1 was not selected in this bootstrap instance.  So why does ID=1 appear with getData()?  Apparently the data frame that getData() returns ignores the ID as used in input argument ans2 and renumbers them consecutively starting with 1.  This sure seems undesirable to me!  Wouldn't it be preferable to treat ID the same as in the original input?  Or at least to give it another column name so that the original input is easily seen?

	> getData(fit1)
		BsIteration ID  TIME    DV  AMT EVID CMT   WT nlmixr.grp nlmixr.num
	109           1  1  0.00  0.00 4.40  101   1 72.4        Y02          1
	110           1  1  0.00  0.00 0.00    0   2 72.4        Y02          2
	121           1  1  0.00  0.00 4.40  101   1 72.4        Y02          3
	122           1  1  0.00  0.00 0.00    0   2 72.4        Y02          4
	111           1  1  0.27  1.72 0.00    0   2 72.4        Y02          5
	123           1  1  0.27  1.72 0.00    0   2 72.4        Y02          6
	112           1  1  0.52  7.91 0.00    0   2 72.4        Y02          7
	124           1  1  0.52  7.91 0.00    0   2 72.4        Y02          8
	113           1  1  1.00  8.31 0.00    0   2 72.4        Y02          9
	125           1  1  1.00  8.31 0.00    0   2 72.4        Y02         10
	114           1  1  1.92  8.33 0.00    0   2 72.4        Y02         11
	126           1  1  1.92  8.33 0.00    0   2 72.4        Y02         12
	115           1  1  3.50  6.85 0.00    0   2 72.4        Y02         13
	127           1  1  3.50  6.85 0.00    0   2 72.4        Y02         14
	116           1  1  5.02  6.08 0.00    0   2 72.4        Y02         15
	128           1  1  5.02  6.08 0.00    0   2 72.4        Y02         16
	117           1  1  7.03  5.40 0.00    0   2 72.4        Y02         17
	129           1  1  7.03  5.40 0.00    0   2 72.4        Y02         18
	118           1  1  9.00  4.55 0.00    0   2 72.4        Y02         19
	130           1  1  9.00  4.55 0.00    0   2 72.4        Y02         20
	119           1  1 12.00  3.01 0.00    0   2 72.4        Y02         21
	131           1  1 12.00  3.01 0.00    0   2 72.4        Y02         22
	120           1  1 24.30  0.90 0.00    0   2 72.4        Y02         23
	132           1  1 24.30  0.90 0.00    0   2 72.4        Y02         24
	1             1  2  0.00  0.00 4.53  101   1 70.5        Y02         25
	2             1  2  0.00  0.00 0.00    0   2 70.5        Y02         26
	3             1  2  0.27  4.40 0.00    0   2 70.5        Y02         27
	4             1  2  0.58  6.90 0.00    0   2 70.5        Y02         28
	5             1  2  1.02  8.20 0.00    0   2 70.5        Y02         29
	6             1  2  2.02  7.80 0.00    0   2 70.5        Y02         30
	7             1  2  3.62  7.50 0.00    0   2 70.5        Y02         31
	8             1  2  5.08  6.20 0.00    0   2 70.5        Y02         32
	9             1  2  7.07  5.30 0.00    0   2 70.5        Y02         33
	10            1  2  9.00  4.90 0.00    0   2 70.5        Y02         34
	11            1  2 12.15  3.70 0.00    0   2 70.5        Y02         35
	12            1  2 24.17  1.05 0.00    0   2 70.5        Y02         36
	133           1  3  0.00  0.00 5.86  101   1 54.6        Y02         37
	134           1  3  0.00  0.00 0.00    0   2 54.6        Y02         38
	135           1  3  0.30  2.02 0.00    0   2 54.6        Y02         39
	136           1  3  0.52  5.63 0.00    0   2 54.6        Y02         40
	137           1  3  1.00 11.40 0.00    0   2 54.6        Y02         41
	138           1  3  2.02  9.33 0.00    0   2 54.6        Y02         42
	139           1  3  3.50  8.74 0.00    0   2 54.6        Y02         43
	140           1  3  5.02  7.56 0.00    0   2 54.6        Y02         44
	141           1  3  7.02  7.09 0.00    0   2 54.6        Y02         45
	142           1  3  9.10  5.90 0.00    0   2 54.6        Y02         46
	143           1  3 12.00  4.37 0.00    0   2 54.6        Y02         47
	144           1  3 24.35  1.57 0.00    0   2 54.6        Y02         48
	49            1  4  0.00  0.00 4.95  101   1 64.6        Y02         49
	50            1  4  0.00  0.15 0.00    0   2 64.6        Y02         50
	51            1  4  0.25  0.85 0.00    0   2 64.6        Y02         51
	52            1  4  0.50  2.35 0.00    0   2 64.6        Y02         52
	53            1  4  1.02  5.02 0.00    0   2 64.6        Y02         53
	54            1  4  2.02  6.58 0.00    0   2 64.6        Y02         54
	55            1  4  3.48  7.09 0.00    0   2 64.6        Y02         55
	56            1  4  5.00  6.66 0.00    0   2 64.6        Y02         56
	57            1  4  6.98  5.25 0.00    0   2 64.6        Y02         57
	58            1  4  9.00  4.39 0.00    0   2 64.6        Y02         58
	59            1  4 12.05  3.53 0.00    0   2 64.6        Y02         59
	60            1  4 24.22  1.15 0.00    0   2 64.6        Y02         60
	13            1  5  0.00  0.00 4.53  101   1 70.5        Y02         61
	14            1  5  0.00  0.00 0.00    0   2 70.5        Y02         62
	97            1  5  0.00  0.00 4.53  101   1 70.5        Y02         63
	98            1  5  0.00  0.00 0.00    0   2 70.5        Y02         64
	15            1  5  0.25  3.05 0.00    0   2 70.5        Y02         65
	99            1  5  0.25  3.05 0.00    0   2 70.5        Y02         66
	16            1  5  0.52  3.05 0.00    0   2 70.5        Y02         67
	100           1  5  0.52  3.05 0.00    0   2 70.5        Y02         68
	17            1  5  0.98  7.31 0.00    0   2 70.5        Y02         69
	101           1  5  0.98  7.31 0.00    0   2 70.5        Y02         70
	18            1  5  2.02  7.56 0.00    0   2 70.5        Y02         71
	102           1  5  2.02  7.56 0.00    0   2 70.5        Y02         72
	19            1  5  3.53  6.59 0.00    0   2 70.5        Y02         73
	103           1  5  3.53  6.59 0.00    0   2 70.5        Y02         74
	20            1  5  5.05  5.88 0.00    0   2 70.5        Y02         75
	104           1  5  5.05  5.88 0.00    0   2 70.5        Y02         76
	21            1  5  7.15  4.73 0.00    0   2 70.5        Y02         77
	105           1  5  7.15  4.73 0.00    0   2 70.5        Y02         78
	22            1  5  9.07  4.57 0.00    0   2 70.5        Y02         79
	106           1  5  9.07  4.57 0.00    0   2 70.5        Y02         80
	23            1  5 12.10  3.00 0.00    0   2 70.5        Y02         81
	107           1  5 12.10  3.00 0.00    0   2 70.5        Y02         82
	24            1  5 24.12  1.25 0.00    0   2 70.5        Y02         83
	108           1  5 24.12  1.25 0.00    0   2 70.5        Y02         84
	25            1  6  0.00  0.00 3.10  101   1 86.4        Y02         85
	26            1  6  0.00  0.00 0.00    0   2 86.4        Y02         86
	73            1  6  0.00  0.00 3.10  101   1 86.4        Y02         87
	74            1  6  0.00  0.00 0.00    0   2 86.4        Y02         88
	27            1  6  0.30  7.37 0.00    0   2 86.4        Y02         89
	75            1  6  0.30  7.37 0.00    0   2 86.4        Y02         90
	28            1  6  0.63  9.03 0.00    0   2 86.4        Y02         91
	76            1  6  0.63  9.03 0.00    0   2 86.4        Y02         92
	29            1  6  1.05  7.14 0.00    0   2 86.4        Y02         93
	77            1  6  1.05  7.14 0.00    0   2 86.4        Y02         94
	30            1  6  2.02  6.33 0.00    0   2 86.4        Y02         95
	78            1  6  2.02  6.33 0.00    0   2 86.4        Y02         96
	31            1  6  3.53  5.66 0.00    0   2 86.4        Y02         97
	79            1  6  3.53  5.66 0.00    0   2 86.4        Y02         98
	32            1  6  5.02  5.67 0.00    0   2 86.4        Y02         99
	80            1  6  5.02  5.67 0.00    0   2 86.4        Y02        100
	 [ reached getOption("max.print") -- omitted 44 rows ]
	> 
 
Fortunately it prints the original row numbers as row names in left most column, so we can see e.g. that the first 2 rows pertain to ans2's ID=2:

	> ans2[109:110,]
		BsIteration ID TIME DV AMT EVID CMT   WT
	109           1  2    0  0 4.4  101   1 72.4
	110           1  2    0  0 0.0    0   2 72.4

The next 2 rows also pertain to ans2's ID=2 which was selected twice:

	> ans2[121:122,]
		BsIteration ID TIME DV AMT EVID CMT   WT
	121           1  2    0  0 4.4  101   1 72.4
	122           1  2    0  0 0.0    0   2 72.4

Apparently ID=1 in getData(fit1) (i.e., getData(fit1)$ID==1) pertains to input ans2's ID=2 which in turn pertains to theo_sd's ID=2.  It is assigned ID=1 because 2 was the lowest factor level selected by the bootstrap, then re-numbered, and it's sorted by renumbered ID and then by time.

Now if we bootstrap it twice, i.e. B = 2, things just get more complicated, but I think that the above is the nub of it.

This was very confusing to me, but I think I figured it out; please correct me if I'm wrong.

James

**Comment by mattfidler** [comment]
I think for bootstrapping you should probably assign a new id each time.  I do understand your frustration.  I will see about changing it back to whatever form it was in before.

SAEM core requires sequentially ordered IDs.  The factor solution allows missing IDs to be assigned sequential IDs to allow SAEM to run without any issues.

Using the nlmixr(...) function fixes this, but doesn't revert the ID back to numeric/Character/factor after it s done.

**Comment by TeunP** [comment]
Fixed - one instance

Q: typo - change $omgea to $omega; search for all instances of $omgea
first. This is seen at
https://nlmixrdevelopment.github.io/nlmixr_bookdown/vignettes.html#rationale
for
one example.
