### ISSUE TITLE
norm error models not working as descibed, also want exp error models

### ISSUE THREAD

**Issue by JSC67** [nlmixrdevelopment/nlmixr#68]
At https://nlmixrdevelopment.github.io/nlmixr_bookdown/vignettes.html#rationale under the section "Model syntax for ODE-based models" under the error syntax description is this sentence:

"You can also specify norm(parameter) for the additive error, since it follows a normal distribution."

So I changed the error distribution to 

	linCmt() ~ norm(add.err)

and ran the (renamed) model.  Here's all the output that appeared to my screen, both stout and sterr; notice the error at the end:

	> fit.nlme.lin     <- nlmixr(cf1cmt.normerr, theo_sd, est="nlme")

	**Iteration 1
	LME step: Loglik: -182.2318, nlminb iterations: 1
	reStruct  parameters:
		  ID1       ID2       ID3 
	1.0022617 0.2783009 2.0758984 
	 Beginning PNLS step: ..  completed fit_nlme() step.
	PNLS step: RSS =  63.1492 
	 fixed effects: -3.211935  0.447998  -0.7859319  
	 iterations: 7 
	Convergence crit. (must all become <= tolerance = 1e-05):
		fixed  reStruct 
	0.2723749 3.2673493 

	**Iteration 2
	LME step: Loglik: -179.291, nlminb iterations: 9
	reStruct  parameters:
		   ID1        ID2        ID3 
	0.96385384 0.08333465 1.63552496 
	 Beginning PNLS step: ..  completed fit_nlme() step.
	PNLS step: RSS =  63.28224 
	 fixed effects: -3.211529  0.4441499  -0.7863391  
	 iterations: 7 
	Convergence crit. (must all become <= tolerance = 1e-05):
		  fixed    reStruct 
	0.008664056 0.172140362 

	**Iteration 3
	LME step: Loglik: -179.337, nlminb iterations: 8
	reStruct  parameters:
		   ID1        ID2        ID3 
	0.96127446 0.07085101 1.63887826 
	 Beginning PNLS step: ..  completed fit_nlme() step.
	PNLS step: RSS =  63.21956 
	 fixed effects: -3.211695  0.445849  -0.7861748  
	 iterations: 7 
	Convergence crit. (must all become <= tolerance = 1e-05):
		  fixed    reStruct 
	0.003810953 0.083041222 

	**Iteration 4
	LME step: Loglik: -179.3201, nlminb iterations: 7
	reStruct  parameters:
		   ID1        ID2        ID3 
	0.96243389 0.07619035 1.63736920 
	 Beginning PNLS step: ..  completed fit_nlme() step.
	PNLS step: RSS =  63.24586 
	 fixed effects: -3.211622  0.4451181  -0.7862475  
	 iterations: 7 
	Convergence crit. (must all become <= tolerance = 1e-05):
		  fixed    reStruct 
	0.001642014 0.034519536 

	**Iteration 5
	LME step: Loglik: -179.328, nlminb iterations: 6
	reStruct  parameters:
		   ID1        ID2        ID3 
	0.96192227 0.07381955 1.63801887 
	 Beginning PNLS step: ..  completed fit_nlme() step.
	PNLS step: RSS =  63.23423 
	 fixed effects: -3.211654  0.4454379  -0.7862161  
	 iterations: 7 
	Convergence crit. (must all become <= tolerance = 1e-05):
		   fixed     reStruct 
	0.0007179909 0.0153297789 

	**Iteration 6
	LME step: Loglik: -179.3247, nlminb iterations: 5
	reStruct  parameters:
		   ID1        ID2        ID3 
	0.96215590 0.07486979 1.63772980 
	 Beginning PNLS step: ..  completed fit_nlme() step.
	PNLS step: RSS =  63.24087 
	 fixed effects: -3.211654  0.4454379  -0.7862161  
	 iterations: 1 
	Convergence crit. (must all become <= tolerance = 1e-05):
		  fixed    reStruct 
	0.000000000 0.008689733 

	**Iteration 7
	LME step: Loglik: -179.3247, nlminb iterations: 1
	reStruct  parameters:
		   ID1        ID2        ID3 
	0.96214642 0.07485047 1.63773353 
	 Beginning PNLS step: ..  completed fit_nlme() step.
	PNLS step: RSS =  63.24087 
	 fixed effects: -3.211654  0.4454379  -0.7862161  
	 iterations: 1 
	Convergence crit. (must all become <= tolerance = 1e-05):
		   fixed     reStruct 
	0.000000e+00 1.297069e-11 
	## Calculate ETA-based prediction and error derivatives:
	Calculate Jacobian...................done.
	Calculate sensitivities.......
	done.
	## Calculate d(f)/d(eta) 
	## ...
	## done
	Error in norm(add.err) : 
	  RxODE doesn't know how to translate 'norm' to SymPy.
	In addition: Warning message:
	In nlmixrUI.nlme.var(obj) :
	 
	 Show Traceback
	 
	 Rerun with Debug
	 Error in norm(add.err) : 
	  RxODE doesn't know how to translate 'norm' to SymPy. 
	> 

I would love to have exponential errors working too, but exp(norm(err)) didn't even parse right.  This at least got part way before failing, but it doesn't behave as the documentation suggests it should.

**Comment by mattfidler** [comment]
Hi @JSC67 

The `norm` should work.  I will look into it.  I am currently working on a different branch of RxODE and nlmixr that supports something like what you want in `FOCEi` and possibly in `SAEM`, though I'm less sure about `nlme`

However, we are following the R standard for naming distributions, so it will be:

```R
linCmt() ~ lnorm(add.err)
```
Becuase `dlnorm` is a lognormal distribution in R, or as you stated "exponential" errors.  Possibly I will allow `exp(norm())` to work, not sure.

**Comment by JSC67** [comment]
For what it's worth, my 2 cents would be to allow exp(norm()).

**Comment by mattfidler** [comment]
`lnorm` works.
