### ISSUE TITLE
Cannot install RxODE because R 3.51. is not compatible with Rtools 3.4 (or 3.5) 

### ISSUE THREAD

**Issue by nholford** [nlmixrdevelopment/nlmixr#70]
Cannot install RxODE because Microsoft R 3.51. is not compatible with Rtools 3.4 (or 3.5). 
Similar results with Cran R.3.5.0 and R.3.5.1. 
OS is Windows 10 Pro.
See Console output below from Microsoft R 3.5.1.
Any suggestions?

#2018-08-20
#Installed Microsoft Open R 3.5.1 into C:\R\Microsoft\R-3.5.1
#Open with C:\R\Microsoft\R-3.5.1\bin\x64\Rgui.exe

#Rtools 3.4 in Windows path C:\Apps\R\Rtools_3.4

install.packages("devtools") 
#mran.microsoft.com/snapshot/2018-08-01/bin/windows/contrib/3.5/devtools_1.13.6.zip'

library(devtools)
# Try with Rtools 3.4
install_github("nlmixrdevelopment/RxODE")
#Downloading GitHub repo nlmixrdevelopment/RxODE@master
#from URL https://api.github.com/repos/nlmixrdevelopment/RxODE/zipball/master
#WARNING: Rtools 3.4 found on the path at C:/Apps/R/Rtools_3.4/Rtools is not compatible with R 3.5.1.

#Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/, remove the incompatible version from your PATH.
#Installation failed: Could not find build tools necessary to build RxODE
 

# Closed Rgui, changed Windows path then try with Rtools 3.5
#Rtools 3.5 in Windows path C:\Apps\R\Rtools_3.5
install_github("nlmixrdevelopment/RxODE")
#Downloading GitHub repo nlmixrdevelopment/RxODE@master
#from URL https://api.github.com/repos/nlmixrdevelopment/RxODE/zipball/master
#WARNING: Rtools 3.5 found on the path at C:/Apps/R/Rtools_3.5/Rtools is not compatible with R 3.5.1.

#Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/, remove the incompatible version from your PATH.
#Installation failed: Could not find build tools necessary to build RxODE

**Comment by mattfidler** [comment]
This is odd.  It seems to be a devtools issue.  Rtools should be compatible with R 3.5.1

**Comment by mattfidler** [comment]
If you have access, use the standard path of `C:\Rtools`.  Perhaps all of the paths were not added appropriately?

**Comment by nholford** [comment]
Thanks for this suggestion. I copied Rtools version 3.4 to C:\Rtools, changed the Windows path and then was able to install RxODE.

**Comment by mattfidler** [comment]
Great!  Glad to hear it!
