### ISSUE TITLE
xpose.nlmixr installation fails because of vpc namespace issue

### ISSUE THREAD

**Issue by nholford** [nlmixrdevelopment/nlmixr#72]
See R console output below  after a clean restart of R-3.5.1 when trying to install xpose.nlmixr.
How do I get the correct namespace?

> library(devtools)
> devtools::install_github("nlmixrdevelopment/xpose.nlmixr")
Downloading GitHub repo nlmixrdevelopment/xpose.nlmixr@master
from URL https://api.github.com/repos/nlmixrdevelopment/xpose.nlmixr/zipball/master
Installing xpose.nlmixr
"C:/R/Microsoft/R-3.5.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/nholf/AppData/Local/Temp/RtmpsVIGfM/devtools104c49432070/nlmixrdevelopment-xpose.nlmixr-de216da"  \
  --library="C:/R/Microsoft/R-3.5.1/library" --install-tests 

* installing *source* package 'xpose.nlmixr' ...
** R
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'vpc' 1.0.1 is being loaded, but >= 1.0.2 is required
ERROR: lazy loading failed for package 'xpose.nlmixr'
* removing 'C:/R/Microsoft/R-3.5.1/library/xpose.nlmixr'
In R CMD INSTALL
Installation failed: Command failed (1)
>

**Comment by nholford** [comment]
Thanks Matt,
That fixed the xpose.nlmixr problem.
Now where do I get the collapsibleTree?

> devtools::install_github("richardhooijmaijers/shinyMixR")
Downloading GitHub repo richardhooijmaijers/shinyMixR@master
from URL https://api.github.com/repos/richardhooijmaijers/shinyMixR/zipball/master
Installing shinyMixR
"C:/R/Microsoft/R-3.5.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/nholf/AppData/Local/Temp/Rtmp8WwyWM/devtools2ab464fd3568/RichardHooijmaijers-shinyMixR-d1bd1f6"  \
  --library="C:/R/Microsoft/R-3.5.1/library" --install-tests 

ERROR: dependency 'collapsibleTree' is not available for package 'shinyMixR'
* removing 'C:/R/Microsoft/R-3.5.1/library/shinyMixR'
In R CMD INSTALL
Installation failed: Command failed (1)
>

**Comment by mattfidler** [comment]
Thanks @TeunP;  I was unaware the CRAN version was removed.

```R
devtools::install_github("AdeelK93/collapsibleTree")
````
should do the trick.

**Comment by nholford** [comment]
Thanks @TeunP -- that is what I needed to complete the puzzle. Now I have finally managed to get nlmixr installed after 2 days of struggling.

**Comment by mattfidler** [comment]
Thanks Nick for trying to get the system setup.

Note that collapsibleTree is on CRAN again

https://cran.r-project.org/web/packages/collapsibleTree/index.html

That should simplify install for shinyMixR
