### ISSUE TITLE
Installing nlmixr Windows 10

### ISSUE THREAD

**Issue by abuhelwa** [nlmixrdevelopment/nlmixr#78]
I am using 64-bits windows operating system and R v 3.5. 
I followed the steps described [here](https://github.com/nlmixrdevelopment/nlmixr). 
I installed [Anaconda 3.6](https://www.anaconda.com/download/) (although when you select to download the 3.6 version, the 5.2 version is actually downloaded) . When I ran `RxODE::rxWinPythonSetup()` I had the following message:

`Requirement already satisfied: sympy in c:\users\abuhela\appdata\local\contin~1\anacon~1\lib\site-p~1 (1.1.1) distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

I installed `mrgpack` by running the command ` pip install msgpack` and upgraded the pip by running the command `python -m pip install --upgrade pip`. 

I ran `RxODE::rxWinPythonSetup()`  in RStudio again which is supposed to install `SnakeCharmR` somehow? but it didn't. Here what I have got:

`RxODE::rxWinPythonSetup()`
`Attempting to install SymPy. This may take a few seconds...`
`Requirement already satisfied: sympy in c:\users\abuhela\appdata\local\contin~1\anacon~1\lib\site-p~1 (1.1.1)`
`Please restart your R session before using RxODE.`

I restarted but it didn't load the package.
`library(SnakeCharmR)`
`Error in library(SnakeCharmR) : there is no package called ‘SnakeCharmR’`

I had no issues installing `RxODE` but haven't got to the stage of installing `nlmixr` package itself. Need to sort this out first.

Any idea of what is going wrong here? Thanks!

**Comment by abuhelwa** [comment]
Did some further investigation. The `SnakeCharmR` should be installed separately using the command.

`library(devtools)`
`install_github("asieira/SnakeCharmR")`

May be adding this to installation instructions would be helpful.
All working fine now.

**Comment by tamas-ferenci** [comment]
I can confirm this one. Having a look at the source code of `RxODE::rxWinPythonSetup()`, it seems to me that it doesn't even try to install `SnakeCharmR`...

**Comment by mattfidler** [comment]
That is true.  Currently trying to transition to something other than `SnakeCharmR`, since it was orphaned 
https://cran.r-project.org/web/packages/SnakeCharmR/index.html

**Comment by tamas-ferenci** [comment]
I'd wholeheartedly welcome this, as - in contrast abuhelwa - I couldn't even install `SnakeCharmR` under Windows...
So thank you in advance for these efforts; do you have any idea on when this transition will be completed?

**Comment by mattfidler** [comment]
@tamas-ferenci 

That can be frustrating.  You can always use the windows installers;  These include:
- R
  - nlmixr
  - tidyverse
  - shinyMixR
  - xpose.nlmixr
- python
  - sympy

These will always be available in the releases:

https://github.com/nlmixrdevelopment/nlmixr/releases

We plan to release some more bug fixes and enhancments very soon in preparation for the ACoP conference.

Another option for windows users is to use nlmixr's fork of SnakeCharmR:

```R
devtools::install_github("nlmixrdevelopment/SnakeCharmR")
```
which has worked on windows for me for awhile.

**Comment by mattfidler** [comment]
In theory nlmixr also works with reticulate.

**Comment by tamas-ferenci** [comment]
@mattfidler Thank you very much! The `devtools::install_github("nlmixrdevelopment/SnakeCharmR")` solution didn't work for me (produced the same error as the original `SnakeCharmR`), however, `install.packages("reticulate")` and `library(reticulate)` indeed solved the problem! After this, `RxODE::rxSymPyVersion()` run (although it took some time), and I could install `nlmixr`. Thanks again!

**Comment by mattfidler** [comment]
I'm glad it worked.  Just closed the issue.
