### ISSUE TITLE
Cannot compile RxODE with nlmixr 1.0.0-5 with Microsoft Open R3.5.1 - undefined reference to `zgees_'

### ISSUE THREAD

**Issue by nholford** [nlmixrdevelopment/nlmixr#79]
I have successfully  installed RxODE with Microsoft Open R3.5.1 and nlmixr 1.0.0-2.
However, I cannot compile RxODE with nlmixr 1.0.0-5 with Microsoft Open R3.5.1 because I get an undefined reference to `zgees_' error.

I am using this command:
 devtools::install_github("nlmixrdevelopment/RxODE") 

A colleague has successfully installed RxODE with nlmixr 1.0.0-5 with Microsoft Open R3.5.1 so this is not an easily predictable problem.

The 'zgees_' variable is part of Lapack so the problem is finding it in the Lapack library.
Does anyone have any suggestions?

**Comment by mattfidler** [comment]
Hi Nick,

I'm unsure.  However, some things that may interefer with this could be:
- Nonstandard installation of Rtools (perhaps to some other directory)
- Custom `.R/Makevars` (which should be under your home directory)

**Comment by nholford** [comment]
Hi Matt,
Rtools 3.5 is installed in C:\Rtools (the only installation directory that works for me).
I have instances of Makevars associated with several R versions. None are in the root of the R directory. 
e.g. for Microsoft Open version installed for nlmixr 1.0.0.-5
C:\R\Microsoft\R-3.5.1_1.0.0-5\library\RcppArmadillo\skeleton\Makevars

```
## With R 3.1.0 or later, you can uncomment the following line to tell R to 
## enable compilation with C++11 (where available)
##
## Also, OpenMP support in Armadillo prefers C++11 support. However, for wider
## availability of the package we do not yet enforce this here.  It is however
## recommended for client packages to set it.
##
## And with R 3.4.0, and RcppArmadillo 0.7.960.*, we turn C++11 on as OpenMP
## support within Armadillo prefers / requires it
CXX_STD = CXX11

PKG_CXXFLAGS = $(SHLIB_OPENMP_CXXFLAGS) 
PKG_LIBS = $(SHLIB_OPENMP_CFLAGS) $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)

```
I cannot get RxODE to compile with Microsoft Open R3.5.1. with nlmixr 1.0.0-5  so I cannot check what R uses when it runs.

For comparison with Microsoft Open version installed for nlmixr 1.0.0.-3 (which installed RxODE without any problem)

C:\R\Microsoft\R-3.5.1_1.0.0-3\library\RcppEigen\skeleton\Makervars

```
## With Rcpp 0.11.0 and later, we no longer need to set PKG_LIBS as there is
## no user-facing library. The include path to headers is already set by R.
#PKG_LIBS = 

## With R 3.1.0 or later, you can uncomment the following line to tell R to 
## enable compilation with C++11 (or even C++14) where available
#CXX_STD = CXX11

```
The compilation under Microsoft Open R3.5.1. with nlmixr 1.0.0-3 looks like this

```
Compiling RxODE differential equations...C:/Rtools/mingw_64/bin/gcc -m64 -I"C:/R/MICROS~1/R-351_~1.0-3/include" -DNDEBUG     -I"C:/swarm/workspace/External-R-3.5.1/vendor/extsoft/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c rx_7c904389e4fe211e6edc382c1268cef5_x64.c -o rx_7c904389e4fe211e6edc382c1268cef5_x64.o
C:/Rtools/mingw_64/bin/gcc -m64 -shared -s -static-libgcc -o rx_7c904389e4fe211e6edc382c1268cef5_x64.dll tmp.def rx_7c904389e4fe211e6edc382c1268cef5_x64.o -LC:/R/MICROS~1/R-351_~1.0-3/bin/x64 -lRblas -LC:/R/MICROS~1/R-351_~1.0-3/bin/x64 -lRlapack -lgfortran -lm -lquadmath -LC:/swarm/workspace/External-R-3.5.1/vendor/extsoft/lib/x64 -LC:/swarm/workspace/External-R-3.5.1/vendor/extsoft/lib -LC:/R/MICROS~1/R-351_~1.0-3/bin/x64 -lR
done.
PKG_CXXFLAGS=-IC:/R/MICROS~1/R-351_~1.0-3/library/nlmixr/include -IC:/R/MICROS~1/R-351_~1.0-3/library/STANHE~1/include -IC:/R/MICROS~1/R-351_~1.0-3/library/Rcpp/include -IC:/R/MICROS~1/R-351_~1.0-3/library/RCPPAR~1/include -IC:/R/MICROS~1/R-351_~1.0-3/library/RCPPEI~1/include -IC:/R/MICROS~1/R-351_~1.0-3/library/BH/include
PKG_LIBS= $(BLAS_LIBS) $(LAPACK_LIBS)
C:/Rtools/mingw_64/bin/g++ -m64 -I"C:/R/MICROS~1/R-351_~1.0-3/include" -DNDEBUG     -I"C:/swarm/workspace/External-R-3.5.1/vendor/extsoft/include"  -IC:/R/MICROS~1/R-351_~1.0-3/library/nlmixr/include -IC:/R/MICROS~1/R-351_~1.0-3/library/STANHE~1/include -IC:/R/MICROS~1/R-351_~1.0-3/library/Rcpp/include -IC:/R/MICROS~1/R-351_~1.0-3/library/RCPPAR~1/include -IC:/R/MICROS~1/R-351_~1.0-3/library/RCPPEI~1/include -IC:/R/MICROS~1/R-351_~1.0-3/library/BH/include   -O2 -Wall  -mtune=core2 -c saem27dc12697136x64.cpp -o saem27dc12697136x64.o
C:/Rtools/mingw_64/bin/g++ -m64 -shared -s -static-libgcc -o saem27dc12697136x64.dll tmp.def saem27dc12697136x64.o -LC:/R/MICROS~1/R-351_~1.0-3/bin/x64 -lRblas -LC:/R/MICROS~1/R-351_~1.0-3/bin/x64 -lRlapack -LC:/swarm/workspace/External-R-3.5.1/vendor/extsoft/lib/x64 -LC:/swarm/workspace/External-R-3.5.1/vendor/extsoft/lib -LC:/R/MICROS~1/R-351_~1.0-3/bin/x64 -lR
done.
```

I have no idea why Makevars appears in different places with different versions of nlmixr. I use the same script to install the various packages in R and the installation of Rtools and Anaconda is the same for all versions of R and nlmixr.

**Comment by wwang-at-github** [comment]
might be related to this post:
https://github.com/RevolutionAnalytics/RRO/issues/88

**Comment by mattfidler** [comment]
For now I'm going to close this.
