### ISSUE TITLE
Error: function 'n1qn1F' not provided by package 'n1qn1'

### ISSUE THREAD

**Issue by tamas-ferenci** [nlmixrdevelopment/nlmixr#80]
When I try to run the second example in the vignette (`fit <- nlmixr(one.compartment.saem, theo_sd, est="saem")`), everything seems to run fine until the end, when I receive the following error:

     done
       Standardized prediction/ebe models produced.
     Error in RxODE::foceiFitCpp_(.ret) : 
       function 'n1qn1F' not provided by package 'n1qn1'
     Error in RxODE::foceiFitCpp_(.ret) : 
       function 'n1qn1F' not provided by package 'n1qn1'
     Warning message:
     In as.focei.saemFit(.fit, uif, pt, data = dat, calcResid = calc.resid,  :
       Error calculating nlmixr object, return classic object

I can't figure out what's the reason of this error...

**Comment by mattfidler** [comment]
It because you don't have the development version of n1qn1;  To fix that, you need to do the following:

```R
devtools::install_github("nlmixrdevelopment/n1qn1")
```

I plan to submit the updates to CRAN for `n1qn1` soon.

**Comment by tamas-ferenci** [comment]
@mattfidler Thank you very much, it indeed solved the problem!
