### ISSUE TITLE
Make the installation more user friendly

### ISSUE THREAD

**Issue by guiastrennec** [nlmixrdevelopment/nlmixr#86]
I came across the [installr](https://github.com/talgalili/installr/) package, it seems that you might be able to generate an `install.nlmixr()` function handling all software requirements for windows users.

**Comment by mattfidler** [comment]
Thank you for the suggestion @guiastrennec.

I will have to see if this will work for the installer.  

For windows, we do have a 32 bit and 64 bit windows installer that installs all the components, python, rtools and sympy.  These are located in:

https://github.com/nlmixrdevelopment/nlmixr/releases

Your solution may allow using whatever local R that you have as well as generation of the installers.

**Comment by mattfidler** [comment]
I looked breifly at the package.  This installs programs by downloading them and running the installers. To me, I think there could be some problems without noting some pitfalls in installation.  

For example, many people think it strange that Rtools installs to `C:\Rtools` and install elsewhere;  This often causes problems in devtools and other packages. Unless the environment is setup carefully it will break both nlmixr and RxODE.

Therefore, it may work for building the installers, though I'm unsure if it would be good to use in general without some initial documentation about the process.  

What do you think?

**Comment by mattfidler** [comment]
On the other hand, the install.nlmixr could grab the latest installer, I suppose, and install that...

**Comment by mattfidler** [comment]
RxODE now does this.  All the tricky dependencies are there and if setup for RxODE work for nlmixr.
