### ISSUE TITLE
error message: With multiple endpoints, all residual error predictions must be specified with the | syntax.

### ISSUE THREAD

**Issue by motyocska** [nlmixrdevelopment/nlmixr#88]
Hello,

getting this error message with 3 outputs when checking model : With multiple endpoints, all residual error predictions must be specified with the | syntax.". I have tried some configs but no success. In my model I have as follows:

    add.err1 <- 0.1
    add.err2 <- 0.1
    add.err3 <- 0.1

then later

    cp = x1 / VD 
    ccsf = x4/V3
    ctech = x7/V6
    
    cp ~ add(add.err1)
    ccsf ~ add(add.err2)
    ctech ~ add(add.err3)

could you please clarify what the | syntax specification means?

thank you,

Andras

**Comment by motyocska** [comment]
Matt,

sure, all makes sense this way and the model compiles... Very nice package, looking forward to explore it further... couple of questions came up as I did run this rather complex model with a simulated data set, here is the code for the sim data and saem run:

set.seed(42);
library(RxODE)

mod <- RxODE({
  VD=tVD*exp(eta.VD);
  V3=tV3*exp(eta.V3);
  CL=tCL*exp(eta.CL);
  K12=tK12*exp(eta.K12);
  K21=tK21*exp(eta.K21);
  K13=tK13*exp(eta.K13);
  K31=tK31*exp(eta.K31);
  K14=tK14*exp(eta.K14);
  K41=tK41*exp(eta.K41);
  K15=tK15*exp(eta.K15);
  K51=tK51*exp(eta.K51);
  K16=tK16*exp(eta.K16);
  K61=tK61*exp(eta.K61);
  KRELECFF=tKRELECFF*exp(eta.KRELECFF);
  KREL=tKREL*exp(eta.KREL);
  KRELB=tKRELB*exp(eta.KRELB);
  KSHUNT=tKSHUNT*exp(eta.KSHUNT);
  V6=tV6*exp(eta.V6);

  d/dt(x1) = -((CL/VD)+K12+K13+K14+K15+K16)*x1+K21*x2+K31*x3+K41*x4+K51*x5+K61*x6+KREL*x7;
  d/dt(x2) = K12*x1-K21*x2;
  d/dt(x3) = K13*x1-K31*x2+KRELB*x4-KRELECFF*x3;
  d/dt(x4) = K14 *x1 - K41 *x4 - KRELB * x4+KRELECFF*x3- KREL * x4+KRELB*x5- KSHUNT *x4;
  d/dt(x5) = K15 *x1 - K51 *x5 + KRELB*x6-KRELB *x5+ KREL * x4- KREL * x5;
  d/dt(x6) = K16 * x1 - K61 * x6 + KRELB*x7-KRELB * x6+ KREL *x5- KREL*x6;
  d/dt(x7) = -KREL *x7+ KREL * x6- KRELB*x7;
  cp = x1 / VD; 
  ccsf = x4/V3;
  ctech = x7/V6;
  
})

theta <- c(tVD=12, tV3=0.025, tCL=4,  # central 
           tK12=0.2, tK21=0.3,                # peripheral
           tK13=0.000006, tK31=0.000007,
           tK14=0.000006, tK41=0.000007,
           tK15=0.000006, tK51=0.000007,
           tK16=0.000006, tK61=0.000007,
           tKRELECFF=0.04,tKREL=0.1,tKRELB=0.01,tKSHUNT=0.03,tV6=0.02) 

omega <- cov(matrix(c(rnorm(5000,0,0.3),
                      rnorm(5000,0,0.3),
                      rnorm(5000,0,0.3),
                      rnorm(5000,0,0.3),
                      rnorm(5000,0,0.3),
                      rnorm(5000,0,0.3),
                      rnorm(5000,0,0.3),
                      rnorm(5000,0,0.3),
                      rnorm(5000,0,0.3),
                      rnorm(5000,0,0.3),
                      rnorm(5000,0,0.3),
                      rnorm(5000,0,0.3),
                      rnorm(5000,0,0.3),
                      rnorm(5000,0,0.3),
                      rnorm(5000,0,0.3),
                      rnorm(5000,0,0.3),
                      rnorm(5000,0,0.3),
                      rnorm(5000,0,0.3)
),ncol=18))

colnames(omega)<-c("eta.VD","eta.V3","eta.CL","eta.K12","eta.K21","eta.K13","eta.K31","eta.K14",
                                                                 "eta.K41","eta.K15","eta.K51","eta.K16",
                                                                 "eta.K61","eta.KRELECFF","eta.KREL","eta.KRELB",
                                                                 "eta.KSHUNT","eta.V6")


ev <- eventTable(amount.units="mg", time.units="hours") %>%
  add.dosing(dose=100, nbr.doses=4, dosing.to=1,dosing.interval=12) %>%
  add.dosing(dose=4, nbr.doses=2, dosing.to=4,dosing.interval=24) %>%
  add.dosing(dose=5, nbr.doses=1, dosing.to=7,start.time=9) %>%
    add.sampling(seq(6,48,length.out=4));

sim  <- rxSolve(mod,theta,ev,omega=omega,nSub=10)

for (i in unique(sim$sim.id)){
  
DV<-cbind(DV=c(subset(sim,sim$sim.id==i)$ccsf,subset(sim,sim$sim.id==i)$cp,
               subset(sim,sim$sim.id==i)$ctech),TIME=rep(subset(sim,sim$sim.id==i)$time,3),
          ID=rep(subset(sim,sim$sim.id==i)$sim.id,3),
          MDV=0,AMT=0,RATE=0,CMT=c(rep(4,4),rep(1,4),rep(7,4)),EVID=0)


DOSEANDRATE<-cbind(DV=NA,TIME=c(seq(0,36,12),c(0,24),9),
                   ID=subset(sim,sim$sim.id==i)$sim.id[1],
                   MDV=1,AMT=c(rep(100,4),c(4,4),5),RATE=0,CMT=c(rep(1,4),rep(4,2),rep(7,1)),EVID=1)

data<-data.frame(rbind(DV,DOSEANDRATE))
data<-data[order(data$TIME),]
datause<-if(i==1) data else rbind(datause,data)
}

########################then the saem fit:
library(nlmixr)
library(rSymPy)
library(ggplot2)

data<-datause
one.compartment.saem <- function() {
  ini({
    tVD<-c(log(12))
    tV3<-log(0.025)
    tCL<-log(4)
    tK12<-log(0.2)
    tK21<-log(0.3)
    tK13<-log(0.000006)
    tK31<-log(0.000007)
    tK14<-log(0.000006)
    tK41<-log(0.000007)
    tK15<-log(0.000006)
    tK51<-log(0.000007)
    tK16<-log(0.000006)
    tK61<-log(0.000007)
    tKRELECFF<-log(0.04)
    tKREL<-log(0.1)
    tKRELB<-log(0.01)
    tKSHUNT<-log(0.03)
    tV6<-log(0.02)

    eta.VD~1
    eta.V3~1
    eta.CL~1
    eta.K12~1
    eta.K21~1
    eta.K13~1
    eta.K31~1
    eta.K14~1
    eta.K41~1
    eta.K15~1
    eta.K51~1
    eta.K16~1
    eta.K61~1
    eta.KRELECFF~1
    eta.KREL~1
    eta.KRELB~1
    eta.KSHUNT~1
    eta.V6~1

    add.err1 <- 1
    add.err2 <- 1
    add.err3 <- 1

  })
  model({
    
    VD<-exp(tVD + eta.VD)
    V3<-exp(tV3 + eta.V3)
    CL<-exp(tCL + eta.CL)
    K12<-exp(tK12 + eta.K12)
    K21<-exp(tK21 + eta.K21)
    K13<-exp(tK13 + eta.K13)
    K31<-exp(tK31 + eta.K31)
    K14<-exp(tK14 + eta.K14)
    K41<-exp(tK41 + eta.K41)
    K15<-exp(tK15 + eta.K15)
    K51<-exp(tK51+ eta.K51)
    K16<-exp(tK16 + eta.K16)
    K61<-exp(tK61 + eta.K61)
    KRELECFF<-exp(tKRELECFF + eta.KRELECFF)
    KREL<-exp(tKREL + eta.KREL)
    KRELB<-exp(tKRELB + eta.KRELB)
    KSHUNT<-exp(tKSHUNT + eta.KSHUNT)
    V6<-exp(tV6 + eta.V6)
    
    d/dt(x1) = -((CL/VD)+K12+K13+K14+K15+K16)*x1+K21*x2+K31*x3+K41*x4+K51*x5+K61*x6+KREL*x7
    d/dt(x2) = K12*x1-K21*x2
    d/dt(x3) = K13*x1-K31*x2+KRELB*x4-KRELECFF*x3
    d/dt(x4) = K14 *x1 - K41 *x4 - KRELB * x4+KRELECFF*x3- KREL * x4+KRELB*x5- KSHUNT *x4
    d/dt(x5) = K15 *x1 - K51 *x5 + KRELB*x6-KRELB *x5+ KREL * x4- KREL * x5
    d/dt(x6) = K16 * x1 - K61 * x6 + KRELB*x7-KRELB * x6+ KREL *x5- KREL*x6
    d/dt(x7) = -KREL *x7+ KREL * x6- KRELB*x7
    
    cp = x1 / VD 
    ccsf = x4/V3
   ctech = x7/V6
    
    cp ~ add(add.err1)|x1
    ccsf~ add(add.err2)|x4
    ctech ~add(add.err3)|x7

  })
}

nlmixr(one.compartment.saem)



fit <- nlmixr(one.compartment.saem, data=data,est="saem")


once I run this the program will terminate with the following error message (simpler models and examples like the theophilline will run as expected):

################################################################################
## Condition: (CMT==1)
################################################################################
Load into sympy...Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.lang.NoSuchMethodException: No suitable method for the given parameters
Warning message:
In as.focei.saemFit(.fit, uif, pt, data = dat, calcResid = calc.resid,  :
  Covariance matrix non-positive definite, corrected by sqrtm(fim %*% fim)

would you have some thoughts on why this may be happening? 

as I have been working with exploring the package have a couple of ore general questions:

1. am I seeing correctly that for saem the parameters hmax, and maxstepsODE can not be changed from within the nlmixr() command using saemControl? Do you have plans for adding this functionality? 

2. would you have plans for adding parameter boundaries to nlme and saem runs?

3. once I try to run the above exact same model with nlme as est instead of saem  I get the following error and this goes smooth with saem (ie no problems), would you have thought son it:

Error in rxSolve.default(object = get("rxDll", envir = <environment>),  : 
  The following parameter(s) are required for solving: CMT

much appreciate all the input...

Andras

**Comment by mattfidler** [comment]
> would you have some thoughts on why this may be happening?

You are using `rSymPy`;  This uses an old version of sympy.  I suggest using python and sympy with at least sympy 1.2

> am I seeing correctly that for saem the parameters hmax, and maxstepsODE can not be changed from within the nlmixr() command using saemControl? Do you have plans for adding this functionality?

I'm unsure, but I believe we eventually we plan to add this functionality.

> would you have plans for adding parameter boundaries to nlme and saem runs?

No.  Not currently.  Doubtful for SAEM. Definately not for `nlme`

> once I try to run the above exact same model with nlme as est instead of saem I get the following error and this goes smooth with saem (ie no problems), would you have thought son it:

I haven't added multiple endpoints to `nlme`.  I need to add an error for this problem.

**Comment by motyocska** [comment]
Matt,
thank you, running nicely now...

Andras

**Comment by mattfidler** [comment]
I'm glad it worked for you Andras. 

If you encounter anything else, please submit a github issue.
