### ISSUE TITLE
Stan now utilizes the C++14 standard

### ISSUE THREAD

**Issue by bgoodri** [nlmixrdevelopment/nlmixr#90]
StanHeaders and rstan 2.18.x are on CRAN now and Stan now utilizes as much of the C++14 standard as is implemented in RTools. It may or may not be necessary to update nlmixr immediately (its error on Solaris is due to a Boost bug that is worked around in StanHeaders 2.18.0-1 which is currently stuck in incoming/inspect on CRAN) but when you next upload nlmixr you should probably change the line in Makevars to `CXX_STD = C++14` and put LinkingTo: StanHeaders (>= 2.18.0) in the DESCRIPTION.

**Comment by mattfidler** [comment]
Thanks @bgoodri.  Added a fix, as you suggested.

I guess without these fixes some of nlmixr's stan-based functions will break.

**Comment by mattfidler** [comment]
@bgoodri, the `CXX_STD = C++14` interferred with boost.  What was the solaris issue you described?  Do you have a pointer to the location of the issue?

**Comment by mattfidler** [comment]
(That is with `CXX_STD=C++14` the boost libraries nlmixr uses do not compile)

**Comment by bgoodri** [comment]
On Solaris, nothing that does #include
<boost/math/quadrature/detail/*_detail.hpp> will work on Solaris due to

https://github.com/boostorg/math/issues/134

which has been fixed but not released yet, nor bundled into BH. I uploaded
a StanHeaders_2.18.0-1 that worked around this issue on October 9 and CRAN
has still not pushed it out.

In the likely even that you do not need Boost's numerical quadrature
routines for nlmixr, you may be able to get around this yourself by only
referencing the precise Stan headers that you need rather than for example
#include <stan/math.hpp> which pulls in everything in Stan.

**Comment by mattfidler** [comment]
Thanks @bgoodri !

**Comment by bgoodri** [comment]
nlmixr needs to use C++14 (or choose its includes more precisely) in order for me to upload the next version of StanHeaders to CRAN. The boost thing was fixed in BH long ago but now `R CMD check nlmixr_*.tar.gz` has an installation error with the new StanHeaders:

> /opt/r-devel/library/StanHeaders/include/stan/math/rev/mat/functor/adj_jac_apply.hpp:31:54: note: deduced return type only available with -std=c++14 or -std=gnu++14
/opt/r-devel/library/StanHeaders/include/stan/math/rev/mat/functor/adj_jac_apply.hpp:48:48: error: ‘apply’ function uses ‘auto’ type specifier without trailing return type
 constexpr auto apply(const F& f, const Tuple& t) {
                                                ^

**Comment by mattfidler** [comment]
I was just looking at this issue. 

Since we are using c14 does that mean you have to do more to install in windows

**Comment by bgoodri** [comment]
No. Some packages have a src/Makevars.win but that is usually simpler than src/Makevars. You can test nlmixr on winbuilder to make sure it works with the new StanHeaders.

**Comment by mattfidler** [comment]
@bgoodri 

The C++14 works for my windows machine locally but has broken travis.  Do you know of the options to build an appropriate c++ compiler?

**Comment by mattfidler** [comment]
Nevermind I figured it out.

**Comment by bgoodri** [comment]
Are we good here? If so, I think nothing else is stopping a StanHeaders release.

**Comment by mattfidler** [comment]
We are submitting nlmixr to cran with the new StanHeaders.  I'm not sure
what they require in CRAN.

**Comment by bgoodri** [comment]
It should be fine. What you have will work with either the StanHeaders
2.18.1 on CRAN or later versions.

**Comment by mattfidler** [comment]
We are now on CRAN with C++14;  I'm sure I will get more questions about setup, but  I think I can close this issue now.
