### ISSUE TITLE
Error: package ‘nlmixr’ is not installed for 'arch = i386'

### ISSUE THREAD

**Issue by nholford** [nlmixrdevelopment/nlmixr#94]
I downloaded nlmixr_1.0.0-7_i386_install.exe from here:
[https://github.com/nlmixrdevelopment/nlmixr/releases]
and installed it on a Windows 2012 64 bit server machine in the default location.
I get this error message when trying to open the library:

> library(nlmixr)
Error: package ‘nlmixr’ is not installed for 'arch = i386'

Is this because this installer works only on 32 bit machines?
Is it possible to release a 64 bit version of the installer?

**Comment by mattfidler** [comment]
I will release a 64 bit version of the installer.

**Comment by mattfidler** [comment]
It has been released.
