### ISSUE TITLE
Is it possible to run nlmixr without random effects?

### ISSUE THREAD

**Issue by tamas-ferenci** [nlmixrdevelopment/nlmixr#95]
Such as with the following model:
```R
    ExponentialModelPop <- function() {
      ini({
        tx10 <- 0   # Log x0
        ta <- 0     # Log a
        add.err <- 1
      })
      model({
        a <- exp( ta )
        x10 <- exp( tx10 )
        x1(0) = x10
        d/dt(x1) = a*x1
        Volume = x1
        Volume ~ add(add.err)
      })
    }
```

(With `est="saem"`, `nlmixr` returns the error `SAEM requires all ETAS to be mu-referenced`.)

I understand that `dynmodel` would be the natural choice here, however, I have multiple subject with different dosings, so I can't use that (if my understanding is correct!). I nevertheless want to fit one, "global" model.

**Comment by mattfidler** [comment]
The UI or model dosen't yet support `dynmodel`;  `dynmodel` does have support for different doses but does not reset the system for a new individual.  That seems to be what you want, correct?

Right now that cannot be accomplished. Eventually you may be able to accomplish this in `fo` by adding a single `ETA` fixed to zero, or expanding dynmodel to support system reset for individuals.

**Comment by mattfidler** [comment]
Now `fo` supports fixed `etas`.

A hack that can fit single subject data is to add a eta that is fixed to zero.  An example of this is below:

``` r
library(nlmixr)
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang
one.cmt <- function() {
    ini({
        tka <- 0.45 # Log Ka
        tcl <- 1 # Log Cl
        tv <- 3.45    # Log V
        eta.ka ~ fix(0)
        add.err <- 0.7
    })
    model({
        ka <- exp(tka + eta.ka)
        cl <- exp(tcl)
        v <- exp(tv)
        linCmt() ~ add(add.err)
    })
}
single <- nlmixr(one.cmt, theo_sd,"fo",list(print=0))
#> Using sympy via SnakeCharmR
#> Calculate ETA-based prediction and error derivatives:
#> Calculate Jacobian
#> [====|====|====|====|====|====|====|====|====|====
#> Calculate Sensitivities
#> [====|====|====|====|====|====|==
#> Load into sympy...
#> done
#> Calculate d(f)/d(eta)
#> [====|====|====|====|====|====|====|====|====|====
#> Freeing Python/SymPy memory...
#> done
#> ################################################################################
#> Optimizing expressions in Predictions/EBE model...done
#> Compiling Predictions/EBE model...done
#> Optimizing expressions in Inner model...done
#> Compiling Inner model...done
#> The model-based sensitivities have been calculated.
#> Calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====done
#> Calculate ETA-based prediction and error derivatives:
#> Calculate Jacobian
#> [====|====|====|====|====|====|====|====|====|====
#> Calculate Sensitivities
#> [====|====|====|====|====|====|==
#> Load into sympy...done
#> Calculate d(f)/d(eta)
#> [====|====|====|====|====|====|====|====|====|====
#> Freeing Python/SymPy memory...done
#> ################################################################################
#> Optimizing expressions in Predictions/EBE model...done
#> Compiling Predictions/EBE model...done
#> Optimizing expressions in Inner model...done
#> Compiling Inner model...done
#> The model-based sensitivities have been calculated.
#> Error in .fitFun(.ret) : 
#>   Infinite/NaN while evaluating initial objective function
#> Warning in (function (uif, data, est = NULL, control = list(), ...,
#> sum.prod = FALSE, : Gradient problems with initial estimate and covariance;
#> see $scaleInfo
print(single)
#> -- nlmixr FO (outer: nlminb) fit ------------------------------------------ 
#>        OBJF      AIC      BIC Log-likelihood Condition Number
#> FO 216.1509 466.7506 478.2818      -229.3753         30.87109
#> 
#> -- Time (sec; $time): ----------------------------------------------------- 
#>          setup optimize covariance  other
#> elapsed 61.933    0.119      0.119 60.189
#> 
#> -- Population Parameters ($parFixed or $parFixedDf): ----------------------
#> Registered S3 method overwritten by 'R.oo':
#>   method        from       
#>   throw.default R.methodsS3
#>         Parameter  Est.     SE %RSE Back-transformed(95%CI) BSV(CV%)
#> tka        Log Ka  0.44  0.161 36.7       1.55 (1.13, 2.13)   fix(0)
#> tcl        Log Cl 0.962 0.0811 8.43       2.62 (2.23, 3.07)         
#> tv          Log V  3.49 0.0452  1.3       32.9 (30.1, 35.9)         
#> add.err            1.38                                1.38         
#>         Shrink(SD)%
#> tka                
#> tcl                
#> tv                 
#> add.err             
#> 
#>   Covariance Type ($covMethod): r,s
#>   No correlations in between subject variability (BSV) matrix
#>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs) 
#>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink 
#>   Minimization message ($message):  
#>     relative convergence (4)
```

<sup>Created on 2019-05-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by nsk64** [comment]
Hello,
Did you plan to implement fixed value for eta and err with focei?
i.e. a fixed add.err compoment in an prop + add error model 
Thanks
Nicolas

**Comment by mattfidler** [comment]
Hi @nsk64 

This is already present in the cran version:

``` r
one.compartment <- function() {
    ini({
        tka <- 0.45 # Log Ka
        tcl <- 1 # Log Cl
        tv <- 3.45    # Log V
        eta.ka ~ 0.6
        eta.cl ~ 0.3
        eta.v ~ fix(0.02)
        add.sd <- fix(0.7)
    })
    model({
        ka <- exp(tka + eta.ka)
        cl <- exp(tcl + eta.cl)
        v <- exp(tv + eta.v)
        d/dt(depot) = -ka * depot
        d/dt(center) = ka * depot - cl / v * center
        cp = center / v
        cp ~ add(add.sd)
    })
}
library(nlmixr)

## Using FOCEi

fit <- nlmixr(one.compartment, theo_sd, est="focei",
              control=list(print=0))
#> Calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00 
#> done
#> Calculating residuals/tables
#> done.
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =
#> FALSE, : Initial ETAs were nudged; (Can control by foceiControl(etaNudge=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod
#> = FALSE, : ETAs were reset to zero during optimization; (Can control by
#> foceiControl(resetEtaP=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =
#> FALSE, : Gradient problems with initial estimate and covariance; see $scaleInfo

print(fit)
#> ── nlmixr FOCEi (outer: nlminb) fit ──────────────────────────────────────────── 
#>           OBJF     AIC     BIC Log-likelihood Condition Number
#> FOCEi 117.3212 369.921 384.335      -179.9605         72.96997
#> 
#> ── Time (sec; $time): ────────────────────────────────────────────────────────── 
#>            setup optimize covariance table    other
#> elapsed 0.698461 0.298432   0.298433   0.1 0.429674
#> 
#> ── Population Parameters ($parFixed or $parFixedDf): ─────────────────────────── 
#>        Parameter  Est.     SE  %RSE Back-transformed(95%CI)  BSV(CV%)
#> tka       Log Ka 0.459    0.2  43.7       1.58 (1.07, 2.34)      86.1
#> tcl       Log Cl  1.02 0.0757  7.43       2.77 (2.39, 3.21)      27.8
#> tv         Log V  3.45 0.0436  1.26         31.6 (29, 34.4) fix(14.2)
#> add.sd             0.7  FIXED FIXED                     0.7          
#>        Shrink(SD)%
#> tka         13.8% 
#> tcl         6.78% 
#> tv          12.1% 
#> add.sd             
#> 
#>   Covariance Type ($covMethod): r,s
#>   Some strong fixed parameter correlations exist ($cor) :
#>     cor:tcl,tka  cor:tv,tka  cor:tv,tcl 
#>          0.158       0.420       0.748   
#> 
#>   No correlations in between subject variability (BSV) matrix
#>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs) 
#>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink 
#>   Minimization message ($message):  
#>     false convergence (8) 
#>   In an ODE system, false convergence may mean "useless" evaluations were performed.
#>   See https://tinyurl.com/yyrrwkce
#>   It could also mean the convergence is poor, check results before accepting fit
#>   You may also try a good derivative free optimization:
#>     nlmixr(...,control=list(outerOpt="bobyqa"))
#> 
#> ── Fit Data (object is a modified tibble): ───────────────────────────────────── 
#> # A tibble: 132 x 22
#>   ID     TIME    DV  EVID  PRED    RES   WRES IPRED   IRES  IWRES CPRED   CRES
#>   <fct> <dbl> <dbl> <int> <dbl>  <dbl>  <dbl> <dbl>  <dbl>  <dbl> <dbl>  <dbl>
#> 1 1     0      0.74     0  0     0.74   0.389  0     0.74   1.06   0     0.74 
#> 2 1     0.25   2.84     0  3.27 -0.429 -0.225  3.85 -1.01  -1.44   3.23 -0.386
#> 3 1     0.570  6.57     0  5.85  0.724  0.381  6.79 -0.218 -0.311  5.79  0.776
#> # … with 129 more rows, and 10 more variables: CWRES <dbl>, eta.ka <dbl>,
#> #   eta.cl <dbl>, eta.v <dbl>, ka <dbl>, cl <dbl>, v <dbl>, cp <dbl>,
#> #   depot <dbl>, center <dbl>
```

<sup>Created on 2019-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by nsk64** [comment]
Hi Matthew,

Many thanks for your response and your huge work.

Best regards
Nicolas


De : Matthew Fidler [mailto:notifications@github.com]
Envoyé : mercredi 11 décembre 2019 15:29
À : nlmixrdevelopment/nlmixr <nlmixr@noreply.github.com>
Cc : SIMON Nicolas <Nicolas.SIMON@ap-hm.fr>; Mention <mention@noreply.github.com>
Objet : Re: [nlmixrdevelopment/nlmixr] Is it possible to run nlmixr without random effects? (#95)


Hi @nsk64<https://urldefense.com/v3/__https:/github.com/nsk64__;!!JQ5agg!PrHD0xaDWPG4MlB9WMuPHBMEnUUS3KMCE2k0sUKRGLpPa4gPnyNukArJNASLioNEcKUd$>

This is already present in the cran version:

one.compartment <- function() {

    ini({

        tka <- 0.45 # Log Ka

        tcl <- 1 # Log Cl

        tv <- 3.45    # Log V

        eta.ka ~ 0.6

        eta.cl ~ 0.3

        eta.v ~ fix(0.02)

        add.sd <- fix(0.7)

    })

    model({

        ka <- exp(tka + eta.ka)

        cl <- exp(tcl + eta.cl)

        v <- exp(tv + eta.v)

        d/dt(depot) = -ka * depot

        d/dt(center) = ka * depot - cl / v * center

        cp = center / v

        cp ~ add(add.sd)

    })

}

library(nlmixr)



## Using FOCEi



fit <- nlmixr(one.compartment, theo_sd, est="focei",

              control=list(print=0))

#> Calculating covariance matrix

#> [====|====|====|====|====|====|====|====|====|====] 0:00:00

#> done

#> Calculating residuals/tables

#> done.

#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =

#> FALSE, : Initial ETAs were nudged; (Can control by foceiControl(etaNudge=.))

#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod

#> = FALSE, : ETAs were reset to zero during optimization; (Can control by

#> foceiControl(resetEtaP=.))

#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =

#> FALSE, : Gradient problems with initial estimate and covariance; see $scaleInfo



print(fit)

#> ── nlmixr FOCEi (outer: nlminb) fit ────────────────────────────────────────────

#>           OBJF     AIC     BIC Log-likelihood Condition Number

#> FOCEi 117.3212 369.921 384.335      -179.9605         72.96997

#>

#> ── Time (sec; $time): ──────────────────────────────────────────────────────────

#>            setup optimize covariance table    other

#> elapsed 0.698461 0.298432   0.298433   0.1 0.429674

#>

#> ── Population Parameters ($parFixed or $parFixedDf): ───────────────────────────

#>        Parameter  Est.     SE  %RSE Back-transformed(95%CI)  BSV(CV%)

#> tka       Log Ka 0.459    0.2  43.7       1.58 (1.07, 2.34)      86.1

#> tcl       Log Cl  1.02 0.0757  7.43       2.77 (2.39, 3.21)      27.8

#> tv         Log V  3.45 0.0436  1.26         31.6 (29, 34.4) fix(14.2)

#> add.sd             0.7  FIXED FIXED                     0.7

#>        Shrink(SD)%

#> tka         13.8%

#> tcl         6.78%

#> tv          12.1%

#> add.sd

#>

#>   Covariance Type ($covMethod): r,s

#>   Some strong fixed parameter correlations exist ($cor) :

#>     cor:tcl,tka  cor:tv,tka  cor:tv,tcl

#>          0.158       0.420       0.748

#>

#>   No correlations in between subject variability (BSV) matrix

#>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs)

#>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink

#>   Minimization message ($message):

#>     false convergence (8)

#>   In an ODE system, false convergence may mean "useless" evaluations were performed.

#>   See https://tinyurl.com/yyrrwkce<https://urldefense.com/v3/__https:/tinyurl.com/yyrrwkce__;!!JQ5agg!PrHD0xaDWPG4MlB9WMuPHBMEnUUS3KMCE2k0sUKRGLpPa4gPnyNukArJNASLikqommsZ$>

#>   It could also mean the convergence is poor, check results before accepting fit

#>   You may also try a good derivative free optimization:

#>     nlmixr(...,control=list(outerOpt="bobyqa"))

#>

#> ── Fit Data (object is a modified tibble): ─────────────────────────────────────

#> # A tibble: 132 x 22

#>   ID     TIME    DV  EVID  PRED    RES   WRES IPRED   IRES  IWRES CPRED   CRES

#>   <fct> <dbl> <dbl> <int> <dbl>  <dbl>  <dbl> <dbl>  <dbl>  <dbl> <dbl>  <dbl>

#> 1 1     0      0.74     0  0     0.74   0.389  0     0.74   1.06   0     0.74

#> 2 1     0.25   2.84     0  3.27 -0.429 -0.225  3.85 -1.01  -1.44   3.23 -0.386

#> 3 1     0.570  6.57     0  5.85  0.724  0.381  6.79 -0.218 -0.311  5.79  0.776

#> # … with 129 more rows, and 10 more variables: CWRES <dbl>, eta.ka <dbl>,

#> #   eta.cl <dbl>, eta.v <dbl>, ka <dbl>, cl <dbl>, v <dbl>, cp <dbl>,

#> #   depot <dbl>, center <dbl>

Created on 2019-12-11 by the reprex package<https://urldefense.com/v3/__https:/reprex.tidyverse.org__;!!JQ5agg!PrHD0xaDWPG4MlB9WMuPHBMEnUUS3KMCE2k0sUKRGLpPa4gPnyNukArJNASLihKc7EyI$> (v0.3.0)

**Comment by nsk64** [comment]
Hi Matthew,

I check with a combined error (always with linCmt)  prop + a fixed add.
prop.err  ~ c(0,.1,1)
add.err ~ fix(.2)
and the print(fit) gives the following value for add
1.41 FIXED

Perhaps I miss something but I was expecting 0.2 (back-transformation?).

Best regards
Nicolas



De : Matthew Fidler [mailto:notifications@github.com]
Envoyé : mercredi 11 décembre 2019 15:29
À : nlmixrdevelopment/nlmixr <nlmixr@noreply.github.com>
Cc : SIMON Nicolas <Nicolas.SIMON@ap-hm.fr>; Mention <mention@noreply.github.com>
Objet : Re: [nlmixrdevelopment/nlmixr] Is it possible to run nlmixr without random effects? (#95)


Hi @nsk64<https://urldefense.com/v3/__https:/github.com/nsk64__;!!JQ5agg!PrHD0xaDWPG4MlB9WMuPHBMEnUUS3KMCE2k0sUKRGLpPa4gPnyNukArJNASLioNEcKUd$>

This is already present in the cran version:

one.compartment <- function() {

    ini({

        tka <- 0.45 # Log Ka

        tcl <- 1 # Log Cl

        tv <- 3.45    # Log V

        eta.ka ~ 0.6

        eta.cl ~ 0.3

        eta.v ~ fix(0.02)

        add.sd <- fix(0.7)

    })

    model({

        ka <- exp(tka + eta.ka)

        cl <- exp(tcl + eta.cl)

        v <- exp(tv + eta.v)

        d/dt(depot) = -ka * depot

        d/dt(center) = ka * depot - cl / v * center

        cp = center / v

        cp ~ add(add.sd)

    })

}

library(nlmixr)



## Using FOCEi



fit <- nlmixr(one.compartment, theo_sd, est="focei",

              control=list(print=0))

#> Calculating covariance matrix

#> [====|====|====|====|====|====|====|====|====|====] 0:00:00

#> done

#> Calculating residuals/tables

#> done.

#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =

#> FALSE, : Initial ETAs were nudged; (Can control by foceiControl(etaNudge=.))

#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod

#> = FALSE, : ETAs were reset to zero during optimization; (Can control by

#> foceiControl(resetEtaP=.))

#> Warning in (function (uif, data, est = NULL, control = list(), ..., sum.prod =

#> FALSE, : Gradient problems with initial estimate and covariance; see $scaleInfo



print(fit)

#> ── nlmixr FOCEi (outer: nlminb) fit ────────────────────────────────────────────

#>           OBJF     AIC     BIC Log-likelihood Condition Number

#> FOCEi 117.3212 369.921 384.335      -179.9605         72.96997

#>

#> ── Time (sec; $time): ──────────────────────────────────────────────────────────

#>            setup optimize covariance table    other

#> elapsed 0.698461 0.298432   0.298433   0.1 0.429674

#>

#> ── Population Parameters ($parFixed or $parFixedDf): ───────────────────────────

#>        Parameter  Est.     SE  %RSE Back-transformed(95%CI)  BSV(CV%)

#> tka       Log Ka 0.459    0.2  43.7       1.58 (1.07, 2.34)      86.1

#> tcl       Log Cl  1.02 0.0757  7.43       2.77 (2.39, 3.21)      27.8

#> tv         Log V  3.45 0.0436  1.26         31.6 (29, 34.4) fix(14.2)

#> add.sd             0.7  FIXED FIXED                     0.7

#>        Shrink(SD)%

#> tka         13.8%

#> tcl         6.78%

#> tv          12.1%

#> add.sd

#>

#>   Covariance Type ($covMethod): r,s

#>   Some strong fixed parameter correlations exist ($cor) :

#>     cor:tcl,tka  cor:tv,tka  cor:tv,tcl

#>          0.158       0.420       0.748

#>

#>   No correlations in between subject variability (BSV) matrix

#>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs)

#>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink

#>   Minimization message ($message):

#>     false convergence (8)

#>   In an ODE system, false convergence may mean "useless" evaluations were performed.

#>   See https://tinyurl.com/yyrrwkce<https://urldefense.com/v3/__https:/tinyurl.com/yyrrwkce__;!!JQ5agg!PrHD0xaDWPG4MlB9WMuPHBMEnUUS3KMCE2k0sUKRGLpPa4gPnyNukArJNASLikqommsZ$>

#>   It could also mean the convergence is poor, check results before accepting fit

#>   You may also try a good derivative free optimization:

#>     nlmixr(...,control=list(outerOpt="bobyqa"))

#>

#> ── Fit Data (object is a modified tibble): ─────────────────────────────────────

#> # A tibble: 132 x 22

#>   ID     TIME    DV  EVID  PRED    RES   WRES IPRED   IRES  IWRES CPRED   CRES

#>   <fct> <dbl> <dbl> <int> <dbl>  <dbl>  <dbl> <dbl>  <dbl>  <dbl> <dbl>  <dbl>

#> 1 1     0      0.74     0  0     0.74   0.389  0     0.74   1.06   0     0.74

#> 2 1     0.25   2.84     0  3.27 -0.429 -0.225  3.85 -1.01  -1.44   3.23 -0.386

#> 3 1     0.570  6.57     0  5.85  0.724  0.381  6.79 -0.218 -0.311  5.79  0.776

#> # … with 129 more rows, and 10 more variables: CWRES <dbl>, eta.ka <dbl>,

#> #   eta.cl <dbl>, eta.v <dbl>, ka <dbl>, cl <dbl>, v <dbl>, cp <dbl>,

#> #   depot <dbl>, center <dbl>

Created on 2019-12-11 by the reprex package<https://urldefense.com/v3/__https:/reprex.tidyverse.org__;!!JQ5agg!PrHD0xaDWPG4MlB9WMuPHBMEnUUS3KMCE2k0sUKRGLpPa4gPnyNukArJNASLihKc7EyI$> (v0.3.0)

**Comment by dzianismr** [comment]
@mattfidler thank you for posting this example!
I have two follow up questins:
1) Could you clarify what that the following errors message means and if it is on concern?
#> The model-based sensitivities have been calculated.
#> Error in .fitFun(.ret) : 
#>   Infinite/NaN while evaluating initial objective function
2) How do I generate standard plots? 
plot(single)
 generates the following error:
>Error in plot.nlmixrFitCore(single) : 
> This is not a nlmixr data frame and cannot be plotted"

**Comment by mattfidler** [comment]
I'm sorry @dzianismr 

I didn't see your message.  

The problem with #1 is the is the omega is zero so the focei objective function has an infinite/NaN value.  With this in mind the table step is aborted and #2 oesn't have a data frame attached and cannot plot.

I am working through a single solver in focei in development now.

**Comment by mattfidler** [comment]
Will be in the next release "focei" will degrade to a nonlinear system solver.

**Comment by dzianismr** [comment]
@mattfidler Thank you for the clarification!

"Will be in the next release "focei" will degrade to a nonlinear system solver."
>> sounds great, would be very nice to have same interface for mean and population models
