### ISSUE TITLE
Where is the Dockerfile?

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/nlmixr#98]
Can you please provide the Dockerfile?

I see the section in the manual for installation with Docker (https://nlmixrdevelopment.github.io/nlmixr_bookdown/install.html#installation-via-docker), but I'd also like to review (and attempt to manually install) the Dockerfile.  I couldn't find it in the source or in a quick look at the other repositories.

**Comment by mattfidler** [comment]
@RichardHooijmaijers can you point Bill to where the docker file is?

**Comment by RichardHooijmaijers** [comment]
I created a repository for the docker files  [link](https://github.com/RichardHooijmaijers/nlmixr.docker). You can also find some information on [dockerhub](https://hub.docker.com/r/nlmixr/nlmixr/). Just let me know if this is what you require.

**Comment by billdenney** [comment]
Thanks!  I have a couple of questions on the file, and I'll ask them in that repository.
